//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acopio
    {
        public int IdAcopio { get; set; }
        public Nullable<int> NumeroAcopio { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Realizo { get; set; }
        public Nullable<int> Aprobo { get; set; }
        public string Nombre { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdAutorizacion1 { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion1 { get; set; }
        public Nullable<int> IdAutorizacion2 { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion2 { get; set; }
        public Nullable<int> IdAutorizacion3 { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion3 { get; set; }
        public Nullable<decimal> MontoPrevisto { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string Estado { get; set; }
        public string UsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> Fechaanulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> IdAutorizoCumplido { get; set; }
        public Nullable<int> IdDioPorCumplido { get; set; }
        public Nullable<System.DateTime> FechaDadoPorCumplido { get; set; }
        public string ObservacionesCumplido { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdAcopioOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
    }
}
