//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public Asiento()
        {
            this.DetalleAsientos = new HashSet<DetalleAsiento>();
        }
    
        public int IdAsiento { get; set; }
        public Nullable<int> NumeroAsiento { get; set; }
        public Nullable<System.DateTime> FechaAsiento { get; set; }
        public Nullable<int> Ejercicio { get; set; }
        public Nullable<int> IdCuentaSubdiario { get; set; }
        public string Concepto { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string AsientoApertura { get; set; }
        public string BaseConsolidadaHija { get; set; }
        public Nullable<System.DateTime> FechaGeneracionConsolidado { get; set; }
        public string ArchivoImportacion { get; set; }
        public string AsignarAPresupuestoObra { get; set; }
    
        public virtual ICollection<DetalleAsiento> DetalleAsientos { get; set; }
    }
}
