//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartasDePorteDetalle_EF
    {
        public int IdCartaDePorteDetalle { get; set; }
        public Nullable<int> IdCartaDePorte { get; set; }
        public string Campo { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual CartasDePorte CartasDePorte { get; set; }
    }
}
