//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartasDePorteReglasDeFacturacion
    {
        public int IdRegla { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public string SeLeFacturaCartaPorteComoTitular { get; set; }
        public string SeLeFacturaCartaPorteComoIntermediario { get; set; }
        public string SeLeFacturaCartaPorteComoRemcomercial { get; set; }
        public string SeLeFacturaCartaPorteComoCorredor { get; set; }
        public string SeLeFacturaCartaPorteComoDestinatario { get; set; }
        public string SeLeFacturaCartaPorteComoDestinatarioExportador { get; set; }
        public string SeLeDerivaSuFacturaAlCorredorDeLaCarta { get; set; }
        public string SeLeFacturaCartaPorteComoClienteAuxiliar { get; set; }
        public string EsEntregador { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
