//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartasDePorteLogDeOCR
    {
        public int IdCartasDePorteLog { get; set; }
        public Nullable<int> NumeroCarta { get; set; }
        public Nullable<int> IdCartaDePorte { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Observaciones { get; set; }
        public string TextoAux1 { get; set; }
        public string TextoAux2 { get; set; }
        public Nullable<int> IntAux1 { get; set; }
        public Nullable<int> IntAux2 { get; set; }
    
        public virtual CartasDePorte CartasDePorte { get; set; }
    }
}
