//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaPorteNormasCalidad
    {
        public int IdCartaPorteNormaCalidad { get; set; }
        public Nullable<int> IdCartaPorteRubroCalidad { get; set; }
        public Nullable<decimal> ResultadoDesde { get; set; }
        public Nullable<decimal> ResultadoHasta { get; set; }
        public Nullable<decimal> RebajaIncremento { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> IdDestino { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual CartaPorteRubrosCalidad CartaPorteRubrosCalidad { get; set; }
        public virtual WilliamsDestino WilliamsDestino { get; set; }
    }
}
