//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPEstablecimiento
    {
        public int IdEstablecimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<int> IdTitular { get; set; }
        public string CUIT { get; set; }
        public string AuxiliarString1 { get; set; }
        public string AuxiliarString2 { get; set; }
        public string AuxiliarString3 { get; set; }
    }
}
