//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciliacione
    {
        public Conciliacione()
        {
            this.DetalleConciliacionesContables = new HashSet<DetalleConciliacione>();
            this.DetalleConciliacionesNoContables = new HashSet<DetalleConciliacionesNoContable>();
        }
    
        public int IdConciliacion { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> SaldoInicialResumen { get; set; }
        public Nullable<decimal> SaldoFinalResumen { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> ImporteAjuste { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdRealizo { get; set; }
        public Nullable<int> IdAprobo { get; set; }
    
        public virtual CuentasBancaria CuentasBancaria { get; set; }
        public virtual ICollection<DetalleConciliacione> DetalleConciliacionesContables { get; set; }
        public virtual ICollection<DetalleConciliacionesNoContable> DetalleConciliacionesNoContables { get; set; }
    }
}
