//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public Concepto()
        {
            this.DetalleNotasCreditoes = new HashSet<DetalleNotasCredito>();
            this.DetalleNotasDebitoes = new HashSet<DetalleNotasDebito>();
            this.OrdenesPagoes = new HashSet<OrdenPago>();
            this.OrdenesPagoes1 = new HashSet<OrdenPago>();
        }
    
        public int IdConcepto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string ValorRechazado { get; set; }
        public Nullable<int> CodigoConcepto { get; set; }
        public string GravadoDefault { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string CodigoAFIP { get; set; }
        public Nullable<decimal> CoeficienteAuxiliar_1 { get; set; }
        public string GeneraComision { get; set; }
        public string NoTomarEnRanking { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<DetalleNotasCredito> DetalleNotasCreditoes { get; set; }
        public virtual ICollection<DetalleNotasDebito> DetalleNotasDebitoes { get; set; }
        public virtual ICollection<OrdenPago> OrdenesPagoes { get; set; }
        public virtual ICollection<OrdenPago> OrdenesPagoes1 { get; set; }
    }
}
