//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumos
    {
        public int IdConsumo { get; set; }
        public Nullable<int> NumeroConsumo { get; set; }
        public Nullable<System.DateTime> FechaConsumo { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdConsumoOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<System.DateTime> FechaImportacion { get; set; }
        public Nullable<int> IdSalidaMaterialesPRONTO { get; set; }
        public Nullable<int> NumeroSalidaMaterialesPRONTO { get; set; }
        public string BDOrigenSalidaPRONTO { get; set; }
        public string Observaciones { get; set; }
    }
}
