//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacione
    {
        public int IdCotizacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<decimal> Cotizacion { get; set; }
        public Nullable<decimal> CotizacionLibre { get; set; }
        public string REP_COTIZACION_INS { get; set; }
        public string REP_COTIZACION_UPD { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
