//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasBancaria
    {
        public CuentasBancaria()
        {
            this.Conciliaciones = new HashSet<Conciliacione>();
        }
    
        public int IdCuentaBancaria { get; set; }
        public string Cuenta { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public string Detalle { get; set; }
        public string PlantillaChequera { get; set; }
        public Nullable<int> ChequesPorPlancha { get; set; }
        public string CBU { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<int> CaracteresBeneficiario { get; set; }
        public string Activa { get; set; }
        public string DiseñoCheque { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual ICollection<Conciliacione> Conciliaciones { get; set; }
    }
}
