//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasCorrientesAcreedor
    {
        public int IdCtaCte { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdTipoComp { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public Nullable<int> NumeroComprobante { get; set; }
        public Nullable<int> IdImputacion { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdDetalleOrdenPago { get; set; }
        public Nullable<decimal> CotizacionDolar { get; set; }
        public Nullable<decimal> ImporteTotalDolar { get; set; }
        public Nullable<decimal> SaldoDolar { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<decimal> CotizacionMoneda { get; set; }
        public Nullable<decimal> CotizacionEuro { get; set; }
        public Nullable<decimal> ImporteTotalEuro { get; set; }
        public Nullable<decimal> SaldoEuro { get; set; }
        public Nullable<decimal> SaldoTrs { get; set; }
        public string Marca { get; set; }
    
        public virtual Proveedor Proveedore { get; set; }
    }
}
