//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescripcionIva
    {
        public DescripcionIva()
        {
            this.Clientes = new HashSet<Cliente>();
            this.ComprobantesProveedores = new HashSet<ComprobanteProveedor>();
            this.Proveedores = new HashSet<Proveedor>();
        }
    
        public int IdCodigoIva { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IvaDiscriminado { get; set; }
        public Nullable<int> CodigoAFIP { get; set; }
        public string ExigirCUIT { get; set; }
        public string ExigirCAI { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<decimal> PorcentajePercepcion { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<ComprobanteProveedor> ComprobantesProveedores { get; set; }
        public virtual ICollection<Proveedor> Proveedores { get; set; }
    }
}
