//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescripcionIva
    {
        public DescripcionIva()
        {
            this.Clientes = new HashSet<Cliente>();
            this.ComprobantesProveedores = new HashSet<ComprobanteProveedor>();
            this.Proveedores = new HashSet<Proveedor>();
        }
    
        public int IdCodigoIva { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IvaDiscriminado { get; set; }
        public Nullable<int> CodigoAFIP { get; set; }
        public string ExigirCUIT { get; set; }
        public string ExigirCAI { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<decimal> PorcentajePercepcion { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<ComprobanteProveedor> ComprobantesProveedores { get; set; }
        public virtual ICollection<Proveedor> Proveedores { get; set; }
    }
}
