//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRequerimiento
    {
        public DetalleRequerimiento()
        {
            this.DetallePresupuestos = new HashSet<DetallePresupuesto>();
            this.DetallePedidos = new HashSet<DetallePedido>();
            this.DetalleRecepciones = new HashSet<DetalleRecepcione>();
            this.DetalleValesSalidas = new HashSet<DetalleValesSalida>();
        }
    
        public int IdDetalleRequerimiento { get; set; }
        public Nullable<int> IdRequerimiento { get; set; }
        public Nullable<int> NumeroItem { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Cantidad1 { get; set; }
        public Nullable<decimal> Cantidad2 { get; set; }
        public Nullable<int> IdDetalleLMateriales { get; set; }
        public Nullable<int> IdControlCalidad { get; set; }
        public string Adjunto { get; set; }
        public string ArchivoAdjunto { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> NumeroFacturaCompra1 { get; set; }
        public Nullable<System.DateTime> FechaFacturaCompra { get; set; }
        public Nullable<decimal> ImporteFacturaCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> NumeroFacturaCompra2 { get; set; }
        public string EsBienDeUso { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string Cumplido { get; set; }
        public string Usuario1 { get; set; }
        public Nullable<System.DateTime> FechaIngreso1 { get; set; }
        public string ArchivoAdjunto1 { get; set; }
        public string ArchivoAdjunto2 { get; set; }
        public string ArchivoAdjunto3 { get; set; }
        public string ArchivoAdjunto4 { get; set; }
        public string ArchivoAdjunto5 { get; set; }
        public string ArchivoAdjunto6 { get; set; }
        public string ArchivoAdjunto7 { get; set; }
        public string ArchivoAdjunto8 { get; set; }
        public string ArchivoAdjunto9 { get; set; }
        public string ArchivoAdjunto10 { get; set; }
        public string Descripcionmanual { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdRequerimientoOriginal { get; set; }
        public Nullable<int> IdDetalleRequerimientoOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<int> IdLlamadoAProveedor { get; set; }
        public Nullable<System.DateTime> FechaLlamadoAProveedor { get; set; }
        public Nullable<int> IdLlamadoRegistradoPor { get; set; }
        public Nullable<System.DateTime> FechaRegistracionLlamada { get; set; }
        public string ObservacionesLlamada { get; set; }
        public Nullable<int> IdAutorizoCumplido { get; set; }
        public Nullable<int> IdDioPorCumplido { get; set; }
        public Nullable<System.DateTime> FechaDadoPorCumplido { get; set; }
        public string ObservacionesCumplido { get; set; }
        public Nullable<int> IdAproboAlmacen { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<System.DateTime> FechaEntrega_Tel { get; set; }
        public string PRESTOConcepto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> OrigenDescripcion { get; set; }
        public string TipoDesignacion { get; set; }
        public Nullable<int> IdLiberoParaCompras { get; set; }
        public Nullable<System.DateTime> FechaLiberacionParaCompras { get; set; }
        public string Recepcionado { get; set; }
        public Nullable<int> Pagina { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> Figura { get; set; }
        public string CodigoDistribucion { get; set; }
        public Nullable<int> IdEquipoDestino { get; set; }
        public string Entregado { get; set; }
        public Nullable<System.DateTime> FechaAsignacionComprador { get; set; }
        public string MoP { get; set; }
        public Nullable<int> IdDetalleObraDestino { get; set; }
        public Nullable<int> IdPresupuestoObraRubro { get; set; }
        public string ObservacionesFirmante_1 { get; set; }
        public Nullable<int> IdFirmanteObservo_1 { get; set; }
        public Nullable<System.DateTime> FechaUltimaObservacionFirmante_1 { get; set; }
        public Nullable<int> IdPresupuestoObrasNodo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual ControlCalidad ControlCalidad { get; set; }
        public virtual Requerimiento Requerimientos { get; set; }
        public virtual ICollection<DetallePresupuesto> DetallePresupuestos { get; set; }
        public virtual ICollection<DetallePedido> DetallePedidos { get; set; }
        public virtual ICollection<DetalleRecepcione> DetalleRecepciones { get; set; }
        public virtual ICollection<DetalleValesSalida> DetalleValesSalidas { get; set; }
    }
}
