//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenesPagoValore
    {
        public int IdDetalleOrdenPagoValores { get; set; }
        public Nullable<int> IdOrdenPago { get; set; }
        public Nullable<int> IdTipoValor { get; set; }
        public Nullable<decimal> NumeroValor { get; set; }
        public Nullable<int> NumeroInterno { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> IdValor { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public Nullable<int> IdBancoChequera { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public string ChequesALaOrdenDe { get; set; }
        public string NoALaOrden { get; set; }
        public string Anulado { get; set; }
        public Nullable<int> IdUsuarioAnulo { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> IdTarjetaCredito { get; set; }
    
        public virtual TiposComprobante TiposComprobante { get; set; }
        public virtual BancoChequera BancoChequera { get; set; }
        public virtual OrdenPago OrdenesPago { get; set; }
    }
}
