//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAcopio
    {
        public int IdDetalleAcopios { get; set; }
        public Nullable<int> IdAcopio { get; set; }
        public Nullable<int> NumeroItem { get; set; }
        public string Revision { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> IdUnidadPeso { get; set; }
        public Nullable<int> IdControlCalidad { get; set; }
        public Nullable<System.DateTime> FechaNecesidad { get; set; }
        public string Adjunto { get; set; }
        public Nullable<decimal> Cantidad1 { get; set; }
        public Nullable<decimal> Cantidad2 { get; set; }
        public string ArchivoAdjunto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string Cumplido { get; set; }
        public string ArchivoAdjunto1 { get; set; }
        public string ArchivoAdjunto2 { get; set; }
        public string ArchivoAdjunto3 { get; set; }
        public string ArchivoAdjunto4 { get; set; }
        public string ArchivoAdjunto5 { get; set; }
        public string ArchivoAdjunto6 { get; set; }
        public string ArchivoAdjunto7 { get; set; }
        public string ArchivoAdjunto8 { get; set; }
        public string ArchivoAdjunto9 { get; set; }
        public string ArchivoAdjunto10 { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> IdLlamadoAProveedor { get; set; }
        public Nullable<System.DateTime> FechaLlamadoAProveedor { get; set; }
        public Nullable<int> IdLlamadoRegistradoPor { get; set; }
        public Nullable<System.DateTime> FechaRegistracionLlamada { get; set; }
        public string ObservacionesLlamada { get; set; }
        public Nullable<int> IdAutorizoCumplido { get; set; }
        public Nullable<int> IdDioPorCumplido { get; set; }
        public Nullable<System.DateTime> FechaDadoPorCumplido { get; set; }
        public string ObservacionesCumplido { get; set; }
        public Nullable<int> IdAproboAlmacen { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdAcopioOriginal { get; set; }
        public Nullable<int> IdDetalleAcopiosOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<System.DateTime> FechaEntrega_Tel { get; set; }
    }
}
