//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleArticulosUnidade
    {
        public int IdDetalleArticuloUnidades { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<decimal> Equivalencia { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdArticuloOriginal { get; set; }
        public Nullable<int> IdDetalleArticuloUnidadesOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
    
        public virtual Unidad Unidade { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
