//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleComparativa
    {
        public DetalleComparativa()
        {
            this.DetallePedidos = new HashSet<DetallePedido>();
        }
    
        public int IdDetalleComparativa { get; set; }
        public Nullable<int> IdComparativa { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
        public Nullable<int> NumeroPresupuesto { get; set; }
        public Nullable<System.DateTime> FechaPresupuesto { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Estado { get; set; }
        public Nullable<int> SubNumero { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> OrigenDescripcion { get; set; }
        public Nullable<decimal> PorcentajeBonificacion { get; set; }
        public Nullable<decimal> CotizacionMoneda { get; set; }
        public Nullable<int> IdDetallePresupuesto { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Unidad Unidade { get; set; }
        public virtual Comparativa Comparativa { get; set; }
        public virtual ICollection<DetallePedido> DetallePedidos { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
