//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRecibosRubrosContable
    {
        public int IdDetalleReciboRubrosContables { get; set; }
        public Nullable<int> IdRecibo { get; set; }
        public Nullable<int> IdRubroContable { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<int> IdReciboOriginal { get; set; }
        public Nullable<int> IdDetalleReciboRubrosContablesOriginal { get; set; }
        public Nullable<System.DateTime> FechaImportacionTransmision { get; set; }
    
        public virtual Recibo Recibo { get; set; }
    }
}
