//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAutorizacionesFirmante
    {
        public int IdDetalleAutorizacionFirmantes { get; set; }
        public Nullable<int> IdDetalleAutorizacion { get; set; }
        public Nullable<int> IdAutorizacion { get; set; }
        public Nullable<int> IdFirmante { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public Nullable<int> IdSubrubro { get; set; }
        public string ParaTaller { get; set; }
        public Nullable<decimal> ImporteDesde { get; set; }
        public Nullable<decimal> ImporteHasta { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdPuntoVenta { get; set; }
    }
}
