//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleObrasPoliza
    {
        public int IdDetalleObraPoliza { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdTipoPoliza { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<decimal> NumeroPoliza { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCuota { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> FechaEstimadaRecupero { get; set; }
        public Nullable<System.DateTime> FechaRecupero { get; set; }
        public string CondicionRecupero { get; set; }
        public string MotivoDeContratacionSeguro { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaFinalizacionCobertura { get; set; }
    
        public virtual Obra Obra { get; set; }
    }
}
