//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleArticulosImagene
    {
        public int IdDetalleArticuloImagenes { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string PathImagen { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
