//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDevolucione
    {
        public int IdDetalleDevolucion { get; set; }
        public Nullable<int> IdDevolucion { get; set; }
        public Nullable<int> NumeroDevolucion { get; set; }
        public string TipoABC { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string CodigoArticulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Bonificacion { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> OrigenDescripcion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> PorcentajeCertificacion { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> NumeroCaja { get; set; }
        public Nullable<int> IdDetalleFactura { get; set; }
        public string Talle { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdDetallePresupuestoVenta { get; set; }
        public string OrigenRegistro { get; set; }
        public Nullable<decimal> PorcentajeIva { get; set; }
        public Nullable<decimal> ImporteIva { get; set; }
    
        public virtual Devolucione Devolucione { get; set; }
    }
}
