//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturasProvincia
    {
        public int IdDetalleFacturaProvincias { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdProvinciaDestino { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
