//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturasOrdenesCompra
    {
        public int IdDetalleFacturaOrdenesCompra { get; set; }
        public Nullable<int> IdDetalleFactura { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdDetalleOrdenCompra { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual DetalleFactura DetalleFactura { get; set; }
    }
}
