//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleArticulosImagene
    {
        public int IdDetalleArticuloImagenes { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string PathImagen { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
