//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRecibosCuenta
    {
        public int IdDetalleReciboCuentas { get; set; }
        public Nullable<int> IdRecibo { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string CodigoCuenta { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdCuentaGasto { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<decimal> CotizacionMonedaDestino { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<int> IdReciboOriginal { get; set; }
        public Nullable<int> IdDetalleReciboCuentasOriginal { get; set; }
        public Nullable<System.DateTime> FechaImportacionTransmision { get; set; }
    
        public virtual Recibo Recibo { get; set; }
    }
}
