//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Requerimientos = new HashSet<Requerimiento>();
            this.Requerimientos1 = new HashSet<Requerimiento>();
            this.Clientes = new HashSet<Cliente>();
            this.Clientes1 = new HashSet<Cliente>();
            this.Pedidos = new HashSet<Pedido>();
            this.Facturas = new HashSet<Factura>();
            this.Presupuestos = new HashSet<Presupuesto>();
            this.Presupuestos1 = new HashSet<Presupuesto>();
            this.EmpleadosAccesos = new HashSet<EmpleadosAcceso>();
            this.Pedidos_1 = new HashSet<Pedido>();
        }
    
        public int IdEmpleado { get; set; }
        public Nullable<int> Legajo { get; set; }
        public string Nombre { get; set; }
        public string UsuarioNT { get; set; }
        public Nullable<int> IdSector { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string Email { get; set; }
        public string Interno { get; set; }
        public string Administrador { get; set; }
        public string Iniciales { get; set; }
        public string Password { get; set; }
        public string SisMan { get; set; }
        public Nullable<decimal> HorasJornada { get; set; }
        public Nullable<int> IdSector1 { get; set; }
        public Nullable<int> IdCargo1 { get; set; }
        public Nullable<int> IdSector2 { get; set; }
        public Nullable<int> IdCargo2 { get; set; }
        public Nullable<int> IdSector3 { get; set; }
        public Nullable<int> IdCargo3 { get; set; }
        public Nullable<int> IdSector4 { get; set; }
        public Nullable<int> IdCargo4 { get; set; }
        public string Dominio { get; set; }
        public string SisMat { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> TipoUsuario { get; set; }
        public Nullable<int> GrupoDeCarga { get; set; }
        public string CuentaBancaria { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<int> IdCuentaFondoFijo { get; set; }
        public Nullable<int> IdObraAsignada { get; set; }
        public string Activo { get; set; }
        public string Idioma { get; set; }
        public Nullable<int> PuntoVentaAsociado_1 { get; set; }
        public Nullable<int> IdLugarEntregaAsignado_1 { get; set; }
        public string EsConductor { get; set; }
        public Nullable<System.DateTime> FechaVencimientoRegistro { get; set; }
        public string LimitarUbicacionesAsignadas { get; set; }
        public string PermitirAccesoATodasLasObras { get; set; }
    
        public virtual Sector Sector { get; set; }
        public virtual ICollection<Requerimiento> Requerimientos { get; set; }
        public virtual ICollection<Requerimiento> Requerimientos1 { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Cliente> Clientes1 { get; set; }
        public virtual ICollection<Pedido> Pedidos { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual ICollection<Presupuesto> Presupuestos { get; set; }
        public virtual ICollection<Presupuesto> Presupuestos1 { get; set; }
        public virtual ICollection<EmpleadosAcceso> EmpleadosAccesos { get; set; }
        public virtual ICollection<Pedido> Pedidos_1 { get; set; }
    }
}
