//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosAcceso
    {
        public int IdEmpleadoAcceso { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string Nodo { get; set; }
        public bool Acceso { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<System.DateTime> FechaDesdeParaModificacion { get; set; }
        public Nullable<System.DateTime> FechaInicialHabilitacion { get; set; }
        public Nullable<System.DateTime> FechaFinalHabilitacion { get; set; }
        public Nullable<int> CantidadAccesos { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public string UsuarioNTUsuarioModifico { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
