//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosDelSistema
    {
        public EventosDelSistema()
        {
            this.DetalleEventosDelSistemas = new HashSet<DetalleEventosDelSistema>();
        }
    
        public int IdEventoDelSistema { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Importancia { get; set; }
    
        public virtual ICollection<DetalleEventosDelSistema> DetalleEventosDelSistemas { get; set; }
    }
}
