//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpuestosDirecto
    {
        public int IdImpuestoDirecto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<int> IdTipoImpuesto { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public Nullable<decimal> BaseMinima { get; set; }
        public Nullable<int> ProximoNumeroCertificado { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string ActivaNumeracionPorGrupo { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> TopeAnual { get; set; }
        public string ParaInscriptosEnRegistroFiscalOperadoresGranos { get; set; }
        public Nullable<int> CodigoRegimen { get; set; }
        public Nullable<decimal> ImpuestoMinimo { get; set; }
    }
}
