//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string Tipo { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public Nullable<int> IdDetalleComprobante { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Detalle { get; set; }
        public string AuxString1 { get; set; }
        public string AuxString2 { get; set; }
        public string AuxString3 { get; set; }
        public string AuxString4 { get; set; }
        public string AuxString5 { get; set; }
        public Nullable<System.DateTime> AuxDate1 { get; set; }
        public Nullable<System.DateTime> AuxDate2 { get; set; }
        public Nullable<System.DateTime> AuxDate3 { get; set; }
        public Nullable<System.DateTime> AuxDate4 { get; set; }
        public Nullable<System.DateTime> AuxDate5 { get; set; }
        public Nullable<decimal> AuxNum1 { get; set; }
        public Nullable<decimal> AuxNum2 { get; set; }
        public Nullable<decimal> AuxNum3 { get; set; }
        public Nullable<decimal> AuxNum4 { get; set; }
        public Nullable<decimal> AuxNum5 { get; set; }
        public int IdLog { get; set; }
    }
}
