//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogComprobantesElectronico
    {
        public int IdLog { get; set; }
        public string Tipo { get; set; }
        public string Letra { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public Nullable<int> NumeroComprobante { get; set; }
        public Nullable<int> Identificador { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Enviado { get; set; }
        public string Recibido { get; set; }
    }
}
