//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesCompra
    {
        public OrdenesCompra()
        {
            this.DetalleOrdenesCompras = new HashSet<DetalleOrdenesCompra>();
        }
    
        public int IdOrdenCompra { get; set; }
        public Nullable<int> NumeroOrdenCompra { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaOrdenCompra { get; set; }
        public Nullable<int> IdCondicionVenta { get; set; }
        public string Anulada { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string ArchivoAdjunto1 { get; set; }
        public string ArchivoAdjunto2 { get; set; }
        public string ArchivoAdjunto3 { get; set; }
        public string ArchivoAdjunto4 { get; set; }
        public string ArchivoAdjunto5 { get; set; }
        public string ArchivoAdjunto6 { get; set; }
        public string ArchivoAdjunto7 { get; set; }
        public string ArchivoAdjunto8 { get; set; }
        public string ArchivoAdjunto9 { get; set; }
        public string ArchivoAdjunto10 { get; set; }
        public string NumeroOrdenCompraCliente { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> IdUsuarioAnulacion { get; set; }
        public Nullable<int> AgrupacionFacturacion { get; set; }
        public Nullable<int> Agrupacion2Facturacion { get; set; }
        public string SeleccionadaParaFacturacion { get; set; }
        public Nullable<decimal> PorcentajeBonificacion { get; set; }
        public Nullable<int> IdListaPrecios { get; set; }
        public Nullable<int> IdUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<int> Aprobo { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string CircuitoFirmasCompleto { get; set; }
        public Nullable<int> IdDetalleClienteLugarEntrega { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdUsuarioCambioEstado { get; set; }
        public Nullable<System.DateTime> FechaCambioEstado { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<DetalleOrdenesCompra> DetalleOrdenesCompras { get; set; }
        public virtual Condiciones_Compra Condiciones_Compra { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Empleado Empleado2 { get; set; }
        public virtual Empleado Empleado3 { get; set; }
        public virtual ListasPrecio ListasPrecio { get; set; }
        public virtual Obra Obra { get; set; }
    }
}
