//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoObrasNodosDato
    {
        public int IdPresupuestoObrasNodoDatos { get; set; }
        public Nullable<int> IdPresupuestoObrasNodo { get; set; }
        public Nullable<int> CodigoPresupuesto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> CantidadBase { get; set; }
        public Nullable<decimal> Rendimiento { get; set; }
        public Nullable<decimal> Incidencia { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioVentaUnitario { get; set; }
    
        public virtual PresupuestoObrasNodo PresupuestoObrasNodo { get; set; }
    }
}
