//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcione
    {
        public Recepcione()
        {
            this.DetalleRecepciones = new HashSet<DetalleRecepcione>();
        }
    
        public int IdRecepcion { get; set; }
        public Nullable<int> NumeroRecepcion1 { get; set; }
        public Nullable<int> NumeroRecepcion2 { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdRequerimiento { get; set; }
        public Nullable<int> NumeroRecepcionAlmacen { get; set; }
        public Nullable<int> IdTransportista { get; set; }
        public string Acargo { get; set; }
        public Nullable<int> Realizo { get; set; }
        public string Anulada { get; set; }
        public Nullable<int> IdAcopio { get; set; }
        public string SubNumero { get; set; }
        public Nullable<System.DateTime> FechaRegistracion { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdRecepcionOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<System.DateTime> FechaImportacionTransmision { get; set; }
        public string ProcesadoPorCPManualmente { get; set; }
        public string ActualizarCostoImportacionDesdePedido { get; set; }
        public Nullable<int> IdUsuarioAnulo { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<decimal> ImpuestosInternos { get; set; }
        public Nullable<decimal> PercepcionIIBB { get; set; }
        public Nullable<decimal> PercepcionIVA { get; set; }
        public Nullable<System.DateTime> PRESTOFechaProceso { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public Nullable<int> IdUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> Libero { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public string CircuitoFirmasCompleto { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> NumeroRecepcionOrigen1 { get; set; }
        public Nullable<int> NumeroRecepcionOrigen2 { get; set; }
        public string Chofer { get; set; }
        public string NumeroDocumentoChofer { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public string Patente { get; set; }
        public Nullable<int> IdDepositoOrigen { get; set; }
        public Nullable<int> IdRecepcionSAT { get; set; }
        public Nullable<int> TipoRecepcion { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> NumeroRemitoTransporte1 { get; set; }
        public Nullable<int> NumeroRemitoTransporte2 { get; set; }
        public Nullable<int> IdChofer { get; set; }
        public Nullable<int> IdFlete { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public Nullable<decimal> CantidadEnOrigen { get; set; }
        public Nullable<decimal> DistanciaRecorrida { get; set; }
        public string CodigoTarifador { get; set; }
        public Nullable<int> NumeroOrdenCarga { get; set; }
        public Nullable<int> IdPesada { get; set; }
        public Nullable<int> IdTarifaFlete { get; set; }
        public Nullable<decimal> TarifaFlete { get; set; }
        public string ArchivoAdjunto1 { get; set; }
        public Nullable<int> NumeroPesada { get; set; }
        public Nullable<decimal> Progresiva1 { get; set; }
        public Nullable<decimal> Progresiva2 { get; set; }
        public Nullable<System.DateTime> FechaPesada { get; set; }
        public string ObservacionesPesada { get; set; }
    
        public virtual ICollection<DetalleRecepcione> DetalleRecepciones { get; set; }
    }
}
