//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public Recibo()
        {
            this.DetalleRecibosImputaciones = new HashSet<DetalleRecibo>();
            this.DetalleRecibosCuentas = new HashSet<DetalleRecibosCuenta>();
            this.DetalleRecibosRubrosContables = new HashSet<DetalleRecibosRubrosContable>();
            this.DetalleRecibosValores = new HashSet<DetalleRecibosValore>();
        }
    
        public int IdRecibo { get; set; }
        public Nullable<int> NumeroRecibo { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> Valores { get; set; }
        public Nullable<decimal> Documentos { get; set; }
        public Nullable<decimal> Otros1 { get; set; }
        public Nullable<int> IdCuenta1 { get; set; }
        public Nullable<decimal> Otros2 { get; set; }
        public Nullable<int> IdCuenta2 { get; set; }
        public Nullable<decimal> Otros3 { get; set; }
        public Nullable<int> IdCuenta3 { get; set; }
        public Nullable<decimal> Deudores { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> RetencionGanancias { get; set; }
        public Nullable<decimal> RetencionIBrutos { get; set; }
        public Nullable<decimal> GastosGenerales { get; set; }
        public Nullable<decimal> Cotizacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public string Dolarizada { get; set; }
        public Nullable<int> IdObra1 { get; set; }
        public Nullable<int> IdCuentaGasto1 { get; set; }
        public Nullable<int> IdObra2 { get; set; }
        public Nullable<int> IdCuentaGasto2 { get; set; }
        public Nullable<int> IdObra3 { get; set; }
        public Nullable<int> IdCuentaGasto3 { get; set; }
        public Nullable<int> IdObra4 { get; set; }
        public Nullable<int> IdCuentaGasto4 { get; set; }
        public Nullable<int> IdCuenta4 { get; set; }
        public Nullable<decimal> Otros4 { get; set; }
        public Nullable<int> IdObra5 { get; set; }
        public Nullable<int> IdCuentaGasto5 { get; set; }
        public Nullable<int> IdCuenta5 { get; set; }
        public Nullable<decimal> Otros5 { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string AsientoManual { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdCuentaGasto { get; set; }
        public Nullable<int> NumeroCertificadoRetencionGanancias { get; set; }
        public Nullable<int> NumeroCertificadoRetencionIVA { get; set; }
        public Nullable<int> NumeroCertificadoSUSS { get; set; }
        public Nullable<int> IdTipoRetencionGanancia { get; set; }
        public Nullable<decimal> CotizacionMoneda { get; set; }
        public Nullable<int> NumeroCertificadoRetencionIngresosBrutos { get; set; }
        public string Anulado { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public Nullable<int> IdPuntoVenta { get; set; }
        public Nullable<int> IdUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> Lote { get; set; }
        public Nullable<int> Sublote { get; set; }
        public Nullable<int> IdCodigoIvaOpcional { get; set; }
        public Nullable<int> TipoOperacionOtros { get; set; }
        public Nullable<System.DateTime> FechaLote { get; set; }
        public string CuitOpcional { get; set; }
        public Nullable<int> IdComprobanteProveedorReintegro { get; set; }
        public Nullable<int> IdObra6 { get; set; }
        public Nullable<int> IdCuentaGasto6 { get; set; }
        public Nullable<int> IdCuenta6 { get; set; }
        public Nullable<decimal> Otros6 { get; set; }
        public Nullable<int> IdObra7 { get; set; }
        public Nullable<int> IdCuentaGasto7 { get; set; }
        public Nullable<int> IdCuenta7 { get; set; }
        public Nullable<decimal> Otros7 { get; set; }
        public Nullable<int> IdObra8 { get; set; }
        public Nullable<int> IdCuentaGasto8 { get; set; }
        public Nullable<int> IdCuenta8 { get; set; }
        public Nullable<decimal> Otros8 { get; set; }
        public Nullable<int> IdObra9 { get; set; }
        public Nullable<int> IdCuentaGasto9 { get; set; }
        public Nullable<int> IdCuenta9 { get; set; }
        public Nullable<decimal> Otros9 { get; set; }
        public Nullable<int> IdObra10 { get; set; }
        public Nullable<int> IdCuentaGasto10 { get; set; }
        public Nullable<int> IdCuenta10 { get; set; }
        public Nullable<decimal> Otros10 { get; set; }
        public Nullable<int> NumeroComprobante1 { get; set; }
        public Nullable<int> NumeroComprobante2 { get; set; }
        public Nullable<int> NumeroComprobante3 { get; set; }
        public Nullable<int> NumeroComprobante4 { get; set; }
        public Nullable<int> NumeroComprobante5 { get; set; }
        public Nullable<int> NumeroComprobante6 { get; set; }
        public Nullable<int> NumeroComprobante7 { get; set; }
        public Nullable<int> NumeroComprobante8 { get; set; }
        public Nullable<int> NumeroComprobante9 { get; set; }
        public Nullable<int> NumeroComprobante10 { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<int> IdReciboOriginal { get; set; }
        public Nullable<System.DateTime> FechaImportacionTransmision { get; set; }
        public string CuitClienteTransmision { get; set; }
        public Nullable<int> IdProvinciaDestino { get; set; }
        public string ServicioCobro { get; set; }
        public string LoteServicioCobro { get; set; }
        public Nullable<int> IdFacturaDirecta { get; set; }
    
        public virtual ICollection<DetalleRecibo> DetalleRecibosImputaciones { get; set; }
        public virtual ICollection<DetalleRecibosCuenta> DetalleRecibosCuentas { get; set; }
        public virtual ICollection<DetalleRecibosRubrosContable> DetalleRecibosRubrosContables { get; set; }
        public virtual ICollection<DetalleRecibosValore> DetalleRecibosValores { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Obra Obra { get; set; }
        public virtual Vendedor Vendedore { get; set; }
        public virtual Vendedor Vendedore1 { get; set; }
    }
}
