//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo
    {
        public Reclamo()
        {
            this.CartasDePortes = new HashSet<CartasDePorte>();
            this.ReclamoComentarios = new HashSet<ReclamoComentario>();
        }
    
        public int IdReclamo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual ICollection<CartasDePorte> CartasDePortes { get; set; }
        public virtual ICollection<ReclamoComentario> ReclamoComentarios { get; set; }
    }
}
