//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubrosContable
    {
        public RubrosContable()
        {
            this.DetalleOrdenesPagoRubrosContables = new HashSet<DetalleOrdenesPagoRubrosContable>();
        }
    
        public int IdRubroContable { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Financiero { get; set; }
        public string IngresoEgreso { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string DistribuirGastosEnResumen { get; set; }
        public Nullable<int> CodigoAgrupacion { get; set; }
        public Nullable<int> IdTipoRubroFinancieroGrupo { get; set; }
        public string TomarMesDeVentaEnResumen { get; set; }
    
        public virtual ICollection<DetalleOrdenesPagoRubrosContable> DetalleOrdenesPagoRubrosContables { get; set; }
    }
}
