//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Requerimientos = new HashSet<Requerimiento>();
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int IdSector { get; set; }
        public string Descripcion { get; set; }
        public string SectorDeObra { get; set; }
        public Nullable<int> IdEncargado { get; set; }
        public string SeUsaEnPresupuestos { get; set; }
        public Nullable<int> OrdenPresentacion { get; set; }
        public Nullable<byte> EnviarEmail { get; set; }
    
        public virtual ICollection<Requerimiento> Requerimientos { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
    }
}
