//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int IdStock { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> CantidadUnidades { get; set; }
        public Nullable<decimal> CantidadAdicional { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> NumeroCaja { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<decimal> Equivalencia { get; set; }
        public Nullable<decimal> CantidadEquivalencia { get; set; }
        public Nullable<int> IdColor { get; set; }
        public string Talle { get; set; }
    }
}
