//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposRetencionGanancia
    {
        public TiposRetencionGanancia()
        {
            this.Ganancias = new HashSet<Ganancia>();
        }
    
        public int IdTipoRetencionGanancia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CodigoImpuestoAFIP { get; set; }
        public Nullable<int> CodigoRegimenAFIP { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<int> ProximoNumeroCertificadoRetencionGanancias { get; set; }
        public string BienesOServicios { get; set; }
    
        public virtual ICollection<Ganancia> Ganancias { get; set; }
    }
}
