//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposRetencionGanancia
    {
        public TiposRetencionGanancia()
        {
            this.Ganancias = new HashSet<Ganancia>();
        }
    
        public int IdTipoRetencionGanancia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CodigoImpuestoAFIP { get; set; }
        public Nullable<int> CodigoRegimenAFIP { get; set; }
        public string InformacionAuxiliar { get; set; }
        public Nullable<int> ProximoNumeroCertificadoRetencionGanancias { get; set; }
        public string BienesOServicios { get; set; }
    
        public virtual ICollection<Ganancia> Ganancias { get; set; }
    }
}
