//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Articulos = new HashSet<Articulo>();
            this.DetalleRequerimientos = new HashSet<DetalleRequerimiento>();
            this.DetallePedidos = new HashSet<DetallePedido>();
            this.DetallePresupuestos = new HashSet<DetallePresupuesto>();
            this.DetalleRemitos = new HashSet<DetalleRemito>();
            this.DetalleOrdenesCompras = new HashSet<DetalleOrdenesCompra>();
            this.DetalleFacturas = new HashSet<DetalleFactura>();
            this.DetalleArticulosUnidades = new HashSet<DetalleArticulosUnidade>();
            this.DetalleComparativas = new HashSet<DetalleComparativa>();
        }
    
        public int IdUnidad { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public string CodigoAFIP { get; set; }
        public Nullable<int> UnidadesPorPack { get; set; }
        public Nullable<decimal> TaraEnKg { get; set; }
    
        public virtual ICollection<Articulo> Articulos { get; set; }
        public virtual ICollection<DetalleRequerimiento> DetalleRequerimientos { get; set; }
        public virtual ICollection<DetallePedido> DetallePedidos { get; set; }
        public virtual ICollection<DetallePresupuesto> DetallePresupuestos { get; set; }
        public virtual ICollection<DetalleRemito> DetalleRemitos { get; set; }
        public virtual ICollection<DetalleOrdenesCompra> DetalleOrdenesCompras { get; set; }
        public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }
        public virtual ICollection<DetalleArticulosUnidade> DetalleArticulosUnidades { get; set; }
        public virtual ICollection<DetalleComparativa> DetalleComparativas { get; set; }
    }
}
