//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosRelacionFertilizantesTiposDespacho
    {
        public int IdUsuariosRelacionFertilizantesTiposDespacho { get; set; }
        public Nullable<int> IdFertilizantesTiposDespacho { get; set; }
        public Nullable<System.Guid> UsuarioEnBaseBDLMaster { get; set; }
    
        public virtual FertilizantesTiposDespacho FertilizantesTiposDespacho { get; set; }
    }
}
