//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresFaltantesVisto
    {
        public int IdValorFaltanteVisto { get; set; }
        public Nullable<int> IdBancoChequera { get; set; }
        public Nullable<decimal> NumeroCheque { get; set; }
        public Nullable<int> IdUsuarioMarco { get; set; }
        public Nullable<System.DateTime> FechaMarcado { get; set; }
        public string MotivoMarcado { get; set; }
    }
}
