//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresFaltantesVisto
    {
        public int IdValorFaltanteVisto { get; set; }
        public Nullable<int> IdBancoChequera { get; set; }
        public Nullable<decimal> NumeroCheque { get; set; }
        public Nullable<int> IdUsuarioMarco { get; set; }
        public Nullable<System.DateTime> FechaMarcado { get; set; }
        public string MotivoMarcado { get; set; }
    }
}
