//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WilliamsMailFiltrosCola
    {
        public int IdWilliamsMailFiltroCola { get; set; }
        public int IdWilliamsMailFiltro { get; set; }
        public string Descripcion { get; set; }
        public string Emails { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string EsPosicion { get; set; }
        public string Enviar { get; set; }
        public string EsMailOesFax { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Modo { get; set; }
        public string AplicarANDuORalFiltro { get; set; }
        public Nullable<int> Vendedor { get; set; }
        public Nullable<int> CuentaOrden1 { get; set; }
        public Nullable<int> CuentaOrden2 { get; set; }
        public Nullable<int> Corredor { get; set; }
        public Nullable<int> Entregador { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<int> Destino { get; set; }
        public Nullable<int> Procedencia { get; set; }
        public string AuxiliarString1 { get; set; }
        public string AuxiliarString2 { get; set; }
        public string UltimoResultado { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public string QueContenga { get; set; }
        public string EstadoDeCartaPorte { get; set; }
        public Nullable<int> IdUsuarioEncolo { get; set; }
        public Nullable<int> AgrupadorDeTandaPeriodos { get; set; }
        public string ModoImpresion { get; set; }
        public Nullable<int> Corredor2 { get; set; }
        public string EnumSyngentaDivision { get; set; }
    }
}
