//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wTempCartasPorteFacturacionAutomatica_EF
    {
        public int IdTempCartasPorteFacturacionAutomatica { get; set; }
        public Nullable<int> IdSesion { get; set; }
        public Nullable<int> IdCartaDePorte { get; set; }
        public Nullable<int> IdFacturarselaA { get; set; }
        public Nullable<int> ColumnaTilde { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<long> NumeroCartaDePorte { get; set; }
        public Nullable<int> SubNumeroVagon { get; set; }
        public Nullable<int> SubnumeroDeFacturacion { get; set; }
        public Nullable<System.DateTime> FechaArribo { get; set; }
        public Nullable<System.DateTime> FechaDescarga { get; set; }
        public string FacturarselaA { get; set; }
        public string Confirmado { get; set; }
        public Nullable<int> IdCodigoIVA { get; set; }
        public string CUIT { get; set; }
        public string ClienteSeparado { get; set; }
        public Nullable<decimal> TarifaFacturada { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> KgNetos { get; set; }
        public Nullable<int> IdCorredor { get; set; }
        public Nullable<int> IdTitular { get; set; }
        public Nullable<int> IdIntermediario { get; set; }
        public Nullable<int> IdRComercial { get; set; }
        public string Titular { get; set; }
        public string RComercial { get; set; }
        public string Corredor { get; set; }
        public string Destinatario { get; set; }
        public string Procedcia { get; set; }
        public string DestinoDesc { get; set; }
        public Nullable<int> IdDestino { get; set; }
        public string AgregaItemDeGastosAdministrativos { get; set; }
    }
}
