CREATE Procedure [dbo].[SubcontratosDatos_A]

@IdSubcontratoDatos int output,
@NumeroSubcontrato int,
@DescripcionSubcontrato varchar(50),
@IdProveedor int,
@Fecha datetime,
@FechaInicio datetime,
@FechaFinalizacion datetime,
@Adjunto1 varchar(100),
@Adjunto2 varchar(100),
@Adjunto3 varchar(100),
@Adjunto4 varchar(100),
@Adjunto5 varchar(100),
@Adjunto6 varchar(100),
@Adjunto7 varchar(100),
@Adjunto8 varchar(100),
@Adjunto9 varchar(100),
@Adjunto10 varchar(100),
@CondicionPago varchar(50),
@AnticipoFinanciero varchar(50),
@Acopio varchar(50),
@FondoReparo numeric(6,2),
@PorcentajeAnticipoFinanciero numeric(6,2),
@IdMoneda int,
@Observaciones ntext,
@Anulado varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@IdObra int

AS 

INSERT INTO [SubcontratosDatos]
(
 NumeroSubcontrato,
 DescripcionSubcontrato,
 IdProveedor,
 Fecha,
 FechaInicio,
 FechaFinalizacion,
 Adjunto1,
 Adjunto2,
 Adjunto3,
 Adjunto4,
 Adjunto5,
 Adjunto6,
 Adjunto7,
 Adjunto8,
 Adjunto9,
 Adjunto10,
 CondicionPago,
 AnticipoFinanciero,
 Acopio,
 FondoReparo,
 PorcentajeAnticipoFinanciero,
 IdMoneda,
 Observaciones,
 Anulado,
 IdUsuarioAnulo,
 FechaAnulacion,
 MotivoAnulacion,
 IdObra
)
VALUES
(
 @NumeroSubcontrato,
 @DescripcionSubcontrato,
 @IdProveedor,
 @Fecha,
 @FechaInicio,
 @FechaFinalizacion,
 @Adjunto1,
 @Adjunto2,
 @Adjunto3,
 @Adjunto4,
 @Adjunto5,
 @Adjunto6,
 @Adjunto7,
 @Adjunto8,
 @Adjunto9,
 @Adjunto10,
 @CondicionPago,
 @AnticipoFinanciero,
 @Acopio,
 @FondoReparo,
 @PorcentajeAnticipoFinanciero,
 @IdMoneda,
 @Observaciones,
 @Anulado,
 @IdUsuarioAnulo,
 @FechaAnulacion,
 @MotivoAnulacion,
 @IdObra
)

SELECT @IdSubcontratoDatos=@@identity

RETURN(@IdSubcontratoDatos)