CREATE Procedure [dbo].[TiposComprobante_A]

@IdTipoComprobante int  output,
@Descripcion varchar(50),
@Coeficiente smallint,
@DescripcionAb varchar(5),
@EsValor varchar(2),
@CodigoDgi varchar(2),
@Agrupacion1 varchar(20),
@CalculaDiferenciaCambio varchar(2),
@VaAlLibro varchar(2),
@PideBancoCuenta varchar(2),
@PideCuenta varchar(2),
@IdCuentaDefault int,
@VaAConciliacionBancaria varchar(2),
@LlevarAPesosEnValores varchar(2),
@CoeficienteParaFondoFijo int,
@CoeficienteParaConciliaciones int,
@VaAlCITI varchar(2),
@VaAlRegistroComprasAFIP varchar(2),
@CodigoAFIP_Letra_A varchar(2),
@CodigoAFIP_Letra_B varchar(2),
@CodigoAFIP_Letra_C varchar(2),
@CodigoAFIP_Letra_E varchar(2),
@InformacionAuxiliar varchar(50),
@ExigirCAI varchar(2),
@NumeradorAuxiliar int,
@CodigoAFIP2_Letra_A varchar(2),
@CodigoAFIP2_Letra_B varchar(2),
@CodigoAFIP2_Letra_C varchar(2),
@CodigoAFIP2_Letra_E varchar(2),
@CodigoAFIP3_Letra_A varchar(2),
@CodigoAFIP3_Letra_B varchar(2),
@CodigoAFIP3_Letra_C varchar(2),
@CodigoAFIP3_Letra_E varchar(2)

AS 

INSERT INTO [TiposComprobante]
(
 Descripcion,
 Coeficiente,
 DescripcionAb,
 EsValor,
 CodigoDgi,
 Agrupacion1,
 CalculaDiferenciaCambio,
 VaAlLibro,
 PideBancoCuenta,
 PideCuenta,
 IdCuentaDefault,
 VaAConciliacionBancaria,
 LlevarAPesosEnValores,
 CoeficienteParaFondoFijo,
 CoeficienteParaConciliaciones,
 VaAlCITI,
 VaAlRegistroComprasAFIP,
 CodigoAFIP_Letra_A,
 CodigoAFIP_Letra_B,
 CodigoAFIP_Letra_C,
 CodigoAFIP_Letra_E,
 InformacionAuxiliar,
 ExigirCAI,
 NumeradorAuxiliar,
 CodigoAFIP2_Letra_A,
 CodigoAFIP2_Letra_B,
 CodigoAFIP2_Letra_C,
 CodigoAFIP2_Letra_E,
 CodigoAFIP3_Letra_A,
 CodigoAFIP3_Letra_B,
 CodigoAFIP3_Letra_C,
 CodigoAFIP3_Letra_E
)
VALUES 
(
 @Descripcion,
 @Coeficiente,
 @DescripcionAb,
 @EsValor,
 @CodigoDgi,
 @Agrupacion1,
 @CalculaDiferenciaCambio,
 @VaAlLibro,
 @PideBancoCuenta,
 @PideCuenta,
 @IdCuentaDefault,
 @VaAConciliacionBancaria,
 @LlevarAPesosEnValores,
 @CoeficienteParaFondoFijo,
 @CoeficienteParaConciliaciones,
 @VaAlCITI,
 @VaAlRegistroComprasAFIP,
 @CodigoAFIP_Letra_A,
 @CodigoAFIP_Letra_B,
 @CodigoAFIP_Letra_C,
 @CodigoAFIP_Letra_E,
 @InformacionAuxiliar,
 @ExigirCAI,
 @NumeradorAuxiliar,
 @CodigoAFIP2_Letra_A,
 @CodigoAFIP2_Letra_B,
 @CodigoAFIP2_Letra_C,
 @CodigoAFIP2_Letra_E,
 @CodigoAFIP3_Letra_A,
 @CodigoAFIP3_Letra_B,
 @CodigoAFIP3_Letra_C,
 @CodigoAFIP3_Letra_E
)

SELECT @IdTipoComprobante=@@identity

RETURN(@IdTipoComprobante)