CREATE Procedure [dbo].[Valores_M]

@IdValor int,
@IdTipoValor int,
@NumeroValor numeric(18,0),
@FechaValor datetime,
@NumeroInterno int,
@IdTipoComprobante int,
@NumeroComprobante int,
@FechaComprobante datetime,
@IdCliente int,
@IdDetalleReciboValores int,
@IdBanco int,
@Importe numeric(18,2),
@Estado varchar(1),
@IdBancoDeposito int,
@NumeroDeposito int,
@FechaDeposito datetime,
@IdProveedor int,
@NumeroOrdenPago int,
@FechaOrdenPago datetime,
@IdCuenta int,
@NumeroSalida int,
@FechaSalida datetime,
@IdCuentaOrigen int,
@FechaEntrada datetime,
@FechaEntradaActivada varchar(2),
@Conciliado varchar(2),
@IdCuentaBancaria int,
@IdCuentaBancariaDeposito int,
@IVA numeric(18,2),
@IdObra int,
@IdCuentaGasto int,
@IdCuentaContable int,
@IdCuentaIVA int,
@PorcentajeIVA numeric(6,2),
@IdDetalleOrdenPagoCuentas int,
@IdCaja int,
@IdDetalleOrdenPagoValores int,
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@IdDetalleComprobanteProveedor int,
@IdDetalleAsiento int,
@CuitLibrador varchar(13),
@IdConciliacion int,
@Emitido varchar(2),
@FechaEmision datetime,
@IdEmitio int,
@IdDetalleReciboCuentas int,
@MovimientoConfirmadoBanco varchar(2),
@FechaConfirmacionBanco datetime,
@IdUsuarioConfirmacionBanco int,
@IdPlazoFijoInicio int,
@IdPlazoFijoFin int,
@FechaGasto datetime,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@Detalle varchar(30),
@IdDetalleNotaDebito int,
@IdDetalleNotaCredito int,
@RegistroContableChequeDiferido varchar(2),
@EnviarEmail tinyint,
@IdOrigenTransmision int,
@IdValorOriginal int,
@FechaImportacionTransmision datetime,
@IdDetalleReciboValoresOriginal int,
@CuitClienteTransmision varchar(13),
@CertificadoRetencion varchar(20),
@AsientoManual varchar(2),
@Anulado varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion varchar(30),
@Rechazado varchar(2),
@IdTarjetaCredito int,
@NumeroTarjetaCredito varchar(20),
@NumeroAutorizacionTarjetaCredito int,
@CantidadCuotas int,
@FechaExpiracionTarjetaCredito varchar(5),
@IdFactura int,
@IdDetallePresentacionTarjeta int,
@IdOrigen int,
@OrigenRegistro varchar(12),
@IdReciboAsignado int

AS 

UPDATE Valores
SET 
 IdTipoValor=@IdTipoValor,
 NumeroValor=@NumeroValor,
 FechaValor=@FechaValor,
 NumeroInterno=@NumeroInterno,
 IdTipoComprobante=@IdTipoComprobante,
 NumeroComprobante=@NumeroComprobante,
 FechaComprobante=@FechaComprobante,
 IdCliente=@IdCliente,
 IdDetalleReciboValores=@IdDetalleReciboValores,
 IdBanco=@IdBanco,
 Importe=@Importe,
 Estado=@Estado,
 IdBancoDeposito=@IdBancoDeposito,
 NumeroDeposito=@NumeroDeposito,
 FechaDeposito=@FechaDeposito,
 IdProveedor=@IdProveedor,
 NumeroOrdenPago=@NumeroOrdenPago,
 FechaOrdenPago=@FechaOrdenPago,
 IdCuenta=@IdCuenta,
 NumeroSalida=@NumeroSalida,
 FechaSalida=@FechaSalida,
 IdCuentaOrigen=@IdCuentaOrigen,
 FechaEntrada=@FechaEntrada,
 FechaEntradaActivada=@FechaEntradaActivada,
 Conciliado=@Conciliado,
 IdCuentaBancaria=@IdCuentaBancaria,
 IdCuentaBancariaDeposito=@IdCuentaBancariaDeposito,
 IVA=@IVA,
 IdObra=@IdObra,
 IdCuentaGasto=@IdCuentaGasto,
 IdCuentaContable=@IdCuentaContable,
 IdCuentaIVA=@IdCuentaIVA,
 PorcentajeIVA=@PorcentajeIVA,
 IdDetalleOrdenPagoCuentas=@IdDetalleOrdenPagoCuentas,
 IdCaja=@IdCaja,
 IdDetalleOrdenPagoValores=@IdDetalleOrdenPagoValores,
 IdMoneda=@IdMoneda,
 CotizacionMoneda=@CotizacionMoneda,
 IdDetalleComprobanteProveedor=@IdDetalleComprobanteProveedor,
 IdDetalleAsiento=@IdDetalleAsiento,
 CuitLibrador=@CuitLibrador,
 IdConciliacion=@IdConciliacion,
 Emitido=@Emitido,
 FechaEmision=@FechaEmision,
 IdEmitio=@IdEmitio,
 IdDetalleReciboCuentas=@IdDetalleReciboCuentas,
 MovimientoConfirmadoBanco=@MovimientoConfirmadoBanco,
 FechaConfirmacionBanco=@FechaConfirmacionBanco,
 IdUsuarioConfirmacionBanco=@IdUsuarioConfirmacionBanco,
 IdPlazoFijoInicio=@IdPlazoFijoInicio,
 IdPlazoFijoFin=@IdPlazoFijoFin,
 FechaGasto=@FechaGasto,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaModifico=@FechaModifico,
 Detalle=@Detalle,
 IdDetalleNotaDebito=@IdDetalleNotaDebito,
 IdDetalleNotaCredito=@IdDetalleNotaCredito,
 RegistroContableChequeDiferido=@RegistroContableChequeDiferido,
 EnviarEmail=@EnviarEmail,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdValorOriginal=@IdValorOriginal, FechaImportacionTransmision=@FechaImportacionTransmision,
 IdDetalleReciboValoresOriginal=@IdDetalleReciboValoresOriginal,
 CuitClienteTransmision=@CuitClienteTransmision,
 CertificadoRetencion=@CertificadoRetencion,
 AsientoManual=@AsientoManual,
 Anulado=@Anulado,
 IdUsuarioAnulo=@IdUsuarioAnulo,
 FechaAnulacion=@FechaAnulacion,
 MotivoAnulacion=@MotivoAnulacion,
 Rechazado=@Rechazado,
 IdTarjetaCredito=@IdTarjetaCredito,
 NumeroTarjetaCredito=@NumeroTarjetaCredito,
 NumeroAutorizacionTarjetaCredito=@NumeroAutorizacionTarjetaCredito,
 CantidadCuotas=@CantidadCuotas,
 FechaExpiracionTarjetaCredito=@FechaExpiracionTarjetaCredito,
 IdFactura=@IdFactura,
 IdDetallePresentacionTarjeta=@IdDetallePresentacionTarjeta,
 IdOrigen=@IdOrigen,
 OrigenRegistro=@OrigenRegistro,
 IdReciboAsignado=@IdReciboAsignado
WHERE (IdValor=@IdValor)

RETURN(@IdValor)