CREATE Procedure [dbo].[Valores_A]

@IdValor int  output,
@IdTipoValor int,
@NumeroValor numeric(18,0),
@FechaValor datetime,
@NumeroInterno int,
@IdTipoComprobante int,
@NumeroComprobante int,
@FechaComprobante datetime,
@IdCliente int,
@IdDetalleReciboValores int,
@IdBanco int,
@Importe numeric(18,2),
@Estado varchar(1),
@IdBancoDeposito int,
@NumeroDeposito int,
@FechaDeposito datetime,
@IdProveedor int,
@NumeroOrdenPago int,
@FechaOrdenPago datetime,
@IdCuenta int,
@NumeroSalida int,
@FechaSalida datetime,
@IdCuentaOrigen int,
@FechaEntrada datetime,
@FechaEntradaActivada varchar(2),
@Conciliado varchar(2),
@IdCuentaBancaria int,
@IdCuentaBancariaDeposito int,
@IVA numeric(18,2),
@IdObra int,
@IdCuentaGasto int,
@IdCuentaContable int,
@IdCuentaIVA int,
@PorcentajeIVA numeric(6,2),
@IdDetalleOrdenPagoCuentas int,
@IdCaja int,
@IdDetalleOrdenPagoValores int,
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@IdDetalleComprobanteProveedor int,
@IdDetalleAsiento int,
@CuitLibrador varchar(13),
@IdConciliacion int,
@Emitido varchar(2),
@FechaEmision datetime,
@IdEmitio int,
@IdDetalleReciboCuentas int,
@MovimientoConfirmadoBanco varchar(2),
@FechaConfirmacionBanco datetime,
@IdUsuarioConfirmacionBanco int,
@IdPlazoFijoInicio int,
@IdPlazoFijoFin int,
@FechaGasto datetime,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@Detalle varchar(30),
@IdDetalleNotaDebito int,
@IdDetalleNotaCredito int,
@RegistroContableChequeDiferido varchar(2),
@EnviarEmail tinyint,
@IdOrigenTransmision int,
@IdValorOriginal int,
@FechaImportacionTransmision datetime,
@IdDetalleReciboValoresOriginal int,
@CuitClienteTransmision varchar(13),
@CertificadoRetencion varchar(20),
@AsientoManual varchar(2),
@Anulado varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion varchar(30),
@Rechazado varchar(2),
@IdTarjetaCredito int,
@NumeroTarjetaCredito varchar(20),
@NumeroAutorizacionTarjetaCredito int,
@CantidadCuotas int,
@FechaExpiracionTarjetaCredito varchar(5),
@IdFactura int,
@IdDetallePresentacionTarjeta int,
@IdOrigen int,
@OrigenRegistro varchar(12),
@IdReciboAsignado int

AS 

INSERT INTO [Valores]
(
 IdTipoValor,
 NumeroValor,
 FechaValor,
 NumeroInterno,
 IdTipoComprobante,
 NumeroComprobante,
 FechaComprobante,
 IdCliente,
 IdDetalleReciboValores,
 IdBanco,
 Importe,
 Estado,
 IdBancoDeposito,
 NumeroDeposito,
 FechaDeposito,
 IdProveedor,
 NumeroOrdenPago,
 FechaOrdenPago,
 IdCuenta,
 NumeroSalida,
 FechaSalida,
 IdCuentaOrigen,
 FechaEntrada,
 FechaEntradaActivada,
 Conciliado,
 IdCuentaBancaria,
 IdCuentaBancariaDeposito,
 IVA,
 IdObra,
 IdCuentaGasto,
 IdCuentaContable,
 IdCuentaIVA,
 PorcentajeIVA,
 IdDetalleOrdenPagoCuentas,
 IdCaja,
 IdDetalleOrdenPagoValores,
 IdMoneda,
 CotizacionMoneda,
 IdDetalleComprobanteProveedor,
 IdDetalleAsiento,
 CuitLibrador,
 IdConciliacion,
 Emitido,
 FechaEmision,
 IdEmitio,
 IdDetalleReciboCuentas,
 MovimientoConfirmadoBanco,
 FechaConfirmacionBanco,
 IdUsuarioConfirmacionBanco,
 IdPlazoFijoInicio,
 IdPlazoFijoFin,
 FechaGasto,
 IdUsuarioIngreso,
 FechaIngreso,
 IdUsuarioModifico,
 FechaModifico,
 Detalle,
 IdDetalleNotaDebito,
 IdDetalleNotaCredito,
 RegistroContableChequeDiferido,
 EnviarEmail,
 IdOrigenTransmision,
 IdValorOriginal,
 FechaImportacionTransmision,
 IdDetalleReciboValoresOriginal,
 CuitClienteTransmision,
 CertificadoRetencion,
 AsientoManual,
 Anulado,
 IdUsuarioAnulo,
 FechaAnulacion,
 MotivoAnulacion,
 Rechazado,
 IdTarjetaCredito,
 NumeroTarjetaCredito,
 NumeroAutorizacionTarjetaCredito,
 CantidadCuotas,
 FechaExpiracionTarjetaCredito,
 IdFactura,
 IdDetallePresentacionTarjeta,
 IdOrigen, 
 OrigenRegistro,
 IdReciboAsignado
)
VALUES 
(
 @IdTipoValor,
 @NumeroValor,
 @FechaValor,
 @NumeroInterno,
 @IdTipoComprobante,
 @NumeroComprobante,
 @FechaComprobante,
 @IdCliente,
 @IdDetalleReciboValores,
 @IdBanco,
 @Importe,
 @Estado,
 @IdBancoDeposito,
 @NumeroDeposito,
 @FechaDeposito,
 @IdProveedor,
 @NumeroOrdenPago,
 @FechaOrdenPago,
 @IdCuenta,
 @NumeroSalida,
 @FechaSalida,
 @IdCuentaOrigen,
 @FechaEntrada,
 @FechaEntradaActivada,
 @Conciliado,
 @IdCuentaBancaria,
 @IdCuentaBancariaDeposito,
 @IVA,
 @IdObra,
 @IdCuentaGasto,
 @IdCuentaContable,
 @IdCuentaIVA,
 @PorcentajeIVA,
 @IdDetalleOrdenPagoCuentas,
 @IdCaja,
 @IdDetalleOrdenPagoValores,
 @IdMoneda,
 @CotizacionMoneda,
 @IdDetalleComprobanteProveedor,
 @IdDetalleAsiento,
 @CuitLibrador,
 @IdConciliacion,
 @Emitido,
 @FechaEmision,
 @IdEmitio,
 @IdDetalleReciboCuentas,
 @MovimientoConfirmadoBanco,
 @FechaConfirmacionBanco,
 @IdUsuarioConfirmacionBanco,
 @IdPlazoFijoInicio,
 @IdPlazoFijoFin, @FechaGasto,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @IdUsuarioModifico,
 @FechaModifico,
 @Detalle,
 @IdDetalleNotaDebito,
 @IdDetalleNotaCredito,
 @RegistroContableChequeDiferido, @EnviarEmail,
 @IdOrigenTransmision,
 @IdValorOriginal,
 @FechaImportacionTransmision,
 @IdDetalleReciboValoresOriginal,
 @CuitClienteTransmision,
 @CertificadoRetencion,
 @AsientoManual,
 @Anulado,
 @IdUsuarioAnulo,
 @FechaAnulacion,
 @MotivoAnulacion,
 @Rechazado,
 @IdTarjetaCredito,
 @NumeroTarjetaCredito,
 @NumeroAutorizacionTarjetaCredito,
 @CantidadCuotas,
 @FechaExpiracionTarjetaCredito,
 @IdFactura,
 @IdDetallePresentacionTarjeta,
 @IdOrigen,
 @OrigenRegistro,
 @IdReciboAsignado
)

SELECT @IdValor=@@identity

RETURN(@IdValor)