
CREATE Procedure [dbo].[wDetPedidos_A]

@IdDetallePedido int,
@IdPedido int,
@NumeroItem int,
@Cantidad numeric(12,2),
@IdUnidad int,
@IdArticulo int,
@FechaEntrega datetime,
@Precio numeric(12,4),
@Observaciones ntext,
@IdDetalleAcopios int,
@IdDetalleRequerimiento int,
@Cumplido varchar(2),
@FechaNecesidad datetime,
@IdDetalleLMateriales int,
@IdCuenta int,
@OrigenDescripcion int,
@IdAutorizoCumplido int,
@IdDioPorCumplido int,
@FechaDadoPorCumplido datetime,
@ObservacionesCumplido ntext,
@PorcentajeBonificacion numeric(6,2),
@ImporteBonificacion numeric(18,4),
@PorcentajeIVA numeric(6,2),
@ImporteIVA numeric(18,4),
@ImporteTotalItem numeric(18,4),
@Costo numeric(18,2),
@IdAsignacionCosto int,
@CostoAsignado numeric(18,4),
@IdUsuarioAsignoCosto int,
@FechaAsignacionCosto datetime,
@IdDetallePedidoOriginal int,
@IdPedidoOriginal int,
@IdOrigenTransmision int,
@PlazoEntrega varchar(50),
@CostoAsignadoDolar numeric(18,4),
@IdDetalleComparativa int,
@IdDetalleRequerimientoOriginal int

AS 

IF IsNull(@IdDetallePedido,0)<=0
    BEGIN
	INSERT INTO [DetallePedidos]
	(
	 IdPedido,
	 NumeroItem,
	 Cantidad,
	 IdUnidad,
	 IdArticulo,
	 FechaEntrega,
	 Precio,
	 Observaciones,
	 IdDetalleAcopios,
	 IdDetalleRequerimiento,
	 Cumplido,
	 FechaNecesidad,
	 IdDetalleLMateriales,
	 IdCuenta,
	 OrigenDescripcion,
	 IdAutorizoCumplido,
	 IdDioPorCumplido,
	 FechaDadoPorCumplido,
	 ObservacionesCumplido,
	 PorcentajeBonificacion,
	 ImporteBonificacion,
	 PorcentajeIVA,
	 ImporteIVA,
	 ImporteTotalItem,
	 Costo,
	 IdAsignacionCosto,
	 CostoAsignado,
	 IdUsuarioAsignoCosto,
	 FechaAsignacionCosto,
	 IdDetallePedidoOriginal,
	 IdPedidoOriginal,
	 IdOrigenTransmision,
	 PlazoEntrega,
	 CostoAsignadoDolar,
	 IdDetalleComparativa,
	 IdDetalleRequerimientoOriginal
	)
	VALUES
	(
	 @IdPedido,
	 @NumeroItem,
	 @Cantidad,
	 @IdUnidad,
	 @IdArticulo,
	 @FechaEntrega,
	 @Precio,
	 @Observaciones,
	 @IdDetalleAcopios,
	 @IdDetalleRequerimiento,
	 @Cumplido,
	 @FechaNecesidad,
	 @IdDetalleLMateriales,
	 @IdCuenta,
	 @OrigenDescripcion,
	 @IdAutorizoCumplido,
	 @IdDioPorCumplido,
	 @FechaDadoPorCumplido,
	 @ObservacionesCumplido,
	 @PorcentajeBonificacion,
	 @ImporteBonificacion,
	 @PorcentajeIVA,
	 @ImporteIVA,
	 @ImporteTotalItem,
	 @Costo,
	 @IdAsignacionCosto,
	 @CostoAsignado,
	 @IdUsuarioAsignoCosto,
	 @FechaAsignacionCosto,
	 @IdDetallePedidoOriginal,
	 @IdPedidoOriginal,
	 @IdOrigenTransmision,
	 @PlazoEntrega,
	 @CostoAsignadoDolar,
	 @IdDetalleComparativa,
	 @IdDetalleRequerimientoOriginal
	)
	SELECT @IdDetallePedido=@@identity
    END
ELSE
    BEGIN
	UPDATE [DetallePedidos]
	SET 
	 IdPedido=@IdPedido,
	 NumeroItem=@NumeroItem,
	 Cantidad=@Cantidad,
	 IdUnidad=@IdUnidad,
	 IdArticulo=@IdArticulo,
	 FechaEntrega=@FechaEntrega,
	 Precio=@Precio,
	 Observaciones=@Observaciones,
	 IdDetalleAcopios=@IdDetalleAcopios,
	 IdDetalleRequerimiento=@IdDetalleRequerimiento,
	 Cumplido=@Cumplido,
	 FechaNecesidad=@FechaNecesidad,
	 IdDetalleLMateriales=@IdDetalleLMateriales,
	 IdCuenta=@IdCuenta,
	 OrigenDescripcion=@OrigenDescripcion,
	 IdAutorizoCumplido=@IdAutorizoCumplido,
	 IdDioPorCumplido=@IdDioPorCumplido,
	 FechaDadoPorCumplido=@FechaDadoPorCumplido,
	 ObservacionesCumplido=@ObservacionesCumplido,
	 PorcentajeBonificacion=@PorcentajeBonificacion,
	 ImporteBonificacion=@ImporteBonificacion,
	 PorcentajeIVA=@PorcentajeIVA,
	 ImporteIVA=@ImporteIVA,
	 ImporteTotalItem=@ImporteTotalItem,
	 Costo=@Costo,
	 IdAsignacionCosto=@IdAsignacionCosto,
	 CostoAsignado=@CostoAsignado,
	 IdUsuarioAsignoCosto=@IdUsuarioAsignoCosto,
	 FechaAsignacionCosto=@FechaAsignacionCosto,
	 IdDetallePedidoOriginal=@IdDetallePedidoOriginal,
	 IdPedidoOriginal=@IdPedidoOriginal,
	 IdOrigenTransmision=@IdOrigenTransmision,
	 PlazoEntrega=@PlazoEntrega,
	 CostoAsignadoDolar=@CostoAsignadoDolar,
	 IdDetalleComparativa=@IdDetalleComparativa,
	 IdDetalleRequerimientoOriginal=@IdDetalleRequerimientoOriginal
	WHERE (IdDetallePedido=@IdDetallePedido)
    END

IF @@ERROR <> 0
	RETURN -1
ELSE
	RETURN @IdDetallePedido

