
CREATE Procedure [dbo].[wObras_A]

@IdObra int  output,
@NumeroObra varchar(13),
@IdCliente int,
@FechaInicio datetime,
@FechaFinalizacion datetime,
@Observaciones ntext,
@FechaEntrega datetime,
@Descripcion varchar(50),
@IdJefe int,
@TipoObra int,
@HorasEstimadas int,
@Consorcial varchar(2),
@EnviarEmail tinyint,
@Activa varchar(2),
@ParaInformes varchar(2),
@IdUnidadOperativa int,
@Jerarquia varchar(20),
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@GeneraReservaStock varchar(2),
@IdGrupoObra int,
@IdArticuloAsociado int,
@Observaciones2 ntext,
@Observaciones3 ntext,
@IdSubjefe int,
@Direccion varchar(50),
@IdLocalidad int,
@IdProvincia int,
@IdPais int,
@CodigoPostal varchar(30),
@Telefono varchar(50),
@LugarPago varchar(50),
@Responsable varchar(50),
@Horario varchar(20),
@Turnos varchar(10),
@Operarios int,
@Zona int,
@Jurisdiccion int,
@IdCuentaContableFF int,
@ValorObra numeric(18,2),
@IdMonedaValorObra int,
@IdJefeRegional int

AS

IF IsNull(@IdObra,0)<=0
    BEGIN
	INSERT INTO [Obras]
	(
	 NumeroObra,
	 IdCliente,
	 FechaInicio,
	 FechaFinalizacion,
	 Observaciones,
	 FechaEntrega,
	 Descripcion,
	 IdJefe,
	 TipoObra,
	 HorasEstimadas,
	 Consorcial,
	 EnviarEmail,
	 Activa,
	 ParaInformes,
	 IdUnidadOperativa,
	 Jerarquia,
	 ArchivoAdjunto1,
	 ArchivoAdjunto2,
	 ArchivoAdjunto3,
	 ArchivoAdjunto4,
	 ArchivoAdjunto5,
	 ArchivoAdjunto6,
	 ArchivoAdjunto7,
	 ArchivoAdjunto8,
	 ArchivoAdjunto9,
	 ArchivoAdjunto10,
	 GeneraReservaStock,
	 IdGrupoObra,
	 IdArticuloAsociado,
	 Observaciones2,
	 Observaciones3,
	 IdSubjefe,
	 Direccion,
	 IdLocalidad,
	 IdProvincia,
	 IdPais,
	 CodigoPostal,
	 Telefono,
	 LugarPago,
	 Responsable,
	 Horario,
	 Turnos,
	 Operarios,
	 Zona,
	 Jurisdiccion,
	 IdCuentaContableFF,
	 ValorObra,
	 IdMonedaValorObra,
	 IdJefeRegional
	)
	VALUES
	(
	 @NumeroObra,
	 @IdCliente,
	 @FechaInicio,
	 @FechaFinalizacion,
	 @Observaciones,
	 @FechaEntrega,
	 @Descripcion,
	 @IdJefe,
	 @TipoObra,
	 @HorasEstimadas,
	 @Consorcial,
	 @EnviarEmail,
	 @Activa,
	 @ParaInformes,
	 @IdUnidadOperativa,
	 @Jerarquia,
	 @ArchivoAdjunto1,
	 @ArchivoAdjunto2,
	 @ArchivoAdjunto3,
	 @ArchivoAdjunto4,
	 @ArchivoAdjunto5,
	 @ArchivoAdjunto6,
	 @ArchivoAdjunto7,
	 @ArchivoAdjunto8,
	 @ArchivoAdjunto9,
	 @ArchivoAdjunto10,
	 @GeneraReservaStock,
	 @IdGrupoObra,
	 @IdArticuloAsociado,
	 @Observaciones2,
	 @Observaciones3,
	 @IdSubjefe,
	 @Direccion,
	 @IdLocalidad,
	 @IdProvincia,
	 @IdPais,
	 @CodigoPostal,
	 @Telefono,
	 @LugarPago,
	 @Responsable,
	 @Horario,
	 @Turnos,
	 @Operarios,
	 @Zona,
	 @Jurisdiccion,
	 @IdCuentaContableFF,
	 @ValorObra,
	 @IdMonedaValorObra,
	 @IdJefeRegional
	)
	SELECT @IdObra=@@identity
    END
ELSE
    BEGIN
	UPDATE Obras
	SET 
	 NumeroObra=@NumeroObra,
	 IdCliente=@IdCliente,
	 FechaInicio=@FechaInicio,
	 FechaFinalizacion=@FechaFinalizacion,
	 Observaciones=@Observaciones,
	 FechaEntrega=@FechaEntrega,
	 Descripcion=@Descripcion,
	 IdJefe=@IdJefe,
	 TipoObra=@TipoObra,
	 HorasEstimadas=@HorasEstimadas,
	 Consorcial=@Consorcial,
	 EnviarEmail=@EnviarEmail,
	 Activa=@Activa,
	 ParaInformes=@ParaInformes,
	 IdUnidadOperativa=@IdUnidadOperativa,
	 Jerarquia=@Jerarquia,
	 ArchivoAdjunto1=@ArchivoAdjunto1,
	 ArchivoAdjunto2=@ArchivoAdjunto2,
	 ArchivoAdjunto3=@ArchivoAdjunto3,
	 ArchivoAdjunto4=@ArchivoAdjunto4,
	 ArchivoAdjunto5=@ArchivoAdjunto5,
	 ArchivoAdjunto6=@ArchivoAdjunto6,
	 ArchivoAdjunto7=@ArchivoAdjunto7,
	 ArchivoAdjunto8=@ArchivoAdjunto8,
	 ArchivoAdjunto9=@ArchivoAdjunto9,
	 ArchivoAdjunto10=@ArchivoAdjunto10,
	 GeneraReservaStock=@GeneraReservaStock,
	 IdGrupoObra=@IdGrupoObra,
	 IdArticuloAsociado=@IdArticuloAsociado,
	 Observaciones2=@Observaciones2,
	 Observaciones3=@Observaciones3,
	 IdSubjefe=@IdSubjefe,
	 Direccion=@Direccion,
	 IdLocalidad=@IdLocalidad,
	 IdProvincia=@IdProvincia,
	 IdPais=@IdPais,
	 CodigoPostal=@CodigoPostal,
	 Telefono=@Telefono,
	 LugarPago=@LugarPago,
	 Responsable=@Responsable,
	 Horario=@Horario,
	 Turnos=@Turnos,
	 Operarios=@Operarios,
	 Zona=@Zona,
	 Jurisdiccion=@Jurisdiccion,
	 IdCuentaContableFF=@IdCuentaContableFF,
	 ValorObra=@ValorObra,
	 IdMonedaValorObra=@IdMonedaValorObra,
	 IdJefeRegional=@IdJefeRegional
	WHERE (IdObra=@IdObra)
    END

IF @@ERROR <> 0
	RETURN -1
ELSE
	RETURN @IdObra

