
CREATE Procedure [dbo].[wPresupuestos_A]
@IdPresupuesto int  output,
@Numero int,
@IdProveedor int,
@FechaIngreso datetime,
@Observaciones ntext,
@Bonificacion numeric(6,2),
@Plazo varchar(50),
@validez varchar(50),
@IdCondicionCompra int,
@Garantia varchar(50),
@LugarEntrega varchar(50),
@IdComprador int,
@Referencia varchar(50),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@Detalle varchar(100),
@Contacto varchar(50),
@ImporteBonificacion money,
@ImporteIva1 money,
@ImporteTotal money,
@SubNumero int,
@Aprobo int,
@IdMoneda int,
@FechaAprobacion datetime,
@DetalleCondicionCompra varchar(200),
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@IdPlazoEntrega int,
@CotizacionMoneda numeric(18,3),
@CircuitoFirmasCompleto varchar(2),

@ConfirmadoPorWeb varchar(2),
@FechaCierreCompulsa datetime,

	@NombreUsuarioWeb nvarchar(256), 
	@FechaRespuestaweb datetime
AS 




IF IsNull(@IdPresupuesto,0)<=0
    BEGIN 
			INSERT INTO Presupuestos
			(
			 Numero,
			 IdProveedor,
			 FechaIngreso,
			 Observaciones,
			 Bonificacion,
			 Plazo,
			 validez,
			 IdCondicionCompra,
			 Garantia,
			 LugarEntrega,
			 IdComprador,
			 Referencia,
			 PorcentajeIva1,
			 PorcentajeIva2,
			 Detalle,
			 Contacto,
			 ImporteBonificacion,
			 ImporteIva1,
			 ImporteTotal,
			 SubNumero,
			 Aprobo,
			 IdMoneda,
			 FechaAprobacion,
			 DetalleCondicionCompra,
			 ArchivoAdjunto1,
			 ArchivoAdjunto2,
			 ArchivoAdjunto3,
			 ArchivoAdjunto4,
			 ArchivoAdjunto5,
			 ArchivoAdjunto6,
			 ArchivoAdjunto7,
			 ArchivoAdjunto8,
			 ArchivoAdjunto9,
			 ArchivoAdjunto10,
			 IdPlazoEntrega,
			 CotizacionMoneda,
			 CircuitoFirmasCompleto,

			ConfirmadoPorWeb,
			FechaCierreCompulsa,

			NombreUsuarioWeb, 
			FechaRespuestaweb
			)
			VALUES
			(
			 @Numero,
			 @IdProveedor,
			 @FechaIngreso,
			 @Observaciones,
			 @Bonificacion,
			 @Plazo,
			 @validez,
			 @IdCondicionCompra,
			 @Garantia,
			 @LugarEntrega,
			 @IdComprador,
			 @Referencia,
			 @PorcentajeIva1,
			 @PorcentajeIva2,
			 @Detalle,
			 @Contacto,
			 @ImporteBonificacion,
			 @ImporteIva1,
			 @ImporteTotal,
			 @SubNumero,
			 @Aprobo,
			 @IdMoneda,
			 @FechaAprobacion,
			 @DetalleCondicionCompra,
			 @ArchivoAdjunto1,
			 @ArchivoAdjunto2,
			 @ArchivoAdjunto3,
			 @ArchivoAdjunto4,
			 @ArchivoAdjunto5,
			 @ArchivoAdjunto6,
			 @ArchivoAdjunto7,
			 @ArchivoAdjunto8,
			 @ArchivoAdjunto9,
			 @ArchivoAdjunto10,
			 @IdPlazoEntrega,
			 @CotizacionMoneda,
			 @CircuitoFirmasCompleto,

			@ConfirmadoPorWeb ,
			@FechaCierreCompulsa, 

			@NombreUsuarioWeb , 
			@FechaRespuestaweb 
			)
			SELECT @IdPresupuesto=@@identity
			RETURN(@IdPresupuesto)
 END
 ELSE
 BEGIN
			UPDATE Presupuestos
			SET 
			 Numero=@Numero,
			 IdProveedor=@IdProveedor,
			 FechaIngreso=@FechaIngreso,
			 Observaciones=@Observaciones,
			 Bonificacion=@Bonificacion,
			 Plazo=@Plazo,
			 validez=@validez,
			 IdCondicionCompra=@IdCondicionCompra,
			 Garantia=@Garantia,
			 LugarEntrega=@LugarEntrega,
			 IdComprador=@IdComprador,
			 Referencia=@Referencia,
			 PorcentajeIva1=@PorcentajeIva1,
			 PorcentajeIva2=@PorcentajeIva2,
			 Detalle=@Detalle,
			 Contacto=@Contacto,
			 ImporteBonificacion=@ImporteBonificacion,
			 ImporteIva1=@ImporteIva1,
			 ImporteTotal=@ImporteTotal,
			 SubNumero=@SubNumero,
			 Aprobo=@Aprobo,
			 IdMoneda=@IdMoneda,
			 FechaAprobacion=@FechaAprobacion,
			 DetalleCondicionCompra=@DetalleCondicionCompra,
			 ArchivoAdjunto1=@ArchivoAdjunto1,
			 ArchivoAdjunto2=@ArchivoAdjunto2,
			 ArchivoAdjunto3=@ArchivoAdjunto3,
			 ArchivoAdjunto4=@ArchivoAdjunto4,
			 ArchivoAdjunto5=@ArchivoAdjunto5,
			 ArchivoAdjunto6=@ArchivoAdjunto6,
			 ArchivoAdjunto7=@ArchivoAdjunto7,
			 ArchivoAdjunto8=@ArchivoAdjunto8,
			 ArchivoAdjunto9=@ArchivoAdjunto9,
			 ArchivoAdjunto10=@ArchivoAdjunto10,
			 IdPlazoEntrega=@IdPlazoEntrega,
			 CotizacionMoneda=@CotizacionMoneda,
			 CircuitoFirmasCompleto=@CircuitoFirmasCompleto,

			 ConfirmadoPorWeb=@ConfirmadoPorWeb ,
			 FechaCierreCompulsa=@FechaCierreCompulsa ,

			 NombreUsuarioWeb=@NombreUsuarioWeb,
		 	 FechaRespuestaweb=@FechaRespuestaweb

			WHERE (IdPresupuesto=@IdPresupuesto)
			RETURN(@IdPresupuesto)
 END

