<?xml version="1.0" encoding="utf-8"?><Database Name="wDemoWilliams" Class="ProntoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MARIANO-PC\SQLEXPRESS2;Initial Catalog=wDemoWilliams;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="wDemoWilliamsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WilliamsMailFiltrosCola" Member="WilliamsMailFiltrosColas">
    <Type Name="WilliamsMailFiltrosCola">
      <Column Name="IdWilliamsMailFiltroCola" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Emails" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EsPosicion" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Enviar" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="EsMailOesFax" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modo" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="AplicarANDuORalFiltro" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaOrden1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaOrden2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Corredor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Entregador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdArticulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contrato" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Destino" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Procedencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuxiliarString1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AuxiliarString2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UltimoResultado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PuntoVenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QueContenga" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EstadoDeCartaPorte" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>