CREATE TABLE [dbo].[_TempCuboPresupuestoFinanciero2] (
    [IdPresupuestoFinanciero2] INT             IDENTITY (1, 1) NOT NULL,
    [Jerarquia1]               VARCHAR (60)    NULL,
    [Jerarquia2]               VARCHAR (60)    NULL,
    [Jerarquia3]               VARCHAR (60)    NULL,
    [Jerarquia4]               VARCHAR (60)    NULL,
    [Cuenta]                   VARCHAR (60)    NULL,
    [Detalle]                  VARCHAR (100)   NULL,
    [PresupuestoTeoricoMes01]  NUMERIC (18, 2) NULL,
    [SaldoMes01]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes02]  NUMERIC (18, 2) NULL,
    [SaldoMes02]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes03]  NUMERIC (18, 2) NULL,
    [SaldoMes03]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes04]  NUMERIC (18, 2) NULL,
    [SaldoMes04]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes05]  NUMERIC (18, 2) NULL,
    [SaldoMes05]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes06]  NUMERIC (18, 2) NULL,
    [SaldoMes06]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes07]  NUMERIC (18, 2) NULL,
    [SaldoMes07]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes08]  NUMERIC (18, 2) NULL,
    [SaldoMes08]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes09]  NUMERIC (18, 2) NULL,
    [SaldoMes09]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes10]  NUMERIC (18, 2) NULL,
    [SaldoMes10]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes11]  NUMERIC (18, 2) NULL,
    [SaldoMes11]               NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes12]  NUMERIC (18, 2) NULL,
    [SaldoMes12]               NUMERIC (18, 2) NULL,
    CONSTRAINT [PK__TempCuboPresupuestoFinanciero2] PRIMARY KEY CLUSTERED ([IdPresupuestoFinanciero2] ASC) WITH (FILLFACTOR = 90)
);

