CREATE TABLE [dbo].[_TempEstadoDeFirmas] (
    [IdComprobante]          INT          NULL,
    [TipoComprobante]        VARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroComprobante]      VARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaComprobante]       DATETIME     NULL,
    [CantidadFirmas]         INT          NULL,
    [IdLibero]               INT          NULL,
    [FechaLiberacion]        DATETIME     NULL,
    [Firma1]                 INT          NULL,
    [FechaFirma1]            DATETIME     NULL,
    [Firma2]                 INT          NULL,
    [FechaFirma2]            DATETIME     NULL,
    [Firma3]                 INT          NULL,
    [FechaFirma3]            DATETIME     NULL,
    [Firma4]                 INT          NULL,
    [FechaFirma4]            DATETIME     NULL,
    [Firma5]                 INT          NULL,
    [FechaFirma5]            DATETIME     NULL,
    [Firma6]                 INT          NULL,
    [FechaFirma6]            DATETIME     NULL,
    [Firma7]                 INT          NULL,
    [FechaFirma7]            DATETIME     NULL,
    [Firma8]                 INT          NULL,
    [FechaFirma8]            DATETIME     NULL,
    [IdObra]                 INT          NULL,
    [IdEquipo]               INT          NULL,
    [IdCentroCosto]          INT          NULL,
    [CircuitoFirmasCompleto] VARCHAR (2)  NULL
);

