CREATE TABLE [dbo].[_TempActivacionCompraMateriales] (
    [IdEquipo]               INT             NULL,
    [IdObra]                 INT             NULL,
    [Tipo]                   VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Codigo]                 INT             NULL,
    [IdDetalleRequerimiento] INT             NULL,
    [IdDetalleAcopios]       INT             NULL,
    [IdDetalleLMateriales]   INT             NULL,
    [NumeroComprobante]      INT             NULL,
    [Item]                   INT             NULL,
    [FechaNecesidad]         DATETIME        NULL,
    [IdArticulo]             INT             NULL,
    [Observaciones]          NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad]               NUMERIC (18, 2) NULL,
    [Cantidad1]              NUMERIC (18, 2) NULL,
    [Cantidad2]              NUMERIC (18, 2) NULL,
    [IdUnidad]               INT             NULL,
    [IdDetallePedido]        INT             NULL,
    [TipoPedido]             VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Pedido]                 VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadPedida]         NUMERIC (18, 2) NULL,
    [FechaSolicitud]         DATETIME        NULL,
    [FechaEntrega]           DATETIME        NULL,
    [Comprador]              VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadReservada]      NUMERIC (18, 2) NULL,
    [CantidadRecibida]       NUMERIC (18, 2) NULL,
    [CantidadFaltante]       NUMERIC (18, 2) NULL
);

