CREATE TABLE [dbo].[_TempEstadoDeObras] (
    [IdTemp]                    INT             IDENTITY (1, 1) NOT NULL,
    [Id]                        INT             NULL,
    [Obra]                      VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Equipo]                    VARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CentroCosto]               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Comprobante]               VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Numero]                    INT             NULL,
    [Item]                      INT             NULL,
    [Emisor]                    VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sector]                    VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaNecesidad]            DATETIME        NULL,
    [CantidadItems]             INT             NULL,
    [Cumplido]                  VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaUltimaFirma]          DATETIME        NULL,
    [Articulo]                  VARCHAR (256)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad]                  NUMERIC (18, 2) NULL,
    [UnidadEn]                  VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadPedida]            NUMERIC (18, 2) NULL,
    [CantidadRecibida]          NUMERIC (18, 2) NULL,
    [CantidadFacturasAsignadas] INT             NULL,
    [CuentaContable]            VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]             NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdObra]                    INT             NULL,
    [ProveedorAsignado]         VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CompradoPor]               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaLlamadoAProveedor]    DATETIME        NULL,
    [NombreAcopio]              VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fecha]                     DATETIME        NULL,
    [Cantidad1]                 NUMERIC (18, 2) NULL,
    [Cantidad2]                 NUMERIC (18, 2) NULL,
    [IdEquipoDestino]           INT             NULL,
    [Codigo]                    VARCHAR (20)    NULL
);

