CREATE TABLE [dbo].[Articulos] (
    [IdArticulo]                          INT             IDENTITY (1, 1) NOT NULL,
    [IdRubro]                             INT             NULL,
    [IdSubrubro]                          INT             NULL,
    [IdFamilia]                           INT             NULL,
    [Descripcion]                         VARCHAR (256)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Productivo]                          VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ancho]                               NUMERIC (18, 3) NULL,
    [IdCalidad]                           INT             NULL,
    [Diametro]                            VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Espesor]                             NUMERIC (18, 3) NULL,
    [IdGrado]                             INT             NULL,
    [Largo]                               NUMERIC (18, 3) NULL,
    [IdMaterial]                          INT             NULL,
    [IdAcabado]                           INT             NULL,
    [IdTipo]                              INT             NULL,
    [Serie]                               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdTratamiento]                       INT             NULL,
    [IdUnidad]                            INT             NULL,
    [Autorizacion]                        VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdInventario]                        TINYINT         NULL,
    [IdCuenta]                            INT             NULL,
    [IdScheduler]                         INT             NULL,
    [Unidad1]                             INT             NULL,
    [Unidad2]                             INT             NULL,
    [Unidad3]                             INT             NULL,
    [Unidad4]                             INT             NULL,
    [Unidad5]                             INT             NULL,
    [Unidad6]                             INT             NULL,
    [Unidad7]                             INT             NULL,
    [Unidad8]                             INT             NULL,
    [Unidad9]                             INT             NULL,
    [Unidad10]                            INT             NULL,
    [Peso]                                NUMERIC (18, 3) NULL,
    [DiametroInterno]                     NUMERIC (18, 2) NULL,
    [IdCodigoUniversal]                   INT             NULL,
    [IdRelacion]                          INT             NULL,
    [IdForma]                             INT             NULL,
    [IdSerie]                             INT             NULL,
    [Altura]                              NUMERIC (18, 2) NULL,
    [Diametro2]                           NUMERIC (18, 2) NULL,
    [IdColor]                             INT             NULL,
    [IdNorma]                             INT             NULL,
    [Capacidad]                           NUMERIC (18, 2) NULL,
    [Potencia]                            NUMERIC (18, 2) NULL,
    [IdRango]                             INT             NULL,
    [IdAlimentacionElectrica]             INT             NULL,
    [IdModelo]                            INT             NULL,
    [IdMarca]                             INT             NULL,
    [IdAnioNorma]                         INT             NULL,
    [Unidad11]                            INT             NULL,
    [Unidad12]                            INT             NULL,
    [Unidad13]                            INT             NULL,
    [Unidad14]                            INT             NULL,
    [Unidad15]                            INT             NULL,
    [IdCuantificacion]                    INT             NULL,
    [IdControlCalidad]                    INT             NULL,
    [IdCodigo]                            INT             NULL,
    [Charpy]                              VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCentroCosto]                       INT             NULL,
    [UsuarioAlta]                         VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaAlta]                           DATETIME        NULL,
    [FechaUltimaModificacion]             DATETIME        NULL,
    [EspesorBase]                         NUMERIC (18, 3) NULL,
    [EspesorRevestimiento]                NUMERIC (18, 3) NULL,
    [IdCalidadBase]                       INT             NULL,
    [IdCalidadRevestimiento]              INT             NULL,
    [IdGradoBase]                         INT             NULL,
    [IdGradoRevestimiento]                INT             NULL,
    [IdBiselado]                          INT             NULL,
    [IdCalidadClad]                       INT             NULL,
    [IdTipoRosca]                         INT             NULL,
    [IdDensidad]                          INT             NULL,
    [Rpm]                                 INT             NULL,
    [Datos1]                              NUMERIC (18)    NULL,
    [Datos2]                              NUMERIC (18)    NULL,
    [Datos3]                              NUMERIC (18)    NULL,
    [Datos4]                              NUMERIC (18)    NULL,
    [Datos5]                              NUMERIC (18)    NULL,
    [Datos6]                              NUMERIC (18)    NULL,
    [Datos7]                              NUMERIC (18)    NULL,
    [Datos8]                              NUMERIC (18)    NULL,
    [Datos9]                              NUMERIC (18)    NULL,
    [Datos10]                             NUMERIC (18)    NULL,
    [Unidad16]                            INT             NULL,
    [Unidad17]                            INT             NULL,
    [Unidad18]                            INT             NULL,
    [Unidad19]                            INT             NULL,
    [Unidad20]                            INT             NULL,
    [EnviarEmail]                         TINYINT         NULL,
    [Codigo]                              VARCHAR (20)    NULL,
    [RegistrarStock]                      VARCHAR (2)     NULL,
    [StockMinimo]                         NUMERIC (18, 2) NULL,
    [DefineKit]                           VARCHAR (2)     NULL,
    [CostoPPP]                            NUMERIC (18, 4) NULL,
    [AlicuotaIVA]                         NUMERIC (6, 2)  NULL,
    [CostoPPPDolar]                       NUMERIC (18, 4) NULL,
    [IdUbicacionStandar]                  INT             NULL,
    [CostoReposicion]                     NUMERIC (18, 3) NULL,
    [CostoReposicionDolar]                NUMERIC (18, 3) NULL,
    [Direccion]                           VARCHAR (50)    NULL,
    [IdLocalidad]                         INT             NULL,
    [IdProvincia]                         INT             NULL,
    [IdPais]                              INT             NULL,
    [CodigoPostal]                        VARCHAR (20)    NULL,
    [NumeroManzana]                       VARCHAR (20)    NULL,
    [NumeroLote]                          INT             NULL,
    [ActivoFijo]                          VARCHAR (2)     NULL,
    [EstadoActivoFijo]                    VARCHAR (2)     NULL,
    [NumeroActivoFijo]                    INT             NULL,
    [IdGrupoActivoFijo]                   INT             NULL,
    [BienImpositivo]                      VARCHAR (2)     NULL,
    [BienContable]                        VARCHAR (2)     NULL,
    [Amortiza]                            VARCHAR (2)     NULL,
    [FechaCompra]                         DATETIME        NULL,
    [IdCuentaAmortizacion]                INT             NULL,
    [VidaUtilImpositiva]                  INT             NULL,
    [VidaUtilContable]                    INT             NULL,
    [ValorOrigenContable]                 NUMERIC (19, 6) NULL,
    [ValorOrigenImpositivo]               NUMERIC (19, 6) NULL,
    [ValorActualizado]                    NUMERIC (19, 2) NULL,
    [ValorResidual]                       NUMERIC (19, 2) NULL,
    [ValorResidualActualizado]            NUMERIC (19, 2) NULL,
    [AmortizacionEjercicio]               NUMERIC (19, 2) NULL,
    [AmortizacionEjercicioActualizada]    NUMERIC (19, 2) NULL,
    [AmortizacionesAcumuladas]            NUMERIC (19, 2) NULL,
    [AmortizacionesAcumuladasActualizada] NUMERIC (19, 2) NULL,
    [VidaUtilImpositivaRestante]          INT             NULL,
    [VidaUtilContableRestante]            INT             NULL,
    [FechaPrimeraAmortizacionImpositiva]  DATETIME        NULL,
    [FechaPrimeraAmortizacionContable]    DATETIME        NULL,
    [IdUbicacionActivoFijo]               INT             NULL,
    [IdSector]                            INT             NULL,
    [FechaBajaAmortizacion]               DATETIME        NULL,
    [ParaMantenimiento]                   VARCHAR (2)     NULL,
    [IdUnidadLecturaMantenimiento]        INT             NULL,
    [LecturaAcumulada]                    NUMERIC (18, 2) NULL,
    [LecturaBase]                         NUMERIC (18, 2) NULL,
    [UltimaLectura]                       NUMERIC (18, 2) NULL,
    [FechaUltimaLectura]                  DATETIME        NULL,
    [EstimadoAnual]                       NUMERIC (18, 2) NULL,
    [NumeroInventario]                    VARCHAR (20)    NULL,
    [ModeloMotor]                         VARCHAR (30)    NULL,
    [EquipoEnObra]                        VARCHAR (2)     NULL,
    [EstadoEquipo]                        VARCHAR (2)     NULL,
    [EsConsumible]                        VARCHAR (2)     NULL,
    [FechaUltimaModificacionArticulo]     DATETIME        NULL,
    [EntidadOrigen]                       VARCHAR (50)    NULL,
    [ComprobanteCompra]                   VARCHAR (20)    NULL,
    [ModeloEspecifico]                    VARCHAR (50)    NULL,
    [NumeroPatente]                       VARCHAR (10)    NULL,
    [NumeroMotor]                         VARCHAR (20)    NULL,
    [NumeroChasis]                        VARCHAR (30)    NULL,
    [AñoFabricacion]                      INT             NULL,
    [AñosAmortizacion]                    INT             NULL,
    [AñoAlta]                             INT             NULL,
    [Caracteristicas]                     VARCHAR (70)    NULL,
    [NumeroGarantia]                      VARCHAR (15)    NULL,
    [FechaCaducidadGarantia]              DATETIME        NULL,
    [TipoCoberturaSeguro]                 VARCHAR (50)    NULL,
    [NumeroPolizaSeguro]                  NUMERIC (18)    NULL,
    [CompañiaSeguro]                      VARCHAR (30)    NULL,
    [FechaVigenciaSeguro]                 DATETIME        NULL,
    [FechaVencimientoVerificacionTecnica] DATETIME        NULL,
    [CalculaAmortizacion]                 VARCHAR (2)     NULL,
    [UltimoRevaluoContable]               NUMERIC (18, 2) NULL,
    [FechaUltimoRevaluo]                  DATETIME        NULL,
    [CodigoLoteo]                         VARCHAR (20)    NULL,
    [Adrema]                              VARCHAR (20)    NULL,
    [Observaciones]                       NTEXT           NULL,
    [ConsumoStandarCombustible]           NUMERIC (18, 2) NULL,
    [UbicacionActivoFijo]                 VARCHAR (20)    NULL,
    [CalculaValorActualizado]             VARCHAR (2)     NULL,
    [ParaPRONTO_MANTENIMIENTO]            VARCHAR (2)     NULL,
    [PosicionAduana]                      VARCHAR (20)    NULL,
    [Alquilado]                           VARCHAR (2)     NULL,
    [IdMarcaMotor]                        INT             NULL,
    [NumeroSerieMotor]                    VARCHAR (20)    NULL,
    [VidaUtilTecnica]                     INT             NULL,
    [ValorCompra]                         NUMERIC (18, 2) NULL,
    [IdMonedaCompra]                      INT             NULL,
    [FechaBaja]                           DATETIME        NULL,
    [DocumentoAlta]                       VARCHAR (20)    NULL,
    [DocumentoBaja]                       VARCHAR (20)    NULL,
    [IdArticuloAsociado]                  INT             NULL,
    [RegistroUnicoTransporteAutomotor]    NUMERIC (16)    NULL,
    [TieneGPS]                            VARCHAR (2)     NULL,
    [CondicionActual]                     VARCHAR (2)     NULL,
    [SituacionActual]                     VARCHAR (2)     NULL,
    [Activo]                              VARCHAR (2)     NULL,
    [Auxiliar1]                           INT             NULL,
    [Auxiliar2]                           INT             NULL,
    [Auxiliar3]                           INT             NULL,
    [Auxiliar4]                           INT             NULL,
    [Auxiliar5]                           INT             NULL,
    [Auxiliar6]                           INT             NULL,
    [Auxiliar7]                           INT             NULL,
    [Auxiliar8]                           INT             NULL,
    [Auxiliar9]                           INT             NULL,
    [Auxiliar10]                          INT             NULL,
    [Auxiliar11]                          INT             NULL,
    [Auxiliar12]                          INT             NULL,
    [Auxiliar13]                          INT             NULL,
    [Auxiliar14]                          INT             NULL,
    [Auxiliar15]                          INT             NULL,
    [Auxiliar16]                          INT             NULL,
    [Auxiliar17]                          INT             NULL,
    [Auxiliar18]                          INT             NULL,
    [Auxiliar19]                          INT             NULL,
    [Auxiliar20]                          INT             NULL,
    [Auxiliar21]                          INT             NULL,
    [Auxiliar22]                          INT             NULL,
    [Auxiliar23]                          INT             NULL,
    [Auxiliar24]                          INT             NULL,
    [Auxiliar25]                          INT             NULL,
    [AuxiliarString1]                     VARCHAR (50)    NULL,
    [AuxiliarString2]                     VARCHAR (50)    NULL,
    [AuxiliarString3]                     VARCHAR (50)    NULL,
    [AuxiliarString4]                     VARCHAR (50)    NULL,
    [AuxiliarString5]                     VARCHAR (50)    NULL,
    [AuxiliarString6]                     VARCHAR (50)    NULL,
    [AuxiliarString7]                     VARCHAR (50)    NULL,
    [AuxiliarString8]                     VARCHAR (50)    NULL,
    [AuxiliarString9]                     VARCHAR (50)    NULL,
    [AuxiliarString10]                    VARCHAR (50)    NULL,
    [CodigoAlternativo]                   VARCHAR (50)    NULL,
    [IdCuentaCompras]                     INT             NULL,
    [StockReposicion]                     NUMERIC (18, 2) NULL,
    [MarcaStock]                          VARCHAR (1)     NULL,
    [CostoInicial]                        NUMERIC (18, 3) NULL,
    [ConsumirPorOT]                       VARCHAR (2)     NULL,
    [IdTransportista]                     INT             NULL,
    [IdTipoEquipo]                        INT             NULL,
    [Replica]                             VARCHAR (2)     NULL,
    [IdPresupuestoObraRubro]              INT             NULL,
    [IdTipoArticulo]                      INT             NULL,
    [FechaUltimoCostoReposicion]          DATETIME        NULL,
    [ADistribuirEnPresupuestoDeObra]      VARCHAR (2)     NULL,
    [IdCuentaComprasActivo]               INT             NULL,
    [AuxiliarNumerico1]                   NUMERIC (18, 2) NULL,
    [AuxiliarNumerico2]                   NUMERIC (18, 2) NULL,
    [AuxiliarNumerico3]                   NUMERIC (18, 2) NULL,
    [AuxiliarNumerico4]                   NUMERIC (18, 2) NULL,
    [AuxiliarNumerico5]                   NUMERIC (18, 2) NULL,
    [IdCurvaTalle]                        INT             NULL,
    [Curva]                               VARCHAR (50)    NULL,
    [GenerarConsumosAutomaticamente]      VARCHAR (2)     NULL,
    [TalleCambioPrecio]                   VARCHAR (2)     NULL,
    [TalleCambioPrecio2]                  VARCHAR (2)     NULL,
    CONSTRAINT [PK_Articulos] PRIMARY KEY CLUSTERED ([IdArticulo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Articulos_Rubros] FOREIGN KEY ([IdRubro]) REFERENCES [dbo].[Rubros] ([IdRubro]),
    CONSTRAINT [FK_Articulos_Subrubros] FOREIGN KEY ([IdSubrubro]) REFERENCES [dbo].[Subrubros] ([IdSubrubro]),
    CONSTRAINT [FK_Articulos_Ubicacion] FOREIGN KEY ([IdUbicacionStandar]) REFERENCES [dbo].[Ubicaciones] ([IdUbicacion])
);


GO
CREATE NONCLUSTERED INDEX [Indice100]
    ON [dbo].[Articulos]([Codigo] ASC) WITH (FILLFACTOR = 90);

