CREATE TABLE [dbo].[BZ_Pesadas] (
    [IdPesada]                      INT             IDENTITY (1, 1) NOT NULL,
    [NumeroPesada]                  INT             NULL,
    [IdUsuarioIngreso]              INT             NULL,
    [FechaIngreso]                  DATETIME        NULL,
    [Anulada]                       VARCHAR (2)     NULL,
    [IdUsuarioAnulo]                INT             NULL,
    [FechaAnulacion]                DATETIME        NULL,
    [Observaciones]                 VARCHAR (200)   NULL,
    [IdArticulo]                    INT             NULL,
    [IdStock]                       INT             NULL,
    [Partida]                       VARCHAR (20)    NULL,
    [IdUnidad]                      INT             NULL,
    [IdUbicacion]                   INT             NULL,
    [Cantidad]                      NUMERIC (12, 2) NULL,
    [PesoBruto]                     NUMERIC (18, 2) NULL,
    [PesoNeto]                      NUMERIC (18, 2) NULL,
    [Tara]                          NUMERIC (18, 2) NULL,
    [Chofer]                        INT             NULL,
    [TxtChofer]                     VARCHAR (30)    NULL,
    [IdCamion]                      INT             NULL,
    [TxtCamion]                     VARCHAR (30)    NULL,
    [IdTransportista]               INT             NULL,
    [IdProveedor]                   INT             NULL,
    [IdCliente]                     INT             NULL,
    [IdObra]                        INT             NULL,
    [RemitoMaterial]                INT             NULL,
    [RemitoTransportista]           INT             NULL,
    [CantidadEnOrigen]              NUMERIC (12, 2) NULL,
    [PesoBrutoIngresadoManualmente] VARCHAR (2)     NULL,
    [TaraIngresadaManualmente]      VARCHAR (2)     NULL,
    [IdDetallePedido]               INT             NULL,
    PRIMARY KEY CLUSTERED ([IdPesada] ASC) WITH (FILLFACTOR = 90),
    FOREIGN KEY ([IdUnidad]) REFERENCES [dbo].[Unidades] ([IdUnidad]),
    FOREIGN KEY ([IdUsuarioIngreso]) REFERENCES [dbo].[Empleados] ([IdEmpleado])
);

