CREATE TABLE [dbo].[CartasPorteMovimientos] (
    [IdCDPMovimiento]     INT             IDENTITY (1, 1) NOT NULL,
    [NumeroCDPMovimiento] INT             NULL,
    [IdUsuarioIngreso]    INT             NULL,
    [FechaIngreso]        DATETIME        NULL,
    [Anulada]             VARCHAR (2)     NULL,
    [IdUsuarioAnulo]      INT             NULL,
    [FechaAnulacion]      DATETIME        NULL,
    [Observaciones]       VARCHAR (200)   NULL,
    [FechaTimeStamp]      ROWVERSION      NULL,
    [IdAjusteStock]       INT             NULL,
    [IdCartaDePorte]      INT             NULL,
    [Entrada_o_Salida]    INT             NULL,
    [IdExportadorOrigen]  INT             NULL,
    [IdExportadorDestino] INT             NULL,
    [Tipo]                INT             NULL,
    [Contrato]            VARCHAR (40)    NULL,
    [Puerto]              INT             NULL,
    [Vapor]               VARCHAR (40)    NULL,
    [Numero]              VARCHAR (40)    NULL,
    [IdArticulo]          INT             NULL,
    [Cantidad]            NUMERIC (12, 2) NULL,
    [IdStock]             INT             NULL,
    [Partida]             VARCHAR (20)    NULL,
    [IdUnidad]            INT             NULL,
    [IdUbicacion]         INT             NULL,
    [IdFacturaImputada]   INT             NULL,
    [IdDetalleFactura]    INT             NULL,
    FOREIGN KEY ([IdDetalleFactura]) REFERENCES [dbo].[DetalleFacturas] ([IdDetalleFactura])
);

