CREATE TABLE [dbo].[CertificacionesObrasDatos] (
    [IdCertificacionObraDatos]       INT            IDENTITY (1, 1) NOT NULL,
    [NumeroProyecto]                 INT            NULL,
    [NumeroCertificado]              INT            NULL,
    [IdCliente]                      INT            NULL,
    [Fecha]                          DATETIME       NULL,
    [FechaInicio]                    DATETIME       NULL,
    [FechaFinalizacion]              DATETIME       NULL,
    [Adjunto1]                       VARCHAR (100)  NULL,
    [Adjunto2]                       VARCHAR (100)  NULL,
    [Adjunto3]                       VARCHAR (100)  NULL,
    [Adjunto4]                       VARCHAR (100)  NULL,
    [Adjunto5]                       VARCHAR (100)  NULL,
    [Adjunto6]                       VARCHAR (100)  NULL,
    [Adjunto7]                       VARCHAR (100)  NULL,
    [Adjunto8]                       VARCHAR (100)  NULL,
    [Adjunto9]                       VARCHAR (100)  NULL,
    [Adjunto10]                      VARCHAR (100)  NULL,
    [CondicionPago]                  VARCHAR (50)   NULL,
    [AnticipoFinanciero]             VARCHAR (50)   NULL,
    [Acopio]                         VARCHAR (50)   NULL,
    [FondoReparo]                    NUMERIC (6, 2) NULL,
    [PorcentajeRetencionesEstimadas] NUMERIC (6, 2) NULL,
    [IdMoneda]                       INT            NULL,
    [Observaciones]                  NTEXT          NULL,
    [Anulado]                        VARCHAR (2)    NULL,
    [IdUsuarioAnulo]                 INT            NULL,
    [FechaAnulacion]                 DATETIME       NULL,
    [MotivoAnulacion]                NTEXT          NULL,
    [NumeroExpediente]               VARCHAR (20)   NULL,
    [FechaVencimiento]               DATETIME       NULL,
    [FechaCesionBanco]               DATETIME       NULL,
    [FechaCancelacionCesion]         DATETIME       NULL,
    [IdBanco]                        INT            NULL,
    [Version]                        VARCHAR (10)   NULL,
    [IdAprobo]                       INT            NULL,
    [CircuitoFirmasCompleto]         VARCHAR (2)    NULL,
    CONSTRAINT [PK_CertificacionesObrasDatos] PRIMARY KEY CLUSTERED ([IdCertificacionObraDatos] ASC) WITH (FILLFACTOR = 90)
);

