CREATE TABLE [dbo].[Clientes] (
    [IdCliente]                                           INT             IDENTITY (1, 1) NOT NULL,
    [RazonSocial]                                         VARCHAR (100)   NULL,
    [Direccion]                                           VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdLocalidad]                                         INT             NULL,
    [CodigoPostal]                                        VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdProvincia]                                         INT             NULL,
    [IdPais]                                              INT             NULL,
    [Telefono]                                            VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fax]                                                 VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Email]                                               VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cuit]                                                VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCodigoIva]                                         INT             NULL,
    [FechaAlta]                                           DATETIME        NULL,
    [Contacto]                                            VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EnviarEmail]                                         TINYINT         NULL,
    [DireccionEntrega]                                    VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdLocalidadEntrega]                                  INT             NULL,
    [IdProvinciaEntrega]                                  INT             NULL,
    [CodigoCliente]                                       INT             NULL,
    [IdCuenta]                                            INT             NULL,
    [Saldo]                                               NUMERIC (18, 2) NULL,
    [SaldoDocumentos]                                     NUMERIC (18, 2) NULL,
    [Vendedor1]                                           INT             NULL,
    [CreditoMaximo]                                       NUMERIC (18, 2) NULL,
    [IGCondicion]                                         INT             NULL,
    [IdCondicionVenta]                                    INT             NULL,
    [IdMoneda]                                            INT             NULL,
    [IBNumeroInscripcion]                                 VARCHAR (20)    NULL,
    [IBCondicion]                                         INT             NULL,
    [TipoCliente]                                         INT             NULL,
    [Codigo]                                              VARCHAR (10)    NULL,
    [IdListaPrecios]                                      INT             NULL,
    [IdIBCondicionPorDefecto]                             INT             NULL,
    [Confirmado]                                          VARCHAR (2)     NULL,
    [CodigoPresto]                                        VARCHAR (13)    NULL,
    [Observaciones]                                       NTEXT           NULL,
    [Importaciones_NumeroInscripcion]                     VARCHAR (20)    NULL,
    [Importaciones_DenominacionInscripcion]               VARCHAR (10)    NULL,
    [IdCuentaMonedaExt]                                   INT             NULL,
    [Cobrador]                                            INT             NULL,
    [Auxiliar]                                            VARCHAR (50)    NULL,
    [IdIBCondicionPorDefecto2]                            INT             NULL,
    [IdIBCondicionPorDefecto3]                            INT             NULL,
    [IdEstado]                                            INT             NULL,
    [NombreFantasia]                                      VARCHAR (50)    NULL,
    [EsAgenteRetencionIVA]                                VARCHAR (2)     NULL,
    [BaseMinimaParaPercepcionIVA]                         NUMERIC (18, 2) NULL,
    [PorcentajePercepcionIVA]                             NUMERIC (6, 2)  NULL,
    [IdUsuarioIngreso]                                    INT             NULL,
    [FechaIngreso]                                        DATETIME        NULL,
    [IdUsuarioModifico]                                   INT             NULL,
    [FechaModifico]                                       DATETIME        NULL,
    [PorcentajeIBDirecto]                                 NUMERIC (6, 2)  NULL,
    [FechaInicioVigenciaIBDirecto]                        DATETIME        NULL,
    [FechaFinVigenciaIBDirecto]                           DATETIME        NULL,
    [GrupoIIBB]                                           INT             NULL,
    [IdBancoDebito]                                       INT             NULL,
    [CBU]                                                 VARCHAR (22)    NULL,
    [PorcentajeIBDirectoCapital]                          NUMERIC (6, 2)  NULL,
    [FechaInicioVigenciaIBDirectoCapital]                 DATETIME        NULL,
    [FechaFinVigenciaIBDirectoCapital]                    DATETIME        NULL,
    [GrupoIIBBCapital]                                    INT             NULL,
    [IdBancoGestionador]                                  INT             NULL,
    [ExpresionRegularNoAgruparFacturasConEstosVendedores] VARCHAR (200)   NULL,
    [ExigeDatosCompletosEnCartaDePorteQueLoUse]           VARCHAR (2)     NULL,
    [DireccionDeCorreos]                                  VARCHAR (200)   NULL,
    [IdLocalidadDeCorreos]                                INT             NULL,
    [IdProvinciaDeCorreos]                                INT             NULL,
    [CodigoPostalDeCorreos]                               VARCHAR (30)    NULL,
    [ObservacionesDeCorreos]                              VARCHAR (150)   NULL,
    [IdTarjetaCredito]                                    INT             NULL,
    [Tarjeta_NumeroTarjeta]                               VARCHAR (16)    NULL,
    [IncluyeTarifaEnFactura]                              VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoTitular]                    VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoIntermediario]              VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoRemcomercial]               VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoCorredor]                   VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoDestinatario]               VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoDestinatarioExportador]     VARCHAR (2)     NULL,
    [SeLeDerivaSuFacturaAlCorredorDeLaCarta]              VARCHAR (2)     NULL,
    [HabilitadoParaCartaPorte]                            VARCHAR (2)     NULL,
    [SeLeFacturaCartaPorteComoClienteAuxiliar]            VARCHAR (2)     NULL,
    [EsAcondicionadoraDeCartaPorte]                       VARCHAR (2)     NULL,
    [Contactos]                                           VARCHAR (400)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TelefonosFijosOficina]                               VARCHAR (400)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TelefonosCelulares]                                  VARCHAR (400)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CorreosElectronicos]                                 VARCHAR (400)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdTransportista]                                     INT             NULL,
    [IdRegion]                                            INT             NULL,
    [IdCategoriaCredito]                                  INT             NULL,
    [RegistrarMovimientosEnCuentaCorriente]               VARCHAR (2)     NULL,
    [ComisionDiferenciada]                                NUMERIC (6, 2)  NULL,
    [EsEntregador]                                        VARCHAR (2)     NULL,
    [OperacionesMercadoInternoEntidadVinculada]           VARCHAR (2)     NULL,
    [CartaPorteTipoDeAdjuntoDeFacturacion]                INT             NULL,
    CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED ([IdCliente] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Clientes_CatIIBB] FOREIGN KEY ([IdIBCondicionPorDefecto]) REFERENCES [dbo].[IBCondiciones] ([IdIBCondicion]),
    CONSTRAINT [FK_Clientes_CatIIBB2] FOREIGN KEY ([IdIBCondicionPorDefecto2]) REFERENCES [dbo].[IBCondiciones] ([IdIBCondicion]),
    CONSTRAINT [FK_Clientes_CatIIBB3] FOREIGN KEY ([IdIBCondicionPorDefecto3]) REFERENCES [dbo].[IBCondiciones] ([IdIBCondicion]),
    CONSTRAINT [FK_Clientes_Cobrador] FOREIGN KEY ([Cobrador]) REFERENCES [dbo].[Vendedores] ([IdVendedor]),
    CONSTRAINT [FK_Clientes_CondicionCompras] FOREIGN KEY ([IdCondicionVenta]) REFERENCES [dbo].[Condiciones Compra] ([IdCondicionCompra]),
    CONSTRAINT [FK_Clientes_Cuentas] FOREIGN KEY ([IdCuenta]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_Clientes_CuentasMonedaExt] FOREIGN KEY ([IdCuentaMonedaExt]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_Clientes_Empleados_Ingreso] FOREIGN KEY ([IdUsuarioIngreso]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Clientes_Empleados_Modifico] FOREIGN KEY ([IdUsuarioModifico]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Clientes_Estados] FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[Estados Proveedores] ([IdEstado]),
    CONSTRAINT [FK_Clientes_IGCondiciones] FOREIGN KEY ([IGCondicion]) REFERENCES [dbo].[IGCondiciones] ([IdIGCondicion]),
    CONSTRAINT [FK_Clientes_listasprecio] FOREIGN KEY ([IdListaPrecios]) REFERENCES [dbo].[ListasPrecios] ([IdListaPrecios]),
    CONSTRAINT [FK_Clientes_LocalidadEntrega] FOREIGN KEY ([IdLocalidadEntrega]) REFERENCES [dbo].[Localidades] ([IdLocalidad]),
    CONSTRAINT [FK_Clientes_Localidades] FOREIGN KEY ([IdLocalidad]) REFERENCES [dbo].[Localidades] ([IdLocalidad]),
    CONSTRAINT [FK_Clientes_Monedas] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[Monedas] ([IdMoneda]),
    CONSTRAINT [FK_Clientes_Pais] FOREIGN KEY ([IdPais]) REFERENCES [dbo].[Paises] ([IdPais]),
    CONSTRAINT [FK_Clientes_Paises] FOREIGN KEY ([IdPais]) REFERENCES [dbo].[Paises] ([IdPais]),
    CONSTRAINT [FK_Clientes_ProvinciaEntrega] FOREIGN KEY ([IdProvinciaEntrega]) REFERENCES [dbo].[Provincias] ([IdProvincia]),
    CONSTRAINT [FK_Clientes_Provincias] FOREIGN KEY ([IdProvincia]) REFERENCES [dbo].[Provincias] ([IdProvincia]),
    CONSTRAINT [FK_Clientes_Vendedor] FOREIGN KEY ([Vendedor1]) REFERENCES [dbo].[Vendedores] ([IdVendedor])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Clientes]([Cuit] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IDX_Clientes_Superbuscador6]
    ON [dbo].[Clientes]([Cuit] ASC, [RazonSocial] ASC, [Telefono] ASC, [Email] ASC, [FechaAlta] ASC);

