CREATE TABLE [dbo].[ComprobantesProveedores] (
    [IdComprobanteProveedor]                 INT             IDENTITY (1, 1) NOT NULL,
    [IdProveedor]                            INT             NULL,
    [IdTipoComprobante]                      INT             NULL,
    [FechaComprobante]                       DATETIME        NULL,
    [Letra]                                  VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroComprobante1]                     INT             NULL,
    [NumeroComprobante2]                     INT             NULL,
    [NumeroReferencia]                       INT             NULL,
    [FechaRecepcion]                         DATETIME        NULL,
    [FechaVencimiento]                       DATETIME        NULL,
    [TotalBruto]                             NUMERIC (18, 2) NULL,
    [TotalIva1]                              NUMERIC (18, 2) NULL,
    [TotalIva2]                              NUMERIC (18, 2) NULL,
    [TotalBonificacion]                      NUMERIC (18, 2) NULL,
    [TotalComprobante]                       NUMERIC (18, 2) NULL,
    [PorcentajeBonificacion]                 NUMERIC (6, 2)  NULL,
    [Observaciones]                          NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DiasVencimiento]                        INT             NULL,
    [IdObra]                                 INT             NULL,
    [IdProveedorEventual]                    INT             NULL,
    [IdOrdenPago]                            INT             NULL,
    [IdCuenta]                               INT             NULL,
    [IdMoneda]                               INT             NULL,
    [CotizacionMoneda]                       NUMERIC (18, 4) NULL,
    [CotizacionDolar]                        NUMERIC (18, 4) NULL,
    [TotalIvaNoDiscriminado]                 NUMERIC (18, 2) NULL,
    [IVAComprasImporte1]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras1]                    INT             NULL,
    [IvaComprasPorcentaje1]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte2]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras2]                    INT             NULL,
    [IvaComprasPorcentaje2]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte3]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras3]                    INT             NULL,
    [IvaComprasPorcentaje3]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte4]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras4]                    INT             NULL,
    [IvaComprasPorcentaje4]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte5]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras5]                    INT             NULL,
    [IvaComprasPorcentaje5]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte6]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras6]                    INT             NULL,
    [IvaComprasPorcentaje6]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte7]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras7]                    INT             NULL,
    [IvaComprasPorcentaje7]                  NUMERIC (18, 2) NULL,
    [IVAComprasImporte8]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras8]                    INT             NULL,
    [IvaComprasPorcentaje8]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte9]                     NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras9]                    INT             NULL,
    [IvaComprasPorcentaje9]                  NUMERIC (6, 2)  NULL,
    [IVAComprasImporte10]                    NUMERIC (18, 2) NULL,
    [IdCuentaIvaCompras10]                   INT             NULL,
    [IvaComprasPorcentaje10]                 NUMERIC (6, 2)  NULL,
    [SubTotalGravado]                        NUMERIC (18, 2) NULL,
    [SubTotalExento]                         NUMERIC (18, 2) NULL,
    [AjusteIVA]                              NUMERIC (18, 2) NULL,
    [PorcentajeIVAAplicacionAjuste]          NUMERIC (6, 2)  NULL,
    [BienesOServicios]                       VARCHAR (1)     NULL,
    [IdDetalleOrdenPagoRetencionIVAAplicada] INT             NULL,
    [IdIBCondicion]                          INT             NULL,
    [PRESTOFactura]                          VARCHAR (13)    NULL,
    [Confirmado]                             VARCHAR (2)     NULL,
    [IdProvinciaDestino]                     INT             NULL,
    [IdTipoRetencionGanancia]                INT             NULL,
    [NumeroCAI]                              VARCHAR (20)    NULL,
    [FechaVencimientoCAI]                    DATETIME        NULL,
    [IdCodigoAduana]                         INT             NULL,
    [IdCodigoDestinacion]                    INT             NULL,
    [NumeroDespacho]                         INT             NULL,
    [DigitoVerificadorNumeroDespacho]        VARCHAR (1)     NULL,
    [FechaDespachoAPlaza]                    DATETIME        NULL,
    [IdUsuarioIngreso]                       INT             NULL,
    [FechaIngreso]                           DATETIME        NULL,
    [IdUsuarioModifico]                      INT             NULL,
    [FechaModifico]                          DATETIME        NULL,
    [PRESTOProveedor]                        VARCHAR (13)    NULL,
    [IdCodigoIva]                            INT             NULL,
    [CotizacionEuro]                         NUMERIC (18, 4) NULL,
    [IdCondicionCompra]                      INT             NULL,
    [Importacion_FOB]                        NUMERIC (18, 2) NULL,
    [Importacion_PosicionAduana]             VARCHAR (20)    NULL,
    [Importacion_Despacho]                   VARCHAR (30)    NULL,
    [Importacion_Guia]                       VARCHAR (20)    NULL,
    [Importacion_IdPaisOrigen]               INT             NULL,
    [Importacion_FechaEmbarque]              DATETIME        NULL,
    [Importacion_FechaOficializacion]        DATETIME        NULL,
    [REP_CTAPRO_INS]                         VARCHAR (1)     NULL,
    [REP_CTAPRO_UPD]                         VARCHAR (1)     NULL,
    [InformacionAuxiliar]                    VARCHAR (50)    NULL,
    [GravadoParaSUSS]                        NUMERIC (18, 2) NULL,
    [PorcentajeParaSUSS]                     NUMERIC (6, 2)  NULL,
    [FondoReparo]                            NUMERIC (18, 2) NULL,
    [AutoincrementarNumeroReferencia]        VARCHAR (2)     NULL,
    [ReintegroImporte]                       NUMERIC (18, 2) NULL,
    [ReintegroDespacho]                      VARCHAR (20)    NULL,
    [ReintegroIdMoneda]                      INT             NULL,
    [ReintegroIdCuenta]                      INT             NULL,
    [PrestoDestino]                          VARCHAR (20)    NULL,
    [IdFacturaVenta_RecuperoGastos]          INT             NULL,
    [IdNotaCreditoVenta_RecuperoGastos]      INT             NULL,
    [IdComprobanteImputado]                  INT             NULL,
    [IdCuentaOtros]                          INT             NULL,
    [PRESTOFechaProceso]                     DATETIME        NULL,
    [DestinoPago]                            VARCHAR (1)     NULL,
    [NumeroRendicionFF]                      INT             NULL,
    [Cuit]                                   VARCHAR (13)    NULL,
    [FechaAsignacionPresupuesto]             DATETIME        NULL,
    [Dolarizada]                             VARCHAR (2)     NULL,
    [NumeroOrdenPagoFondoReparo]             INT             NULL,
    [IdListaPrecios]                         INT             NULL,
    [IdComprobanteProveedorOriginal]         INT             NULL,
    [PorcentajeIVAParaMonotributistas]       NUMERIC (6, 2)  NULL,
    [IdDiferenciaCambio]                     INT             NULL,
    [TomarEnCuboDeGastos]                    VARCHAR (2)     NULL,
    [ConfirmadoPorWeb]                       VARCHAR (2)     NULL,
    [CircuitoFirmasCompleto]                 VARCHAR (2)     NULL,
    [IdLiquidacionFlete]                     INT             NULL,
    [NumeroCAE]                              VARCHAR (20)    NULL,
    [IdImpuestoDirecto]                      INT             NULL,
    [IdPoliza]                               INT             NULL,
    [NumeroCuotaPoliza]                      INT             NULL,
    [IdOrdenPagoRetencionIva]                INT             NULL,
    [ImporteRetencionIvaEnOrdenPago]         NUMERIC (18, 2) NULL,
    [DebitoAutomatico]                       VARCHAR (2)     NULL,
    [FechaPrestacionServicio]                DATETIME        NULL,
    [IdTipoOperacion]                        INT             NULL,
    [ArchivoAdjunto1]                        VARCHAR (200)   NULL,
    [ArchivoAdjunto2]                        VARCHAR (200)   NULL,
    CONSTRAINT [PK_ComprobantesProveedores] PRIMARY KEY NONCLUSTERED ([IdComprobanteProveedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ComprobantesProveedores_Cuenta] FOREIGN KEY ([IdCuenta]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_ComprobantesProveedores_CuentaOtros] FOREIGN KEY ([IdCuentaOtros]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_ComprobantesProveedores_DescripcionIva] FOREIGN KEY ([IdCodigoIva]) REFERENCES [dbo].[DescripcionIva] ([IdCodigoIva]),
    CONSTRAINT [FK_ComprobantesProveedores_Obra] FOREIGN KEY ([IdObra]) REFERENCES [dbo].[Obras] ([IdObra])
);

