CREATE TABLE [dbo].[Condiciones Compra] (
    [IdCondicionCompra]      INT            IDENTITY (1, 1) NOT NULL,
    [Descripcion]            VARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadDias]           INT            NULL,
    [CodigoCondicion]        VARCHAR (2)    NULL,
    [CantidadDias1]          INT            NULL,
    [CantidadDias2]          INT            NULL,
    [CantidadDias3]          INT            NULL,
    [CantidadDias4]          INT            NULL,
    [CantidadDias5]          INT            NULL,
    [CantidadDias6]          INT            NULL,
    [Porcentaje1]            NUMERIC (6, 2) NULL,
    [Porcentaje2]            NUMERIC (6, 2) NULL,
    [Porcentaje3]            NUMERIC (6, 2) NULL,
    [Porcentaje4]            NUMERIC (6, 2) NULL,
    [Porcentaje5]            NUMERIC (6, 2) NULL,
    [Porcentaje6]            NUMERIC (6, 2) NULL,
    [CantidadDias7]          INT            NULL,
    [CantidadDias8]          INT            NULL,
    [CantidadDias9]          INT            NULL,
    [CantidadDias10]         INT            NULL,
    [CantidadDias11]         INT            NULL,
    [CantidadDias12]         INT            NULL,
    [Porcentaje7]            NUMERIC (6, 2) NULL,
    [Porcentaje8]            NUMERIC (6, 2) NULL,
    [Porcentaje9]            NUMERIC (6, 2) NULL,
    [Porcentaje10]           NUMERIC (6, 2) NULL,
    [Porcentaje11]           NUMERIC (6, 2) NULL,
    [Porcentaje12]           NUMERIC (6, 2) NULL,
    [Observaciones]          NTEXT          NULL,
    [Codigo]                 VARCHAR (10)   NULL,
    [PorcentajeBonificacion] NUMERIC (6, 2) NULL,
    [ContraEntregaDeValores] VARCHAR (2)    NULL,
    CONSTRAINT [PK_Condiciones Compra] PRIMARY KEY CLUSTERED ([IdCondicionCompra] ASC) WITH (FILLFACTOR = 90)
);

