CREATE TABLE [dbo].[CostosImportacion] (
    [IdCostoImportacion]    INT             IDENTITY (1, 1) NOT NULL,
    [IdArticulo]            INT             NULL,
    [IdProveedor]           INT             NULL,
    [PosicionNCE]           VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdPosicionImportacion] INT             NULL,
    [Derechos]              NUMERIC (18, 2) NULL,
    [GastosEstadisticas]    NUMERIC (18, 2) NULL,
    [OtrosGastos1]          NUMERIC (18, 2) NULL,
    [OtrosGastos2]          NUMERIC (18, 2) NULL,
    [FechaCostoImportacion] DATETIME        NULL,
    [Observaciones]         NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PrecioFOB]             NUMERIC (18, 2) NULL,
    [IdMoneda1]             INT             NULL,
    [Conversion1]           NUMERIC (18, 2) NULL,
    [FleteMaritimo]         NUMERIC (18, 2) NULL,
    [IdMoneda2]             INT             NULL,
    [Conversion2]           NUMERIC (18, 2) NULL,
    [OtrosFletes]           NUMERIC (18, 2) NULL,
    [IdMoneda3]             INT             NULL,
    [Conversion3]           NUMERIC (18, 2) NULL,
    [PrecioCF]              NUMERIC (18, 2) NULL,
    [PorcGastosDespacho]    NUMERIC (18, 2) NULL,
    [TotalGastosDespacho]   NUMERIC (18, 2) NULL,
    [PorcTotalGastos]       NUMERIC (18, 2) NULL,
    [TotalGastos]           NUMERIC (18, 2) NULL,
    [PrecioTotal]           NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_CostosImportacion] PRIMARY KEY NONCLUSTERED ([IdCostoImportacion] ASC) WITH (FILLFACTOR = 90)
);

