CREATE TABLE [dbo].[Cuentas] (
    [IdCuenta]                  INT             IDENTITY (1, 1) NOT NULL,
    [Codigo]                    INT             NULL,
    [Descripcion]               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdTipoCuenta]              INT             NULL,
    [NivelTotal]                INT             NULL,
    [IdRubroContable]           INT             NULL,
    [Jerarquia]                 VARCHAR (20)    NULL,
    [IdObra]                    INT             NULL,
    [IdCuentaGasto]             INT             NULL,
    [DebeHaber]                 VARCHAR (1)     NULL,
    [IdTipoCuentaGrupo]         INT             NULL,
    [VaAlCiti]                  VARCHAR (2)     NULL,
    [PresupuestoTeoricoMes01]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes02]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes03]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes04]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes05]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes06]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes07]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes08]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes09]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes10]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes11]   NUMERIC (18, 2) NULL,
    [PresupuestoTeoricoMes12]   NUMERIC (18, 2) NULL,
    [EnviarEmail]               TINYINT         NULL,
    [CodigoAgrupacionAuxiliar]  INT             NULL,
    [IdObraAgrupacionAuxiliar]  INT             NULL,
    [IdProvincia]               INT             NULL,
    [AjustaPorInflacion]        VARCHAR (2)     NULL,
    [CodigoSecundario]          VARCHAR (30)    NULL,
    [IdCuentaConsolidacion]     INT             NULL,
    [IdCuentaConsolidacion2]    INT             NULL,
    [IdCuentaConsolidacion3]    INT             NULL,
    [NumeroAuxiliar]            INT             NULL,
    [IdRubroFinanciero]         INT             NULL,
    [IdPresupuestoObraRubro]    INT             NULL,
    [OrdenamientoAuxiliar]      INT             NULL,
    [TextoAuxiliar1]            VARCHAR (100)   NULL,
    [TextoAuxiliar2]            VARCHAR (100)   NULL,
    [TextoAuxiliar3]            VARCHAR (100)   NULL,
    [ImputarAPresupuestoDeObra] VARCHAR (2)     NULL,
    CONSTRAINT [PK_Cuentas] PRIMARY KEY CLUSTERED ([IdCuenta] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Cuentas_CuentasGastos] FOREIGN KEY ([IdCuentaGasto]) REFERENCES [dbo].[CuentasGastos] ([IdCuentaGasto]),
    CONSTRAINT [FK_Cuentas_TipoCuentaGrupos] FOREIGN KEY ([IdTipoCuentaGrupo]) REFERENCES [dbo].[TiposCuentaGrupos] ([IdTipoCuentaGrupo])
);

