CREATE TABLE [dbo].[DetalleOrdenesCompra] (
    [IdDetalleOrdenCompra]       INT             IDENTITY (1, 1) NOT NULL,
    [IdOrdenCompra]              INT             NULL,
    [NumeroItem]                 INT             NULL,
    [Cantidad]                   NUMERIC (18, 3) NULL,
    [IdUnidad]                   INT             NULL,
    [IdArticulo]                 INT             NULL,
    [Precio]                     NUMERIC (19, 8) NULL,
    [Observaciones]              NTEXT           NULL,
    [OrigenDescripcion]          INT             NULL,
    [TipoCancelacion]            INT             NULL,
    [Cumplido]                   VARCHAR (2)     NULL,
    [FacturacionAutomatica]      VARCHAR (2)     NULL,
    [FechaComienzoFacturacion]   DATETIME        NULL,
    [CantidadMesesAFacturar]     INT             NULL,
    [FacturacionCompletaMensual] VARCHAR (2)     NULL,
    [PorcentajeBonificacion]     NUMERIC (6, 2)  NULL,
    [IdDetalleObraDestino]       INT             NULL,
    [FechaNecesidad]             DATETIME        NULL,
    [FechaEntrega]               DATETIME        NULL,
    [IdColor]                    INT             NULL,
    [IdDioPorCumplido]           INT             NULL,
    [FechaDadoPorCumplido]       DATETIME        NULL,
    [ObservacionesCumplido]      NTEXT           NULL,
    [Estado]                     VARCHAR (2)     NULL,
    [IdUsuarioCambioEstado]      INT             NULL,
    [FechaCambioEstado]          DATETIME        NULL,
    CONSTRAINT [PK_DetallesOrdenesCompra] PRIMARY KEY CLUSTERED ([IdDetalleOrdenCompra] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DetalleOrdenesCompra_OrdenesCompra] FOREIGN KEY ([IdOrdenCompra]) REFERENCES [dbo].[OrdenesCompra] ([IdOrdenCompra]),
    CONSTRAINT [FK_DetalleOrdenesCompra_Unidades] FOREIGN KEY ([IdUnidad]) REFERENCES [dbo].[Unidades] ([IdUnidad])
);

