CREATE TABLE [dbo].[DetalleComprobantesProveedores] (
    [IdDetalleComprobanteProveedor]         INT             IDENTITY (1, 1) NOT NULL,
    [IdComprobanteProveedor]                INT             NULL,
    [IdArticulo]                            INT             NULL,
    [CodigoArticulo]                        VARCHAR (8)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCuenta]                              INT             NULL,
    [CodigoCuenta]                          VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PorcentajeIvaAplicado]                 NUMERIC (6, 2)  NULL,
    [Importe]                               NUMERIC (18, 2) NULL,
    [IdCuentaGasto]                         INT             NULL,
    [IdCuentaIvaCompras1]                   INT             NULL,
    [IVAComprasPorcentaje1]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA1]                           NUMERIC (18, 2) NULL,
    [AplicarIVA1]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras2]                   INT             NULL,
    [IVAComprasPorcentaje2]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA2]                           NUMERIC (18, 2) NULL,
    [AplicarIVA2]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras3]                   INT             NULL,
    [IVAComprasPorcentaje3]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA3]                           NUMERIC (18, 2) NULL,
    [AplicarIVA3]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras4]                   INT             NULL,
    [IVAComprasPorcentaje4]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA4]                           NUMERIC (18, 2) NULL,
    [AplicarIVA4]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras5]                   INT             NULL,
    [IVAComprasPorcentaje5]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA5]                           NUMERIC (18, 2) NULL,
    [AplicarIVA5]                           VARCHAR (2)     NULL,
    [IdObra]                                INT             NULL,
    [Item]                                  INT             NULL,
    [IdCuentaIvaCompras6]                   INT             NULL,
    [IVAComprasPorcentaje6]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA6]                           NUMERIC (18, 2) NULL,
    [AplicarIVA6]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras7]                   INT             NULL,
    [IVAComprasPorcentaje7]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA7]                           NUMERIC (18, 2) NULL,
    [AplicarIVA7]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras8]                   INT             NULL,
    [IVAComprasPorcentaje8]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA8]                           NUMERIC (18, 2) NULL,
    [AplicarIVA8]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras9]                   INT             NULL,
    [IVAComprasPorcentaje9]                 NUMERIC (6, 2)  NULL,
    [ImporteIVA9]                           NUMERIC (18, 2) NULL,
    [AplicarIVA9]                           VARCHAR (2)     NULL,
    [IdCuentaIvaCompras10]                  INT             NULL,
    [IVAComprasPorcentaje10]                NUMERIC (6, 2)  NULL,
    [ImporteIVA10]                          NUMERIC (18, 2) NULL,
    [AplicarIVA10]                          VARCHAR (2)     NULL,
    [IVAComprasPorcentajeDirecto]           NUMERIC (6, 2)  NULL,
    [IdCuentaBancaria]                      INT             NULL,
    [PRESTOConcepto]                        VARCHAR (50)    NULL,
    [PRESTOObra]                            VARCHAR (13)    NULL,
    [IdDetalleRecepcion]                    INT             NULL,
    [TomarEnCalculoDeImpuestos]             VARCHAR (2)     NULL,
    [IdRubroContable]                       INT             NULL,
    [IdPedido]                              INT             NULL,
    [IdDetallePedido]                       INT             NULL,
    [Importacion_FOB]                       NUMERIC (18, 2) NULL,
    [Importacion_PosicionAduana]            VARCHAR (20)    NULL,
    [Importacion_Despacho]                  VARCHAR (30)    NULL,
    [Importacion_Guia]                      VARCHAR (20)    NULL,
    [Importacion_IdPaisOrigen]              INT             NULL,
    [Importacion_FechaEmbarque]             DATETIME        NULL,
    [Importacion_FechaOficializacion]       DATETIME        NULL,
    [IdProvinciaDestino1]                   INT             NULL,
    [PorcentajeProvinciaDestino1]           NUMERIC (6, 2)  NULL,
    [IdProvinciaDestino2]                   INT             NULL,
    [PorcentajeProvinciaDestino2]           NUMERIC (6, 2)  NULL,
    [IdDistribucionObra]                    INT             NULL,
    [Cantidad]                              NUMERIC (18, 2) NULL,
    [IdDetalleObraDestino]                  INT             NULL,
    [IdPresupuestoObraRubro]                INT             NULL,
    [IdPedidoAnticipo]                      INT             NULL,
    [PorcentajeAnticipo]                    NUMERIC (6, 2)  NULL,
    [PorcentajeCertificacion]               NUMERIC (6, 2)  NULL,
    [IdPresupuestoObrasNodo]                INT             NULL,
    [IdDetalleComprobanteProveedorOriginal] INT             NULL,
    [NumeroSubcontrato]                     INT             NULL,
    [IdSubcontrato]                         INT             NULL,
    [AmpliacionSubcontrato]                 VARCHAR (2)     NULL,
    [IdDetalleSubcontratoDatos]             INT             NULL,
    [IdEquipoDestino]                       INT             NULL,
    [IdUsuarioModificoCuenta]               INT             NULL,
    [FechaModificacionCuenta]               DATETIME        NULL,
    CONSTRAINT [PK_DetalleComprobantesProveedores] PRIMARY KEY NONCLUSTERED ([IdDetalleComprobanteProveedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DetalleComprobantesProveedores] FOREIGN KEY ([IdComprobanteProveedor]) REFERENCES [dbo].[ComprobantesProveedores] ([IdComprobanteProveedor]),
    CONSTRAINT [FK_DetalleComprobantesProveedores_Cuenta] FOREIGN KEY ([IdCuenta]) REFERENCES [dbo].[Cuentas] ([IdCuenta])
);

