CREATE TABLE [dbo].[DetalleAutorizaciones] (
    [IdDetalleAutorizacion] INT             IDENTITY (1, 1) NOT NULL,
    [IdAutorizacion]        INT             NULL,
    [OrdenAutorizacion]     INT             NULL,
    [SectorEmisor1]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza1]     INT             NULL,
    [IdCargoAutoriza1]      INT             NULL,
    [SectorEmisor2]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza2]     INT             NULL,
    [IdCargoAutoriza2]      INT             NULL,
    [SectorEmisor3]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza3]     INT             NULL,
    [IdCargoAutoriza3]      INT             NULL,
    [SectorEmisor4]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza4]     INT             NULL,
    [IdCargoAutoriza4]      INT             NULL,
    [SectorEmisor5]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza5]     INT             NULL,
    [IdCargoAutoriza5]      INT             NULL,
    [SectorEmisor6]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSectorAutoriza6]     INT             NULL,
    [IdCargoAutoriza6]      INT             NULL,
    [IdFirmante1]           INT             NULL,
    [ImporteDesde1]         NUMERIC (18, 2) NULL,
    [ImporteHasta1]         NUMERIC (18, 2) NULL,
    [IdFirmante2]           INT             NULL,
    [ImporteDesde2]         NUMERIC (18, 2) NULL,
    [ImporteHasta2]         NUMERIC (18, 2) NULL,
    [IdFirmante3]           INT             NULL,
    [ImporteDesde3]         NUMERIC (18, 2) NULL,
    [ImporteHasta3]         NUMERIC (18, 2) NULL,
    [IdFirmante4]           INT             NULL,
    [ImporteDesde4]         NUMERIC (18, 2) NULL,
    [ImporteHasta4]         NUMERIC (18, 2) NULL,
    [IdFirmante5]           INT             NULL,
    [ImporteDesde5]         NUMERIC (18, 2) NULL,
    [ImporteHasta5]         NUMERIC (18, 2) NULL,
    [IdFirmante6]           INT             NULL,
    [ImporteDesde6]         NUMERIC (18, 2) NULL,
    [ImporteHasta6]         NUMERIC (18, 2) NULL,
    [PersonalObra1]         INT             NULL,
    [PersonalObra2]         INT             NULL,
    [PersonalObra3]         INT             NULL,
    [PersonalObra4]         INT             NULL,
    [PersonalObra5]         INT             NULL,
    [PersonalObra6]         INT             NULL,
    [ADesignar]             VARCHAR (2)     NULL,
    [IdsTipoCompra]         VARCHAR (100)   NULL,
    CONSTRAINT [PK_DetalleAutorizaciones] PRIMARY KEY CLUSTERED ([IdDetalleAutorizacion] ASC) WITH (FILLFACTOR = 90)
);

