CREATE TABLE [dbo].[DetallePedidos] (
    [IdDetallePedido]                INT             IDENTITY (1, 1) NOT NULL,
    [IdPedido]                       INT             NULL,
    [NumeroItem]                     INT             NULL,
    [Cantidad]                       NUMERIC (18, 2) NULL,
    [IdUnidad]                       INT             NULL,
    [IdArticulo]                     INT             NULL,
    [FechaEntrega]                   DATETIME        NULL,
    [IdControlCalidad]               INT             NULL,
    [Precio]                         NUMERIC (18, 4) NULL,
    [Observaciones]                  NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad1]                      NUMERIC (18, 2) NULL,
    [Cantidad2]                      NUMERIC (18, 2) NULL,
    [IdDetalleAcopios]               INT             NULL,
    [IdDetalleRequerimiento]         INT             NULL,
    [Cumplido]                       VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadAdicional]              NUMERIC (18, 2) NULL,
    [CantidadRecibida]               NUMERIC (18, 2) NULL,
    [CantidadAdicionalRecibida]      NUMERIC (18, 2) NULL,
    [Adjunto]                        VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto]                 VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaNecesidad]                 DATETIME        NULL,
    [IdDetalleLMateriales]           INT             NULL,
    [IdCuenta]                       INT             NULL,
    [OrigenDescripcion]              INT             NULL,
    [ArchivoAdjunto1]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto2]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto3]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto4]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto5]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto6]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto7]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto8]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto9]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto10]               VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdAutorizoCumplido]             INT             NULL,
    [IdDioPorCumplido]               INT             NULL,
    [FechaDadoPorCumplido]           DATETIME        NULL,
    [ObservacionesCumplido]          NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCentroCosto]                  INT             NULL,
    [PorcentajeBonificacion]         NUMERIC (18, 2) NULL,
    [Importebonificacion]            NUMERIC (18, 4) NULL,
    [PorcentajeIVA]                  NUMERIC (18, 2) NULL,
    [ImporteIva]                     NUMERIC (18, 4) NULL,
    [ImporteTotalItem]               NUMERIC (18, 4) NULL,
    [Costo]                          NUMERIC (18, 2) NULL,
    [PRESTOPedido]                   VARCHAR (13)    NULL,
    [PRESTOFechaProceso]             DATETIME        NULL,
    [IdAsignacionCosto]              INT             NULL,
    [CostoAsignado]                  NUMERIC (18, 4) NULL,
    [IdUsuarioAsignoCosto]           INT             NULL,
    [FechaAsignacionCosto]           DATETIME        NULL,
    [EnviarEmail]                    TINYINT         NULL,
    [IdDetallePedidoOriginal]        INT             NULL,
    [IdPedidoOriginal]               INT             NULL,
    [IdOrigenTransmision]            INT             NULL,
    [PlazoEntrega]                   VARCHAR (50)    NULL,
    [CostoAsignadoDolar]             NUMERIC (18, 4) NULL,
    [IdDetalleComparativa]           INT             NULL,
    [IdDetalleRequerimientoOriginal] INT             NULL,
    [ImpuestosInternos]              NUMERIC (18, 2) NULL,
    [CostoOriginal]                  NUMERIC (18, 4) NULL,
    [IdUsuarioModificoCosto]         INT             NULL,
    [FechaModificacionCosto]         DATETIME        NULL,
    [ObservacionModificacionCosto]   NTEXT           NULL,
    CONSTRAINT [PK_DetallePedidos] PRIMARY KEY CLUSTERED ([IdDetallePedido] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DetallePedidos_ControlCalidad] FOREIGN KEY ([IdControlCalidad]) REFERENCES [dbo].[ControlesCalidad] ([IdControlCalidad]),
    CONSTRAINT [FK_DetallePedidos_DetalleComparativa] FOREIGN KEY ([IdDetalleComparativa]) REFERENCES [dbo].[DetalleComparativas] ([IdDetalleComparativa]),
    CONSTRAINT [FK_DetallePedidos_DetalleRequerimientos] FOREIGN KEY ([IdDetalleRequerimiento]) REFERENCES [dbo].[DetalleRequerimientos] ([IdDetalleRequerimiento])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[DetallePedidos]([IdDetalleRequerimiento] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Indice2]
    ON [dbo].[DetallePedidos]([IdPedido] ASC) WITH (FILLFACTOR = 90);

