CREATE TABLE [dbo].[DetalleLMateriales] (
    [IdDetalleLMateriales]         INT             IDENTITY (1, 1) NOT NULL,
    [IdLMateriales]                INT             NULL,
    [NumeroItem]                   INT             NULL,
    [NumeroOrden]                  INT             NULL,
    [Revision]                     VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad]                     NUMERIC (18, 2) NULL,
    [IdUnidad]                     INT             NULL,
    [IdArticulo]                   INT             NULL,
    [Peso]                         NUMERIC (18, 2) NULL,
    [IdUnidadPeso]                 INT             NULL,
    [IdControlCalidad]             INT             NULL,
    [Cantidad1]                    NUMERIC (18, 2) NULL,
    [Cantidad2]                    NUMERIC (18, 2) NULL,
    [Detalle]                      VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdPlano]                      INT             NULL,
    [IdDetalleAcopios]             INT             NULL,
    [Adjunto]                      VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto]               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]                NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Despacha]                     VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto1]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto2]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto3]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto4]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto5]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto6]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto7]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto8]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto9]              VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto10]             VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DescripcionManual]            VARCHAR (250)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EnviarEmail]                  TINYINT         NULL,
    [IdLMaterialesOriginal]        INT             NULL,
    [IdDetalleLMaterialesOriginal] INT             NULL,
    [IdOrigenTransmision]          INT             NULL,
    [IdDetalleObraDestino]         INT             NULL,
    CONSTRAINT [PK_DetalleLMateriales] PRIMARY KEY CLUSTERED ([IdDetalleLMateriales] ASC) WITH (FILLFACTOR = 90)
);

