CREATE TABLE [dbo].[DetalleSalidasMaterialesSAT] (
    [IdDetalleSalidaMateriales]         INT             IDENTITY (1, 1) NOT NULL,
    [IdSalidaMateriales]                INT             NULL,
    [IdArticulo]                        INT             NULL,
    [IdStock]                           INT             NULL,
    [Partida]                           INT             NULL,
    [Cantidad]                          DECIMAL (18, 2) NULL,
    [CantidadAdicional]                 DECIMAL (18, 2) NULL,
    [IdUnidad]                          INT             NULL,
    [Cantidad1]                         DECIMAL (18, 2) NULL,
    [Cantidad2]                         DECIMAL (18, 2) NULL,
    [IdDetalleValeSalida]               INT             NULL,
    [Adjunto]                           VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto1]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto2]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto3]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto4]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto5]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto6]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto7]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto8]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto9]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto10]                  VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]                     NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdUbicacion]                       INT             NULL,
    [IdObra]                            INT             NULL,
    [CostoUnitario]                     NUMERIC (18, 4) NULL,
    [IdMoneda]                          INT             NULL,
    [CotizacionDolar]                   NUMERIC (18, 4) NULL,
    [CotizacionMoneda]                  NUMERIC (18, 4) NULL,
    [IdEquipoDestino]                   INT             NULL,
    [EnviarEmail]                       TINYINT         NULL,
    [IdDetalleSalidaMaterialesOriginal] INT             NULL,
    [IdSalidaMaterialesOriginal]        INT             NULL,
    [IdOrigenTransmision]               INT             NULL,
    CONSTRAINT [PK_DetalleSalidasMaterialesSAT] PRIMARY KEY CLUSTERED ([IdDetalleSalidaMateriales] ASC) WITH (FILLFACTOR = 90)
);

