CREATE TABLE [dbo].[DetalleRecepcionesSAT] (
    [IdDetalleRecepcion]              INT             IDENTITY (1, 1) NOT NULL,
    [IdRecepcion]                     INT             NULL,
    [Cantidad]                        DECIMAL (18, 2) NULL,
    [IdUnidad]                        INT             NULL,
    [IdArticulo]                      INT             NULL,
    [IdControlCalidad]                INT             NULL,
    [Observaciones]                   NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad1]                       DECIMAL (18, 2) NULL,
    [Cantidad2]                       DECIMAL (18, 2) NULL,
    [IdDetallePedido]                 INT             NULL,
    [Controlado]                      VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadAdicional]               NUMERIC (18, 2) NULL,
    [Partida]                         VARCHAR (20)    NULL,
    [CantidadCC]                      NUMERIC (18, 2) NULL,
    [Cantidad1CC]                     NUMERIC (18, 2) NULL,
    [Cantidad2CC]                     NUMERIC (18, 2) NULL,
    [CantidadAdicionalCC]             NUMERIC (18, 2) NULL,
    [ObservacionesCC]                 NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CantidadRechazadaCC]             NUMERIC (18, 2) NULL,
    [IdMotivoRechazo]                 INT             NULL,
    [IdRealizo]                       INT             NULL,
    [IdDetalleRequerimiento]          INT             NULL,
    [Trasabilidad]                    VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdDetalleAcopios]                INT             NULL,
    [IdUbicacion]                     INT             NULL,
    [IdObra]                          INT             NULL,
    [CostoUnitario]                   NUMERIC (18, 3) NULL,
    [IdMoneda]                        INT             NULL,
    [CotizacionDolar]                 NUMERIC (18, 3) NULL,
    [CotizacionMoneda]                NUMERIC (18, 3) NULL,
    [EnviarEmail]                     TINYINT         NULL,
    [IdDetalleRecepcionOriginal]      INT             NULL,
    [IdRecepcionOriginal]             INT             NULL,
    [IdOrigenTransmision]             INT             NULL,
    [IdDetalleSalidaMaterialesPRONTO] INT             NULL,
    CONSTRAINT [PK_DetalleRecepcionesSAT] PRIMARY KEY CLUSTERED ([IdDetalleRecepcion] ASC) WITH (FILLFACTOR = 90)
);

