CREATE TABLE [dbo].[DetalleAcopios] (
    [IdDetalleAcopios]         INT             IDENTITY (1, 1) NOT NULL,
    [IdAcopio]                 INT             NULL,
    [NumeroItem]               INT             NULL,
    [Revision]                 VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad]                 DECIMAL (18, 2) NULL,
    [IdUnidad]                 INT             NULL,
    [IdArticulo]               INT             NULL,
    [Peso]                     DECIMAL (18, 2) NULL,
    [IdUnidadPeso]             INT             NULL,
    [IdControlCalidad]         INT             NULL,
    [FechaNecesidad]           DATETIME        NULL,
    [Adjunto]                  VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cantidad1]                NUMERIC (18, 2) NULL,
    [Cantidad2]                NUMERIC (18, 2) NULL,
    [ArchivoAdjunto]           VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]            NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCuenta]                 INT             NULL,
    [Cumplido]                 VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto1]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto2]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto3]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto4]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto5]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto6]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto7]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto8]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto9]          VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ArchivoAdjunto10]         VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdProveedor]              INT             NULL,
    [IdComprador]              INT             NULL,
    [IdLlamadoAProveedor]      INT             NULL,
    [FechaLlamadoAProveedor]   DATETIME        NULL,
    [IdLlamadoRegistradoPor]   INT             NULL,
    [FechaRegistracionLlamada] DATETIME        NULL,
    [ObservacionesLlamada]     NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdAutorizoCumplido]       INT             NULL,
    [IdDioPorCumplido]         INT             NULL,
    [FechaDadoPorCumplido]     DATETIME        NULL,
    [ObservacionesCumplido]    NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdAproboAlmacen]          INT             NULL,
    [EnviarEmail]              TINYINT         NULL,
    [IdAcopioOriginal]         INT             NULL,
    [IdDetalleAcopiosOriginal] INT             NULL,
    [IdOrigenTransmision]      INT             NULL,
    [Precio]                   NUMERIC (18, 2) NULL,
    [IdEquipo]                 INT             NULL,
    [FechaEntrega_Tel]         DATETIME        NULL,
    CONSTRAINT [PK_DetalleAcopios] PRIMARY KEY CLUSTERED ([IdDetalleAcopios] ASC) WITH (FILLFACTOR = 90)
);

