CREATE TABLE [dbo].[Devoluciones] (
    [IdDevolucion]            INT             IDENTITY (1, 1) NOT NULL,
    [NumeroDevolucion]        INT             NULL,
    [TipoABC]                 VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PuntoVenta]              INT             NULL,
    [IdFactura]               INT             NULL,
    [IdCliente]               INT             NULL,
    [FechaDevolucion]         DATETIME        NULL,
    [IdVendedor]              INT             NULL,
    [TipoPedidoConsignacion]  VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Anulada]                 VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaAnulacion]          DATETIME        NULL,
    [ImporteTotal]            NUMERIC (19, 2) NULL,
    [ImporteIva1]             NUMERIC (19, 2) NULL,
    [ImporteIva2]             NUMERIC (19, 2) NULL,
    [ImporteBonificacion]     NUMERIC (19, 2) NULL,
    [RetencionIBrutos1]       NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos1]      NUMERIC (6, 2)  NULL,
    [RetencionIBrutos2]       NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos2]      NUMERIC (6, 2)  NULL,
    [ConvenioMultilateral]    VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RetencionIBrutos3]       NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos3]      NUMERIC (6, 2)  NULL,
    [IdTipoVentaC]            SMALLINT        NULL,
    [ImporteIvaIncluido]      NUMERIC (19, 2) NULL,
    [CotizacionDolar]         NUMERIC (18, 2) NULL,
    [PorcentajeIva1]          NUMERIC (6, 2)  NULL,
    [PorcentajeIva2]          NUMERIC (6, 2)  NULL,
    [IVANoDiscriminado]       NUMERIC (18, 2) NULL,
    [IdMoneda]                INT             NULL,
    [CotizacionMoneda]        NUMERIC (18, 4) NULL,
    [PorcentajeBonificacion]  NUMERIC (6, 2)  NULL,
    [Observaciones]           NTEXT           NULL,
    [FechaRegistracion]       DATETIME        NULL,
    [IdProvinciaDestino]      INT             NULL,
    [OtrasPercepciones1]      NUMERIC (18, 2) NULL,
    [OtrasPercepciones1Desc]  VARCHAR (15)    NULL,
    [OtrasPercepciones2]      NUMERIC (18, 2) NULL,
    [OtrasPercepciones2Desc]  VARCHAR (15)    NULL,
    [IdIBCondicion]           INT             NULL,
    [IdPuntoVenta]            INT             NULL,
    [NumeroCAI]               NUMERIC (19)    NULL,
    [FechaVencimientoCAI]     DATETIME        NULL,
    [IdObra]                  INT             NULL,
    [IdCodigoIva]             INT             NULL,
    [IdListaPrecios]          INT             NULL,
    [IdIBCondicion2]          INT             NULL,
    [IdIBCondicion3]          INT             NULL,
    [PercepcionIVA]           NUMERIC (18, 2) NULL,
    [PorcentajePercepcionIVA] NUMERIC (6, 2)  NULL,
    [IdDeposito]              INT             NULL,
    [IdUsuarioAnulacion]      INT             NULL,
    CONSTRAINT [PK_Devoluciones] PRIMARY KEY NONCLUSTERED ([IdDevolucion] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Devoluciones]([FechaDevolucion] ASC, [IdDevolucion] ASC) WITH (FILLFACTOR = 90);

