CREATE TABLE [dbo].[Empleados] (
    [IdEmpleado]                   INT             IDENTITY (1, 1) NOT NULL,
    [Legajo]                       INT             NULL,
    [Nombre]                       VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UsuarioNT]                    VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSector]                     INT             NULL,
    [IdCargo]                      INT             NULL,
    [Email]                        VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Interno]                      VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Administrador]                VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Iniciales]                    VARCHAR (6)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Password]                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SisMan]                       VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [HorasJornada]                 NUMERIC (18, 2) NULL,
    [IdSector1]                    INT             NULL,
    [IdCargo1]                     INT             NULL,
    [IdSector2]                    INT             NULL,
    [IdCargo2]                     INT             NULL,
    [IdSector3]                    INT             NULL,
    [IdCargo3]                     INT             NULL,
    [IdSector4]                    INT             NULL,
    [IdCargo4]                     INT             NULL,
    [Dominio]                      VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SisMat]                       VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaNacimiento]              DATETIME        NULL,
    [TipoUsuario]                  INT             NULL,
    [GrupoDeCarga]                 INT             NULL,
    [CuentaBancaria]               VARCHAR (20)    NULL,
    [InformacionAuxiliar]          VARCHAR (50)    NULL,
    [IdCuentaFondoFijo]            INT             NULL,
    [IdObraAsignada]               INT             NULL,
    [Activo]                       VARCHAR (2)     NULL,
    [Idioma]                       VARCHAR (3)     NULL,
    [PuntoVentaAsociado]           INT             NULL,
    [IdLugarEntregaAsignado]       INT             NULL,
    [EsConductor]                  VARCHAR (2)     NULL,
    [FechaVencimientoRegistro]     DATETIME        NULL,
    [LimitarUbicacionesAsignadas]  VARCHAR (2)     NULL,
    [PermitirAccesoATodasLasObras] VARCHAR (2)     NULL,
    CONSTRAINT [PK_Empleados] PRIMARY KEY CLUSTERED ([IdEmpleado] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Empleados_Cargos] FOREIGN KEY ([IdCargo]) REFERENCES [dbo].[Cargos] ([IdCargo]),
    CONSTRAINT [FK_Empleados_Sectores] FOREIGN KEY ([IdSector]) REFERENCES [dbo].[Sectores] ([IdSector])
);

