CREATE TABLE [dbo].[ExcelImportador] (
    [IdExcelImportador]            INT           IDENTITY (1, 1) NOT NULL,
    [IdTanda]                      INT           NULL,
    [FechaIngreso]                 DATETIME      NULL,
    [IdUsuarioIngreso]             INT           NULL,
    [FechaTimeStamp]               ROWVERSION    NULL,
    [Estado]                       VARCHAR (50)  NULL,
    [check1]                       VARCHAR (50)  NULL,
    [URLgenerada]                  VARCHAR (50)  NULL,
    [IdTitular]                    VARCHAR (50)  NULL,
    [IdIntermediario]              VARCHAR (50)  NULL,
    [IdRComercial]                 VARCHAR (50)  NULL,
    [IdCorredor]                   VARCHAR (50)  NULL,
    [IdDestinatario]               VARCHAR (50)  NULL,
    [IdChofer]                     VARCHAR (50)  NULL,
    [Producto]                     VARCHAR (100) NULL,
    [Titular]                      VARCHAR (100) NULL,
    [Intermediario]                VARCHAR (100) NULL,
    [RComercial]                   VARCHAR (100) NULL,
    [Corredor]                     VARCHAR (100) NULL,
    [Procedencia]                  VARCHAR (100) NULL,
    [Patente]                      VARCHAR (50)  NULL,
    [NumeroCDP]                    VARCHAR (50)  NULL,
    [Acoplado]                     VARCHAR (50)  NULL,
    [NetoProc]                     VARCHAR (50)  NULL,
    [Calidad]                      VARCHAR (50)  NULL,
    [column12]                     VARCHAR (50)  NULL,
    [column13]                     VARCHAR (50)  NULL,
    [column14]                     VARCHAR (50)  NULL,
    [column15]                     VARCHAR (50)  NULL,
    [column16]                     VARCHAR (50)  NULL,
    [column17]                     VARCHAR (50)  NULL,
    [column18]                     VARCHAR (50)  NULL,
    [column19]                     VARCHAR (50)  NULL,
    [column20]                     VARCHAR (50)  NULL,
    [column21]                     VARCHAR (50)  NULL,
    [column22]                     VARCHAR (50)  NULL,
    [column23]                     VARCHAR (50)  NULL,
    [column24]                     VARCHAR (50)  NULL,
    [column25]                     VARCHAR (50)  NULL,
    [Comprador]                    VARCHAR (100) NULL,
    [Destino]                      VARCHAR (100) NULL,
    [Subcontratista1]              VARCHAR (50)  NULL,
    [Subcontratista2]              VARCHAR (50)  NULL,
    [FechaDescarga]                VARCHAR (50)  NULL,
    [Hora]                         VARCHAR (50)  NULL,
    [Auxiliar1]                    VARCHAR (50)  NULL,
    [Auxiliar2]                    VARCHAR (50)  NULL,
    [Auxiliar3]                    VARCHAR (50)  NULL,
    [Auxiliar4]                    VARCHAR (50)  NULL,
    [Auxiliar5]                    VARCHAR (50)  NULL,
    [EntregadorFiltrarPorWilliams] VARCHAR (50)  NULL,
    [CTG]                          VARCHAR (50)  NULL,
    [KmARecorrer]                  VARCHAR (50)  NULL,
    [TarifaTransportista]          VARCHAR (50)  NULL,
    [Exporta]                      VARCHAR (10)  NULL,
    [SubnumeroDeFacturacion]       VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([IdExcelImportador] ASC) WITH (FILLFACTOR = 90)
);

