CREATE TABLE [dbo].[Facturas] (
    [IdFactura]                                       INT              IDENTITY (1, 1) NOT NULL,
    [NumeroFactura]                                   INT              NULL,
    [TipoABC]                                         VARCHAR (1)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PuntoVenta]                                      INT              NULL,
    [IdCliente]                                       INT              NULL,
    [FechaFactura]                                    DATETIME         NULL,
    [IdCondicionVenta]                                SMALLINT         NULL,
    [IdVendedor]                                      INT              NULL,
    [IdTransportista1]                                INT              NULL,
    [IdTransportista2]                                INT              NULL,
    [ItemDireccion]                                   TINYINT          NULL,
    [OrdenCompra]                                     VARCHAR (20)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TipoPedidoConsignacion]                          VARCHAR (1)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Anulada]                                         VARCHAR (2)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaAnulacion]                                  DATETIME         NULL,
    [Observaciones]                                   NTEXT            COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdRemito]                                        INT              NULL,
    [NumeroRemito]                                    INT              NULL,
    [IdPedido]                                        INT              NULL,
    [NumeroPedido]                                    INT              NULL,
    [ImporteTotal]                                    NUMERIC (19, 2)  NULL,
    [ImporteIva1]                                     NUMERIC (19, 2)  NULL,
    [ImporteIva2]                                     NUMERIC (19, 2)  NULL,
    [ImporteBonificacion]                             NUMERIC (19, 2)  NULL,
    [RetencionIBrutos1]                               NUMERIC (19, 2)  NULL,
    [PorcentajeIBrutos1]                              NUMERIC (6, 2)   NULL,
    [RetencionIBrutos2]                               NUMERIC (19, 2)  NULL,
    [PorcentajeIBrutos2]                              NUMERIC (6, 2)   NULL,
    [ConvenioMultilateral]                            VARCHAR (2)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RetencionIBrutos3]                               NUMERIC (19, 2)  NULL,
    [PorcentajeIBrutos3]                              NUMERIC (6, 2)   NULL,
    [IdTipoVentaC]                                    SMALLINT         NULL,
    [ImporteIvaIncluido]                              NUMERIC (19, 2)  NULL,
    [CotizacionDolar]                                 NUMERIC (18, 3)  NULL,
    [EsMuestra]                                       VARCHAR (2)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CotizacionADolarFijo]                            NUMERIC (18, 3)  NULL,
    [ImporteParteEnDolares]                           NUMERIC (18, 2)  NULL,
    [ImporteParteEnPesos]                             NUMERIC (18, 2)  NULL,
    [PorcentajeIva1]                                  NUMERIC (6, 2)   NULL,
    [PorcentajeIva2]                                  NUMERIC (6, 2)   NULL,
    [FechaVencimiento]                                DATETIME         NULL,
    [IVANoDiscriminado]                               NUMERIC (18, 2)  NULL,
    [IdMoneda]                                        INT              NULL,
    [CotizacionMoneda]                                NUMERIC (18, 4)  NULL,
    [PorcentajeBonificacion]                          NUMERIC (6, 2)   NULL,
    [OtrasPercepciones1]                              NUMERIC (18, 2)  NULL,
    [OtrasPercepciones1Desc]                          VARCHAR (15)     NULL,
    [OtrasPercepciones2]                              NUMERIC (18, 2)  NULL,
    [OtrasPercepciones2Desc]                          VARCHAR (15)     NULL,
    [IdProvinciaDestino]                              INT              NULL,
    [IdIBCondicion]                                   INT              NULL,
    [IdAutorizaAnulacion]                             INT              NULL,
    [IdPuntoVenta]                                    INT              NULL,
    [NumeroCAI]                                       NUMERIC (19)     NULL,
    [FechaVencimientoCAI]                             DATETIME         NULL,
    [NumeroCertificadoPercepcionIIBB]                 INT              NULL,
    [NumeroTicketInicial]                             INT              NULL,
    [NumeroTicketFinal]                               INT              NULL,
    [IdUsuarioIngreso]                                INT              NULL,
    [FechaIngreso]                                    DATETIME         NULL,
    [IdObra]                                          INT              NULL,
    [IdIBCondicion2]                                  INT              NULL,
    [IdIBCondicion3]                                  INT              NULL,
    [IdCodigoIva]                                     INT              NULL,
    [Exportacion_FOB]                                 NUMERIC (18, 2)  NULL,
    [Exportacion_PosicionAduana]                      VARCHAR (20)     NULL,
    [Exportacion_Despacho]                            VARCHAR (30)     NULL,
    [Exportacion_Guia]                                VARCHAR (20)     NULL,
    [Exportacion_IdPaisDestino]                       INT              NULL,
    [Exportacion_FechaEmbarque]                       DATETIME         NULL,
    [Exportacion_FechaOficializacion]                 DATETIME         NULL,
    [OtrasPercepciones3]                              NUMERIC (18, 2)  NULL,
    [OtrasPercepciones3Desc]                          VARCHAR (15)     NULL,
    [NoIncluirEnCubos]                                VARCHAR (2)      NULL,
    [PercepcionIVA]                                   NUMERIC (18, 2)  NULL,
    [PorcentajePercepcionIVA]                         NUMERIC (6, 2)   NULL,
    [ActivarRecuperoGastos]                           VARCHAR (2)      NULL,
    [IdAutorizoRecuperoGastos]                        INT              NULL,
    [ContabilizarAFechaVencimiento]                   VARCHAR (2)      NULL,
    [FacturaContado]                                  VARCHAR (2)      NULL,
    [IdReciboContado]                                 INT              NULL,
    [EnviarEmail]                                     TINYINT          NULL,
    [IdOrigenTransmision]                             INT              NULL,
    [IdFacturaOriginal]                               INT              NULL,
    [FechaImportacionTransmision]                     DATETIME         NULL,
    [CuitClienteTransmision]                          VARCHAR (13)     NULL,
    [IdReciboContadoOriginal]                         INT              NULL,
    [DevolucionAnticipo]                              VARCHAR (2)      NULL,
    [PorcentajeDevolucionAnticipo]                    NUMERIC (18, 10) NULL,
    [CAE]                                             VARCHAR (14)     NULL,
    [RechazoCAE]                                      VARCHAR (11)     NULL,
    [FechaVencimientoORechazoCAE]                     DATETIME         NULL,
    [IdListaPrecios]                                  INT              NULL,
    [IdIdentificacionCAE]                             INT              NULL,
    [AjusteIva]                                       NUMERIC (18, 2)  NULL,
    [TipoExportacion]                                 INT              NULL,
    [PermisoEmbarque]                                 VARCHAR (2)      NULL,
    [NumeroFacturaInicial]                            INT              NULL,
    [NumeroFacturaFinal]                              INT              NULL,
    [CodigoIdAuxiliar]                                INT              NULL,
    [NumeroCertificadoObra]                           INT              NULL,
    [ImporteCertificacionObra]                        NUMERIC (18, 2)  NULL,
    [FondoReparoCertificacionObra]                    NUMERIC (18, 2)  NULL,
    [PorcentajeRetencionesEstimadasCertificacionObra] NUMERIC (6, 2)   NULL,
    [NumeroExpedienteCertificacionObra]               VARCHAR (20)     NULL,
    [NumeroProyecto]                                  INT              NULL,
    [IdCertificacionObras]                            INT              NULL,
    [IdCertificacionObraDatos]                        INT              NULL,
    [FechaRecepcionCliente]                           DATETIME         NULL,
    [CuentaVentaLetra]                                VARCHAR (1)      NULL,
    [CuentaVentaPuntoVenta]                           INT              NULL,
    [CuentaVentaNumero]                               INT              NULL,
    [IdDeposito]                                      INT              NULL,
    [Cliente]                                         VARCHAR (50)     NULL,
    [OrigenRegistro]                                  VARCHAR (12)     NULL,
    [TotalBultos]                                     INT              NULL,
    [IdDetalleClienteLugarEntrega]                    INT              NULL,
    [CuitClienteExterno]                              VARCHAR (13)     NULL,
    [ComisionDiferenciada]                            NUMERIC (6, 2)   NULL,
    [IdTipoNegocioVentas]                             INT              NULL,
    [NumeroOrdenCompraExterna]                        BIGINT           NULL,
    [IdTipoOperacion]                                 INT              NULL,
    [FueEnviadoCorreoConFacturaElectronica]           VARCHAR (2)      NULL,
    CONSTRAINT [PK_Facturas] PRIMARY KEY NONCLUSTERED ([IdFactura] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Facturas_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente]),
    CONSTRAINT [FK_Facturas_Obra] FOREIGN KEY ([IdObra]) REFERENCES [dbo].[Obras] ([IdObra]),
    CONSTRAINT [FK_Facturas_Provincia] FOREIGN KEY ([IdProvinciaDestino]) REFERENCES [dbo].[Provincias] ([IdProvincia]),
    CONSTRAINT [FK_Facturas_Vendedor] FOREIGN KEY ([IdVendedor]) REFERENCES [dbo].[Vendedores] ([IdVendedor])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Facturas]([FechaFactura] ASC, [IdFactura] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IDX_Facturas_Superbuscador5]
    ON [dbo].[Facturas]([IdFactura] ASC, [NumeroFactura] ASC, [FechaFactura] ASC);

