CREATE TABLE [dbo].[IBCondiciones] (
    [IdIBCondicion]                  INT             IDENTITY (1, 1) NOT NULL,
    [Descripcion]                    VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImporteTopeMinimo]              NUMERIC (18, 2) NULL,
    [Alicuota]                       NUMERIC (8, 3)  NULL,
    [FechaVigencia]                  DATETIME        NULL,
    [AcumulaMensualmente]            VARCHAR (2)     NULL,
    [BaseCalculo]                    VARCHAR (15)    NULL,
    [AlicuotaPercepcion]             NUMERIC (8, 3)  NULL,
    [IdProvincia]                    INT             NULL,
    [ImporteTopeMinimoPercepcion]    NUMERIC (18, 2) NULL,
    [AlicuotaPercepcionConvenio]     NUMERIC (8, 3)  NULL,
    [IdCuentaPercepcionIIBB]         INT             NULL,
    [IdCuentaPercepcionIIBBConvenio] INT             NULL,
    [PorcentajeATomarSobreBase]      NUMERIC (6, 2)  NULL,
    [PorcentajeAdicional]            NUMERIC (6, 2)  NULL,
    [LeyendaPorcentajeAdicional]     VARCHAR (50)    NULL,
    [Codigo]                         INT             NULL,
    [CodigoAFIP]                     INT             NULL,
    [InformacionAuxiliar]            VARCHAR (50)    NULL,
    [IdCuentaPercepcionIIBBCompras]  INT             NULL,
    [IdProvinciaReal]                INT             NULL,
    [CodigoNormaRetencion]           INT             NULL,
    [CodigoNormaPercepcion]          INT             NULL,
    [CodigoActividad]                INT             NULL,
    [CodigoArticuloInciso]           VARCHAR (5)     NULL,
    CONSTRAINT [PK_IBCondiciones] PRIMARY KEY CLUSTERED ([IdIBCondicion] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IBCondiciones_Cuentas_IIBB] FOREIGN KEY ([IdCuentaPercepcionIIBB]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_IBCondiciones_Cuentas_IIBBCompras] FOREIGN KEY ([IdCuentaPercepcionIIBBCompras]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_IBCondiciones_Cuentas_IIBBConvenio] FOREIGN KEY ([IdCuentaPercepcionIIBBConvenio]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_IBCondiciones_Provincias] FOREIGN KEY ([IdProvincia]) REFERENCES [dbo].[Provincias] ([IdProvincia]),
    CONSTRAINT [FK_IBCondiciones_Provincias_Real] FOREIGN KEY ([IdProvinciaReal]) REFERENCES [dbo].[Provincias] ([IdProvincia])
);

