CREATE TABLE [dbo].[NotasDebito] (
    [IdNotaDebito]                      INT             IDENTITY (1, 1) NOT NULL,
    [NumeroNotaDebito]                  INT             NULL,
    [TipoABC]                           VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PuntoVenta]                        SMALLINT        NULL,
    [IdCliente]                         INT             NULL,
    [FechaNotaDebito]                   DATETIME        NULL,
    [IdVendedor]                        INT             NULL,
    [ImporteTotal]                      NUMERIC (19, 2) NULL,
    [ImporteIva1]                       NUMERIC (19, 2) NULL,
    [ImporteIva2]                       NUMERIC (19, 2) NULL,
    [RetencionIBrutos1]                 NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos1]                NUMERIC (6, 2)  NULL,
    [RetencionIBrutos2]                 NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos2]                NUMERIC (6, 2)  NULL,
    [IdCodigoIva]                       INT             NULL,
    [PorcentajeIva1]                    NUMERIC (6, 2)  NULL,
    [PorcentajeIva2]                    NUMERIC (6, 2)  NULL,
    [Observaciones]                     NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImporteIvaIncluido]                NUMERIC (19, 2) NULL,
    [CotizacionDolar]                   NUMERIC (18, 3) NULL,
    [CtaCte]                            VARCHAR (2)     NULL,
    [IdMoneda]                          INT             NULL,
    [CotizacionMoneda]                  NUMERIC (18, 4) NULL,
    [IVANoDiscriminado]                 NUMERIC (18, 2) NULL,
    [ConvenioMultilateral]              VARCHAR (2)     NULL,
    [OtrasPercepciones1]                NUMERIC (18, 2) NULL,
    [OtrasPercepciones1Desc]            VARCHAR (15)    NULL,
    [OtrasPercepciones2]                NUMERIC (18, 2) NULL,
    [OtrasPercepciones2Desc]            VARCHAR (15)    NULL,
    [IdProvinciaDestino]                INT             NULL,
    [IdIBCondicion]                     INT             NULL,
    [IdPuntoVenta]                      INT             NULL,
    [Anulada]                           VARCHAR (2)     NULL,
    [IdUsuarioAnulacion]                INT             NULL,
    [FechaAnulacion]                    DATETIME        NULL,
    [NumeroCAI]                         NUMERIC (19)    NULL,
    [FechaVencimientoCAI]               DATETIME        NULL,
    [IdObra]                            INT             NULL,
    [NumeroCertificadoPercepcionIIBB]   INT             NULL,
    [IdVentaEnCuotas]                   INT             NULL,
    [NumeroCuota]                       INT             NULL,
    [IdUsuarioIngreso]                  INT             NULL,
    [FechaIngreso]                      DATETIME        NULL,
    [AplicarEnCtaCte]                   VARCHAR (2)     NULL,
    [IdIBCondicion2]                    INT             NULL,
    [OtrasPercepciones3]                NUMERIC (18, 2) NULL,
    [OtrasPercepciones3Desc]            VARCHAR (15)    NULL,
    [NoIncluirEnCubos]                  VARCHAR (2)     NULL,
    [PercepcionIVA]                     NUMERIC (18, 2) NULL,
    [PorcentajePercepcionIVA]           NUMERIC (6, 2)  NULL,
    [IdNotaCreditoVenta_RecuperoGastos] INT             NULL,
    [IdListaPrecios]                    INT             NULL,
    [IdIBCondicion3]                    INT             NULL,
    [RetencionIBrutos3]                 NUMERIC (19, 2) NULL,
    [PorcentajeIBrutos3]                NUMERIC (6, 2)  NULL,
    [CAE]                               VARCHAR (14)    NULL,
    [RechazoCAE]                        VARCHAR (11)    NULL,
    [FechaVencimientoORechazoCAE]       DATETIME        NULL,
    [IdIdentificacionCAE]               INT             NULL,
    CONSTRAINT [PK_NotasDebito] PRIMARY KEY NONCLUSTERED ([IdNotaDebito] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_NotasDebito_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[NotasDebito]([FechaNotaDebito] ASC, [IdNotaDebito] ASC) WITH (FILLFACTOR = 90);

