CREATE TABLE [dbo].[Obras] (
    [IdObra]                          INT             IDENTITY (1, 1) NOT NULL,
    [NumeroObra]                      VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCliente]                       INT             NULL,
    [FechaInicio]                     DATETIME        NULL,
    [FechaFinalizacion]               DATETIME        NULL,
    [Observaciones]                   NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaEntrega]                    DATETIME        NULL,
    [Descripcion]                     VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdJefe]                          INT             NULL,
    [TipoObra]                        INT             NULL,
    [HorasEstimadas]                  INT             NULL,
    [Consorcial]                      VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EnviarEmail]                     TINYINT         NULL,
    [Activa]                          VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ParaInformes]                    VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdUnidadOperativa]               INT             NULL,
    [Jerarquia]                       VARCHAR (20)    NULL,
    [ArchivoAdjunto1]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto2]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto3]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto4]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto5]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto6]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto7]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto8]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto9]                 VARCHAR (100)   NULL,
    [ArchivoAdjunto10]                VARCHAR (100)   NULL,
    [GeneraReservaStock]              VARCHAR (2)     NULL,
    [IdGrupoObra]                     INT             NULL,
    [IdArticuloAsociado]              INT             NULL,
    [Observaciones2]                  NTEXT           NULL,
    [Observaciones3]                  NTEXT           NULL,
    [IdSubjefe]                       INT             NULL,
    [Direccion]                       VARCHAR (50)    NULL,
    [IdLocalidad]                     INT             NULL,
    [IdProvincia]                     INT             NULL,
    [IdPais]                          INT             NULL,
    [CodigoPostal]                    VARCHAR (30)    NULL,
    [Telefono]                        VARCHAR (50)    NULL,
    [LugarPago]                       VARCHAR (50)    NULL,
    [Responsable]                     VARCHAR (50)    NULL,
    [Horario]                         VARCHAR (20)    NULL,
    [Turnos]                          VARCHAR (10)    NULL,
    [Operarios]                       INT             NULL,
    [Zona]                            INT             NULL,
    [Jurisdiccion]                    INT             NULL,
    [IdCuentaContableFF]              INT             NULL,
    [ValorObra]                       NUMERIC (18, 2) NULL,
    [IdMonedaValorObra]               INT             NULL,
    [IdJefeRegional]                  INT             NULL,
    [EsPlantaDeProduccionInterna]     VARCHAR (2)     NULL,
    [ActivarPresupuestoObra]          VARCHAR (2)     NULL,
    [ProximoNumeroAutorizacionCompra] INT             NULL,
    [AuxiliarDeMateriales]            VARCHAR (2)     NULL,
    [DiasLiquidacionCertificados]     INT             NULL,
    [IdObraRelacionada]               INT             NULL,
    [OrdenamientoSecundario]          INT             NULL,
    CONSTRAINT [PK_Obras] PRIMARY KEY CLUSTERED ([IdObra] ASC) WITH (FILLFACTOR = 90)
);

