CREATE TABLE [dbo].[OrdenesPago] (
    [IdOrdenPago]                            INT             IDENTITY (1, 1) NOT NULL,
    [NumeroOrdenPago]                        INT             NULL,
    [FechaOrdenPago]                         DATETIME        NULL,
    [IdProveedor]                            INT             NULL,
    [Efectivo]                               NUMERIC (18, 2) NULL,
    [Descuentos]                             NUMERIC (18, 2) NULL,
    [Valores]                                NUMERIC (18, 2) NULL,
    [Documentos]                             NUMERIC (18, 2) NULL,
    [Otros1]                                 NUMERIC (18, 2) NULL,
    [IdCuenta1]                              INT             NULL,
    [Otros2]                                 NUMERIC (18, 2) NULL,
    [IdCuenta2]                              INT             NULL,
    [Otros3]                                 NUMERIC (18, 2) NULL,
    [IdCuenta3]                              INT             NULL,
    [Acreedores]                             NUMERIC (18, 2) NULL,
    [RetencionIVA]                           NUMERIC (18, 2) NULL,
    [RetencionGanancias]                     NUMERIC (18, 2) NULL,
    [RetencionIBrutos]                       NUMERIC (18, 2) NULL,
    [GastosGenerales]                        NUMERIC (18, 2) NULL,
    [Estado]                                 VARCHAR (2)     NULL,
    [IdCuenta]                               INT             NULL,
    [Tipo]                                   VARCHAR (2)     NULL,
    [Anulada]                                VARCHAR (2)     NULL,
    [CotizacionDolar]                        NUMERIC (18, 4) NULL,
    [Dolarizada]                             VARCHAR (2)     NULL,
    [Exterior]                               VARCHAR (2)     NULL,
    [NumeroCertificadoRetencionGanancias]    INT             NULL,
    [BaseGanancias]                          NUMERIC (18, 2) NULL,
    [IdMoneda]                               INT             NULL,
    [CotizacionMoneda]                       NUMERIC (18, 4) NULL,
    [AsientoManual]                          VARCHAR (2)     NULL,
    [Observaciones]                          NTEXT           NULL,
    [IdObra]                                 INT             NULL,
    [IdCuentaGasto]                          INT             NULL,
    [DiferenciaBalanceo]                     NUMERIC (18, 2) NULL,
    [IdOPComplementariaFF]                   INT             NULL,
    [IdEmpleadoFF]                           INT             NULL,
    [NumeroCertificadoRetencionIVA]          INT             NULL,
    [NumeroCertificadoRetencionIIBB]         INT             NULL,
    [RetencionSUSS]                          NUMERIC (18, 2) NULL,
    [NumeroCertificadoRetencionSUSS]         INT             NULL,
    [TipoOperacionOtros]                     INT             NULL,
    [IdUsuarioIngreso]                       INT             NULL,
    [FechaIngreso]                           DATETIME        NULL,
    [IdUsuarioModifico]                      INT             NULL,
    [FechaModifico]                          DATETIME        NULL,
    [Confirmado]                             VARCHAR (2)     NULL,
    [IdObraOrigen]                           INT             NULL,
    [CotizacionEuro]                         NUMERIC (18, 4) NULL,
    [TipoGrabacion]                          VARCHAR (1)     NULL,
    [IdProvinciaDestino]                     INT             NULL,
    [CalculaSUSS]                            VARCHAR (2)     NULL,
    [RetencionIVAComprobantesM]              NUMERIC (18, 2) NULL,
    [IdUsuarioAnulo]                         INT             NULL,
    [FechaAnulacion]                         DATETIME        NULL,
    [MotivoAnulacion]                        NTEXT           NULL,
    [NumeroRendicionFF]                      INT             NULL,
    [ConfirmacionAcreditacionFF]             VARCHAR (2)     NULL,
    [OPInicialFF]                            VARCHAR (2)     NULL,
    [IdConcepto]                             INT             NULL,
    [IdConcepto2]                            INT             NULL,
    [FormaAnulacionCheques]                  VARCHAR (1)     NULL,
    [Detalle]                                VARCHAR (20)    NULL,
    [RecalculoRetencionesUltimaModificacion] VARCHAR (2)     NULL,
    [IdImpuestoDirecto]                      INT             NULL,
    [NumeroReciboProveedor]                  INT             NULL,
    [FechaReciboProveedor]                   DATETIME        NULL,
    [TextoAuxiliar1]                         VARCHAR (100)   NULL,
    [TextoAuxiliar2]                         VARCHAR (100)   NULL,
    [TextoAuxiliar3]                         VARCHAR (100)   NULL,
    [IdsComprobanteProveedorRetenidosIva]    VARCHAR (100)   NULL,
    [TotalesImportesRetenidosIva]            VARCHAR (100)   NULL,
    [ReversionContablePorAnulacion]          VARCHAR (2)     NULL,
    CONSTRAINT [PK_OrdenesPago] PRIMARY KEY NONCLUSTERED ([IdOrdenPago] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_OrdenesPago_Cuentas] FOREIGN KEY ([IdCuenta]) REFERENCES [dbo].[Cuentas] ([IdCuenta]),
    CONSTRAINT [FK_OrdenesPago_Proveedor] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor]),
    CONSTRAINT [FK_OrdenesPago_Proveedores] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[Proveedores] ([IdProveedor])
);

