CREATE TABLE [dbo].[OrdenesCompra] (
    [IdOrdenCompra]                INT             IDENTITY (1, 1) NOT NULL,
    [NumeroOrdenCompra]            INT             NULL,
    [IdCliente]                    INT             NULL,
    [FechaOrdenCompra]             DATETIME        NULL,
    [IdCondicionVenta]             INT             NULL,
    [Anulada]                      VARCHAR (2)     NULL,
    [FechaAnulacion]               DATETIME        NULL,
    [Observaciones]                NTEXT           NULL,
    [ImporteTotal]                 NUMERIC (18, 2) NULL,
    [ArchivoAdjunto1]              VARCHAR (100)   NULL,
    [ArchivoAdjunto2]              VARCHAR (100)   NULL,
    [ArchivoAdjunto3]              VARCHAR (100)   NULL,
    [ArchivoAdjunto4]              VARCHAR (100)   NULL,
    [ArchivoAdjunto5]              VARCHAR (100)   NULL,
    [ArchivoAdjunto6]              VARCHAR (100)   NULL,
    [ArchivoAdjunto7]              VARCHAR (100)   NULL,
    [ArchivoAdjunto8]              VARCHAR (100)   NULL,
    [ArchivoAdjunto9]              VARCHAR (100)   NULL,
    [ArchivoAdjunto10]             VARCHAR (100)   NULL,
    [NumeroOrdenCompraCliente]     VARCHAR (20)    NULL,
    [IdObra]                       INT             NULL,
    [IdMoneda]                     INT             NULL,
    [IdUsuarioAnulacion]           INT             NULL,
    [AgrupacionFacturacion]        INT             NULL,
    [Agrupacion2Facturacion]       INT             NULL,
    [SeleccionadaParaFacturacion]  VARCHAR (2)     NULL,
    [PorcentajeBonificacion]       NUMERIC (6, 2)  NULL,
    [IdListaPrecios]               INT             NULL,
    [IdUsuarioIngreso]             INT             NULL,
    [FechaIngreso]                 DATETIME        NULL,
    [IdUsuarioModifico]            INT             NULL,
    [FechaModifico]                DATETIME        NULL,
    [Aprobo]                       INT             NULL,
    [FechaAprobacion]              DATETIME        NULL,
    [CircuitoFirmasCompleto]       VARCHAR (2)     NULL,
    [IdDetalleClienteLugarEntrega] INT             NULL,
    [Estado]                       VARCHAR (2)     NULL,
    [IdUsuarioCambioEstado]        INT             NULL,
    [FechaCambioEstado]            DATETIME        NULL,
    CONSTRAINT [PK_OrdenesCompra] PRIMARY KEY CLUSTERED ([IdOrdenCompra] ASC) WITH (FILLFACTOR = 90)
);

