CREATE TABLE [dbo].[Parametros] (
    [IdParametro]                                INT             IDENTITY (1, 1) NOT NULL,
    [ProximoPresupuesto]                         INT             NULL,
    [Iva1]                                       NUMERIC (6, 2)  NULL,
    [Iva2]                                       NUMERIC (6, 2)  NULL,
    [ProximaListaAcopio]                         INT             NULL,
    [ProximaListaMateriales]                     INT             NULL,
    [ProximoNumeroRequerimiento]                 INT             NULL,
    [IdUnidadPorUnidad]                          INT             NULL,
    [ProximoNumeroAjusteStock]                   INT             NULL,
    [ProximoNumeroReservaStock]                  INT             NULL,
    [ProximoNumeroPedido]                        INT             NULL,
    [ControlCalidadDefault]                      INT             NULL,
    [ProximoNumeroValeSalida]                    INT             NULL,
    [ProximoNumeroSalidaMateriales]              INT             NULL,
    [ProximaComparativa]                         INT             NULL,
    [PathAdjuntos]                               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdUnidadPorKilo]                            INT             NULL,
    [PedidosGarantia]                            NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PedidosDocumentacion]                       NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PedidosPlazoEntrega]                        NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PedidosLugarEntrega]                        NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PedidosFormaPago]                           NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ProximoNumeroSalidaMaterialesAObra]         INT             NULL,
    [ProximoNumeroSalidaMaterialesParaFacturar]  INT             NULL,
    [ProximoNumeroSalidaMateriales2]             INT             NULL,
    [ProximoNumeroSalidaMaterialesAObra2]        INT             NULL,
    [ProximoNumeroSalidaMaterialesParaFacturar2] INT             NULL,
    [PedidosInspecciones]                        NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PedidosImportante]                          NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PathEnvioEmails]                            VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PathRecepcionEmails]                        VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ProximoNumeroSalidaMaterialesAProveedor]    INT             NULL,
    [ProximoNumeroSalidaMaterialesAProveedor2]   INT             NULL,
    [ProximoNumeroDevolucionDeFabrica]           INT             NULL,
    [ProximoNumeroDevolucionDeFabrica2]          INT             NULL,
    [ArchivoAyuda]                               VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PathArchivoExcelDatanet]                    VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PathArchivoExcelProveedores]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Porc_IBrutos_Cap]                           NUMERIC (18, 2) NULL,
    [Tope_IBrutos_Cap]                           NUMERIC (18, 2) NULL,
    [Porc_IBrutos_BsAs]                          NUMERIC (18, 2) NULL,
    [Tope_IBrutos_BsAs]                          NUMERIC (18, 2) NULL,
    [Porc_IBrutos_BsAsM]                         NUMERIC (18, 2) NULL,
    [Tope_IBrutos_BsAsM]                         NUMERIC (18, 2) NULL,
    [Decimales]                                  SMALLINT        NULL,
    [AclaracionAlPieDeFactura]                   VARCHAR (250)   NULL,
    [CotizacionDolar]                            NUMERIC (18, 2) NULL,
    [ProximoAsiento]                             INT             NULL,
    [ProximoNumeroInterno]                       INT             NULL,
    [NumeracionUnica]                            VARCHAR (2)     NULL,
    [EjercicioActual]                            INT             NULL,
    [IdCuentaVentas]                             INT             NULL,
    [IdCuentaBonificaciones]                     INT             NULL,
    [IdCuentaIvaInscripto]                       INT             NULL,
    [IdCuentaIvaNoInscripto]                     INT             NULL,
    [IdCuentaIvaSinDiscriminar]                  INT             NULL,
    [IdCuentaRetencionIBrutosBsAs]               INT             NULL,
    [IdCuentaRetencionIBrutosCap]                INT             NULL,
    [IdCuentaReventas]                           INT             NULL,
    [IdCuentaND]                                 INT             NULL,
    [IdCuentaNC]                                 INT             NULL,
    [IdCuentaCaja]                               INT             NULL,
    [IdCuentaValores]                            INT             NULL,
    [IdCuentaRetencionIva]                       INT             NULL,
    [IdCuentaRetencionGanancias]                 INT             NULL,
    [IdCuentaRetencionIBrutos]                   INT             NULL,
    [IdCuentaDescuentos]                         INT             NULL,
    [IdCuentaDescuentosyRetenciones]             INT             NULL,
    [IdUnidad]                                   INT             NULL,
    [IdMoneda]                                   INT             NULL,
    [IdCuentaCompras]                            INT             NULL,
    [ProximoComprobanteProveedorReferencia]      INT             NULL,
    [ProximoNumeroInternoChequeEmitido]          INT             NULL,
    [ProximaNumeroOrdenPago]                     INT             NULL,
    [IdCuentaIvaCompras]                         INT             NULL,
    [CAI]                                        VARCHAR (50)    NULL,
    [FechaCAI]                                   VARCHAR (20)    NULL,
    [ClausulaDolar]                              VARCHAR (1000)  NULL,
    [IdMonedaDolar]                              INT             NULL,
    [NumeroCAI_R_A]                              VARCHAR (50)    NULL,
    [FechaCAI_R_A]                               DATETIME        NULL,
    [NumeroCAI_F_A]                              VARCHAR (50)    NULL,
    [FechaCAI_F_A]                               DATETIME        NULL,
    [NumeroCAI_D_A]                              VARCHAR (50)    NULL,
    [FechaCAI_D_A]                               DATETIME        NULL,
    [NumeroCAI_C_A]                              VARCHAR (50)    NULL,
    [FechaCAI_C_A]                               DATETIME        NULL,
    [NumeroCAI_R_B]                              VARCHAR (50)    NULL,
    [FechaCAI_R_B]                               DATETIME        NULL,
    [NumeroCAI_F_B]                              VARCHAR (50)    NULL,
    [FechaCAI_F_B]                               DATETIME        NULL,
    [NumeroCAI_D_B]                              VARCHAR (50)    NULL,
    [FechaCAI_D_B]                               DATETIME        NULL,
    [NumeroCAI_C_B]                              VARCHAR (50)    NULL,
    [FechaCAI_C_B]                               DATETIME        NULL,
    [NumeroCAI_R_E]                              VARCHAR (50)    NULL,
    [FechaCAI_R_E]                               DATETIME        NULL,
    [NumeroCAI_F_E]                              VARCHAR (50)    NULL,
    [FechaCAI_F_E]                               DATETIME        NULL,
    [NumeroCAI_D_E]                              VARCHAR (50)    NULL,
    [FechaCAI_D_E]                               DATETIME        NULL,
    [NumeroCAI_C_E]                              VARCHAR (50)    NULL,
    [FechaCAI_C_E]                               DATETIME        NULL,
    [NumeracionCorrelativa]                      VARCHAR (2)     NULL,
    [ProximoNumeroRefProveedores]                INT             NULL,
    [ProximoNumeroCuentaContable]                INT             NULL,
    [IdCuentaAcreedoresVarios]                   INT             NULL,
    [IdCuentaDeudoresVarios]                     INT             NULL,
    [ProximaOrdenPago]                           INT             NULL,
    [IdCuentaIvaCompras1]                        INT             NULL,
    [IVAComprasPorcentaje1]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras2]                        INT             NULL,
    [IVAComprasPorcentaje2]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras3]                        INT             NULL,
    [IVAComprasPorcentaje3]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras4]                        INT             NULL,
    [IVAComprasPorcentaje4]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras5]                        INT             NULL,
    [IVAComprasPorcentaje5]                      NUMERIC (6, 2)  NULL,
    [ProximaOrdenPagoExterior]                   INT             NULL,
    [MinimoNoImponible]                          NUMERIC (18, 2) NULL,
    [DeduccionEspecial]                          NUMERIC (18, 2) NULL,
    [ProximoNumeroCertificadoRetencionGanancias] INT             NULL,
    [IdCuentaVentasTitulo]                       INT             NULL,
    [IdCuentaNDTitulo]                           INT             NULL,
    [IdCuentaNCTitulo]                           INT             NULL,
    [IdCuentaCajaTitulo]                         INT             NULL,
    [IdCuentaValoresTitulo]                      INT             NULL,
    [IdCuentaDescuentosyRetencionesTitulo]       INT             NULL,
    [IdCuentaComprasTitulo]                      INT             NULL,
    [IdCuentaIvaCompras6]                        INT             NULL,
    [IVAComprasPorcentaje6]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras7]                        INT             NULL,
    [IVAComprasPorcentaje7]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras8]                        INT             NULL,
    [IVAComprasPorcentaje8]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras9]                        INT             NULL,
    [IVAComprasPorcentaje9]                      NUMERIC (6, 2)  NULL,
    [IdCuentaIvaCompras10]                       INT             NULL,
    [IVAComprasPorcentaje10]                     NUMERIC (6, 2)  NULL,
    [ProximoNumeroOrdenCompra]                   INT             NULL,
    [ProximoNumeroRemito]                        INT             NULL,
    [IdCuentaRetencionGananciasCobros]           INT             NULL,
    [IdTipoCuentaGrupoIVA]                       INT             NULL,
    [IGCondicionExcepcion]                       INT             NULL,
    [IdCuentaIvaVentas1]                         INT             NULL,
    [IVAVentasPorcentaje1]                       NUMERIC (6, 2)  NULL,
    [IdCuentaIvaVentas2]                         INT             NULL,
    [IVAVentasPorcentaje2]                       NUMERIC (6, 2)  NULL,
    [IdCuentaIvaVentas3]                         INT             NULL,
    [IVAVentasPorcentaje3]                       NUMERIC (6, 2)  NULL,
    [IdCuentaIvaVentas4]                         INT             NULL,
    [IVAVentasPorcentaje4]                       NUMERIC (6, 2)  NULL,
    [ProximaOrdenPagoOtros]                      INT             NULL,
    [IdTipoComprobanteEfectivo]                  INT             NULL,
    [IdTipoComprobanteDeposito]                  INT             NULL,
    [ProximaNotaDebitoInterna]                   INT             NULL,
    [ProximaNotaCreditoInterna]                  INT             NULL,
    [IdTipoComprobanteCajaIngresos]              INT             NULL,
    [IdTipoComprobanteCajaEgresos]               INT             NULL,
    [DirectorioDTS]                              VARCHAR (100)   NULL,
    [PathObra]                                   VARCHAR (50)    NULL,
    [FechaUltimoCierre]                          DATETIME        NULL,
    [IdConceptoDiferenciaCambio]                 INT             NULL,
    [IdTipoCuentaGrupoFF]                        INT             NULL,
    [ProximoNumeroOtroIngresoAlmacen]            INT             NULL,
    [AgenteRetencionIVA]                         VARCHAR (2)     NULL,
    [ImporteTotalMinimoAplicacionRetencionIVA]   NUMERIC (18, 2) NULL,
    [PorcentajeBaseRetencionIVABienes]           NUMERIC (6, 2)  NULL,
    [PorcentajeBaseRetencionIVAServicios]        NUMERIC (6, 2)  NULL,
    [ImporteMinimoRetencionIVA]                  NUMERIC (18, 2) NULL,
    [ProximoNumeroCertificadoRetencionIVA]       INT             NULL,
    [ProximoNumeroCertificadoRetencionIIBB]      INT             NULL,
    [IdTipoComprobanteFacturaCompra]             INT             NULL,
    [IdTipoComprobanteFacturaVenta]              INT             NULL,
    [IdTipoComprobanteDevoluciones]              INT             NULL,
    [IdTipoComprobanteNotaDebito]                INT             NULL,
    [IdTipoComprobanteNotaCredito]               INT             NULL,
    [IdTipoComprobanteRecibo]                    INT             NULL,
    [IdControlCalidadStandar]                    INT             NULL,
    [IdTipoCuentaGrupoAnticiposAlPersonal]       INT             NULL,
    [IdTipoComprobanteNDInternaAcreedores]       INT             NULL,
    [IdTipoComprobanteNCInternaAcreedores]       INT             NULL,
    [PercepcionIIBB]                             VARCHAR (2)     NULL,
    [OtrasPercepciones1]                         VARCHAR (2)     NULL,
    [OtrasPercepciones1Desc]                     VARCHAR (15)    NULL,
    [OtrasPercepciones2]                         VARCHAR (2)     NULL,
    [OtrasPercepciones2Desc]                     VARCHAR (15)    NULL,
    [IdCuentaDiferenciaCambio]                   INT             NULL,
    [ProximoNumeroReciboPago]                    INT             NULL,
    [NumeroReciboPagoAutomatico]                 VARCHAR (2)     NULL,
    [IdCuentaPercepcionIIBB]                     INT             NULL,
    [IdCuentaOtrasPercepciones1]                 INT             NULL,
    [IdCuentaOtrasPercepciones2]                 INT             NULL,
    [ConfirmarClausulaDolar]                     VARCHAR (2)     NULL,
    [ProximoNumeroPedidoExterior]                INT             NULL,
    [ExigirTrasabilidad_RMLA_PE]                 VARCHAR (2)     NULL,
    [AgenteRetencionSUSS]                        VARCHAR (2)     NULL,
    [PorcentajeRetencionSUSS]                    NUMERIC (6, 2)  NULL,
    [ProximoNumeroCertificadoRetencionSUSS]      INT             NULL,
    [IdCuentaRetencionSUSS]                      INT             NULL,
    [IdCuentaPercepcionIVACompras]               INT             NULL,
    [IdPuntoVentaNumeracionUnica]                INT             NULL,
    [AgenteRetencionIIBB]                        VARCHAR (2)     NULL,
    [PathArchivosExportados]                     VARCHAR (100)   NULL,
    [IdObraStockDisponible]                      INT             NULL,
    [IdTipoComprobanteOrdenPago]                 INT             NULL,
    [ProximoNumeroInternoRecepcion]              INT             NULL,
    [IdCuentaRetencionSUSS_Recibida]             INT             NULL,
    [Plantilla_Factura_A]                        VARCHAR (50)    NULL,
    [Plantilla_Factura_B]                        VARCHAR (50)    NULL,
    [Plantilla_Factura_E]                        VARCHAR (50)    NULL,
    [Plantilla_Devoluciones_A]                   VARCHAR (50)    NULL,
    [Plantilla_Devoluciones_B]                   VARCHAR (50)    NULL,
    [Plantilla_Devoluciones_E]                   VARCHAR (50)    NULL,
    [Plantilla_NotasDebito_A]                    VARCHAR (50)    NULL,
    [Plantilla_NotasDebito_B]                    VARCHAR (50)    NULL,
    [Plantilla_NotasDebito_E]                    VARCHAR (50)    NULL,
    [Plantilla_NotasCredito_A]                   VARCHAR (50)    NULL,
    [Plantilla_NotasCredito_B]                   VARCHAR (50)    NULL,
    [Plantilla_NotasCredito_E]                   VARCHAR (50)    NULL,
    [FechaArranqueCajaYBancos]                   DATETIME        NULL,
    [IdRubroVentasEnCuotas]                      INT             NULL,
    [IdConceptoVentasEnCuotas]                   INT             NULL,
    [IdCuentaPlazosFijos]                        INT             NULL,
    [IdCuentaInteresesPlazosFijos]               INT             NULL,
    [NumeroGeneracionVentaEnCuotas]              INT             NULL,
    [IdBancoGestionCobroCuotas]                  INT             NULL,
    [PathArchivoCobranzaCuotas]                  VARCHAR (100)   NULL,
    [TipoAmortizacionContable]                   VARCHAR (1)     NULL,
    [FrecuenciaAmortizacionContable]             VARCHAR (1)     NULL,
    [TipoAmortizacionImpositiva]                 VARCHAR (1)     NULL,
    [FrecuenciaAmortizacionImpositiva]           VARCHAR (1)     NULL,
    [IdCuentaResultadosEjercicio]                INT             NULL,
    [IdCuentaResultadosAcumulados]               INT             NULL,
    [CuentasResultadoDesde]                      INT             NULL,
    [CuentasResultadoHasta]                      INT             NULL,
    [CuentasPatrimonialesDesde]                  INT             NULL,
    [CuentasPatrimonialesHasta]                  INT             NULL,
    [IdArticuloVariosParaPRESTO]                 INT             NULL,
    [ControlarRubrosContablesEnOP]               VARCHAR (2)     NULL,
    [IdObraActiva]                               INT             NULL,
    [IdCuentaAdicionalIVACompras1]               INT             NULL,
    [IdCuentaAdicionalIVACompras2]               INT             NULL,
    [IdCuentaAdicionalIVACompras3]               INT             NULL,
    [IdCuentaAdicionalIVACompras4]               INT             NULL,
    [IdCuentaAdicionalIVACompras5]               INT             NULL,
    [FechaUltimoCierreEjercicio]                 DATETIME        NULL,
    [EmiteAsientoEnOP]                           VARCHAR (2)     NULL,
    [IdMonedaEuro]                               INT             NULL,
    [LineasDiarioDetallado]                      INT             NULL,
    [LineasDiarioResumido]                       INT             NULL,
    [PathEnvioEmailsMANTENIMIENTO]               VARCHAR (100)   NULL,
    [PathRecepcionEmailsMANTENIMIENTO]           VARCHAR (100)   NULL,
    [ImporteComprobantesMParaRetencionIVA]       NUMERIC (18, 2) NULL,
    [PorcentajeRetencionIVAComprobantesM]        NUMERIC (6, 2)  NULL,
    [ImporteComprobantesMParaRetencionGanancias] NUMERIC (18, 2) NULL,
    [PorcentajeRetencionGananciasComprobantesM]  NUMERIC (6, 2)  NULL,
    [IdTipoComprobanteFacturaCompraExportacion]  INT             NULL,
    [IvaCompras_DesglosarNOGRAVADOS]             VARCHAR (2)     NULL,
    [IdCuentaImpuestosInternos]                  INT             NULL,
    [Subdiarios_ResumirRegistros]                VARCHAR (2)     NULL,
    [IdCajaEnPesosDefault]                       INT             NULL,
    [ProximoNumeroGastoBancario]                 INT             NULL,
    [ProximoNumeroSolicitudCompra]               INT             NULL,
    [IdCuentaReintegros]                         INT             NULL,
    [IdArticuloPRONTO_MANTENIMIENTO]             INT             NULL,
    [ProximoCodigoArticulo]                      INT             NULL,
    [FechaTimeStamp]                             ROWVERSION      NULL,
    [PathPlantillas]                             VARCHAR (100)   NULL,
    [OtrasPercepciones3]                         VARCHAR (2)     NULL,
    [OtrasPercepciones3Desc]                     VARCHAR (15)    NULL,
    [IdCuentaOtrasPercepciones3]                 INT             NULL,
    [FechaArranqueMovimientosStock]              DATETIME        NULL,
    [IdCuentaRetencionIvaComprobantesM]          INT             NULL,
    [IdJefeCompras]                              INT             NULL,
    [ImporteMinimoRetencionIVAServicios]         NUMERIC (18, 2) NULL,
    [IdCuentaPercepcionesIVA]                    INT             NULL,
    [IdCuentaREI_Ganancia]                       INT             NULL,
    [IdCuentaREI_Perdida]                        INT             NULL,
    [ActivarCircuitoChequesDiferidos]            VARCHAR (2)     NULL,
    [BasePRONTOSyJAsociada]                      VARCHAR (50)    NULL,
    [IdConceptoAnticiposSyJ]                     INT             NULL,
    [IdConceptoRecuperoGastos]                   INT             NULL,
    [BasePRONTOConsolidacion]                    VARCHAR (50)    NULL,
    [PorcentajeConsolidacion]                    NUMERIC (6, 2)  NULL,
    [BasePRONTOConsolidacion2]                   VARCHAR (50)    NULL,
    [PorcentajeConsolidacion2]                   NUMERIC (6, 2)  NULL,
    [BasePRONTOConsolidacion3]                   VARCHAR (50)    NULL,
    [PorcentajeConsolidacion3]                   NUMERIC (6, 2)  NULL,
    [IdCuentaAjusteConsolidacion]                INT             NULL,
    [PathImportacionDatos]                       VARCHAR (50)    NULL,
    [ActivarSolicitudMateriales]                 VARCHAR (2)     NULL,
    [TopeMinimoRetencionIVA]                     NUMERIC (18, 2) NULL,
    [TopeMinimoRetencionIVAServicios]            NUMERIC (18, 2) NULL,
    [IdMonedaPrincipal]                          INT             NULL,
    [IdTipoComprobanteTarjetaCredito]            INT             NULL,
    [ProximoNumeroOrdenTrabajo]                  INT             NULL,
    [BasePRONTOMantenimiento]                    VARCHAR (50)    NULL,
    [ProximaOrdenPagoFF]                         INT             NULL,
    CONSTRAINT [PK_Parametros] PRIMARY KEY CLUSTERED ([IdParametro] ASC) WITH (FILLFACTOR = 90)
);

