CREATE TABLE [dbo].[Pesadas] (
    [IdPesada]                       INT             IDENTITY (1, 1) NOT NULL,
    [NumeroPesada]                   INT             NULL,
    [IdUsuarioIngreso]               INT             NULL,
    [FechaIngreso]                   DATETIME        NULL,
    [Anulada]                        VARCHAR (2)     NULL,
    [IdUsuarioAnulo]                 INT             NULL,
    [FechaAnulacion]                 DATETIME        NULL,
    [Observaciones]                  VARCHAR (200)   NULL,
    [IdArticulo]                     INT             NULL,
    [IdStock]                        INT             NULL,
    [Partida]                        VARCHAR (20)    NULL,
    [IdUnidad]                       INT             NULL,
    [IdUbicacion]                    INT             NULL,
    [Cantidad]                       NUMERIC (12, 2) NULL,
    [PesoBruto]                      NUMERIC (18, 2) NULL,
    [PesoNeto]                       NUMERIC (18, 2) NULL,
    [Tara]                           NUMERIC (18, 2) NULL,
    [Chofer]                         INT             NULL,
    [TxtChofer]                      VARCHAR (30)    NULL,
    [IdCamion]                       INT             NULL,
    [TxtCamion]                      VARCHAR (30)    NULL,
    [IdTransportista]                INT             NULL,
    [IdProveedor]                    INT             NULL,
    [IdCliente]                      INT             NULL,
    [IdObra]                         INT             NULL,
    [RemitoMaterial]                 INT             NULL,
    [RemitoTransportista]            INT             NULL,
    [CantidadEnOrigen]               NUMERIC (12, 2) NULL,
    [PesoBrutoIngresadoManualmente]  VARCHAR (2)     NULL,
    [TaraIngresadaManualmente]       VARCHAR (2)     NULL,
    [Tipo]                           VARCHAR (15)    NULL,
    [IdSalidaMateriales]             INT             NULL,
    [IdOtroIngresoAlmacen]           INT             NULL,
    [IdRecepcion]                    INT             NULL,
    [IdRemito]                       INT             NULL,
    [NetoEquivalente]                NUMERIC (12, 2) NULL,
    [IdChofer]                       INT             NULL,
    [IdFlete]                        INT             NULL,
    [RemitoTransportista2]           INT             NULL,
    [DistanciaRecorrida]             NUMERIC (18, 2) NULL,
    [CodigoTarifador]                VARCHAR (10)    NULL,
    [RemitoMaterial2]                INT             NULL,
    [NumeroOrdenCarga]               INT             NULL,
    [Patente]                        VARCHAR (10)    NULL,
    [IdDetallePedido]                INT             NULL,
    [IdTarifaFlete]                  INT             NULL,
    [TarifaFlete]                    NUMERIC (18, 2) NULL,
    [PesadaTara1]                    NUMERIC (18, 2) NULL,
    [PesadaTara2]                    NUMERIC (18, 2) NULL,
    [PesadaPesoBruto1]               NUMERIC (18, 2) NULL,
    [PesadaPesoBruto2]               NUMERIC (18, 2) NULL,
    [TipoMovimiento]                 VARCHAR (1)     NULL,
    [IdOrdenCarga]                   INT             NULL,
    [CoeficienteAKilos]              NUMERIC (18, 6) NULL,
    [FechaUltimaPesada]              DATETIME        NULL,
    [IdDetalleRequerimiento]         INT             NULL,
    [CoeficienteControlPesada]       NUMERIC (18, 2) NULL,
    [CantidadSegunRemitoMasCoefEnKg] NUMERIC (18, 2) NULL,
    [TomarPesadaORemito]             VARCHAR (1)     NULL,
    [Progresiva1]                    NUMERIC (18, 2) NULL,
    [Progresiva2]                    NUMERIC (18, 2) NULL,
    [IdPesadaOriginal]               INT             NOT NULL,
    [IdOrigenTransmision]            INT             NULL,
    [FechaImportacionTransmision]    DATETIME        NULL,
    CONSTRAINT [PK_Pesadas] PRIMARY KEY CLUSTERED ([IdPesada] ASC) WITH (FILLFACTOR = 90)
);

