CREATE TABLE [dbo].[PlazosFijos] (
    [IdPlazoFijo]                   INT             IDENTITY (1, 1) NOT NULL,
    [IdBanco]                       INT             NULL,
    [NumeroCertificado1]            INT             NULL,
    [NumeroCertificado2]            VARCHAR (20)    NULL,
    [DireccionEmisionYPago]         VARCHAR (50)    NULL,
    [Titulares]                     VARCHAR (50)    NULL,
    [CodigoDeposito]                INT             NULL,
    [CodigoClase]                   INT             NULL,
    [PlazoEnDias]                   INT             NULL,
    [TasaNominalAnual]              NUMERIC (18, 3) NULL,
    [Importe]                       NUMERIC (18, 2) NULL,
    [TasaEfectivaMensual]           NUMERIC (18, 3) NULL,
    [FechaVencimiento]              DATETIME        NULL,
    [ImporteIntereses]              NUMERIC (18, 2) NULL,
    [Orden]                         VARCHAR (50)    NULL,
    [Detalle]                       VARCHAR (50)    NULL,
    [IdPlazoFijoOrigen]             INT             NULL,
    [FechaInicioPlazoFijo]          DATETIME        NULL,
    [IdMoneda]                      INT             NULL,
    [CotizacionMonedaAlInicio]      NUMERIC (18, 4) NULL,
    [CotizacionMonedaAlFinal]       NUMERIC (18, 4) NULL,
    [Finalizado]                    VARCHAR (2)     NULL,
    [IdCajaOrigen]                  INT             NULL,
    [IdCuentaBancariaOrigen]        INT             NULL,
    [IdCajaDestino]                 INT             NULL,
    [IdCuentaBancariaDestino]       INT             NULL,
    [RetencionGanancia]             NUMERIC (18, 2) NULL,
    [Anulado]                       VARCHAR (2)     NULL,
    [AcreditarInteresesAlFinalizar] VARCHAR (2)     NULL,
    [NoExigirRubroContable]         VARCHAR (2)     NULL,
    CONSTRAINT [PK_PlazosFijos] PRIMARY KEY CLUSTERED ([IdPlazoFijo] ASC) WITH (FILLFACTOR = 90)
);

