CREATE TABLE [dbo].[ProduccionOrdenes] (
    [IdProduccionOrden]             INT             IDENTITY (1, 1) NOT NULL,
    [NumeroOrdenProduccion]         INT             NULL,
    [FechaOrdenProduccion]          DATETIME        NULL,
    [IdObra]                        INT             NULL,
    [Observaciones]                 NTEXT           NULL,
    [Aprobo]                        INT             NULL,
    [IdTransportista1]              INT             NULL,
    [Cliente]                       VARCHAR (50)    NULL,
    [Direccion]                     VARCHAR (50)    NULL,
    [Localidad]                     VARCHAR (50)    NULL,
    [CodigoPostal]                  VARCHAR (30)    NULL,
    [CondicionIva]                  VARCHAR (30)    NULL,
    [Cuit]                          VARCHAR (13)    NULL,
    [ACargo]                        VARCHAR (1)     NULL,
    [Emitio]                        INT             NULL,
    [ValePreimpreso]                INT             NULL,
    [Referencia]                    VARCHAR (50)    NULL,
    [NumeroDocumento]               VARCHAR (30)    NULL,
    [FechaRegistracion]             DATETIME        NULL,
    [Anulada]                       VARCHAR (2)     NULL,
    [FechaAnulacion]                DATETIME        NULL,
    [IdUsuarioAnulo]                INT             NULL,
    [EnviarEmail]                   TINYINT         NULL,
    [IdOrigenTransmision]           INT             NULL,
    [MotivoAnulacion]               NTEXT           NULL,
    [NumeroOrdenesProduccion]       INT             NULL,
    [IdDepositoOrigen]              INT             NULL,
    [IdUsuarioIngreso]              INT             NULL,
    [FechaIngreso]                  DATETIME        NULL,
    [IdUsuarioModifico]             INT             NULL,
    [FechaModifico]                 DATETIME        NULL,
    [ClaveTipoSalida]               VARCHAR (30)    NULL,
    [SalidaADepositoEnTransito]     VARCHAR (2)     NULL,
    [ValorDeclarado]                NUMERIC (18, 2) NULL,
    [Bultos]                        INT             NULL,
    [IdColor]                       INT             NULL,
    [Embalo]                        VARCHAR (50)    NULL,
    [CircuitoFirmasCompleto]        VARCHAR (2)     NULL,
    [IdPuntoVenta]                  INT             NULL,
    [NumeroRemitoTransporte]        INT             NULL,
    [IdEquipo]                      INT             NULL,
    [Codigo]                        VARCHAR (20)    NULL,
    [Descripcion]                   VARCHAR (50)    NULL,
    [Cantidad]                      NUMERIC (18, 2) NULL,
    [IdUnidad]                      INT             NULL,
    [Programada]                    VARCHAR (2)     NULL,
    [Confirmado]                    VARCHAR (2)     NULL,
    [Reserva]                       VARCHAR (2)     NULL,
    [EnEjecucion]                   VARCHAR (2)     NULL,
    [FechaInicioPrevista]           DATETIME        NULL,
    [FechaFinalPrevista]            DATETIME        NULL,
    [FechaInicioReal]               DATETIME        NULL,
    [FechaFinalReal]                DATETIME        NULL,
    [IdArticuloGenerado]            INT             NULL,
    [IdStockGenerado]               INT             NULL,
    [Cerro]                         INT             NULL,
    [ArchivoAdjunto1]               VARCHAR (100)   NULL,
    [ArchivoAdjunto2]               VARCHAR (100)   NULL,
    [IdDetalleOrdenCompraImputado1] INT             NULL,
    [IdDetalleOrdenCompraImputado2] INT             NULL,
    [IdDetalleOrdenCompraImputado3] INT             NULL,
    [IdDetalleOrdenCompraImputado4] INT             NULL,
    [IdDetalleOrdenCompraImputado5] INT             NULL,
    PRIMARY KEY CLUSTERED ([IdProduccionOrden] ASC) WITH (FILLFACTOR = 90)
);

