CREATE TABLE [dbo].[ProduccionPartes] (
    [IdProduccionParte]          INT             IDENTITY (1, 1) NOT NULL,
    [IdEmpleado]                 INT             NULL,
    [FechaDia]                   DATETIME        NULL,
    [FechaInicio]                DATETIME        NULL,
    [FechaFinal]                 DATETIME        NULL,
    [IdProduccionOrden]          INT             NULL,
    [IdProduccionProceso]        INT             NULL,
    [Horas]                      INT             NULL,
    [HorasReales]                INT             NULL,
    [idMaquina]                  INT             NULL,
    [IdArticulo]                 INT             NULL,
    [IdStock]                    INT             NULL,
    [Partida]                    VARCHAR (20)    NULL,
    [Cantidad]                   NUMERIC (12, 2) NULL,
    [IdUnidad]                   INT             NULL,
    [IdPROD_TiposControlCalidad] INT             NULL,
    [Control1]                   NUMERIC (18, 2) NULL,
    [Control2]                   NUMERIC (18, 2) NULL,
    [Control3]                   NUMERIC (18, 2) NULL,
    [Control4]                   NUMERIC (18, 2) NULL,
    [Control5]                   NUMERIC (18, 2) NULL,
    [ParoObservacion]            VARCHAR (20)    NULL,
    [ParoInicio]                 DATETIME        NULL,
    [ParoFinal]                  DATETIME        NULL,
    [IdArticuloGenerado]         INT             NULL,
    [CantidadGenerado]           NUMERIC (12, 2) NULL,
    [IdUnidadGenerado]           INT             NULL,
    [IdArticuloDeshecho]         INT             NULL,
    [CantidadDeshecho]           NUMERIC (12, 2) NULL,
    [IdSMConsumo]                INT             NULL,
    [IdOIProducto]               INT             NULL,
    [IdOISubProducto]            INT             NULL,
    [FechaRegistracion]          DATETIME        NULL,
    [Anulada]                    VARCHAR (2)     NULL,
    [FechaAnulacion]             DATETIME        NULL,
    [IdUsuarioAnulo]             INT             NULL,
    [IdUbicacion]                INT             NULL,
    [Aux_txtStockActual]         NUMERIC (18, 2) NULL,
    [Aux_txtPendiente]           NUMERIC (18, 2) NULL,
    [Aux_txtTolerancia]          NUMERIC (18, 2) NULL,
    [IdUsuarioCerro]             INT             NULL,
    PRIMARY KEY CLUSTERED ([IdProduccionParte] ASC) WITH (FILLFACTOR = 90),
    FOREIGN KEY ([IdEmpleado]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    FOREIGN KEY ([IdPROD_TiposControlCalidad]) REFERENCES [dbo].[PROD_TiposControlCalidad] ([IdPROD_TiposControlCalidad]),
    FOREIGN KEY ([IdProduccionOrden]) REFERENCES [dbo].[ProduccionOrdenes] ([IdProduccionOrden]),
    FOREIGN KEY ([IdProduccionProceso]) REFERENCES [dbo].[ProduccionProcesos] ([IdProduccionProceso]),
    FOREIGN KEY ([IdUnidad]) REFERENCES [dbo].[Unidades] ([IdUnidad]),
    FOREIGN KEY ([IdUnidadGenerado]) REFERENCES [dbo].[Unidades] ([IdUnidad])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Campo Agregado el dia 02/01/07', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProduccionPartes', @level2type = N'COLUMN', @level2name = N'IdUsuarioCerro';

