CREATE TABLE [dbo].[Proveedores] (
    [IdProveedor]                               INT             IDENTITY (1, 1) NOT NULL,
    [RazonSocial]                               VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Direccion]                                 VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdLocalidad]                               INT             NULL,
    [CodigoPostal]                              VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdProvincia]                               INT             NULL,
    [IdPais]                                    INT             NULL,
    [Telefono1]                                 VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Telefono2]                                 VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fax]                                       VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Email]                                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cuit]                                      VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCodigoIva]                               INT             NULL,
    [FechaAlta]                                 DATETIME        NULL,
    [FechaUltimaCompra]                         DATETIME        NULL,
    [Excencion]                                 DECIMAL (6, 2)  NULL,
    [IdCondicionCompra]                         INT             NULL,
    [Contacto]                                  VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdActividad]                               INT             NULL,
    [Nif]                                       VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdEstado]                                  INT             NULL,
    [EstadoFecha]                               DATETIME        NULL,
    [EstadoUsuario]                             VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AltaUsuario]                               VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CodigoEmpresa]                             VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Nombre1]                                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Nombre2]                                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NombreFantasia]                            VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IGCondicion]                               INT             NULL,
    [IGCertificadoAutoretencion]                VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IGCertificadoNORetencion]                  VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IGFechaCaducidadExencion]                  DATETIME        NULL,
    [IGPorcentajeNORetencion]                   DECIMAL (6, 2)  NULL,
    [IvaAgenteRetencion]                        VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IvaExencionRetencion]                      VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IvaFechaCaducidadExencion]                 DATETIME        NULL,
    [IvaPorcentajeExencion]                     DECIMAL (6, 2)  NULL,
    [IBNumeroInscripcion]                       VARCHAR (20)    NULL,
    [IBCondicion]                               INT             NULL,
    [IBFechaCaducidadExencion]                  DATETIME        NULL,
    [IBPorcentajeExencion]                      DECIMAL (6, 2)  NULL,
    [SSFechaCaducidadExencion]                  DATETIME        NULL,
    [SSPorcentajeExcencion]                     DECIMAL (6, 2)  NULL,
    [PaginaWeb]                                 VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Habitual]                                  VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]                             NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Saldo]                                     NUMERIC (18, 2) NULL,
    [SaldoDocumentos]                           NUMERIC (18, 2) NULL,
    [CodigoProveedor]                           INT             NULL,
    [IdCuenta]                                  INT             NULL,
    [NumeroIngresosBrutos]                      VARCHAR (30)    NULL,
    [IdMoneda]                                  INT             NULL,
    [LimiteCredito]                             NUMERIC (18, 2) NULL,
    [TipoProveedor]                             INT             NULL,
    [Eventual]                                  VARCHAR (2)     NULL,
    [IdTipoRetencionGanancia]                   INT             NULL,
    [Confirmado]                                VARCHAR (2)     NULL,
    [CodigoPresto]                              VARCHAR (13)    NULL,
    [BienesOServicios]                          VARCHAR (1)     NULL,
    [IdIBCondicionPorDefecto]                   INT             NULL,
    [RetenerSUSS]                               VARCHAR (2)     NULL,
    [ChequesALaOrdenDe]                         VARCHAR (100)   NULL,
    [FechaLimiteExentoGanancias]                DATETIME        NULL,
    [FechaLimiteExentoIIBB]                     DATETIME        NULL,
    [IdImpuestoDirectoSUSS]                     INT             NULL,
    [Importaciones_NumeroInscripcion]           VARCHAR (20)    NULL,
    [Importaciones_DenominacionInscripcion]     VARCHAR (10)    NULL,
    [EnviarEmail]                               TINYINT         NULL,
    [REP_PROVEEDO_INS]                          VARCHAR (1)     NULL,
    [REP_PROVEEDO_UPD]                          VARCHAR (1)     NULL,
    [InformacionAuxiliar]                       VARCHAR (50)    NULL,
    [CoeficienteIIBBUnificado]                  NUMERIC (6, 2)  NULL,
    [FechaUltimaPresentacionDocumentacion]      DATETIME        NULL,
    [ObservacionesPresentacionDocumentacion]    NTEXT           NULL,
    [FechaLimiteCondicionIVA]                   DATETIME        NULL,
    [CodigoSituacionRetencionIVA]               VARCHAR (1)     NULL,
    [SUSSFechaCaducidadExencion]                DATETIME        NULL,
    [Calificacion]                              INT             NULL,
    [IdUsuarioIngreso]                          INT             NULL,
    [FechaIngreso]                              DATETIME        NULL,
    [IdUsuarioModifico]                         INT             NULL,
    [FechaModifico]                             DATETIME        NULL,
    [Exterior]                                  VARCHAR (2)     NULL,
    [SujetoEmbargado]                           VARCHAR (2)     NULL,
    [SaldoEmbargo]                              NUMERIC (18, 2) NULL,
    [DetalleEmbargo]                            VARCHAR (50)    NULL,
    [PorcentajeIBDirecto]                       NUMERIC (6, 2)  NULL,
    [FechaInicioVigenciaIBDirecto]              DATETIME        NULL,
    [FechaFinVigenciaIBDirecto]                 DATETIME        NULL,
    [GrupoIIBB]                                 INT             NULL,
    [IvaFechaInicioExencion]                    DATETIME        NULL,
    [IdTransportista]                           INT             NULL,
    [CodigoRetencionIVA]                        VARCHAR (10)    NULL,
    [IdListaPrecios]                            INT             NULL,
    [RegimenEspecialConstruccionIIBB]           VARCHAR (2)     NULL,
    [PorcentajeIBDirectoCapital]                NUMERIC (6, 2)  NULL,
    [FechaInicioVigenciaIBDirectoCapital]       DATETIME        NULL,
    [FechaFinVigenciaIBDirectoCapital]          DATETIME        NULL,
    [GrupoIIBBCapital]                          INT             NULL,
    [IdCuentaProvision]                         INT             NULL,
    [TextoAuxiliar1]                            VARCHAR (100)   NULL,
    [TextoAuxiliar2]                            VARCHAR (100)   NULL,
    [TextoAuxiliar3]                            VARCHAR (100)   NULL,
    [InscriptoRegistroFiscalOperadoresGranos]   VARCHAR (2)     NULL,
    [ArchivoAdjunto1]                           VARCHAR (200)   NULL,
    [ArchivoAdjunto2]                           VARCHAR (200)   NULL,
    [ArchivoAdjunto3]                           VARCHAR (200)   NULL,
    [ArchivoAdjunto4]                           VARCHAR (200)   NULL,
    [CancelacionInmediataDeDeuda]               VARCHAR (2)     NULL,
    [DebitoAutomaticoPorDefecto]                VARCHAR (2)     NULL,
    [RegistrarMovimientosEnCuentaCorriente]     VARCHAR (2)     NULL,
    [FechaVencimientoParaEgresosProyectados]    VARCHAR (2)     NULL,
    [SUSSFechaInicioVigencia]                   DATETIME        NULL,
    [OperacionesMercadoInternoEntidadVinculada] VARCHAR (2)     NULL,
    [IdCuentaAplicacion]                        INT             NULL,
    [CodigoCategoriaIIBBAlternativo]            VARCHAR (1)     NULL,
    [FechaInicialControlComprobantes]           DATETIME        NULL,
    [ResolucionAfip3668]                        VARCHAR (2)     NULL,
    CONSTRAINT [PK_Proveedores] PRIMARY KEY CLUSTERED ([IdProveedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Proveedores_EstadosProveedores] FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[Estados Proveedores] ([IdEstado])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Proveedores]([Cuit] ASC) WITH (FILLFACTOR = 90);

