CREATE TABLE [dbo].[PuntosVenta] (
    [IdPuntoVenta]         INT          IDENTITY (1, 1) NOT NULL,
    [Letra]                VARCHAR (1)  NULL,
    [PuntoVenta]           INT          NULL,
    [IdTipoComprobante]    INT          NULL,
    [ProximoNumero]        INT          NULL,
    [NumeroCAI_R_A]        VARCHAR (20) NULL,
    [FechaCAI_R_A]         DATETIME     NULL,
    [NumeroCAI_F_A]        VARCHAR (20) NULL,
    [FechaCAI_F_A]         DATETIME     NULL,
    [NumeroCAI_D_A]        VARCHAR (20) NULL,
    [FechaCAI_D_A]         DATETIME     NULL,
    [NumeroCAI_C_A]        VARCHAR (20) NULL,
    [FechaCAI_C_A]         DATETIME     NULL,
    [NumeroCAI_R_B]        VARCHAR (20) NULL,
    [FechaCAI_R_B]         DATETIME     NULL,
    [NumeroCAI_F_B]        VARCHAR (20) NULL,
    [FechaCAI_F_B]         DATETIME     NULL,
    [NumeroCAI_D_B]        VARCHAR (20) NULL,
    [FechaCAI_D_B]         DATETIME     NULL,
    [NumeroCAI_C_B]        VARCHAR (20) NULL,
    [FechaCAI_C_B]         DATETIME     NULL,
    [NumeroCAI_R_E]        VARCHAR (20) NULL,
    [FechaCAI_R_E]         DATETIME     NULL,
    [NumeroCAI_F_E]        VARCHAR (20) NULL,
    [FechaCAI_F_E]         DATETIME     NULL,
    [NumeroCAI_D_E]        VARCHAR (20) NULL,
    [FechaCAI_D_E]         DATETIME     NULL,
    [NumeroCAI_C_E]        VARCHAR (20) NULL,
    [FechaCAI_C_E]         DATETIME     NULL,
    [ProximoNumero1]       INT          NULL,
    [ProximoNumero2]       INT          NULL,
    [ProximoNumero3]       INT          NULL,
    [ProximoNumero4]       INT          NULL,
    [ProximoNumero5]       INT          NULL,
    [Descripcion]          VARCHAR (50) NULL,
    [WebService]           VARCHAR (5)  NULL,
    [WebServiceModoTest]   VARCHAR (2)  NULL,
    [CAEManual]            VARCHAR (2)  NULL,
    [Activo]               VARCHAR (2)  NULL,
    [AgentePercepcionIIBB] VARCHAR (2)  NULL,
    [CodigoAuxiliar]       INT          NULL,
    [IdDeposito]           INT          NULL,
    CONSTRAINT [PK_PuntosVenta] PRIMARY KEY CLUSTERED ([IdPuntoVenta] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PuntosVenta_TiposComprobante] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobante] ([IdTipoComprobante])
);

