CREATE TABLE [dbo].[RecepcionesSAT] (
    [IdRecepcion]                           INT             IDENTITY (1, 1) NOT NULL,
    [NumeroRecepcion1]                      INT             NULL,
    [NumeroRecepcion2]                      INT             NULL,
    [IdProveedor]                           INT             NULL,
    [FechaRecepcion]                        DATETIME        NULL,
    [Observaciones]                         NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdPedido]                              INT             NULL,
    [IdRequerimiento]                       INT             NULL,
    [NumeroRecepcionAlmacen]                INT             NULL,
    [IdTransportista]                       INT             NULL,
    [Acargo]                                VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Realizo]                               INT             NULL,
    [Anulada]                               VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdAcopio]                              INT             NULL,
    [SubNumero]                             VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaRegistracion]                     DATETIME        NULL,
    [EnviarEmail]                           TINYINT         NULL,
    [IdRecepcionOriginal]                   INT             NULL,
    [IdOrigenTransmision]                   INT             NULL,
    [FechaImportacionTransmision]           DATETIME        NULL,
    [ProcesadoPorCPManualmente]             VARCHAR (2)     NULL,
    [ActualizarCostoImportacionDesdePedido] VARCHAR (2)     NULL,
    [ImpuestosInternos]                     NUMERIC (18, 2) NULL,
    [PercepcionIIBB]                        NUMERIC (18, 2) NULL,
    [PercepcionIVA]                         NUMERIC (18, 2) NULL,
    [ImporteIVA]                            NUMERIC (18, 2) NULL,
    [Chofer]                                VARCHAR (50)    NULL,
    [Patente]                               VARCHAR (10)    NULL,
    [NumeroRemitoTransporte1]               INT             NULL,
    [NumeroRemitoTransporte2]               INT             NULL,
    [IdChofer]                              INT             NULL,
    [IdFlete]                               INT             NULL,
    [PesoBruto]                             NUMERIC (18, 2) NULL,
    [PesoNeto]                              NUMERIC (18, 2) NULL,
    [Tara]                                  NUMERIC (18, 2) NULL,
    [CantidadEnOrigen]                      NUMERIC (18, 2) NULL,
    [DistanciaRecorrida]                    NUMERIC (18, 2) NULL,
    [CodigoTarifador]                       VARCHAR (10)    NULL,
    [NumeroOrdenCarga]                      INT             NULL,
    [IdPesada]                              INT             NULL,
    CONSTRAINT [PK_RecepcionesSAT] PRIMARY KEY CLUSTERED ([IdRecepcion] ASC) WITH (FILLFACTOR = 90)
);

