CREATE TABLE [dbo].[Recepciones] (
    [IdRecepcion]                           INT             IDENTITY (1, 1) NOT NULL,
    [NumeroRecepcion1]                      INT             NULL,
    [NumeroRecepcion2]                      INT             NULL,
    [IdProveedor]                           INT             NULL,
    [FechaRecepcion]                        DATETIME        NULL,
    [Observaciones]                         NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdPedido]                              INT             NULL,
    [IdRequerimiento]                       INT             NULL,
    [NumeroRecepcionAlmacen]                INT             NULL,
    [IdTransportista]                       INT             NULL,
    [Acargo]                                VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Realizo]                               INT             NULL,
    [Anulada]                               VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdAcopio]                              INT             NULL,
    [SubNumero]                             VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaRegistracion]                     DATETIME        NULL,
    [EnviarEmail]                           TINYINT         NULL,
    [IdRecepcionOriginal]                   INT             NULL,
    [IdOrigenTransmision]                   INT             NULL,
    [FechaImportacionTransmision]           DATETIME        NULL,
    [ProcesadoPorCPManualmente]             VARCHAR (2)     NULL,
    [ActualizarCostoImportacionDesdePedido] VARCHAR (2)     NULL,
    [IdUsuarioAnulo]                        INT             NULL,
    [FechaAnulacion]                        DATETIME        NULL,
    [MotivoAnulacion]                       NTEXT           NULL,
    [IdUsuarioModifico]                     INT             NULL,
    [FechaUltimaModificacion]               DATETIME        NULL,
    [ImpuestosInternos]                     NUMERIC (18, 2) NULL,
    [PercepcionIIBB]                        NUMERIC (18, 2) NULL,
    [PercepcionIVA]                         NUMERIC (18, 2) NULL,
    [PRESTOFechaProceso]                    DATETIME        NULL,
    [ImporteIVA]                            NUMERIC (18, 2) NULL,
    [IdUsuarioIngreso]                      INT             NULL,
    [FechaIngreso]                          DATETIME        NULL,
    [Libero]                                INT             NULL,
    [FechaLiberacion]                       DATETIME        NULL,
    [CircuitoFirmasCompleto]                VARCHAR (2)     NULL,
    [IdComprador]                           INT             NULL,
    [NumeroRecepcionOrigen1]                INT             NULL,
    [NumeroRecepcionOrigen2]                INT             NULL,
    [Chofer]                                VARCHAR (50)    NULL,
    [NumeroDocumentoChofer]                 VARCHAR (30)    NULL,
    [IdEquipo]                              INT             NULL,
    [Patente]                               VARCHAR (10)    NULL,
    [IdDepositoOrigen]                      INT             NULL,
    [IdRecepcionSAT]                        INT             NULL,
    [TipoRecepcion]                         INT             NULL,
    [IdObra]                                INT             NULL,
    [NumeroRemitoTransporte1]               INT             NULL,
    [NumeroRemitoTransporte2]               INT             NULL,
    [IdChofer]                              INT             NULL,
    [IdFlete]                               INT             NULL,
    [PesoBruto]                             NUMERIC (18, 2) NULL,
    [PesoNeto]                              NUMERIC (18, 2) NULL,
    [Tara]                                  NUMERIC (18, 2) NULL,
    [CantidadEnOrigen]                      NUMERIC (18, 2) NULL,
    [DistanciaRecorrida]                    NUMERIC (18, 2) NULL,
    [CodigoTarifador]                       VARCHAR (10)    NULL,
    [NumeroOrdenCarga]                      INT             NULL,
    [IdPesada]                              INT             NULL,
    [IdTarifaFlete]                         INT             NULL,
    [TarifaFlete]                           NUMERIC (18, 2) NULL,
    [ArchivoAdjunto1]                       VARCHAR (200)   NULL,
    [NumeroPesada]                          INT             NULL,
    [Progresiva1]                           NUMERIC (18, 2) NULL,
    [Progresiva2]                           NUMERIC (18, 2) NULL,
    [FechaPesada]                           DATETIME        NULL,
    [ObservacionesPesada]                   VARCHAR (200)   NULL,
    CONSTRAINT [PK_Recepciones] PRIMARY KEY CLUSTERED ([IdRecepcion] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Recepciones]([FechaRecepcion] ASC) WITH (FILLFACTOR = 90);

