CREATE TABLE [dbo].[Recibos] (
    [IdRecibo]                                 INT             IDENTITY (1, 1) NOT NULL,
    [NumeroRecibo]                             INT             NULL,
    [FechaRecibo]                              DATETIME        NULL,
    [IdCliente]                                INT             NULL,
    [Efectivo]                                 NUMERIC (19, 2) NULL,
    [Descuentos]                               NUMERIC (19, 2) NULL,
    [Valores]                                  NUMERIC (19, 2) NULL,
    [Documentos]                               NUMERIC (19, 2) NULL,
    [Otros1]                                   NUMERIC (19, 2) NULL,
    [IdCuenta1]                                INT             NULL,
    [Otros2]                                   NUMERIC (19, 2) NULL,
    [IdCuenta2]                                INT             NULL,
    [Otros3]                                   NUMERIC (19, 2) NULL,
    [IdCuenta3]                                INT             NULL,
    [Deudores]                                 NUMERIC (19, 2) NULL,
    [RetencionIVA]                             NUMERIC (19, 2) NULL,
    [RetencionGanancias]                       NUMERIC (19, 2) NULL,
    [RetencionIBrutos]                         NUMERIC (19, 2) NULL,
    [GastosGenerales]                          NUMERIC (19, 2) NULL,
    [Cotizacion]                               NUMERIC (18, 3) NULL,
    [Observaciones]                            NTEXT           NULL,
    [IdMoneda]                                 INT             NULL,
    [Dolarizada]                               VARCHAR (2)     NULL,
    [IdObra1]                                  INT             NULL,
    [IdCuentaGasto1]                           INT             NULL,
    [IdObra2]                                  INT             NULL,
    [IdCuentaGasto2]                           INT             NULL,
    [IdObra3]                                  INT             NULL,
    [IdCuentaGasto3]                           INT             NULL,
    [IdObra4]                                  INT             NULL,
    [IdCuentaGasto4]                           INT             NULL,
    [IdCuenta4]                                INT             NULL,
    [Otros4]                                   NUMERIC (19, 2) NULL,
    [IdObra5]                                  INT             NULL,
    [IdCuentaGasto5]                           INT             NULL,
    [IdCuenta5]                                INT             NULL,
    [Otros5]                                   NUMERIC (19, 2) NULL,
    [Tipo]                                     VARCHAR (2)     NULL,
    [IdCuenta]                                 INT             NULL,
    [AsientoManual]                            VARCHAR (2)     NULL,
    [IdObra]                                   INT             NULL,
    [IdCuentaGasto]                            INT             NULL,
    [NumeroCertificadoRetencionGanancias]      NUMERIC (18)    NULL,
    [NumeroCertificadoRetencionIVA]            NUMERIC (18)    NULL,
    [NumeroCertificadoSUSS]                    NUMERIC (18)    NULL,
    [IdTipoRetencionGanancia]                  INT             NULL,
    [CotizacionMoneda]                         NUMERIC (18, 4) NULL,
    [NumeroCertificadoRetencionIngresosBrutos] INT             NULL,
    [Anulado]                                  VARCHAR (2)     NULL,
    [PuntoVenta]                               INT             NULL,
    [IdPuntoVenta]                             INT             NULL,
    [IdUsuarioIngreso]                         INT             NULL,
    [FechaIngreso]                             DATETIME        NULL,
    [IdUsuarioModifico]                        INT             NULL,
    [FechaModifico]                            DATETIME        NULL,
    [IdCobrador]                               INT             NULL,
    [IdVendedor]                               INT             NULL,
    [Lote]                                     INT             NULL,
    [Sublote]                                  INT             NULL,
    [IdCodigoIvaOpcional]                      INT             NULL,
    [TipoOperacionOtros]                       INT             NULL,
    [FechaLote]                                DATETIME        NULL,
    [CuitOpcional]                             VARCHAR (13)    NULL,
    [IdComprobanteProveedorReintegro]          INT             NULL,
    [IdObra6]                                  INT             NULL,
    [IdCuentaGasto6]                           INT             NULL,
    [IdCuenta6]                                INT             NULL,
    [Otros6]                                   NUMERIC (18, 2) NULL,
    [IdObra7]                                  INT             NULL,
    [IdCuentaGasto7]                           INT             NULL,
    [IdCuenta7]                                INT             NULL,
    [Otros7]                                   NUMERIC (18, 2) NULL,
    [IdObra8]                                  INT             NULL,
    [IdCuentaGasto8]                           INT             NULL,
    [IdCuenta8]                                INT             NULL,
    [Otros8]                                   NUMERIC (18, 2) NULL,
    [IdObra9]                                  INT             NULL,
    [IdCuentaGasto9]                           INT             NULL,
    [IdCuenta9]                                INT             NULL,
    [Otros9]                                   NUMERIC (18, 2) NULL,
    [IdObra10]                                 INT             NULL,
    [IdCuentaGasto10]                          INT             NULL,
    [IdCuenta10]                               INT             NULL,
    [Otros10]                                  NUMERIC (18, 2) NULL,
    [NumeroComprobante1]                       NUMERIC (18)    NULL,
    [NumeroComprobante2]                       NUMERIC (18)    NULL,
    [NumeroComprobante3]                       NUMERIC (18)    NULL,
    [NumeroComprobante4]                       NUMERIC (18)    NULL,
    [NumeroComprobante5]                       NUMERIC (18)    NULL,
    [NumeroComprobante6]                       NUMERIC (18)    NULL,
    [NumeroComprobante7]                       NUMERIC (18)    NULL,
    [NumeroComprobante8]                       NUMERIC (18)    NULL,
    [NumeroComprobante9]                       NUMERIC (18)    NULL,
    [NumeroComprobante10]                      NUMERIC (18)    NULL,
    [EnviarEmail]                              TINYINT         NULL,
    [IdOrigenTransmision]                      INT             NULL,
    [IdReciboOriginal]                         INT             NULL,
    [FechaImportacionTransmision]              DATETIME        NULL,
    [CuitClienteTransmision]                   VARCHAR (13)    NULL,
    [IdProvinciaDestino]                       INT             NULL,
    [ServicioCobro]                            VARCHAR (10)    NULL,
    [LoteServicioCobro]                        VARCHAR (15)    NULL,
    [IdFacturaDirecta]                         INT             NULL,
    CONSTRAINT [PK_Recibos] PRIMARY KEY NONCLUSTERED ([IdRecibo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Recibos_Clientes] FOREIGN KEY ([IdCliente]) REFERENCES [dbo].[Clientes] ([IdCliente])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Recibos]([FechaRecibo] ASC, [IdRecibo] ASC) WITH (FILLFACTOR = 90);

