CREATE TABLE [dbo].[Requerimientos] (
    [IdRequerimiento]              INT             IDENTITY (1, 1) NOT NULL,
    [NumeroRequerimiento]          INT             NULL,
    [FechaRequerimiento]           DATETIME        NULL,
    [LugarEntrega]                 NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Observaciones]                NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdObra]                       INT             NULL,
    [IdCentroCosto]                INT             NULL,
    [IdSolicito]                   INT             NULL,
    [IdSector]                     INT             NULL,
    [MontoPrevisto]                NUMERIC (18, 2) NULL,
    [IdComprador]                  INT             NULL,
    [Aprobo]                       INT             NULL,
    [FechaAprobacion]              DATETIME        NULL,
    [MontoParaCompra]              NUMERIC (18, 2) NULL,
    [Cumplido]                     VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Consorcial]                   VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UsuarioAnulacion]             VARCHAR (6)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FechaAnulacion]               DATETIME        NULL,
    [MotivoAnulacion]              NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EnviarEmail]                  TINYINT         NULL,
    [IdRequerimientoOriginal]      INT             NULL,
    [IdOrigenTransmision]          INT             NULL,
    [IdAutorizoCumplido]           INT             NULL,
    [IdDioPorCumplido]             INT             NULL,
    [FechaDadoPorCumplido]         DATETIME        NULL,
    [ObservacionesCumplido]        NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdMoneda]                     INT             NULL,
    [Detalle]                      VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DirectoACompras]              VARCHAR (2)     NULL,
    [IdAutorizoDirectoACompras]    INT             NULL,
    [PRESTOContrato]               VARCHAR (13)    NULL,
    [Confirmado]                   VARCHAR (2)     NULL,
    [FechaImportacionTransmision]  DATETIME        NULL,
    [IdEquipoDestino]              INT             NULL,
    [Impresa]                      VARCHAR (2)     NULL,
    [Recepcionado]                 VARCHAR (2)     NULL,
    [Entregado]                    VARCHAR (2)     NULL,
    [TipoRequerimiento]            VARCHAR (2)     NULL,
    [IdOrdenTrabajo]               INT             NULL,
    [Aprobo2]                      INT             NULL,
    [FechaAprobacion2]             DATETIME        NULL,
    [IdTipoCompra]                 INT             NULL,
    [IdImporto]                    INT             NULL,
    [FechaLlegadaImportacion]      DATETIME        NULL,
    [CircuitoFirmasCompleto]       VARCHAR (2)     NULL,
    [IdCuentaPresupuesto]          INT             NULL,
    [MesPresupuesto]               INT             NULL,
    [RequisitosSeguridad]          NTEXT           NULL,
    [Adjuntos]                     VARCHAR (2)     NULL,
    [ConfirmadoPorWeb]             VARCHAR (2)     NULL,
    [DetalleImputacion]            VARCHAR (50)    NULL,
    [IdUsuarioDeslibero]           INT             NULL,
    [FechaDesliberacion]           DATETIME        NULL,
    [NumeradorDesliberaciones]     INT             NULL,
    [IdUsuarioEliminoFirmas]       INT             NULL,
    [FechaEliminacionFirmas]       DATETIME        NULL,
    [NumeradorEliminacionesFirmas] INT             NULL,
    [NumeradorModificaciones]      INT             NULL,
    [ParaTaller]                   VARCHAR (2)     NULL,
    [FechasLiberacion]             VARCHAR (100)   NULL,
    [Presupuestos]                 VARCHAR (100)   NULL,
    [Comparativas]                 VARCHAR (100)   NULL,
    [Pedidos]                      VARCHAR (100)   NULL,
    [Recepciones]                  VARCHAR (100)   NULL,
    [SalidasMateriales]            VARCHAR (100)   NULL,
    CONSTRAINT [PK_Requerimientos] PRIMARY KEY CLUSTERED ([IdRequerimiento] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Requerimientos_Empleados_Aprobo] FOREIGN KEY ([Aprobo]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Requerimientos_Empleados_IdAutorizoCumplido] FOREIGN KEY ([IdAutorizoCumplido]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Requerimientos_Empleados_IdComprador] FOREIGN KEY ([IdComprador]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Requerimientos_Empleados_IdDioPorCumplido] FOREIGN KEY ([IdDioPorCumplido]) REFERENCES [dbo].[Empleados] ([IdEmpleado]),
    CONSTRAINT [FK_Requerimientos_Empleados_IdSolicito] FOREIGN KEY ([IdSolicito]) REFERENCES [dbo].[Empleados] ([IdEmpleado])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Requerimientos]([FechaRequerimiento] ASC) WITH (FILLFACTOR = 90);

