CREATE TABLE [dbo].[SalidasMaterialesSAT] (
    [IdSalidaMateriales]          INT             IDENTITY (1, 1) NOT NULL,
    [NumeroSalidaMateriales]      INT             NULL,
    [FechaSalidaMateriales]       DATETIME        NULL,
    [IdObra]                      INT             NULL,
    [Observaciones]               NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Aprobo]                      INT             NULL,
    [TipoSalida]                  INT             NULL,
    [IdTransportista1]            INT             NULL,
    [IdTransportista2]            INT             NULL,
    [Cliente]                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Direccion]                   VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Localidad]                   VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CodigoPostal]                VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CondicionIva]                VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cuit]                        VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroSalidaMateriales2]     INT             NULL,
    [Acargo]                      VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Emitio]                      INT             NULL,
    [ValePreimpreso]              INT             NULL,
    [Referencia]                  VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroDocumento]             VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente1]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente2]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente3]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente4]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdProveedor]                 INT             NULL,
    [Chofer]                      VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCentroCosto]               INT             NULL,
    [FechaRegistracion]           DATETIME        NULL,
    [Anulada]                     VARCHAR (2)     NULL,
    [FechaAnulacion]              DATETIME        NULL,
    [IdUsuarioAnulo]              INT             NULL,
    [EnviarEmail]                 TINYINT         NULL,
    [IdSalidaMaterialesOriginal]  INT             NULL,
    [IdOrigenTransmision]         INT             NULL,
    [FechaImportacionTransmision] DATETIME        NULL,
    [MotivoAnulacion]             NTEXT           NULL,
    [NumeroRemitoTransporte1]     INT             NULL,
    [NumeroRemitoTransporte2]     INT             NULL,
    [IdChofer]                    INT             NULL,
    [IdFlete]                     INT             NULL,
    [PesoBruto]                   NUMERIC (18, 2) NULL,
    [PesoNeto]                    NUMERIC (18, 2) NULL,
    [Tara]                        NUMERIC (18, 2) NULL,
    [CantidadEnOrigen]            NUMERIC (18, 2) NULL,
    [DistanciaRecorrida]          NUMERIC (18, 2) NULL,
    [CodigoTarifador]             VARCHAR (10)    NULL,
    [IdPesada]                    INT             NULL,
    CONSTRAINT [PK_SalidasMaterialesSAT] PRIMARY KEY CLUSTERED ([IdSalidaMateriales] ASC) WITH (FILLFACTOR = 90)
);

