CREATE TABLE [dbo].[SalidasMateriales] (
    [IdSalidaMateriales]          INT             IDENTITY (1, 1) NOT NULL,
    [NumeroSalidaMateriales]      INT             NULL,
    [FechaSalidaMateriales]       DATETIME        NULL,
    [IdObra]                      INT             NULL,
    [Observaciones]               NTEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Aprobo]                      INT             NULL,
    [TipoSalida]                  INT             NULL,
    [IdTransportista1]            INT             NULL,
    [IdTransportista2]            INT             NULL,
    [Cliente]                     VARCHAR (100)   NULL,
    [Direccion]                   VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Localidad]                   VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CodigoPostal]                VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CondicionIva]                VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cuit]                        VARCHAR (13)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroSalidaMateriales2]     INT             NULL,
    [Acargo]                      VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Emitio]                      INT             NULL,
    [ValePreimpreso]              INT             NULL,
    [Referencia]                  VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NumeroDocumento]             VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente1]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente2]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente3]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Patente4]                    VARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdProveedor]                 INT             NULL,
    [Chofer]                      VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdCentroCosto]               INT             NULL,
    [FechaRegistracion]           DATETIME        NULL,
    [Anulada]                     VARCHAR (2)     NULL,
    [FechaAnulacion]              DATETIME        NULL,
    [IdUsuarioAnulo]              INT             NULL,
    [EnviarEmail]                 TINYINT         NULL,
    [IdSalidaMaterialesOriginal]  INT             NULL,
    [IdOrigenTransmision]         INT             NULL,
    [FechaImportacionTransmision] DATETIME        NULL,
    [MotivoAnulacion]             NTEXT           NULL,
    [NumeroOrdenProduccion]       INT             NULL,
    [IdDepositoOrigen]            INT             NULL,
    [IdUsuarioIngreso]            INT             NULL,
    [FechaIngreso]                DATETIME        NULL,
    [IdUsuarioModifico]           INT             NULL,
    [FechaModifico]               DATETIME        NULL,
    [IdRecepcionSAT]              INT             NULL,
    [ClaveTipoSalida]             VARCHAR (30)    NULL,
    [SalidaADepositoEnTransito]   VARCHAR (2)     NULL,
    [ValorDeclarado]              NUMERIC (18, 2) NULL,
    [Bultos]                      INT             NULL,
    [IdColor]                     INT             NULL,
    [Embalo]                      VARCHAR (50)    NULL,
    [CircuitoFirmasCompleto]      VARCHAR (2)     NULL,
    [IdPuntoVenta]                INT             NULL,
    [NumeroRemitoTransporte]      VARCHAR (15)    NULL,
    [IdEquipo]                    INT             NULL,
    [IdSalidaMaterialesSAT]       INT             NULL,
    [IdObraOrigen]                INT             NULL,
    [NumeroRemitoPreimpreso1]     INT             NULL,
    [NumeroRemitoPreimpreso2]     INT             NULL,
    [IdFlete]                     INT             NULL,
    [IdChofer]                    INT             NULL,
    [DestinoDeObra]               VARCHAR (50)    NULL,
    [PesoBruto]                   NUMERIC (18, 2) NULL,
    [PesoNeto]                    NUMERIC (18, 2) NULL,
    [Tara]                        NUMERIC (18, 2) NULL,
    [CantidadEnOrigen]            NUMERIC (18, 2) NULL,
    [DistanciaRecorrida]          NUMERIC (18, 2) NULL,
    [CodigoTarifador]             VARCHAR (10)    NULL,
    [IdPesada]                    INT             NULL,
    [IdTarifaFlete]               INT             NULL,
    [TarifaFlete]                 NUMERIC (18, 2) NULL,
    [Detalle]                     VARCHAR (30)    NULL,
    [IdProduccionOrden]           INT             NULL,
    [IdDepositoIntermedio]        INT             NULL,
    [NumeroPesada]                INT             NULL,
    [Progresiva1]                 NUMERIC (18, 2) NULL,
    [Progresiva2]                 NUMERIC (18, 2) NULL,
    [FechaPesada]                 DATETIME        NULL,
    [ObservacionesPesada]         VARCHAR (200)   NULL,
    [NumeroRemitoTransporte1]     INT             NULL,
    [NumeroRemitoTransporte2]     INT             NULL,
    [RecibidosEnDestino]          VARCHAR (2)     NULL,
    [RecibidosEnDestinoFecha]     DATETIME        NULL,
    [RecibidosEnDestinoIdUsuario] INT             NULL,
    [IdCalle1]                    INT             NULL,
    [IdCalle2]                    INT             NULL,
    [IdCalle3]                    INT             NULL,
    CONSTRAINT [PK_SalidasMateriales] PRIMARY KEY CLUSTERED ([IdSalidaMateriales] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[SalidasMateriales]([FechaSalidaMateriales] ASC) WITH (FILLFACTOR = 90);

