CREATE TABLE [dbo].[SubcontratosDatos] (
    [IdSubcontratoDatos]           INT            IDENTITY (1, 1) NOT NULL,
    [NumeroSubcontrato]            INT            NULL,
    [DescripcionSubcontrato]       VARCHAR (50)   NULL,
    [IdProveedor]                  INT            NULL,
    [Fecha]                        DATETIME       NULL,
    [FechaInicio]                  DATETIME       NULL,
    [FechaFinalizacion]            DATETIME       NULL,
    [Adjunto1]                     VARCHAR (100)  NULL,
    [Adjunto2]                     VARCHAR (100)  NULL,
    [Adjunto3]                     VARCHAR (100)  NULL,
    [Adjunto4]                     VARCHAR (100)  NULL,
    [Adjunto5]                     VARCHAR (100)  NULL,
    [Adjunto6]                     VARCHAR (100)  NULL,
    [Adjunto7]                     VARCHAR (100)  NULL,
    [Adjunto8]                     VARCHAR (100)  NULL,
    [Adjunto9]                     VARCHAR (100)  NULL,
    [Adjunto10]                    VARCHAR (100)  NULL,
    [CondicionPago]                VARCHAR (50)   NULL,
    [AnticipoFinanciero]           VARCHAR (50)   NULL,
    [Acopio]                       VARCHAR (50)   NULL,
    [FondoReparo]                  NUMERIC (6, 2) NULL,
    [PorcentajeAnticipoFinanciero] NUMERIC (6, 2) NULL,
    [IdMoneda]                     INT            NULL,
    [Observaciones]                NTEXT          NULL,
    [Anulado]                      VARCHAR (2)    NULL,
    [IdUsuarioAnulo]               INT            NULL,
    [FechaAnulacion]               DATETIME       NULL,
    [MotivoAnulacion]              NTEXT          NULL,
    [IdObra]                       INT            NULL,
    CONSTRAINT [PK_SubcontratosDatos] PRIMARY KEY CLUSTERED ([IdSubcontratoDatos] ASC) WITH (FILLFACTOR = 90)
);

