CREATE TABLE [dbo].[TiposComprobante] (
    [IdTipoComprobante]             INT          NOT NULL,
    [Descripcion]                   VARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Coeficiente]                   SMALLINT     NULL,
    [DescripcionAb]                 VARCHAR (5)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EsValor]                       VARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CodigoDgi]                     VARCHAR (2)  NULL,
    [Agrupacion1]                   VARCHAR (20) NULL,
    [CalculaDiferenciaCambio]       VARCHAR (2)  NULL,
    [VaAlLibro]                     VARCHAR (2)  NULL,
    [PideBancoCuenta]               VARCHAR (2)  NULL,
    [PideCuenta]                    VARCHAR (2)  NULL,
    [IdCuentaDefault]               INT          NULL,
    [VaAConciliacionBancaria]       VARCHAR (2)  NULL,
    [LlevarAPesosEnValores]         VARCHAR (2)  NULL,
    [CoeficienteParaFondoFijo]      INT          NULL,
    [CoeficienteParaConciliaciones] INT          NULL,
    [VaAlCiti]                      VARCHAR (2)  NULL,
    [VaAlRegistroComprasAFIP]       VARCHAR (2)  NULL,
    [CodigoAFIP_Letra_A]            VARCHAR (2)  NULL,
    [CodigoAFIP_Letra_B]            VARCHAR (2)  NULL,
    [CodigoAFIP_Letra_C]            VARCHAR (2)  NULL,
    [CodigoAFIP_Letra_E]            VARCHAR (2)  NULL,
    [InformacionAuxiliar]           VARCHAR (50) NULL,
    [ExigirCAI]                     VARCHAR (2)  NULL,
    [NumeradorAuxiliar]             INT          NULL,
    [CodigoAFIP2_Letra_A]           VARCHAR (2)  NULL,
    [CodigoAFIP2_Letra_B]           VARCHAR (2)  NULL,
    [CodigoAFIP2_Letra_C]           VARCHAR (2)  NULL,
    [CodigoAFIP2_Letra_E]           VARCHAR (2)  NULL,
    [CodigoAFIP3_Letra_A]           VARCHAR (2)  NULL,
    [CodigoAFIP3_Letra_B]           VARCHAR (2)  NULL,
    [CodigoAFIP3_Letra_C]           VARCHAR (2)  NULL,
    [CodigoAFIP3_Letra_E]           VARCHAR (2)  NULL,
    CONSTRAINT [PK_TiposComprobante] PRIMARY KEY CLUSTERED ([IdTipoComprobante] ASC) WITH (FILLFACTOR = 90)
);

