CREATE TABLE [dbo].[Valores] (
    [IdValor]                          INT             IDENTITY (1, 1) NOT NULL,
    [IdTipoValor]                      INT             NULL,
    [NumeroValor]                      NUMERIC (18)    NULL,
    [FechaValor]                       DATETIME        NULL,
    [NumeroInterno]                    INT             NULL,
    [IdTipoComprobante]                INT             NULL,
    [NumeroComprobante]                INT             NULL,
    [FechaComprobante]                 DATETIME        NULL,
    [IdCliente]                        INT             NULL,
    [IdDetalleReciboValores]           INT             NULL,
    [IdBanco]                          INT             NULL,
    [Importe]                          NUMERIC (18, 2) NULL,
    [Estado]                           VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdBancoDeposito]                  INT             NULL,
    [NumeroDeposito]                   INT             NULL,
    [FechaDeposito]                    DATETIME        NULL,
    [IdProveedor]                      INT             NULL,
    [NumeroOrdenPago]                  INT             NULL,
    [FechaOrdenPago]                   DATETIME        NULL,
    [IdCuenta]                         INT             NULL,
    [NumeroSalida]                     INT             NULL,
    [FechaSalida]                      DATETIME        NULL,
    [IdCuentaOrigen]                   INT             NULL,
    [FechaEntrada]                     DATETIME        NULL,
    [FechaEntradaActivada]             VARCHAR (2)     NULL,
    [Conciliado]                       VARCHAR (2)     NULL,
    [IdCuentaBancaria]                 INT             NULL,
    [IdCuentaBancariaDeposito]         INT             NULL,
    [Iva]                              NUMERIC (18, 2) NULL,
    [IdObra]                           INT             NULL,
    [IdCuentaGasto]                    INT             NULL,
    [IdCuentaContable]                 INT             NULL,
    [IdCuentaIVA]                      INT             NULL,
    [PorcentajeIVA]                    NUMERIC (6, 2)  NULL,
    [IdDetalleOrdenPagoCuentas]        INT             NULL,
    [IdCaja]                           INT             NULL,
    [IdDetalleOrdenPagoValores]        INT             NULL,
    [IdMoneda]                         INT             NULL,
    [CotizacionMoneda]                 NUMERIC (18, 4) NULL,
    [IdDetalleComprobanteProveedor]    INT             NULL,
    [IdDetalleAsiento]                 INT             NULL,
    [CuitLibrador]                     VARCHAR (13)    NULL,
    [IdConciliacion]                   INT             NULL,
    [Emitido]                          VARCHAR (2)     NULL,
    [FechaEmision]                     DATETIME        NULL,
    [IdEmitio]                         INT             NULL,
    [IdDetalleReciboCuentas]           INT             NULL,
    [MovimientoConfirmadoBanco]        VARCHAR (2)     NULL,
    [FechaConfirmacionBanco]           DATETIME        NULL,
    [IdUsuarioConfirmacionBanco]       INT             NULL,
    [IdPlazoFijoInicio]                INT             NULL,
    [IdPlazoFijoFin]                   INT             NULL,
    [FechaGasto]                       DATETIME        NULL,
    [IdUsuarioIngreso]                 INT             NULL,
    [FechaIngreso]                     DATETIME        NULL,
    [IdUsuarioModifico]                INT             NULL,
    [FechaModifico]                    DATETIME        NULL,
    [Detalle]                          VARCHAR (30)    NULL,
    [IdDetalleNotaDebito]              INT             NULL,
    [IdDetalleNotaCredito]             INT             NULL,
    [RegistroContableChequeDiferido]   VARCHAR (2)     NULL,
    [EnviarEmail]                      TINYINT         NULL,
    [IdOrigenTransmision]              INT             NULL,
    [IdValorOriginal]                  INT             NULL,
    [FechaImportacionTransmision]      DATETIME        NULL,
    [IdDetalleReciboValoresOriginal]   INT             NULL,
    [CuitClienteTransmision]           VARCHAR (13)    NULL,
    [CertificadoRetencion]             VARCHAR (20)    NULL,
    [AsientoManual]                    VARCHAR (2)     NULL,
    [Anulado]                          VARCHAR (2)     NULL,
    [IdUsuarioAnulo]                   INT             NULL,
    [FechaAnulacion]                   DATETIME        NULL,
    [MotivoAnulacion]                  VARCHAR (30)    NULL,
    [Rechazado]                        VARCHAR (2)     NULL,
    [IdTarjetaCredito]                 INT             NULL,
    [NumeroTarjetaCredito]             VARCHAR (20)    NULL,
    [NumeroAutorizacionTarjetaCredito] INT             NULL,
    [CantidadCuotas]                   INT             NULL,
    [FechaExpiracionTarjetaCredito]    VARCHAR (5)     NULL,
    [IdFactura]                        INT             NULL,
    [IdDetallePresentacionTarjeta]     INT             NULL,
    [IdOrigen]                         INT             NULL,
    [OrigenRegistro]                   VARCHAR (12)    NULL,
    [IdReciboAsignado]                 INT             NULL,
    CONSTRAINT [PK_Valores] PRIMARY KEY NONCLUSTERED ([IdValor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Valores_Monedas_IdMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[Monedas] ([IdMoneda]),
    CONSTRAINT [FK_Valores_TiposComprobante_IdTipoComprobante] FOREIGN KEY ([IdTipoComprobante]) REFERENCES [dbo].[TiposComprobante] ([IdTipoComprobante]),
    CONSTRAINT [FK_Valores_TiposComprobante_IdTipoValor] FOREIGN KEY ([IdTipoValor]) REFERENCES [dbo].[TiposComprobante] ([IdTipoComprobante])
);


GO
CREATE NONCLUSTERED INDEX [Indice1]
    ON [dbo].[Valores]([FechaComprobante] ASC, [NumeroInterno] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Indice2]
    ON [dbo].[Valores]([IdCuentaBancaria] ASC, [FechaValor] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Indice3]
    ON [dbo].[Valores]([IdReciboAsignado] ASC, [IdValor] ASC) WITH (FILLFACTOR = 90);

