CREATE TABLE [dbo].[wTempCartasPorteFacturacionAutomatica] (
    [IdTempCartasPorteFacturacionAutomatica] INT             IDENTITY (1, 1) NOT NULL,
    [IdSesion]                               INT             NULL,
    [IdCartaDePorte]                         INT             NULL,
    [IdFacturarselaA]                        INT             NULL,
    [ColumnaTilde]                           INT             NULL,
    [IdArticulo]                             INT             NULL,
    [NumeroCartaDePorte]                     BIGINT          NULL,
    [SubNumeroVagon]                         INT             NULL,
    [SubnumeroDeFacturacion]                 INT             NULL,
    [FechaArribo]                            DATETIME        NULL,
    [FechaDescarga]                          DATETIME        NULL,
    [FacturarselaA]                          VARCHAR (50)    NULL,
    [Confirmado]                             VARCHAR (2)     NULL,
    [IdCodigoIVA]                            INT             NULL,
    [CUIT]                                   VARCHAR (50)    NULL,
    [ClienteSeparado]                        VARCHAR (50)    NULL,
    [TarifaFacturada]                        NUMERIC (18, 2) NULL,
    [Producto]                               VARCHAR (50)    NULL,
    [KgNetos]                                NUMERIC (18, 2) NULL,
    [IdCorredor]                             INT             NULL,
    [IdTitular]                              INT             NULL,
    [IdIntermediario]                        INT             NULL,
    [IdRComercial]                           INT             NULL,
    [Titular]                                VARCHAR (50)    NULL,
    [RComercial]                             VARCHAR (50)    NULL,
    [Corredor]                               VARCHAR (50)    NULL,
    [Destinatario]                           VARCHAR (50)    NULL,
    [Procedcia]                              VARCHAR (50)    NULL,
    [DestinoDesc]                            VARCHAR (50)    NULL,
    [IdDestino]                              INT             NULL,
    PRIMARY KEY CLUSTERED ([IdTempCartasPorteFacturacionAutomatica] ASC)
);

