 use autotrol

select * from conceptos join Cuentas on cuentas.IdCuenta=Conceptos.IdCuenta

sp_helptext  



select * from clientes
select * from cuentas

 select * from PuntosVenta
select * from DescripcionIva

 exec Tree_TX_Arbol  

 sp_helptext Tree_TX_Arbol


 exec Requerimientos_TX_PendientesDeFirma 
 exec Requerimientos_TX_Pendientes1 'T'
 exec Requerimientos_TX_Pendientes1 'P'


 --sp_helptext Requerimientos_TX_PendientesDeFirma


 exec AutorizacionesPorComprobante_EliminarFirmas 
 exec AutorizacionesPorComprobante_TX_AutorizacionesPorComprobante 4,18317
 
 exec Autorizaciones_TX_CantidadAutorizaciones 4,9.00
 exec Autorizaciones_TX_CantidadAutorizaciones 4,0

 exec autorizaciones_tx_ca

 select * from pedidos


 select * from bdlmaster.dbo.userdatosextendidos

 exec DetPedidos_TX_DetallesParametrizados 18259,1
  exec DetPedidos_TX_DetallesParametrizados  11,


declare @p5 int
set @p5=0
exec sp_executesql N'EXEC @RETURN_VALUE = [dbo].[DetPedidos_TX_DetallesParametrizados] @IdPedido = @p0, @NivelParametrizacion = @p1',N'@p0 int,@p1 int,@RETURN_VALUE int output',@p0=18259,@p1=-1,@RETURN_VALUE=@p5 output
select @p5





















	ALTER TABLE  articulos ADD

	[IdCuentaComprasActivo] int  NULL,
    [AuxiliarNumerico1] decimal(18,2)  NULL,
    [AuxiliarNumerico2] decimal(18,2)  NULL,
    [AuxiliarNumerico3] decimal(18,2)  NULL,
    [AuxiliarNumerico4] decimal(18,2)  NULL,
    [AuxiliarNumerico5] decimal(18,2)  NULL

GO

-- Creating table 'ControlesCalidads'
CREATE TABLE [dbo].[ControlesCalidads] (
    [IdControlCalidad] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(250)  NULL,
    [Inspeccion] varchar(2)  NULL,
    [Abreviatura] varchar(2)  NULL,
    [Detalle] nvarchar(max)  NULL
);
GO

-- Creating table 'DetalleRequerimientos'
CREATE TABLE [dbo].[DetalleRequerimientos] (
    [IdDetalleRequerimiento] int IDENTITY(1,1) NOT NULL,
    [IdRequerimiento] int  NULL,
    [NumeroItem] int  NULL,
    [Cantidad] decimal(18,2)  NULL,
    [IdUnidad] int  NULL,
    [IdArticulo] int  NULL,
    [FechaEntrega] datetime  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [Cantidad1] decimal(18,2)  NULL,
    [Cantidad2] decimal(18,2)  NULL,
    [IdDetalleLMateriales] int  NULL,
    [IdControlCalidad] int  NULL,
    [Adjunto] varchar(2)  NULL,
    [ArchivoAdjunto] varchar(50)  NULL,
    [IdCentroCosto] int  NULL,
    [IdComprador] int  NULL,
    [NumeroFacturaCompra1] int  NULL,
    [FechaFacturaCompra] datetime  NULL,
    [ImporteFacturaCompra] decimal(18,2)  NULL,
    [IdProveedor] int  NULL,
    [NumeroFacturaCompra2] int  NULL,
    [EsBienDeUso] varchar(2)  NULL,
    [IdCuenta] int  NULL,
    [Cumplido] varchar(2)  NULL,
    [Usuario1] varchar(6)  NULL,
    [FechaIngreso1] datetime  NULL,
    [ArchivoAdjunto1] varchar(100)  NULL,
    [ArchivoAdjunto2] varchar(100)  NULL,
    [ArchivoAdjunto3] varchar(100)  NULL,
    [ArchivoAdjunto4] varchar(100)  NULL,
    [ArchivoAdjunto5] varchar(100)  NULL,
    [ArchivoAdjunto6] varchar(100)  NULL,
    [ArchivoAdjunto7] varchar(100)  NULL,
    [ArchivoAdjunto8] varchar(100)  NULL,
    [ArchivoAdjunto9] varchar(100)  NULL,
    [ArchivoAdjunto10] varchar(100)  NULL,
    [Descripcionmanual] varchar(250)  NULL,
    [EnviarEmail] tinyint  NULL,
    [IdRequerimientoOriginal] int  NULL,
    [IdDetalleRequerimientoOriginal] int  NULL,
    [IdOrigenTransmision] int  NULL,
    [IdLlamadoAProveedor] int  NULL,
    [FechaLlamadoAProveedor] datetime  NULL,
    [IdLlamadoRegistradoPor] int  NULL,
    [FechaRegistracionLlamada] datetime  NULL,
    [ObservacionesLlamada] nvarchar(max)  NULL,
    [IdAutorizoCumplido] int  NULL,
    [IdDioPorCumplido] int  NULL,
    [FechaDadoPorCumplido] datetime  NULL,
    [ObservacionesCumplido] nvarchar(max)  NULL,
    [IdAproboAlmacen] int  NULL,
    [IdEquipo] int  NULL,
    [FechaEntrega_Tel] datetime  NULL,
    [PRESTOConcepto] varchar(13)  NULL,
    [Costo] decimal(18,2)  NULL,
    [OrigenDescripcion] int  NULL,
    [TipoDesignacion] varchar(3)  NULL,
    [IdLiberoParaCompras] int  NULL,
    [FechaLiberacionParaCompras] datetime  NULL,
    [Recepcionado] varchar(2)  NULL,
    [Pagina] int  NULL,
    [Item] int  NULL,
    [Figura] int  NULL,
    [CodigoDistribucion] varchar(3)  NULL,
    [IdEquipoDestino] int  NULL,
    [Entregado] varchar(2)  NULL,
    [FechaAsignacionComprador] datetime  NULL,
    [MoP] varchar(1)  NULL,
    [IdDetalleObraDestino] int  NULL,
    [IdPresupuestoObraRubro] int  NULL,
    [ObservacionesFirmante] nvarchar(max)  NULL,
    [IdFirmanteObservo] int  NULL,
    [FechaUltimaObservacionFirmante] datetime  NULL
);
GO

-- Creating table 'Empleados'
CREATE TABLE [dbo].[Empleados] (
    [IdEmpleado] int IDENTITY(1,1) NOT NULL,
    [Legajo] int  NULL,
    [Nombre] varchar(50)  NULL,
    [UsuarioNT] varchar(50)  NULL,
    [IdSector] int  NULL,
    [IdCargo] int  NULL,
    [Email] varchar(50)  NULL,
    [Interno] varchar(20)  NULL,
    [Administrador] varchar(2)  NULL,
    [Iniciales] varchar(6)  NULL,
    [Password] varchar(50)  NULL,
    [SisMan] varchar(2)  NULL,
    [HorasJornada] decimal(18,2)  NULL,
    [IdSector1] int  NULL,
    [IdCargo1] int  NULL,
    [IdSector2] int  NULL,
    [IdCargo2] int  NULL,
    [IdSector3] int  NULL,
    [IdCargo3] int  NULL,
    [IdSector4] int  NULL,
    [IdCargo4] int  NULL,
    [Dominio] varchar(50)  NULL,
    [SisMat] varchar(2)  NULL,
    [FechaNacimiento] datetime  NULL,
    [TipoUsuario] int  NULL,
    [GrupoDeCarga] int  NULL,
    [CuentaBancaria] varchar(20)  NULL,
    [InformacionAuxiliar] varchar(50)  NULL,
    [IdCuentaFondoFijo] int  NULL,
    [IdObraAsignada] int  NULL,
    [Activo] varchar(2)  NULL,
    [Idioma] varchar(3)  NULL,
    [PuntoVentaAsociado] int  NULL,
    [IdLugarEntregaAsignado] int  NULL
);
GO

-- Creating table 'Obras'
CREATE TABLE [dbo].[Obras] (
    [IdObra] int IDENTITY(1,1) NOT NULL,
    [NumeroObra] varchar(13)  NULL,
    [IdCliente] int  NULL,
    [FechaInicio] datetime  NULL,
    [FechaFinalizacion] datetime  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [FechaEntrega] datetime  NULL,
    [Descripcion] varchar(100)  NULL,
    [IdJefe] int  NULL,
    [TipoObra] int  NULL,
    [HorasEstimadas] int  NULL,
    [Consorcial] varchar(2)  NULL,
    [EnviarEmail] tinyint  NULL,
    [Activa] varchar(2)  NULL,
    [ParaInformes] varchar(2)  NULL,
    [IdUnidadOperativa] int  NULL,
    [Jerarquia] varchar(20)  NULL,
    [ArchivoAdjunto1] varchar(100)  NULL,
    [ArchivoAdjunto2] varchar(100)  NULL,
    [ArchivoAdjunto3] varchar(100)  NULL,
    [ArchivoAdjunto4] varchar(100)  NULL,
    [ArchivoAdjunto5] varchar(100)  NULL,
    [ArchivoAdjunto6] varchar(100)  NULL,
    [ArchivoAdjunto7] varchar(100)  NULL,
    [ArchivoAdjunto8] varchar(100)  NULL,
    [ArchivoAdjunto9] varchar(100)  NULL,
    [ArchivoAdjunto10] varchar(100)  NULL,
    [GeneraReservaStock] varchar(2)  NULL,
    [IdGrupoObra] int  NULL,
    [IdArticuloAsociado] int  NULL,
    [Observaciones2] nvarchar(max)  NULL,
    [Observaciones3] nvarchar(max)  NULL,
    [IdSubjefe] int  NULL,
    [Direccion] varchar(50)  NULL,
    [IdLocalidad] int  NULL,
    [IdProvincia] int  NULL,
    [IdPais] int  NULL,
    [CodigoPostal] varchar(30)  NULL,
    [Telefono] varchar(50)  NULL,
    [LugarPago] varchar(50)  NULL,
    [Responsable] varchar(50)  NULL,
    [Horario] varchar(20)  NULL,
    [Turnos] varchar(10)  NULL,
    [Operarios] int  NULL,
    [Zona] int  NULL,
    [Jurisdiccion] int  NULL,
    [IdCuentaContableFF] int  NULL,
    [ValorObra] decimal(18,2)  NULL,
    [IdMonedaValorObra] int  NULL,
    [IdJefeRegional] int  NULL,
    [EsPlantaDeProduccionInterna] varchar(2)  NULL,
    [ActivarPresupuestoObra] varchar(2)  NULL,
    [ProximoNumeroAutorizacionCompra] int  NULL,
    [AuxiliarDeMateriales] varchar(2)  NULL,
    [DiasLiquidacionCertificados] int  NULL
);
GO

-- Creating table 'Requerimientos'
alter table requerimientos add
    [FechasLiberacion] varchar(100)  NULL,
    [Presupuestos] varchar(100)  NULL,
    [Comparativas] varchar(100)  NULL,
    [Pedidos] varchar(100)  NULL,
    [Recepciones] varchar(100)  NULL,
    [SalidasMateriales] varchar(100)  NULL
GO


-- Creating table 'Sectores'
CREATE TABLE [dbo].[Sectores] (
    [IdSector] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL,
    [SectorDeObra] varchar(2)  NULL,
    [IdEncargado] int  NULL,
    [SeUsaEnPresupuestos] varchar(2)  NULL,
    [OrdenPresentacion] int  NULL,
    [EnviarEmail] tinyint  NULL
);
GO

-- Creating table 'Unidades'
CREATE TABLE [dbo].[Unidades] (
    [IdUnidad] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(30)  NULL,
    [Abreviatura] varchar(15)  NULL,
    [CodigoAFIP] varchar(2)  NULL,
    [UnidadesPorPack] int  NULL,
    [TaraEnKg] decimal(18,4)  NULL
);
GO

-- Creating table 'Parametros'
CREATE TABLE [dbo].[Parametros] (
    [IdParametro] int IDENTITY(1,1) NOT NULL,
    [ProximoPresupuesto] int  NULL,
    [Iva1] decimal(6,2)  NULL,
    [Iva2] decimal(6,2)  NULL,
    [ProximaListaAcopio] int  NULL,
    [ProximaListaMateriales] int  NULL,
    [ProximoNumeroRequerimiento] int  NULL,
    [IdUnidadPorUnidad] int  NULL,
    [ProximoNumeroAjusteStock] int  NULL,
    [ProximoNumeroReservaStock] int  NULL,
    [ProximoNumeroPedido] int  NULL,
    [ControlCalidadDefault] int  NULL,
    [ProximoNumeroValeSalida] int  NULL,
    [ProximoNumeroSalidaMateriales] int  NULL,
    [ProximaComparativa] int  NULL,
    [PathAdjuntos] varchar(50)  NULL,
    [IdUnidadPorKilo] int  NULL,
    [PedidosGarantia] nvarchar(max)  NULL,
    [PedidosDocumentacion] nvarchar(max)  NULL,
    [PedidosPlazoEntrega] nvarchar(max)  NULL,
    [PedidosLugarEntrega] nvarchar(max)  NULL,
    [PedidosFormaPago] nvarchar(max)  NULL,
    [ProximoNumeroSalidaMaterialesAObra] int  NULL,
    [ProximoNumeroSalidaMaterialesParaFacturar] int  NULL,
    [ProximoNumeroSalidaMateriales2] int  NULL,
    [ProximoNumeroSalidaMaterialesAObra2] int  NULL,
    [ProximoNumeroSalidaMaterialesParaFacturar2] int  NULL,
    [PedidosInspecciones] nvarchar(max)  NULL,
    [PedidosImportante] nvarchar(max)  NULL,
    [PathEnvioEmails] varchar(100)  NULL,
    [PathRecepcionEmails] varchar(100)  NULL,
    [ProximoNumeroSalidaMaterialesAProveedor] int  NULL,
    [ProximoNumeroSalidaMaterialesAProveedor2] int  NULL,
    [ProximoNumeroDevolucionDeFabrica] int  NULL,
    [ProximoNumeroDevolucionDeFabrica2] int  NULL,
    [ArchivoAyuda] varchar(100)  NULL,
    [PathArchivoExcelDatanet] varchar(100)  NULL,
    [PathArchivoExcelProveedores] varchar(100)  NULL,
    [Porc_IBrutos_Cap] decimal(18,2)  NULL,
    [Tope_IBrutos_Cap] decimal(18,2)  NULL,
    [Porc_IBrutos_BsAs] decimal(18,2)  NULL,
    [Tope_IBrutos_BsAs] decimal(18,2)  NULL,
    [Porc_IBrutos_BsAsM] decimal(18,2)  NULL,
    [Tope_IBrutos_BsAsM] decimal(18,2)  NULL,
    [Decimales] smallint  NULL,
    [AclaracionAlPieDeFactura] varchar(250)  NULL,
    [CotizacionDolar] decimal(18,2)  NULL,
    [ProximoAsiento] int  NULL,
    [ProximoNumeroInterno] int  NULL,
    [NumeracionUnica] varchar(2)  NULL,
    [EjercicioActual] int  NULL,
    [IdCuentaVentas] int  NULL,
    [IdCuentaBonificaciones] int  NULL,
    [IdCuentaIvaInscripto] int  NULL,
    [IdCuentaIvaNoInscripto] int  NULL,
    [IdCuentaIvaSinDiscriminar] int  NULL,
    [IdCuentaRetencionIBrutosBsAs] int  NULL,
    [IdCuentaRetencionIBrutosCap] int  NULL,
    [IdCuentaReventas] int  NULL,
    [IdCuentaND] int  NULL,
    [IdCuentaNC] int  NULL,
    [IdCuentaCaja] int  NULL,
    [IdCuentaValores] int  NULL,
    [IdCuentaRetencionIva] int  NULL,
    [IdCuentaRetencionGanancias] int  NULL,
    [IdCuentaRetencionIBrutos] int  NULL,
    [IdCuentaDescuentos] int  NULL,
    [IdCuentaDescuentosyRetenciones] int  NULL,
    [IdUnidad] int  NULL,
    [IdMoneda] int  NULL,
    [IdCuentaCompras] int  NULL,
    [ProximoComprobanteProveedorReferencia] int  NULL,
    [ProximoNumeroInternoChequeEmitido] int  NULL,
    [ProximaNumeroOrdenPago] int  NULL,
    [IdCuentaIvaCompras] int  NULL,
    [CAI] varchar(50)  NULL,
    [FechaCAI] varchar(20)  NULL,
    [ClausulaDolar] varchar(1000)  NULL,
    [IdMonedaDolar] int  NULL,
    [NumeroCAI_R_A] varchar(50)  NULL,
    [FechaCAI_R_A] datetime  NULL,
    [NumeroCAI_F_A] varchar(50)  NULL,
    [FechaCAI_F_A] datetime  NULL,
    [NumeroCAI_D_A] varchar(50)  NULL,
    [FechaCAI_D_A] datetime  NULL,
    [NumeroCAI_C_A] varchar(50)  NULL,
    [FechaCAI_C_A] datetime  NULL,
    [NumeroCAI_R_B] varchar(50)  NULL,
    [FechaCAI_R_B] datetime  NULL,
    [NumeroCAI_F_B] varchar(50)  NULL,
    [FechaCAI_F_B] datetime  NULL,
    [NumeroCAI_D_B] varchar(50)  NULL,
    [FechaCAI_D_B] datetime  NULL,
    [NumeroCAI_C_B] varchar(50)  NULL,
    [FechaCAI_C_B] datetime  NULL,
    [NumeroCAI_R_E] varchar(50)  NULL,
    [FechaCAI_R_E] datetime  NULL,
    [NumeroCAI_F_E] varchar(50)  NULL,
    [FechaCAI_F_E] datetime  NULL,
    [NumeroCAI_D_E] varchar(50)  NULL,
    [FechaCAI_D_E] datetime  NULL,
    [NumeroCAI_C_E] varchar(50)  NULL,
    [FechaCAI_C_E] datetime  NULL,
    [NumeracionCorrelativa] varchar(2)  NULL,
    [ProximoNumeroRefProveedores] int  NULL,
    [ProximoNumeroCuentaContable] int  NULL,
    [IdCuentaAcreedoresVarios] int  NULL,
    [IdCuentaDeudoresVarios] int  NULL,
    [ProximaOrdenPago] int  NULL,
    [IdCuentaIvaCompras1] int  NULL,
    [IVAComprasPorcentaje1] decimal(6,2)  NULL,
    [IdCuentaIvaCompras2] int  NULL,
    [IVAComprasPorcentaje2] decimal(6,2)  NULL,
    [IdCuentaIvaCompras3] int  NULL,
    [IVAComprasPorcentaje3] decimal(6,2)  NULL,
    [IdCuentaIvaCompras4] int  NULL,
    [IVAComprasPorcentaje4] decimal(6,2)  NULL,
    [IdCuentaIvaCompras5] int  NULL,
    [IVAComprasPorcentaje5] decimal(6,2)  NULL,
    [ProximaOrdenPagoExterior] int  NULL,
    [MinimoNoImponible] decimal(18,2)  NULL,
    [DeduccionEspecial] decimal(18,2)  NULL,
    [ProximoNumeroCertificadoRetencionGanancias] int  NULL,
    [IdCuentaVentasTitulo] int  NULL,
    [IdCuentaNDTitulo] int  NULL,
    [IdCuentaNCTitulo] int  NULL,
    [IdCuentaCajaTitulo] int  NULL,
    [IdCuentaValoresTitulo] int  NULL,
    [IdCuentaDescuentosyRetencionesTitulo] int  NULL,
    [IdCuentaComprasTitulo] int  NULL,
    [IdCuentaIvaCompras6] int  NULL,
    [IVAComprasPorcentaje6] decimal(6,2)  NULL,
    [IdCuentaIvaCompras7] int  NULL,
    [IVAComprasPorcentaje7] decimal(6,2)  NULL,
    [IdCuentaIvaCompras8] int  NULL,
    [IVAComprasPorcentaje8] decimal(6,2)  NULL,
    [IdCuentaIvaCompras9] int  NULL,
    [IVAComprasPorcentaje9] decimal(6,2)  NULL,
    [IdCuentaIvaCompras10] int  NULL,
    [IVAComprasPorcentaje10] decimal(6,2)  NULL,
    [ProximoNumeroOrdenCompra] int  NULL,
    [ProximoNumeroRemito] int  NULL,
    [IdCuentaRetencionGananciasCobros] int  NULL,
    [IdTipoCuentaGrupoIVA] int  NULL,
    [IGCondicionExcepcion] int  NULL,
    [IdCuentaIvaVentas1] int  NULL,
    [IVAVentasPorcentaje1] decimal(6,2)  NULL,
    [IdCuentaIvaVentas2] int  NULL,
    [IVAVentasPorcentaje2] decimal(6,2)  NULL,
    [IdCuentaIvaVentas3] int  NULL,
    [IVAVentasPorcentaje3] decimal(6,2)  NULL,
    [IdCuentaIvaVentas4] int  NULL,
    [IVAVentasPorcentaje4] decimal(6,2)  NULL,
    [ProximaOrdenPagoOtros] int  NULL,
    [IdTipoComprobanteEfectivo] int  NULL,
    [IdTipoComprobanteDeposito] int  NULL,
    [ProximaNotaDebitoInterna] int  NULL,
    [ProximaNotaCreditoInterna] int  NULL,
    [IdTipoComprobanteCajaIngresos] int  NULL,
    [IdTipoComprobanteCajaEgresos] int  NULL,
    [DirectorioDTS] varchar(100)  NULL,
    [PathObra] varchar(50)  NULL,
    [FechaUltimoCierre] datetime  NULL,
    [IdConceptoDiferenciaCambio] int  NULL,
    [IdTipoCuentaGrupoFF] int  NULL,
    [ProximoNumeroOtroIngresoAlmacen] int  NULL,
    [AgenteRetencionIVA] varchar(2)  NULL,
    [ImporteTotalMinimoAplicacionRetencionIVA] decimal(18,2)  NULL,
    [PorcentajeBaseRetencionIVABienes] decimal(6,2)  NULL,
    [PorcentajeBaseRetencionIVAServicios] decimal(6,2)  NULL,
    [ImporteMinimoRetencionIVA] decimal(18,2)  NULL,
    [ProximoNumeroCertificadoRetencionIVA] int  NULL,
    [ProximoNumeroCertificadoRetencionIIBB] int  NULL,
    [IdTipoComprobanteFacturaCompra] int  NULL,
    [IdTipoComprobanteFacturaVenta] int  NULL,
    [IdTipoComprobanteDevoluciones] int  NULL,
    [IdTipoComprobanteNotaDebito] int  NULL,
    [IdTipoComprobanteNotaCredito] int  NULL,
    [IdTipoComprobanteRecibo] int  NULL,
    [IdControlCalidadStandar] int  NULL,
    [IdTipoCuentaGrupoAnticiposAlPersonal] int  NULL,
    [IdTipoComprobanteNDInternaAcreedores] int  NULL,
    [IdTipoComprobanteNCInternaAcreedores] int  NULL,
    [PercepcionIIBB] varchar(2)  NULL,
    [OtrasPercepciones1] varchar(2)  NULL,
    [OtrasPercepciones1Desc] varchar(15)  NULL,
    [OtrasPercepciones2] varchar(2)  NULL,
    [OtrasPercepciones2Desc] varchar(15)  NULL,
    [IdCuentaDiferenciaCambio] int  NULL,
    [ProximoNumeroReciboPago] int  NULL,
    [NumeroReciboPagoAutomatico] varchar(2)  NULL,
    [IdCuentaPercepcionIIBB] int  NULL,
    [IdCuentaOtrasPercepciones1] int  NULL,
    [IdCuentaOtrasPercepciones2] int  NULL,
    [ConfirmarClausulaDolar] varchar(2)  NULL,
    [ProximoNumeroPedidoExterior] int  NULL,
    [ExigirTrasabilidad_RMLA_PE] varchar(2)  NULL,
    [AgenteRetencionSUSS] varchar(2)  NULL,
    [PorcentajeRetencionSUSS] decimal(6,2)  NULL,
    [ProximoNumeroCertificadoRetencionSUSS] int  NULL,
    [IdCuentaRetencionSUSS] int  NULL,
    [IdCuentaPercepcionIVACompras] int  NULL,
    [IdPuntoVentaNumeracionUnica] int  NULL,
    [AgenteRetencionIIBB] varchar(2)  NULL,
    [PathArchivosExportados] varchar(100)  NULL,
    [IdObraStockDisponible] int  NULL,
    [IdTipoComprobanteOrdenPago] int  NULL,
    [ProximoNumeroInternoRecepcion] int  NULL,
    [IdCuentaRetencionSUSS_Recibida] int  NULL,
    [Plantilla_Factura_A] varchar(50)  NULL,
    [Plantilla_Factura_B] varchar(50)  NULL,
    [Plantilla_Factura_E] varchar(50)  NULL,
    [Plantilla_Devoluciones_A] varchar(50)  NULL,
    [Plantilla_Devoluciones_B] varchar(50)  NULL,
    [Plantilla_Devoluciones_E] varchar(50)  NULL,
    [Plantilla_NotasDebito_A] varchar(50)  NULL,
    [Plantilla_NotasDebito_B] varchar(50)  NULL,
    [Plantilla_NotasDebito_E] varchar(50)  NULL,
    [Plantilla_NotasCredito_A] varchar(50)  NULL,
    [Plantilla_NotasCredito_B] varchar(50)  NULL,
    [Plantilla_NotasCredito_E] varchar(50)  NULL,
    [FechaArranqueCajaYBancos] datetime  NULL,
    [IdRubroVentasEnCuotas] int  NULL,
    [IdConceptoVentasEnCuotas] int  NULL,
    [IdCuentaPlazosFijos] int  NULL,
    [IdCuentaInteresesPlazosFijos] int  NULL,
    [NumeroGeneracionVentaEnCuotas] int  NULL,
    [IdBancoGestionCobroCuotas] int  NULL,
    [PathArchivoCobranzaCuotas] varchar(100)  NULL,
    [TipoAmortizacionContable] varchar(1)  NULL,
    [FrecuenciaAmortizacionContable] varchar(1)  NULL,
    [TipoAmortizacionImpositiva] varchar(1)  NULL,
    [FrecuenciaAmortizacionImpositiva] varchar(1)  NULL,
    [IdCuentaResultadosEjercicio] int  NULL,
    [IdCuentaResultadosAcumulados] int  NULL,
    [CuentasResultadoDesde] int  NULL,
    [CuentasResultadoHasta] int  NULL,
    [CuentasPatrimonialesDesde] int  NULL,
    [CuentasPatrimonialesHasta] int  NULL,
    [IdArticuloVariosParaPRESTO] int  NULL,
    [ControlarRubrosContablesEnOP] varchar(2)  NULL,
    [IdObraActiva] int  NULL,
    [IdCuentaAdicionalIVACompras1] int  NULL,
    [IdCuentaAdicionalIVACompras2] int  NULL,
    [IdCuentaAdicionalIVACompras3] int  NULL,
    [IdCuentaAdicionalIVACompras4] int  NULL,
    [IdCuentaAdicionalIVACompras5] int  NULL,
    [FechaUltimoCierreEjercicio] datetime  NULL,
    [EmiteAsientoEnOP] varchar(2)  NULL,
    [IdMonedaEuro] int  NULL,
    [LineasDiarioDetallado] int  NULL,
    [LineasDiarioResumido] int  NULL,
    [PathEnvioEmailsMANTENIMIENTO] varchar(100)  NULL,
    [PathRecepcionEmailsMANTENIMIENTO] varchar(100)  NULL,
    [ImporteComprobantesMParaRetencionIVA] decimal(18,3)  NULL,
    [PorcentajeRetencionIVAComprobantesM] decimal(6,2)  NULL,
    [ImporteComprobantesMParaRetencionGanancias] decimal(18,2)  NULL,
    [PorcentajeRetencionGananciasComprobantesM] decimal(18,2)  NULL,
    [IdTipoComprobanteFacturaCompraExportacion] int  NULL,
    [IvaCompras_DesglosarNOGRAVADOS] varchar(2)  NULL,
    [IdCuentaImpuestosInternos] int  NULL,
    [Subdiarios_ResumirRegistros] varchar(2)  NULL,
    [IdCajaEnPesosDefault] int  NULL,
    [ProximoNumeroGastoBancario] int  NULL,
    [ProximoNumeroSolicitudCompra] int  NULL,
    [IdCuentaReintegros] int  NULL,
    [IdArticuloPRONTO_MANTENIMIENTO] int  NULL,
    [ProximoCodigoArticulo] int  NULL,
    [FechaTimeStamp] binary(8)  NULL,
    [PathPlantillas] varchar(50)  NULL,
    [OtrasPercepciones3] varchar(2)  NULL,
    [OtrasPercepciones3Desc] varchar(15)  NULL,
    [IdCuentaOtrasPercepciones3] int  NULL,
    [FechaArranqueMovimientosStock] datetime  NULL,
    [IdCuentaRetencionIvaComprobantesM] int  NULL,
    [IdJefeCompras] int  NULL,
    [ImporteMinimoRetencionIVAServicios] decimal(18,2)  NULL,
    [IdCuentaPercepcionesIVA] int  NULL,
    [IdCuentaREI_Ganancia] int  NULL,
    [IdCuentaREI_Perdida] int  NULL,
    [ActivarCircuitoChequesDiferidos] varchar(2)  NULL,
    [BasePRONTOSyJAsociada] varchar(50)  NULL,
    [IdConceptoAnticiposSyJ] int  NULL,
    [IdConceptoRecuperoGastos] int  NULL,
    [BasePRONTOConsolidacion] varchar(50)  NULL,
    [PorcentajeConsolidacion] decimal(6,2)  NULL,
    [BasePRONTOConsolidacion2] varchar(50)  NULL,
    [PorcentajeConsolidacion2] decimal(6,2)  NULL,
    [BasePRONTOConsolidacion3] varchar(50)  NULL,
    [PorcentajeConsolidacion3] decimal(6,2)  NULL,
    [IdCuentaAjusteConsolidacion] int  NULL,
    [PathImportacionDatos] varchar(50)  NULL,
    [ActivarSolicitudMateriales] varchar(2)  NULL,
    [TopeMinimoRetencionIVA] decimal(18,2)  NULL,
    [TopeMinimoRetencionIVAServicios] decimal(18,2)  NULL,
    [IdMonedaPrincipal] int  NULL,
    [IdTipoComprobanteTarjetaCredito] int  NULL,
    [ProximoNumeroOrdenTrabajo] int  NULL,
    [BasePRONTOMantenimiento] varchar(50)  NULL,
    [ProximaOrdenPagoFF] int  NULL
);
GO

-- Creating table 'Parametros2'
CREATE TABLE [dbo].[Parametros2] (
    [IdParametro] int IDENTITY(1,1) NOT NULL,
    [Campo] varchar(50)  NULL,
    [Valor] varchar(50)  NULL
);
GO

-- Creating table 'Vendedores'
CREATE TABLE [dbo].[Vendedores] (
    [IdVendedor] int IDENTITY(1,1) NOT NULL,
    [CodigoVendedor] int  NOT NULL,
    [Nombre] varchar(50)  NULL,
    [Direccion] varchar(50)  NULL,
    [IdLocalidad] smallint  NOT NULL,
    [CodigoPostal] int  NULL,
    [IdProvincia] tinyint  NOT NULL,
    [Telefono] varchar(50)  NULL,
    [Fax] varchar(50)  NULL,
    [Email] varchar(50)  NULL,
    [Comision] decimal(7,2)  NULL,
    [IdEmpleado] int  NULL,
    [Cuit] varchar(13)  NULL
);
GO

-- Creating table 'Clientes'
CREATE TABLE [dbo].[Clientes] (
    [IdCliente] int IDENTITY(1,1) NOT NULL,
    [RazonSocial] varchar(100)  NULL,
    [Direccion] varchar(100)  NULL,
    [IdLocalidad] int  NULL,
    [CodigoPostal] varchar(30)  NULL,
    [IdProvincia] int  NULL,
    [IdPais] int  NULL,
    [Telefono] varchar(30)  NULL,
    [Fax] varchar(30)  NULL,
    [Email] varchar(200)  NULL,
    [Cuit] varchar(13)  NULL,
    [IdCodigoIva] tinyint  NULL,
    [FechaAlta] datetime  NULL,
    [Contacto] varchar(50)  NULL,
    [EnviarEmail] tinyint  NULL,
    [DireccionEntrega] varchar(50)  NULL,
    [IdLocalidadEntrega] int  NULL,
    [IdProvinciaEntrega] int  NULL,
    [CodigoCliente] int  NULL,
    [IdCuenta] int  NULL,
    [Saldo] decimal(18,2)  NULL,
    [SaldoDocumentos] decimal(18,2)  NULL,
    [Vendedor1] int  NULL,
    [CreditoMaximo] decimal(18,2)  NULL,
    [IGCondicion] int  NULL,
    [IdCondicionVenta] int  NULL,
    [IdMoneda] int  NULL,
    [IBNumeroInscripcion] varchar(20)  NULL,
    [IBCondicion] int  NULL,
    [TipoCliente] int  NULL,
    [Codigo] varchar(10)  NULL,
    [IdListaPrecios] int  NULL,
    [IdIBCondicionPorDefecto] int  NULL,
    [Confirmado] varchar(2)  NULL,
    [CodigoPresto] varchar(13)  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [Importaciones_NumeroInscripcion] varchar(20)  NULL,
    [Importaciones_DenominacionInscripcion] varchar(10)  NULL,
    [IdCuentaMonedaExt] int  NULL,
    [Cobrador] int  NULL,
    [Auxiliar] varchar(50)  NULL,
    [IdIBCondicionPorDefecto2] int  NULL,
    [IdIBCondicionPorDefecto3] int  NULL,
    [IdEstado] int  NULL,
    [NombreFantasia] varchar(50)  NULL,
    [EsAgenteRetencionIVA] varchar(2)  NULL,
    [BaseMinimaParaPercepcionIVA] decimal(18,2)  NULL,
    [PorcentajePercepcionIVA] decimal(6,2)  NULL,
    [IdUsuarioIngreso] int  NULL,
    [FechaIngreso] datetime  NULL,
    [IdUsuarioModifico] int  NULL,
    [FechaModifico] datetime  NULL,
    [PorcentajeIBDirecto] decimal(6,2)  NULL,
    [FechaInicioVigenciaIBDirecto] datetime  NULL,
    [FechaFinVigenciaIBDirecto] datetime  NULL,
    [GrupoIIBB] int  NULL,
    [IdBancoDebito] int  NULL,
    [CBU] varchar(22)  NULL,
    [PorcentajeIBDirectoCapital] decimal(6,2)  NULL,
    [FechaInicioVigenciaIBDirectoCapital] datetime  NULL,
    [FechaFinVigenciaIBDirectoCapital] datetime  NULL,
    [GrupoIIBBCapital] int  NULL,
    [IdBancoGestionador] int  NULL,
    [ExpresionRegularNoAgruparFacturasConEstosVendedores] varchar(200)  NULL,
    [ExigeDatosCompletosEnCartaDePorteQueLoUse] varchar(2)  NULL,
    [DireccionDeCorreos] varchar(50)  NULL,
    [IdLocalidadDeCorreos] int  NULL,
    [IdProvinciaDeCorreos] int  NULL,
    [CodigoPostalDeCorreos] varchar(30)  NULL,
    [ObservacionesDeCorreos] varchar(150)  NULL,
    [IncluyeTarifaEnFactura] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoTitular] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoIntermediario] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoRemcomercial] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoCorredor] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoDestinatario] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoDestinatarioExportador] varchar(2)  NULL,
    [SeLeDerivaSuFacturaAlCorredorDeLaCarta] varchar(2)  NULL,
    [HabilitadoParaCartaPorte] varchar(2)  NULL,
    [SeLeFacturaCartaPorteComoClienteAuxiliar] varchar(2)  NULL,
    [EsAcondicionadoraDeCartaPorte] varchar(2)  NULL,
    [Contactos] varchar(150)  NULL,
    [TelefonosFijosOficina] varchar(150)  NULL,
    [TelefonosCelulares] varchar(150)  NULL,
    [CorreosElectronicos] varchar(150)  NULL
);
GO

-- Creating table 'DetalleFacturas'
CREATE TABLE [dbo].[DetalleFacturas] (
    [IdDetalleFactura] int IDENTITY(1,1) NOT NULL,
    [IdFactura] int  NULL,
    [NumeroFactura] int  NULL,
    [TipoABC] varchar(1)  NULL,
    [PuntoVenta] int  NULL,
    [IdArticulo] int  NULL,
    [CodigoArticulo] varchar(20)  NULL,
    [Cantidad] decimal(18,2)  NULL,
    [Costo] decimal(19,8)  NULL,
    [PrecioUnitario] decimal(19,8)  NULL,
    [Bonificacion] decimal(6,2)  NULL,
    [IdDetalleRemito] int  NULL,
    [ParteDolar] decimal(18,2)  NULL,
    [PartePesos] decimal(18,2)  NULL,
    [PorcentajeCertificacion] decimal(12,6)  NULL,
    [OrigenDescripcion] int  NULL,
    [TipoCancelacion] int  NULL,
    [IdUnidad] int  NULL,
    [PrecioUnitarioTotal] decimal(18,2)  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [NotaAclaracion] varchar(50)  NULL,
    [EnviarEmail] tinyint  NULL,
    [IdOrigenTransmision] int  NULL,
    [IdFacturaOriginal] int  NULL,
    [IdDetalleFacturaOriginal] int  NULL,
    [FechaImportacionTransmision] datetime  NULL
);
GO

-- Creating table 'Facturas'
CREATE TABLE [dbo].[Facturas] (
    [IdFactura] int IDENTITY(1,1) NOT NULL,
    [NumeroFactura] int  NULL,
    [TipoABC] varchar(1)  NULL,
    [PuntoVenta] int  NULL,
    [IdCliente] int  NULL,
    [FechaFactura] datetime  NULL,
    [IdCondicionVenta] smallint  NULL,
    [IdVendedor] int  NULL,
    [IdTransportista1] tinyint  NULL,
    [IdTransportista2] tinyint  NULL,
    [ItemDireccion] tinyint  NULL,
    [OrdenCompra] varchar(20)  NULL,
    [TipoPedidoConsignacion] varchar(1)  NULL,
    [Anulada] varchar(2)  NULL,
    [FechaAnulacion] datetime  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [IdRemito] int  NULL,
    [NumeroRemito] int  NULL,
    [IdPedido] int  NULL,
    [NumeroPedido] int  NULL,
    [ImporteTotal] decimal(19,2)  NULL,
    [ImporteIva1] decimal(19,2)  NULL,
    [ImporteIva2] decimal(19,2)  NULL,
    [ImporteBonificacion] decimal(19,2)  NULL,
    [RetencionIBrutos1] decimal(19,2)  NULL,
    [PorcentajeIBrutos1] decimal(6,2)  NULL,
    [RetencionIBrutos2] decimal(19,2)  NULL,
    [PorcentajeIBrutos2] decimal(6,2)  NULL,
    [ConvenioMultilateral] varchar(2)  NULL,
    [RetencionIBrutos3] decimal(19,2)  NULL,
    [PorcentajeIBrutos3] decimal(6,2)  NULL,
    [IdTipoVentaC] smallint  NULL,
    [ImporteIvaIncluido] decimal(19,2)  NULL,
    [CotizacionDolar] decimal(18,3)  NULL,
    [EsMuestra] varchar(2)  NULL,
    [CotizacionADolarFijo] decimal(18,3)  NULL,
    [ImporteParteEnDolares] decimal(18,2)  NULL,
    [ImporteParteEnPesos] decimal(18,2)  NULL,
    [PorcentajeIva1] decimal(6,2)  NULL,
    [PorcentajeIva2] decimal(6,2)  NULL,
    [FechaVencimiento] datetime  NULL,
    [IVANoDiscriminado] decimal(18,2)  NULL,
    [IdMoneda] int  NULL,
    [CotizacionMoneda] decimal(18,4)  NULL,
    [PorcentajeBonificacion] decimal(6,2)  NULL,
    [OtrasPercepciones1] decimal(18,2)  NULL,
    [OtrasPercepciones1Desc] varchar(15)  NULL,
    [OtrasPercepciones2] decimal(18,2)  NULL,
    [OtrasPercepciones2Desc] varchar(15)  NULL,
    [IdProvinciaDestino] int  NULL,
    [IdIBCondicion] int  NULL,
    [IdAutorizaAnulacion] int  NULL,
    [IdPuntoVenta] int  NULL,
    [NumeroCAI] decimal(19,0)  NULL,
    [FechaVencimientoCAI] datetime  NULL,
    [NumeroCertificadoPercepcionIIBB] int  NULL,
    [NumeroTicketInicial] int  NULL,
    [NumeroTicketFinal] int  NULL,
    [IdUsuarioIngreso] int  NULL,
    [FechaIngreso] datetime  NULL,
    [IdObra] int  NULL,
    [IdIBCondicion2] int  NULL,
    [IdIBCondicion3] int  NULL,
    [IdCodigoIva] int  NULL,
    [Exportacion_FOB] decimal(18,2)  NULL,
    [Exportacion_PosicionAduana] varchar(20)  NULL,
    [Exportacion_Despacho] varchar(30)  NULL,
    [Exportacion_Guia] varchar(20)  NULL,
    [Exportacion_IdPaisDestino] int  NULL,
    [Exportacion_FechaEmbarque] datetime  NULL,
    [Exportacion_FechaOficializacion] datetime  NULL,
    [OtrasPercepciones3] decimal(18,2)  NULL,
    [OtrasPercepciones3Desc] varchar(15)  NULL,
    [NoIncluirEnCubos] varchar(2)  NULL,
    [PercepcionIVA] decimal(18,2)  NULL,
    [PorcentajePercepcionIVA] decimal(6,2)  NULL,
    [ActivarRecuperoGastos] varchar(2)  NULL,
    [IdAutorizoRecuperoGastos] int  NULL,
    [ContabilizarAFechaVencimiento] varchar(2)  NULL,
    [FacturaContado] varchar(2)  NULL,
    [IdReciboContado] int  NULL,
    [EnviarEmail] int  NULL,
    [IdOrigenTransmision] int  NULL,
    [IdFacturaOriginal] int  NULL,
    [FechaImportacionTransmision] datetime  NULL,
    [CuitClienteTransmision] varchar(13)  NULL,
    [IdReciboContadoOriginal] int  NULL,
    [DevolucionAnticipo] varchar(2)  NULL,
    [PorcentajeDevolucionAnticipo] decimal(12,6)  NULL,
    [CAE] varchar(14)  NULL,
    [RechazoCAE] varchar(11)  NULL,
    [FechaVencimientoORechazoCAE] datetime  NULL,
    [IdListaPrecios] int  NULL,
    [IdIdentificacionCAE] int  NULL,
    [AjusteIva] decimal(18,2)  NULL,
    [TipoExportacion] int  NULL,
    [PermisoEmbarque] varchar(2)  NULL,
    [NumeroFacturaInicial] int  NULL,
    [NumeroFacturaFinal] int  NULL,
    [CodigoIdAuxiliar] int  NULL,
    [NumeroCertificadoObra] int  NULL,
    [ImporteCertificacionObra] decimal(18,2)  NULL,
    [FondoReparoCertificacionObra] decimal(18,2)  NULL,
    [PorcentajeRetencionesEstimadasCertificacionObra] decimal(6,2)  NULL,
    [NumeroExpedienteCertificacionObra] varchar(20)  NULL,
    [NumeroProyecto] int  NULL,
    [IdCertificacionObras] int  NULL,
    [IdCertificacionObraDatos] int  NULL,
    [FechaRecepcionCliente] datetime  NULL
);
GO

-- Creating table 'PuntosVentas'
CREATE TABLE [dbo].[PuntosVentas] (
    [IdPuntoVenta] int IDENTITY(1,1) NOT NULL,
    [Letra] varchar(1)  NULL,
    [PuntoVenta] int  NULL,
    [IdTipoComprobante] int  NULL,
    [ProximoNumero] int  NULL,
    [NumeroCAI_R_A] varchar(20)  NULL,
    [FechaCAI_R_A] datetime  NULL,
    [NumeroCAI_F_A] varchar(20)  NULL,
    [FechaCAI_F_A] datetime  NULL,
    [NumeroCAI_D_A] varchar(50)  NULL,
    [FechaCAI_D_A] datetime  NULL,
    [NumeroCAI_C_A] varchar(20)  NULL,
    [FechaCAI_C_A] datetime  NULL,
    [NumeroCAI_R_B] varchar(20)  NULL,
    [FechaCAI_R_B] datetime  NULL,
    [NumeroCAI_F_B] varchar(20)  NULL,
    [FechaCAI_F_B] datetime  NULL,
    [NumeroCAI_D_B] varchar(20)  NULL,
    [FechaCAI_D_B] datetime  NULL,
    [NumeroCAI_C_B] varchar(20)  NULL,
    [FechaCAI_C_B] datetime  NULL,
    [NumeroCAI_R_E] varchar(20)  NULL,
    [FechaCAI_R_E] datetime  NULL,
    [NumeroCAI_F_E] varchar(20)  NULL,
    [FechaCAI_F_E] datetime  NULL,
    [NumeroCAI_D_E] varchar(20)  NULL,
    [FechaCAI_D_E] datetime  NULL,
    [NumeroCAI_C_E] varchar(20)  NULL,
    [FechaCAI_C_E] datetime  NULL,
    [ProximoNumero1] int  NULL,
    [ProximoNumero2] int  NULL,
    [ProximoNumero3] int  NULL,
    [ProximoNumero4] int  NULL,
    [ProximoNumero5] int  NULL,
    [Descripcion] varchar(50)  NULL,
    [WebService] varchar(5)  NULL,
    [WebServiceModoTest] varchar(2)  NULL,
    [CAEManual] varchar(2)  NULL,
    [Activo] varchar(2)  NULL
);
GO

-- Creating table 'DescripcionIvas'
CREATE TABLE [dbo].[DescripcionIvas] (
    [IdCodigoIva] tinyint IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL,
    [IvaDiscriminado] int  NULL,
    [CodigoAFIP] int  NULL,
    [ExigirCUIT] varchar(2)  NULL,
    [ExigirCAI] varchar(2)  NULL,
    [InformacionAuxiliar] varchar(50)  NULL
);
GO

-- Creating table 'Condiciones_Compras'
CREATE TABLE [dbo].[Condiciones_Compras] (
    [IdCondicionCompra] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL,
    [CantidadDias] int  NULL,
    [CodigoCondicion] varchar(2)  NULL,
    [CantidadDias1] int  NULL,
    [CantidadDias2] int  NULL,
    [CantidadDias3] int  NULL,
    [CantidadDias4] int  NULL,
    [CantidadDias5] int  NULL,
    [CantidadDias6] int  NULL,
    [Porcentaje1] decimal(6,2)  NULL,
    [Porcentaje2] decimal(6,2)  NULL,
    [Porcentaje3] decimal(6,2)  NULL,
    [Porcentaje4] decimal(6,2)  NULL,
    [Porcentaje5] decimal(6,2)  NULL,
    [Porcentaje6] decimal(6,2)  NULL,
    [CantidadDias7] int  NULL,
    [CantidadDias8] int  NULL,
    [CantidadDias9] int  NULL,
    [CantidadDias10] int  NULL,
    [CantidadDias11] int  NULL,
    [CantidadDias12] int  NULL,
    [Porcentaje7] decimal(6,2)  NULL,
    [Porcentaje8] decimal(6,2)  NULL,
    [Porcentaje9] decimal(6,2)  NULL,
    [Porcentaje10] decimal(6,2)  NULL,
    [Porcentaje11] decimal(6,2)  NULL,
    [Porcentaje12] decimal(6,2)  NULL,
    [Observaciones] nvarchar(max)  NULL,
    [Codigo] varchar(10)  NULL
);
GO

-- Creating table 'Ganancias'
CREATE TABLE [dbo].[Ganancias] (
    [IdGanancia] int IDENTITY(1,1) NOT NULL,
    [Desde] decimal(18,2)  NULL,
    [Hasta] decimal(18,2)  NULL,
    [SumaFija] decimal(18,2)  NULL,
    [PorcentajeAdicional] decimal(6,2)  NULL,
    [IdTipoRetencionGanancia] int  NULL,
    [MinimoNoImponible] decimal(18,2)  NULL,
    [MinimoARetener] decimal(18,2)  NULL
);
GO

-- Creating table 'IBCondiciones'
CREATE TABLE [dbo].[IBCondiciones] (
    [IdIBCondicion] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL,
    [ImporteTopeMinimo] decimal(18,2)  NULL,
    [Alicuota] decimal(6,2)  NULL,
    [FechaVigencia] datetime  NULL,
    [AcumulaMensualmente] varchar(2)  NULL,
    [BaseCalculo] varchar(15)  NULL,
    [AlicuotaPercepcion] decimal(8,3)  NULL,
    [IdProvincia] int  NULL,
    [ImporteTopeMinimoPercepcion] decimal(18,2)  NULL,
    [AlicuotaPercepcionConvenio] decimal(8,3)  NULL,
    [IdCuentaPercepcionIIBB] int  NULL,
    [IdCuentaPercepcionIIBBConvenio] int  NULL,
    [PorcentajeATomarSobreBase] decimal(6,2)  NULL,
    [PorcentajeAdicional] decimal(6,2)  NULL,
    [LeyendaPorcentajeAdicional] varchar(50)  NULL,
    [Codigo] int  NULL,
    [CodigoAFIP] int  NULL,
    [InformacionAuxiliar] varchar(50)  NULL,
    [IdCuentaPercepcionIIBBCompras] int  NULL,
    [IdProvinciaReal] varchar(2)  NULL,
    [CodigoNormaRetencion] int  NULL,
    [CodigoNormaPercepcion] int  NULL,
    [CodigoActividad] int  NULL,
    [Alícuota] decimal(8,3)  NULL
);
GO

-- Creating table 'IGCondiciones'
CREATE TABLE [dbo].[IGCondiciones] (
    [IdIGCondicion] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL
);
GO

-- Creating table 'ListasPrecios'
CREATE TABLE [dbo].[ListasPrecios] (
    [IdListaPrecios] int IDENTITY(1,1) NOT NULL,
    [Descripcion] varchar(50)  NULL,
    [NumeroLista] int  NULL,
    [FechaVigencia] datetime  NULL,
    [Activa] varchar(2)  NULL,
    [IdMoneda] int  NULL
);
GO

-- Creating table 'ListasPreciosDetalles'
CREATE TABLE [dbo].[ListasPreciosDetalles] (
    [IdListaPreciosDetalle] int IDENTITY(1,1) NOT NULL,
    [IdListaPrecios] int  NULL,
    [IdArticulo] int  NULL,
    [Precio] decimal(18,2)  NULL,
    [IdDestinoDeCartaDePorte] int  NULL,
    [PrecioDescargaLocal] decimal(19,4)  NULL,
    [PrecioDescargaExportacion_] decimal(19,4)  NULL,
    [PrecioCaladaLocal_] decimal(19,4)  NULL,
    [PrecioCaladaExportacion__] decimal(19,4)  NULL,
    [PrecioRepetidoPeroConPrecision__] decimal(19,4)  NULL,
    [PrecioExportacion] decimal(19,4)  NULL,
    [PrecioEmbarque] decimal(19,4)  NULL
);
GO


alter TABLE [dbo].detallerequerimientos  add
  [ObservacionesFirmante]          NTEXT           NULL,
  [IdFirmanteObservo]              INT             NULL,
    [FechaUltimaObservacionFirmante] DATETIME        NULL
	


