CREATE  Procedure [dbo].[Articulos_M]

@IdArticulo int,
@IdRubro int,
@IdSubrubro int,
@IdFamilia int,
@Descripcion varchar(256),
@Productivo varchar(2),
@Ancho numeric(18,3),
@IdCalidad int,
@Diametro varchar(10),
@Espesor numeric(18,3),
@IdGrado int,
@Largo numeric(18,3),
@IdMaterial int,
@IdAcabado int,
@IdTipo int,
@Serie varchar(50),
@IdTratamiento int,
@IdUnidad int,
@Autorizacion varchar(2),
@IdInventario tinyint,
@IdCuenta int,
@IdScheduler int,
@Unidad1 int,
@Unidad2 int,
@Unidad3 int,
@Unidad4 int,
@Unidad5 int,
@Unidad6 int,
@Unidad7 int,
@Unidad8 int,
@Unidad9 int,
@Unidad10 int,
@Peso numeric(18,3),
@DiametroInterno numeric(18,2),
@IdCodigoUniversal int,
@IdRelacion int,
@IdForma int,
@IdSerie int,
@Altura numeric(18,2),
@Diametro2 numeric(18,2),
@IdColor int,
@IdNorma int,
@Capacidad numeric(18,2),
@Potencia numeric(18,2),
@IdRango int,
@IdAlimentacionElectrica int,
@IdModelo int,
@IdMarca int,
@IdAnioNorma int,
@Unidad11 int,
@Unidad12 int,
@Unidad13 int,
@Unidad14 int,
@Unidad15 int,
@IdCuantificacion int,
@IdControlCalidad int,
@IdCodigo int,
@Charpy varchar(2),
@IdCentroCosto int,
@UsuarioAlta varchar(50),
@FechaAlta datetime,
@FechaUltimaModificacion datetime,
@EspesorBase numeric(18,3),
@EspesorRevestimiento numeric(18,3),
@IdCalidadBase int,
@IdCalidadRevestimiento int,
@IdGradoBase int,
@IdGradoRevestimiento int,
@IdBiselado int,
@IdCalidadClad int,
@IdTipoRosca int,
@IdDensidad int,
@Rpm int,
@Datos1 numeric(18,0),
@Datos2 numeric(18,0),
@Datos3 numeric(18,0),
@Datos4 numeric(18,0),
@Datos5 numeric(18,0),
@Datos6 numeric(18,0),
@Datos7 numeric(18,0),
@Datos8 numeric(18,0),
@Datos9 numeric(18,0),
@Datos10 numeric(18,0),
@Unidad16 int,
@Unidad17 int,
@Unidad18 int,
@Unidad19 int,
@Unidad20 int,
@EnviarEmail tinyint,
@Codigo varchar(20),
@RegistrarStock varchar(2),
@StockMinimo numeric(18,2),
@DefineKit varchar(2),
@CostoPPP numeric(18,4),
@AlicuotaIVA numeric(6,2),
@CostoPPPDolar numeric(18,4),
@IdUbicacionStandar int,
@CostoReposicion numeric(18,2),
@CostoReposicionDolar numeric(18,2),
@Direccion varchar(50),
@IdLocalidad int,
@IdProvincia int,
@IdPais int,
@CodigoPostal varchar(20),
@NumeroManzana varchar(20),
@NumeroLote int,
@ActivoFijo varchar(2),
@EstadoActivoFijo varchar(2),
@NumeroActivoFijo int,
@IdGrupoActivoFijo int,
@BienImpositivo varchar(2),
@BienContable varchar(2),
@Amortiza varchar(2),
@FechaCompra datetime,
@IdCuentaAmortizacion int,
@VidaUtilImpositiva int,
@VidaUtilContable int,
@ValorOrigenContable numeric(19,6),
@ValorOrigenImpositivo numeric(19,6),
@ValorActualizado numeric(19,2),
@ValorResidual numeric(19,2),
@ValorResidualActualizado numeric(19,2),
@AmortizacionEjercicio numeric(19,2),
@AmortizacionEjercicioActualizada numeric(19,2),
@AmortizacionesAcumuladas numeric(19,2),
@AmortizacionesAcumuladasActualizada numeric(19,2),
@VidaUtilImpositivaRestante int,
@VidaUtilContableRestante int,
@FechaPrimeraAmortizacionImpositiva datetime,
@FechaPrimeraAmortizacionContable datetime,
@IdUbicacionActivoFijo int,
@IdSector int,
@FechaBajaAmortizacion datetime,
@ParaMantenimiento varchar(2),
@IdUnidadLecturaMantenimiento int,
@LecturaAcumulada numeric(19,2),
@LecturaBase numeric(19,2),
@UltimaLectura numeric(19,2),
@FechaUltimaLectura datetime,
@EstimadoAnual numeric(19,2),
@NumeroInventario varchar(20),
@ModeloMotor varchar(30),
@EquipoEnObra varchar(2),
@EstadoEquipo varchar(2),
@EsConsumible varchar(2),
@FechaUltimaModificacionArticulo datetime,
@EntidadOrigen varchar(50),
@ComprobanteCompra varchar(20),
@ModeloEspecifico varchar(20),
@NumeroPatente varchar(20),
@NumeroMotor varchar(20),
@NumeroChasis varchar(30),
@AñoFabricacion int,
@AñosAmortizacion int,
@AñoAlta int,
@Caracteristicas varchar(70),
@NumeroGarantia varchar(50),
@FechaCaducidadGarantia datetime,
@TipoCoberturaSeguro varchar(50),
@NumeroPolizaSeguro numeric(18,0),@CompañiaSeguro varchar(30),
@FechaVigenciaSeguro datetime,
@FechaVencimientoVerificacionTecnica datetime,
@CalculaAmortizacion varchar(2),
@UltimoRevaluoContable numeric(18,2),
@FechaUltimoRevaluo datetime,
@CodigoLoteo varchar(20),
@Adrema varchar(20),
@Observaciones ntext,
@ConsumoStandarCombustible numeric(18,2),
@UbicacionActivoFijo varchar(20),
@CalculaValorActualizado varchar(2),
@ParaPRONTO_MANTENIMIENTO varchar(2),
@PosicionAduana varchar(20),
@Alquilado varchar(2),
@IdMarcaMotor int,
@NumeroSerieMotor varchar(20),
@VidaUtilTecnica int,
@ValorCompra numeric(18,2),
@IdMonedaCompra int,
@FechaBaja datetime,
@DocumentoAlta varchar(20),
@DocumentoBaja varchar(20),
@IdArticuloAsociado int,
@RegistroUnicoTransporteAutomotor numeric(16,0),
@TieneGPS varchar(2),
@CondicionActual varchar(2),
@SituacionActual varchar(2),
@Activo varchar(2),
@Auxiliar1 int,
@Auxiliar2 int,
@Auxiliar3 int,
@Auxiliar4 int,
@Auxiliar5 int,
@Auxiliar6 int,
@Auxiliar7 int,
@Auxiliar8 int,
@Auxiliar9 int,
@Auxiliar10 int,
@Auxiliar11 int,
@Auxiliar12 int,
@Auxiliar13 int,
@Auxiliar14 int,
@Auxiliar15 int,
@Auxiliar16 int,
@Auxiliar17 int,
@Auxiliar18 int,
@Auxiliar19 int,
@Auxiliar20 int,
@Auxiliar21 int,
@Auxiliar22 int,
@Auxiliar23 int,
@Auxiliar24 int,
@Auxiliar25 int,
@AuxiliarString1 varchar(50),
@AuxiliarString2 varchar(50),
@AuxiliarString3 varchar(50),
@AuxiliarString4 varchar(50),
@AuxiliarString5 varchar(50),
@AuxiliarString6 varchar(50),
@AuxiliarString7 varchar(50),
@AuxiliarString8 varchar(50),
@AuxiliarString9 varchar(50),
@AuxiliarString10 varchar(50),
@CodigoAlternativo varchar(50),
@IdCuentaCompras int,
@StockReposicion numeric(18,2),
@MarcaStock varchar(1),
@CostoInicial numeric(18,3),
@ConsumirPorOT varchar(2),
@IdTransportista int,
@IdTipoEquipo int,
@Replica varchar(2),
@IdPresupuestoObraRubro int,
@IdTipoArticulo int,
@FechaUltimoCostoReposicion datetime,
@ADistribuirEnPresupuestoDeObra varchar(2),
@IdCuentaComprasActivo int,
@AuxiliarNumerico1 numeric(18,2),
@AuxiliarNumerico2 numeric(18,2),
@AuxiliarNumerico3 numeric(18,2),
@AuxiliarNumerico4 numeric(18,2),
@AuxiliarNumerico5 numeric(18,2),
@IdCurvaTalle int,
@Curva varchar(50),
@GenerarConsumosAutomaticamente varchar(2),
@TalleCambioPrecio varchar(2),
@TalleCambioPrecio2 varchar(2)

AS

UPDATE Articulos
SET 
 IdRubro=@IdRubro,
 IdSubrubro=@IdSubrubro,
 IdFamilia=@IdFamilia,
 Descripcion=@Descripcion,
 Productivo=@Productivo,
 Ancho=@Ancho,
 IdCalidad=@IdCalidad,
 Diametro=@Diametro,
 Espesor=@Espesor,
 IdGrado=@IdGrado,
 Largo=@Largo,
 IdMaterial=@IdMaterial,
 IdAcabado=@IdAcabado,
 IdTipo=@IdTipo,
 Serie=@Serie,
 IdTratamiento=@IdTratamiento,
 IdUnidad=@IdUnidad,
 Autorizacion=@Autorizacion,
 IdInventario=@IdInventario,
 IdCuenta=@IdCuenta,
 IdScheduler=@IdScheduler,
 Unidad1=@Unidad1,
 Unidad2=@Unidad2,
 Unidad3=@Unidad3,
 Unidad4=@Unidad4,
 Unidad5=@Unidad5,
 Unidad6=@Unidad6,
 Unidad7=@Unidad7,
 Unidad8=@Unidad8,
 Unidad9=@Unidad9,
 Unidad10=@Unidad10,
 Peso=@Peso,
 DiametroInterno=@DiametroInterno,
 IdCodigoUniversal=@IdCodigoUniversal,
 IdRelacion=@IdRelacion,
 IdForma=@IdForma,
 IdSerie=@IdSerie,
 Altura=@Altura,
 Diametro2=@Diametro2,
 IdColor=@IdColor,
 IdNorma=@IdNorma,
 Capacidad=@Capacidad,
 Potencia=@Potencia,
 IdRango=@IdRango,
 IdAlimentacionElectrica=@IdAlimentacionElectrica,
 IdModelo=@IdModelo,
 IdMarca=@IdMarca,
 IdAnioNorma=@IdAnioNorma,
 Unidad11=@Unidad11,
 Unidad12=@Unidad12,
 Unidad13=@Unidad13,
 Unidad14=@Unidad14,
 Unidad15=@Unidad15,
 IdCuantificacion=@IdCuantificacion,
 IdControlCalidad=@IdControlCalidad,
 IdCodigo=@IdCodigo,
 Charpy=@Charpy,
 IdCentroCosto=@IdCentroCosto,
 UsuarioAlta=@UsuarioAlta,
 FechaAlta=@FechaAlta,
 FechaUltimaModificacion=@FechaUltimaModificacion,
 EspesorBase=@EspesorBase,
 EspesorRevestimiento=@EspesorRevestimiento,
 IdCalidadBase=@IdCalidadBase,
 IdCalidadRevestimiento=@IdCalidadRevestimiento,
 IdGradoBase=@IdGradoBase,
 IdGradoRevestimiento=@IdGradoRevestimiento,
 IdBiselado=@IdBiselado,
 IdCalidadClad=@IdCalidadClad,
 IdTipoRosca=@IdTipoRosca,
 IdDensidad=@IdDensidad,
 Rpm=@Rpm,
 Datos1=@Datos1,
 Datos2=@Datos2,
 Datos3=@Datos3,
 Datos4=@Datos4,
 Datos5=@Datos5,
 Datos6=@Datos6,
 Datos7=@Datos7,
 Datos8=@Datos8,
 Datos9=@Datos9,
 Datos10=@Datos10,
 Unidad16=@Unidad16,
 Unidad17=@Unidad17,
 Unidad18=@Unidad18,
 Unidad19=@Unidad19,
 Unidad20=@Unidad20,
 EnviarEmail=@EnviarEmail,
 Codigo=@Codigo,
 RegistrarStock=@RegistrarStock,
 StockMinimo=@StockMinimo,
 DefineKit=@DefineKit,
 CostoPPP=@CostoPPP,
 AlicuotaIVA=@AlicuotaIVA,
 CostoPPPDolar=@CostoPPPDolar,
 IdUbicacionStandar=@IdUbicacionStandar,
 CostoReposicion=@CostoReposicion,
 CostoReposicionDolar=@CostoReposicionDolar,
 Direccion=@Direccion,
 IdLocalidad=@IdLocalidad,
 IdProvincia=@IdProvincia,
 IdPais=@IdPais,
 CodigoPostal=@CodigoPostal,
 NumeroManzana=@NumeroManzana,
 NumeroLote=@NumeroLote,
 ActivoFijo=@ActivoFijo,
 EstadoActivoFijo=@EstadoActivoFijo,
 NumeroActivoFijo=@NumeroActivoFijo,
 IdGrupoActivoFijo=@IdGrupoActivoFijo,
 BienImpositivo=@BienImpositivo,
 BienContable=@BienContable,
 Amortiza=@Amortiza,
 FechaCompra=@FechaCompra,
 IdCuentaAmortizacion=@IdCuentaAmortizacion,
 VidaUtilImpositiva=@VidaUtilImpositiva,
 VidaUtilContable=@VidaUtilContable,
 ValorOrigenContable=@ValorOrigenContable,
 ValorOrigenImpositivo=@ValorOrigenImpositivo,
 ValorActualizado=@ValorActualizado,
 ValorResidual=@ValorResidual,
 ValorResidualActualizado=@ValorResidualActualizado,
 AmortizacionEjercicio=@AmortizacionEjercicio,
 AmortizacionEjercicioActualizada=@AmortizacionEjercicioActualizada,
 AmortizacionesAcumuladas=@AmortizacionesAcumuladas,
 AmortizacionesAcumuladasActualizada=@AmortizacionesAcumuladasActualizada,
 VidaUtilImpositivaRestante=@VidaUtilImpositivaRestante,
 VidaUtilContableRestante=@VidaUtilContableRestante,
 FechaPrimeraAmortizacionImpositiva=@FechaPrimeraAmortizacionImpositiva,
 FechaPrimeraAmortizacionContable=@FechaPrimeraAmortizacionContable,
 IdUbicacionActivoFijo=@IdUbicacionActivoFijo, IdSector=@IdSector,
 FechaBajaAmortizacion=@FechaBajaAmortizacion,
 ParaMantenimiento=@ParaMantenimiento,
 IdUnidadLecturaMantenimiento=@IdUnidadLecturaMantenimiento,
 LecturaAcumulada=@LecturaAcumulada,
 LecturaBase=@LecturaBase,
 UltimaLectura=@UltimaLectura,
 FechaUltimaLectura=@FechaUltimaLectura,
 EstimadoAnual=@EstimadoAnual,
 NumeroInventario=@NumeroInventario,
 ModeloMotor=@ModeloMotor,
 EquipoEnObra=@EquipoEnObra,
 EstadoEquipo=@EstadoEquipo,
 EsConsumible=@EsConsumible,
 FechaUltimaModificacionArticulo=@FechaUltimaModificacionArticulo,
 EntidadOrigen=@EntidadOrigen,
 ComprobanteCompra=@ComprobanteCompra,
 ModeloEspecifico=@ModeloEspecifico,
 NumeroPatente=@NumeroPatente,
 NumeroMotor=@NumeroMotor,
 NumeroChasis=@NumeroChasis,
 AñoFabricacion=@AñoFabricacion,
 AñosAmortizacion=@AñosAmortizacion,
 AñoAlta=@AñoAlta,
 Caracteristicas=@Caracteristicas,
 NumeroGarantia=@NumeroGarantia,
 FechaCaducidadGarantia=@FechaCaducidadGarantia,
 TipoCoberturaSeguro=@TipoCoberturaSeguro,
 NumeroPolizaSeguro=@NumeroPolizaSeguro,
 CompañiaSeguro=@CompañiaSeguro,
 FechaVigenciaSeguro=@FechaVigenciaSeguro,
 FechaVencimientoVerificacionTecnica=@FechaVencimientoVerificacionTecnica,
 CalculaAmortizacion=@CalculaAmortizacion,
 UltimoRevaluoContable=@UltimoRevaluoContable,
 FechaUltimoRevaluo=@FechaUltimoRevaluo,
 CodigoLoteo=@CodigoLoteo,
 Adrema=@Adrema,
 Observaciones=@Observaciones,
 ConsumoStandarCombustible=@ConsumoStandarCombustible,
 UbicacionActivoFijo=@UbicacionActivoFijo,
 CalculaValorActualizado=@CalculaValorActualizado,
 ParaPRONTO_MANTENIMIENTO=@ParaPRONTO_MANTENIMIENTO,
 PosicionAduana=@PosicionAduana,
 Alquilado=@Alquilado,
 IdMarcaMotor=@IdMarcaMotor,
 NumeroSerieMotor=@NumeroSerieMotor,
 VidaUtilTecnica=@VidaUtilTecnica,
 ValorCompra=@ValorCompra,
 IdMonedaCompra=@IdMonedaCompra,
 FechaBaja=@FechaBaja,
 DocumentoAlta=@DocumentoAlta,
 DocumentoBaja=@DocumentoBaja,
 IdArticuloAsociado=@IdArticuloAsociado,
 RegistroUnicoTransporteAutomotor=@RegistroUnicoTransporteAutomotor,
 TieneGPS=@TieneGPS,
 CondicionActual=@CondicionActual,
 SituacionActual=@SituacionActual,
 Activo=@Activo,
 Auxiliar1=@Auxiliar1,
 Auxiliar2=@Auxiliar2,
 Auxiliar3=@Auxiliar3,
 Auxiliar4=@Auxiliar4,
 Auxiliar5=@Auxiliar5,
 Auxiliar6=@Auxiliar6,
 Auxiliar7=@Auxiliar7,
 Auxiliar8=@Auxiliar8,
 Auxiliar9=@Auxiliar9, Auxiliar10=@Auxiliar10,
 Auxiliar11=@Auxiliar11,
 Auxiliar12=@Auxiliar12,
 Auxiliar13=@Auxiliar13,
 Auxiliar14=@Auxiliar14,
 Auxiliar15=@Auxiliar15,
 Auxiliar16=@Auxiliar16,
 Auxiliar17=@Auxiliar17,
 Auxiliar18=@Auxiliar18,
 Auxiliar19=@Auxiliar19,
 Auxiliar20=@Auxiliar20,
 Auxiliar21=@Auxiliar21,
 Auxiliar22=@Auxiliar22,
 Auxiliar23=@Auxiliar23,
 Auxiliar24=@Auxiliar24,
 Auxiliar25=@Auxiliar25,
 AuxiliarString1=@AuxiliarString1,
 AuxiliarString2=@AuxiliarString2,
 AuxiliarString3=@AuxiliarString3,
 AuxiliarString4=@AuxiliarString4,
 AuxiliarString5=@AuxiliarString5,
 AuxiliarString6=@AuxiliarString6,
 AuxiliarString7=@AuxiliarString7,
 AuxiliarString8=@AuxiliarString8,
 AuxiliarString9=@AuxiliarString9,
 AuxiliarString10=@AuxiliarString10,
 CodigoAlternativo=@CodigoAlternativo,
 IdCuentaCompras=@IdCuentaCompras,
 StockReposicion=@StockReposicion,
 MarcaStock=@MarcaStock,
 CostoInicial=@CostoInicial,
 ConsumirPorOT=@ConsumirPorOT,
 IdTransportista=@IdTransportista,
 IdTipoEquipo=@IdTipoEquipo, 
 Replica=@Replica,
 IdPresupuestoObraRubro=@IdPresupuestoObraRubro,
 IdTipoArticulo=@IdTipoArticulo,
 FechaUltimoCostoReposicion =@FechaUltimoCostoReposicion,
 ADistribuirEnPresupuestoDeObra=@ADistribuirEnPresupuestoDeObra,
 IdCuentaComprasActivo=@IdCuentaComprasActivo,
 AuxiliarNumerico1=@AuxiliarNumerico1,
 AuxiliarNumerico2=@AuxiliarNumerico2,
 AuxiliarNumerico3=@AuxiliarNumerico3,
 AuxiliarNumerico4=@AuxiliarNumerico4,
 AuxiliarNumerico5=@AuxiliarNumerico5,
 IdCurvaTalle=@IdCurvaTalle,
 Curva=@Curva,
 GenerarConsumosAutomaticamente=@GenerarConsumosAutomaticamente,
 TalleCambioPrecio=@TalleCambioPrecio,
 TalleCambioPrecio2=@TalleCambioPrecio2
WHERE (IdArticulo=@IdArticulo)

RETURN(@IdArticulo)