CREATE Procedure [dbo].[CertificacionesObrasDatos_A]

@IdCertificacionObraDatos int output,
@NumeroProyecto int,
@NumeroCertificado int,
@IdCliente int,
@Fecha datetime,
@FechaInicio datetime,
@FechaFinalizacion datetime,
@Adjunto1 varchar(100),
@Adjunto2 varchar(100),
@Adjunto3 varchar(100),
@Adjunto4 varchar(100),
@Adjunto5 varchar(100),
@Adjunto6 varchar(100),
@Adjunto7 varchar(100),
@Adjunto8 varchar(100),
@Adjunto9 varchar(100),
@Adjunto10 varchar(100),
@CondicionPago varchar(50),
@AnticipoFinanciero varchar(50),
@Acopio varchar(50),
@FondoReparo numeric(6,2),
@PorcentajeRetencionesEstimadas numeric(6,2),
@IdMoneda int,
@Observaciones ntext,
@Anulado varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@NumeroExpediente varchar(20),
@FechaVencimiento datetime,
@FechaCesionBanco datetime,
@FechaCancelacionCesion datetime,
@IdBanco int,
@Version varchar(10),
@IdAprobo int,
@CircuitoFirmasCompleto varchar(2)

AS 

INSERT INTO [CertificacionesObrasDatos]
(
 NumeroProyecto,
 NumeroCertificado,
 IdCliente,
 Fecha,
 FechaInicio,
 FechaFinalizacion,
 Adjunto1,
 Adjunto2,
 Adjunto3,
 Adjunto4,
 Adjunto5,
 Adjunto6,
 Adjunto7,
 Adjunto8,
 Adjunto9,
 Adjunto10,
 CondicionPago,
 AnticipoFinanciero,
 Acopio,
 FondoReparo,
 PorcentajeRetencionesEstimadas,
 IdMoneda,
 Observaciones,
 Anulado,
 IdUsuarioAnulo,
 FechaAnulacion,
 MotivoAnulacion,
 NumeroExpediente,
 FechaVencimiento,
 FechaCesionBanco,
 FechaCancelacionCesion,
 IdBanco,
 Version,
 IdAprobo,
 CircuitoFirmasCompleto
)
VALUES
(
 @NumeroProyecto,
 @NumeroCertificado,
 @IdCliente,
 @Fecha,
 @FechaInicio,
 @FechaFinalizacion,
 @Adjunto1,
 @Adjunto2,
 @Adjunto3,
 @Adjunto4,
 @Adjunto5,
 @Adjunto6,
 @Adjunto7,
 @Adjunto8,
 @Adjunto9,
 @Adjunto10,
 @CondicionPago,
 @AnticipoFinanciero,
 @Acopio,
 @FondoReparo,
 @PorcentajeRetencionesEstimadas,
 @IdMoneda,
 @Observaciones,
 @Anulado,
 @IdUsuarioAnulo,
 @FechaAnulacion,
 @MotivoAnulacion,
 @NumeroExpediente,
 @FechaVencimiento,
 @FechaCesionBanco,
 @FechaCancelacionCesion,
 @IdBanco,
 @Version,
 @IdAprobo,
 @CircuitoFirmasCompleto
)

SELECT @IdCertificacionObraDatos=@@identity

RETURN(@IdCertificacionObraDatos)