CREATE Procedure [dbo].[ComprobantesProveedores_M]

@IdComprobanteProveedor int,
@IdProveedor int,
@IdTipoComprobante int,
@FechaComprobante datetime,
@Letra varchar(1),
@NumeroComprobante1 int,
@NumeroComprobante2 int,
@NumeroReferencia int,
@FechaRecepcion datetime,
@FechaVencimiento datetime,
@TotalBruto numeric(12,2),
@TotalIva1 numeric(12,2),
@TotalIva2 numeric(12,2),
@TotalBonificacion numeric(12,2),
@TotalComprobante numeric(12,2),
@PorcentajeBonificacion numeric(6,2),
@Observaciones ntext,
@DiasVencimiento int,
@IdObra int,
@IdProveedorEventual int,
@IdOrdenPago int,
@IdCuenta int,
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@CotizacionDolar numeric(18,4),
@TotalIVANoDiscriminado numeric(18,2),
@IdCuentaIvaCompras1 int,
@IVAComprasPorcentaje1 numeric(6,2),
@IVAComprasImporte1 numeric(18,2),
@IdCuentaIvaCompras2 int,
@IVAComprasPorcentaje2 numeric(6,2),
@IVAComprasImporte2 numeric(18,2),
@IdCuentaIvaCompras3 int,
@IVAComprasPorcentaje3 numeric(6,2),
@IVAComprasImporte3 numeric(18,2),
@IdCuentaIvaCompras4 int,
@IVAComprasPorcentaje4 numeric(6,2),
@IVAComprasImporte4 numeric(18,2),
@IdCuentaIvaCompras5 int,
@IVAComprasPorcentaje5 numeric(6,2),
@IVAComprasImporte5 numeric(18,2),
@IdCuentaIvaCompras6 int,
@IVAComprasPorcentaje6 numeric(6,2),
@IVAComprasImporte6 numeric(18,2),
@IdCuentaIvaCompras7 int,
@IVAComprasPorcentaje7 numeric(6,2),
@IVAComprasImporte7 numeric(18,2),
@IdCuentaIvaCompras8 int,
@IVAComprasPorcentaje8 numeric(6,2),
@IVAComprasImporte8 numeric(18,2),
@IdCuentaIvaCompras9 int,
@IVAComprasPorcentaje9 numeric(6,2),
@IVAComprasImporte9 numeric(18,2),
@IdCuentaIvaCompras10 int,
@IVAComprasPorcentaje10 numeric(6,2),
@IVAComprasImporte10 numeric(18,2),
@SubtotalGravado numeric(18,2),
@SubtotalExento numeric(18,2),
@AjusteIVA numeric(18,2),
@PorcentajeIVAAplicacionAjuste numeric(6,2),
@BienesOServicios varchar(1),
@IdDetalleOrdenPagoRetencionIVAAplicada int,
@IdIBCondicion int,
@PRESTOFactura varchar(13),
@Confirmado varchar(2),
@IdProvinciaDestino int,
@IdTipoRetencionGanancia int,
@NumeroCAI varchar(20),
@FechaVencimientoCAI datetime,
@IdCodigoAduana int,
@IdCodigoDestinacion int,
@NumeroDespacho int,
@DigitoVerificadorNumeroDespacho varchar(1),
@FechaDespachoAPlaza datetime,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@PRESTOProveedor varchar(13),
@IdCodigoIva int,
@CotizacionEuro numeric(18,4),
@IdCondicionCompra int,
@Importacion_FOB numeric(18,2),
@Importacion_PosicionAduana varchar(20),
@Importacion_Despacho varchar(30),
@Importacion_Guia varchar(20),
@Importacion_IdPaisOrigen int,
@Importacion_FechaEmbarque datetime,
@Importacion_FechaOficializacion datetime,
@REP_CTAPRO_INS varchar(1),
@REP_CTAPRO_UPD varchar(1),
@InformacionAuxiliar varchar(50),
@GravadoParaSUSS numeric(18,2),
@PorcentajeParaSUSS numeric(6,2),
@FondoReparo numeric(18,2),
@AutoincrementarNumeroReferencia varchar(2),
@ReintegroImporte numeric(18,2),
@ReintegroDespacho varchar(20),
@ReintegroIdMoneda int,
@ReintegroIdCuenta int,
@PrestoDestino varchar(20),
@IdFacturaVenta_RecuperoGastos int,
@IdNotaCreditoVenta_RecuperoGastos int,
@IdComprobanteImputado int,
@IdCuentaOtros int,
@PRESTOFechaProceso datetime,
@DestinoPago varchar(1),
@NumeroRendicionFF int,
@Cuit varchar(13),
@FechaAsignacionPresupuesto datetime,
@Dolarizada varchar(2),
@NumeroOrdenPagoFondoReparo int,
@IdListaPrecios int,
@IdComprobanteProveedorOriginal int,
@PorcentajeIVAParaMonotributistas numeric(6,2),
@IdDiferenciaCambio int,
@TomarEnCuboDeGastos varchar(2),
@ConfirmadoPorWeb varchar(2),
@CircuitoFirmasCompleto varchar(2),
@IdLiquidacionFlete int,
@NumeroCAE varchar(20),
@IdImpuestoDirecto int,
@IdPoliza int,
@NumeroCuotaPoliza int,
@IdOrdenPagoRetencionIva int,
@ImporteRetencionIvaEnOrdenPago numeric(18,2),
@DebitoAutomatico varchar(2),
@FechaPrestacionServicio datetime,
@IdTipoOperacion int,
@ArchivoAdjunto1 varchar(200),
@ArchivoAdjunto2 varchar(200)

AS

UPDATE ComprobantesProveedores
SET 
 IdProveedor=@IdProveedor,
 IdTipoComprobante=@IdTipoComprobante,
 FechaComprobante=@FechaComprobante,
 Letra=@Letra,
 NumeroComprobante1=@NumeroComprobante1,
 NumeroComprobante2=@NumeroComprobante2,
 NumeroReferencia=@NumeroReferencia,
 FechaRecepcion=@FechaRecepcion,
 FechaVencimiento=@FechaVencimiento,
 TotalBruto=@TotalBruto,
 TotalIva1=@TotalIva1,
 TotalIva2=@TotalIva2,
 TotalBonificacion=@TotalBonificacion,
 TotalComprobante=@TotalComprobante,
 PorcentajeBonificacion=@PorcentajeBonificacion,
 Observaciones=@Observaciones,
 DiasVencimiento=@DiasVencimiento,
 IdObra=@IdObra, IdProveedorEventual=@IdProveedorEventual,
 IdOrdenPago=@IdOrdenPago,
 IdCuenta=@IdCuenta,
 IdMoneda=@IdMoneda,
 CotizacionMoneda=@CotizacionMoneda,
 CotizacionDolar=@CotizacionDolar,
 TotalIVANoDiscriminado=@TotalIVANoDiscriminado,
 IdCuentaIvaCompras1=@IdCuentaIvaCompras1,
 IVAComprasPorcentaje1=@IVAComprasPorcentaje1,
 IVAComprasImporte1=@IVAComprasImporte1,
 IdCuentaIvaCompras2=@IdCuentaIvaCompras2,
 IVAComprasPorcentaje2=@IVAComprasPorcentaje2,
 IVAComprasImporte2=@IVAComprasImporte2,
 IdCuentaIvaCompras3=@IdCuentaIvaCompras3,
 IVAComprasPorcentaje3=@IVAComprasPorcentaje3,
 IVAComprasImporte3=@IVAComprasImporte3,
 IdCuentaIvaCompras4=@IdCuentaIvaCompras4,
 IVAComprasPorcentaje4=@IVAComprasPorcentaje4,
 IVAComprasImporte4=@IVAComprasImporte4,
 IdCuentaIvaCompras5=@IdCuentaIvaCompras5,
 IVAComprasPorcentaje5=@IVAComprasPorcentaje5,
 IVAComprasImporte5=@IVAComprasImporte5,
 IdCuentaIvaCompras6=@IdCuentaIvaCompras6, IVAComprasPorcentaje6=@IVAComprasPorcentaje6,
 IVAComprasImporte6=@IVAComprasImporte6,
 IdCuentaIvaCompras7=@IdCuentaIvaCompras7,
 IVAComprasPorcentaje7=@IVAComprasPorcentaje7,
 IVAComprasImporte7=@IVAComprasImporte7,
 IdCuentaIvaCompras8=@IdCuentaIvaCompras8,
 IVAComprasPorcentaje8=@IVAComprasPorcentaje8,
 IVAComprasImporte8=@IVAComprasImporte8,
 IdCuentaIvaCompras9=@IdCuentaIvaCompras9,
 IVAComprasPorcentaje9=@IVAComprasPorcentaje9,
 IVAComprasImporte9=@IVAComprasImporte9,
 IdCuentaIvaCompras10=@IdCuentaIvaCompras10,
 IVAComprasPorcentaje10=@IVAComprasPorcentaje10,
 IVAComprasImporte10=@IVAComprasImporte10,
 SubtotalGravado=@SubtotalGravado,
 SubtotalExento=@SubtotalExento,
 AjusteIVA=@AjusteIVA,
 PorcentajeIVAAplicacionAjuste=@PorcentajeIVAAplicacionAjuste,
 BienesOServicios=@BienesOServicios,
 IdDetalleOrdenPagoRetencionIVAAplicada=@IdDetalleOrdenPagoRetencionIVAAplicada,
 IdIBCondicion=@IdIBCondicion,
 PRESTOFactura=@PRESTOFactura,
 Confirmado=@Confirmado,
 IdProvinciaDestino=@IdProvinciaDestino,
 IdTipoRetencionGanancia=@IdTipoRetencionGanancia,
 NumeroCAI=@NumeroCAI,
 FechaVencimientoCAI=@FechaVencimientoCAI,
 IdCodigoAduana=@IdCodigoAduana,
 IdCodigoDestinacion=@IdCodigoDestinacion,
 NumeroDespacho=@NumeroDespacho,
 DigitoVerificadorNumeroDespacho=@DigitoVerificadorNumeroDespacho,
 FechaDespachoAPlaza=@FechaDespachoAPlaza,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaModifico=@FechaModifico,
 PRESTOProveedor=@PRESTOProveedor,
 IdCodigoIva=@IdCodigoIva,
 CotizacionEuro=@CotizacionEuro,
 IdCondicionCompra=@IdCondicionCompra,
 Importacion_FOB=@Importacion_FOB,
 Importacion_PosicionAduana=@Importacion_PosicionAduana,
 Importacion_Despacho=@Importacion_Despacho,
 Importacion_Guia=@Importacion_Guia,
 Importacion_IdPaisOrigen=@Importacion_IdPaisOrigen,
 Importacion_FechaEmbarque=@Importacion_FechaEmbarque,
 Importacion_FechaOficializacion=@Importacion_FechaOficializacion,
 InformacionAuxiliar=@InformacionAuxiliar,
 GravadoParaSUSS=@GravadoParaSUSS,
 PorcentajeParaSUSS=@PorcentajeParaSUSS,
 FondoReparo=@FondoReparo,
 ReintegroImporte=@ReintegroImporte,
 ReintegroDespacho=@ReintegroDespacho,
 ReintegroIdMoneda=@ReintegroIdMoneda,
 ReintegroIdCuenta=@ReintegroIdCuenta,
 PrestoDestino=@PrestoDestino,
 IdFacturaVenta_RecuperoGastos=@IdFacturaVenta_RecuperoGastos,
 IdNotaCreditoVenta_RecuperoGastos=@IdNotaCreditoVenta_RecuperoGastos,
 IdComprobanteImputado=@IdComprobanteImputado,
 IdCuentaOtros=@IdCuentaOtros,
 PRESTOFechaProceso=@PRESTOFechaProceso,
 DestinoPago=@DestinoPago,
 NumeroRendicionFF=@NumeroRendicionFF,
 Cuit=@Cuit,
 FechaAsignacionPresupuesto=@FechaAsignacionPresupuesto,
 Dolarizada=@Dolarizada,
 NumeroOrdenPagoFondoReparo=@NumeroOrdenPagoFondoReparo,
 IdListaPrecios=@IdListaPrecios,
 IdComprobanteProveedorOriginal=@IdComprobanteProveedorOriginal,
 PorcentajeIVAParaMonotributistas=@PorcentajeIVAParaMonotributistas,
 IdDiferenciaCambio=@IdDiferenciaCambio,
 TomarEnCuboDeGastos=@TomarEnCuboDeGastos,
 ConfirmadoPorWeb=@ConfirmadoPorWeb,
 CircuitoFirmasCompleto=@CircuitoFirmasCompleto,
 IdLiquidacionFlete=@IdLiquidacionFlete,
 NumeroCAE=@NumeroCAE,
 IdImpuestoDirecto=@IdImpuestoDirecto,
 IdPoliza=@IdPoliza,
 NumeroCuotaPoliza=@NumeroCuotaPoliza,
 IdOrdenPagoRetencionIva=@IdOrdenPagoRetencionIva,
 ImporteRetencionIvaEnOrdenPago=@ImporteRetencionIvaEnOrdenPago,
 DebitoAutomatico=@DebitoAutomatico,
 FechaPrestacionServicio=@FechaPrestacionServicio,
 IdTipoOperacion=@IdTipoOperacion,
 ArchivoAdjunto1=@ArchivoAdjunto1,
 ArchivoAdjunto2=@ArchivoAdjunto2
WHERE (IdComprobanteProveedor=@IdComprobanteProveedor)

RETURN(@IdComprobanteProveedor)