CREATE Procedure [dbo].[ComprobantesProveedores_A]

@IdComprobanteProveedor int  output,
@IdProveedor int,
@IdTipoComprobante int,
@FechaComprobante datetime,
@Letra varchar(1),
@NumeroComprobante1 int,
@NumeroComprobante2 int,
@NumeroReferencia int,
@FechaRecepcion datetime,
@FechaVencimiento datetime,
@TotalBruto numeric(12,2),
@TotalIva1 numeric(12,2),
@TotalIva2 numeric(12,2),
@TotalBonificacion numeric(12,2),
@TotalComprobante numeric(12,2),
@PorcentajeBonificacion numeric(6,2),
@Observaciones ntext,
@DiasVencimiento int,
@IdObra int,
@IdProveedorEventual int,
@IdOrdenPago int,
@IdCuenta int,
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@CotizacionDolar numeric(18,4),
@TotalIVANoDiscriminado numeric(18,2),
@IdCuentaIvaCompras1 int,
@IVAComprasPorcentaje1 numeric(6,2),
@IVAComprasImporte1 numeric(18,2),
@IdCuentaIvaCompras2 int,
@IVAComprasPorcentaje2 numeric(6,2),
@IVAComprasImporte2 numeric(18,2),
@IdCuentaIvaCompras3 int,
@IVAComprasPorcentaje3 numeric(6,2),
@IVAComprasImporte3 numeric(18,2),
@IdCuentaIvaCompras4 int,
@IVAComprasPorcentaje4 numeric(6,2),
@IVAComprasImporte4 numeric(18,2),
@IdCuentaIvaCompras5 int,
@IVAComprasPorcentaje5 numeric(6,2),
@IVAComprasImporte5 numeric(18,2),
@IdCuentaIvaCompras6 int,
@IVAComprasPorcentaje6 numeric(6,2),
@IVAComprasImporte6 numeric(18,2),
@IdCuentaIvaCompras7 int,
@IVAComprasPorcentaje7 numeric(6,2),
@IVAComprasImporte7 numeric(18,2),
@IdCuentaIvaCompras8 int,
@IVAComprasPorcentaje8 numeric(6,2),
@IVAComprasImporte8 numeric(18,2),
@IdCuentaIvaCompras9 int,
@IVAComprasPorcentaje9 numeric(6,2),
@IVAComprasImporte9 numeric(18,2),
@IdCuentaIvaCompras10 int,
@IVAComprasPorcentaje10 numeric(6,2),
@IVAComprasImporte10 numeric(18,2),
@SubtotalGravado numeric(18,2),
@SubtotalExento numeric(18,2),
@AjusteIVA numeric(18,2),
@PorcentajeIVAAplicacionAjuste numeric(6,2),
@BienesOServicios varchar(1),
@IdDetalleOrdenPagoRetencionIVAAplicada int,
@IdIBCondicion int,
@PRESTOFactura varchar(13),
@Confirmado varchar(2),
@IdProvinciaDestino int,
@IdTipoRetencionGanancia int,
@NumeroCAI varchar(20),
@FechaVencimientoCAI datetime,
@IdCodigoAduana int,
@IdCodigoDestinacion int,
@NumeroDespacho int,
@DigitoVerificadorNumeroDespacho varchar(1),
@FechaDespachoAPlaza datetime,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@PRESTOProveedor varchar(13),
@IdCodigoIva int,
@CotizacionEuro numeric(18,4),
@IdCondicionCompra int,
@Importacion_FOB numeric(18,2),
@Importacion_PosicionAduana varchar(20),
@Importacion_Despacho varchar(30),
@Importacion_Guia varchar(20),
@Importacion_IdPaisOrigen int,
@Importacion_FechaEmbarque datetime,
@Importacion_FechaOficializacion datetime,
@REP_CTAPRO_INS varchar(1),
@REP_CTAPRO_UPD varchar(1),
@InformacionAuxiliar varchar(50),
@GravadoParaSUSS numeric(18,2),
@PorcentajeParaSUSS numeric(6,2),
@FondoReparo numeric(18,2),
@AutoincrementarNumeroReferencia varchar(2),
@ReintegroImporte numeric(18,2),
@ReintegroDespacho varchar(20),
@ReintegroIdMoneda int,
@ReintegroIdCuenta int,
@PrestoDestino varchar(20),
@IdFacturaVenta_RecuperoGastos int,
@IdNotaCreditoVenta_RecuperoGastos int,
@IdComprobanteImputado int,
@IdCuentaOtros int,
@PRESTOFechaProceso datetime,
@DestinoPago varchar(1),
@NumeroRendicionFF int,
@Cuit varchar(13),
@FechaAsignacionPresupuesto datetime,
@Dolarizada varchar(2),
@NumeroOrdenPagoFondoReparo int,
@IdListaPrecios int,
@IdComprobanteProveedorOriginal int,
@PorcentajeIVAParaMonotributistas numeric(6,2),
@IdDiferenciaCambio int,
@TomarEnCuboDeGastos varchar(2),
@ConfirmadoPorWeb varchar(2),
@CircuitoFirmasCompleto varchar(2),
@IdLiquidacionFlete int,
@NumeroCAE varchar(20),
@IdImpuestoDirecto int,
@IdPoliza int,
@NumeroCuotaPoliza int,
@IdOrdenPagoRetencionIva int,
@ImporteRetencionIvaEnOrdenPago numeric(18,2),
@DebitoAutomatico varchar(2),
@FechaPrestacionServicio datetime,
@IdTipoOperacion int,
@ArchivoAdjunto1 varchar(200),
@ArchivoAdjunto2 varchar(200)

AS

BEGIN TRAN

IF ISNULL(@AutoincrementarNumeroReferencia,'SI')='SI'
   BEGIN
	SET @NumeroReferencia=IsNull((Select Top 1 P.ProximoComprobanteProveedorReferencia From Parametros P Where P.IdParametro=1),1)
	UPDATE Parametros SET ProximoComprobanteProveedorReferencia=@NumeroReferencia+1
   END

IF NOT EXISTS(Select Top 1 Autorizaciones.IdFormulario From DetalleAutorizaciones da 
		Left Outer Join Autorizaciones On Autorizaciones.IdAutorizacion=da.IdAutorizacion
		Where Autorizaciones.IdFormulario=31)
	SET @CircuitoFirmasCompleto='SI'

INSERT INTO [ComprobantesProveedores]
(
 IdProveedor,
 IdTipoComprobante,
 FechaComprobante,
 Letra,
 NumeroComprobante1,
 NumeroComprobante2,
 NumeroReferencia,
 FechaRecepcion,
 FechaVencimiento,
 TotalBruto,
 TotalIva1, TotalIva2,
 TotalBonificacion,
 TotalComprobante,
 PorcentajeBonificacion,
 Observaciones,
 DiasVencimiento,
 IdObra,
 IdProveedorEventual,
 IdOrdenPago,
 IdCuenta,
 IdMoneda,
 CotizacionMoneda,
 CotizacionDolar,
 TotalIVANoDiscriminado,
 IdCuentaIvaCompras1,
 IVAComprasPorcentaje1,
 IVAComprasImporte1, IdCuentaIvaCompras2,
 IVAComprasPorcentaje2,
 IVAComprasImporte2,
 IdCuentaIvaCompras3,
 IVAComprasPorcentaje3,
 IVAComprasImporte3,
 IdCuentaIvaCompras4,
 IVAComprasPorcentaje4,
 IVAComprasImporte4,
 IdCuentaIvaCompras5,
 IVAComprasPorcentaje5,
 IVAComprasImporte5,
 IdCuentaIvaCompras6,
 IVAComprasPorcentaje6,
 IVAComprasImporte6,
 IdCuentaIvaCompras7,
 IVAComprasPorcentaje7,
 IVAComprasImporte7,
 IdCuentaIvaCompras8,
 IVAComprasPorcentaje8,
 IVAComprasImporte8,
 IdCuentaIvaCompras9,
 IVAComprasPorcentaje9,
 IVAComprasImporte9,
 IdCuentaIvaCompras10,
 IVAComprasPorcentaje10,
 IVAComprasImporte10,
 SubtotalGravado,
 SubtotalExento,
 AjusteIVA,
 PorcentajeIVAAplicacionAjuste,
 BienesOServicios,
 IdDetalleOrdenPagoRetencionIVAAplicada,
 IdIBCondicion,
 PRESTOFactura,
 Confirmado,
 IdProvinciaDestino,
 IdTipoRetencionGanancia,
 NumeroCAI,
 FechaVencimientoCAI,
 IdCodigoAduana,
 IdCodigoDestinacion,
 NumeroDespacho,
 DigitoVerificadorNumeroDespacho,
 FechaDespachoAPlaza, IdUsuarioIngreso,
 FechaIngreso,
 IdUsuarioModifico,
 FechaModifico,
 PRESTOProveedor,
 IdCodigoIva,
 CotizacionEuro,
 IdCondicionCompra,
 Importacion_FOB,
 Importacion_PosicionAduana,
 Importacion_Despacho,
 Importacion_Guia,
 Importacion_IdPaisOrigen,
 Importacion_FechaEmbarque,
 Importacion_FechaOficializacion,
 REP_CTAPRO_INS,
 REP_CTAPRO_UPD,
 InformacionAuxiliar,
 GravadoParaSUSS,
 PorcentajeParaSUSS,
 FondoReparo,
 AutoincrementarNumeroReferencia,
 ReintegroImporte,
 ReintegroDespacho,
 ReintegroIdMoneda,
 ReintegroIdCuenta,
 PrestoDestino,
 IdFacturaVenta_RecuperoGastos,
 IdNotaCreditoVenta_RecuperoGastos,
 IdComprobanteImputado,
 IdCuentaOtros,
 PRESTOFechaProceso,
 DestinoPago,
 NumeroRendicionFF,
 Cuit,
 FechaAsignacionPresupuesto,
 Dolarizada,
 NumeroOrdenPagoFondoReparo,
 IdListaPrecios,
 IdComprobanteProveedorOriginal,
 PorcentajeIVAParaMonotributistas,
 IdDiferenciaCambio,
 TomarEnCuboDeGastos,
 ConfirmadoPorWeb,
 CircuitoFirmasCompleto,
 IdLiquidacionFlete,
 NumeroCAE,
 IdImpuestoDirecto,
 IdPoliza,
 NumeroCuotaPoliza,
 IdOrdenPagoRetencionIva,
 ImporteRetencionIvaEnOrdenPago,
 DebitoAutomatico,
 FechaPrestacionServicio,
 IdTipoOperacion,
 ArchivoAdjunto1,
 ArchivoAdjunto2
)
VALUES 
(
 @IdProveedor,
 @IdTipoComprobante,
 @FechaComprobante,
 @Letra,
 @NumeroComprobante1,
 @NumeroComprobante2,
 @NumeroReferencia,
 @FechaRecepcion,
 @FechaVencimiento,
 @TotalBruto,
 @TotalIva1,
 @TotalIva2,
 @TotalBonificacion,
 @TotalComprobante,
 @PorcentajeBonificacion,
 @Observaciones,
 @DiasVencimiento,
 @IdObra,
 @IdProveedorEventual,
 @IdOrdenPago,
 @IdCuenta,
 @IdMoneda,
 @CotizacionMoneda,
 @CotizacionDolar,
 @TotalIVANoDiscriminado,
 @IdCuentaIvaCompras1,
 @IVAComprasPorcentaje1,
 @IVAComprasImporte1,
 @IdCuentaIvaCompras2,
 @IVAComprasPorcentaje2,
 @IVAComprasImporte2,
 @IdCuentaIvaCompras3,
 @IVAComprasPorcentaje3,
 @IVAComprasImporte3,
 @IdCuentaIvaCompras4,
 @IVAComprasPorcentaje4,
 @IVAComprasImporte4,
 @IdCuentaIvaCompras5,
 @IVAComprasPorcentaje5, @IVAComprasImporte5,
 @IdCuentaIvaCompras6,
 @IVAComprasPorcentaje6,
 @IVAComprasImporte6,
 @IdCuentaIvaCompras7, @IVAComprasPorcentaje7,
 @IVAComprasImporte7,
 @IdCuentaIvaCompras8,
 @IVAComprasPorcentaje8,
 @IVAComprasImporte8,
 @IdCuentaIvaCompras9,
 @IVAComprasPorcentaje9,
 @IVAComprasImporte9,
 @IdCuentaIvaCompras10,
 @IVAComprasPorcentaje10,
 @IVAComprasImporte10,
 @SubtotalGravado,
 @SubtotalExento,
 @AjusteIVA,
 @PorcentajeIVAAplicacionAjuste,
 @BienesOServicios,
 @IdDetalleOrdenPagoRetencionIVAAplicada,
 @IdIBCondicion,
 @PRESTOFactura,
 @Confirmado,
 @IdProvinciaDestino,
 @IdTipoRetencionGanancia,
 @NumeroCAI,
 @FechaVencimientoCAI,
 @IdCodigoAduana,
 @IdCodigoDestinacion,
 @NumeroDespacho,
 @DigitoVerificadorNumeroDespacho,
 @FechaDespachoAPlaza,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @IdUsuarioModifico,
 @FechaModifico,
 @PRESTOProveedor,
 @IdCodigoIva, @CotizacionEuro,
 @IdCondicionCompra,
 @Importacion_FOB,
 @Importacion_PosicionAduana,
 @Importacion_Despacho,
 @Importacion_Guia,
 @Importacion_IdPaisOrigen,
 @Importacion_FechaEmbarque,
 @Importacion_FechaOficializacion,
 @REP_CTAPRO_INS,
 @REP_CTAPRO_UPD,
 @InformacionAuxiliar,
 @GravadoParaSUSS,
 @PorcentajeParaSUSS,
 @FondoReparo,
 @AutoincrementarNumeroReferencia,
 @ReintegroImporte,
 @ReintegroDespacho,
 @ReintegroIdMoneda,
 @ReintegroIdCuenta,
 @PrestoDestino,
 @IdFacturaVenta_RecuperoGastos,
 @IdNotaCreditoVenta_RecuperoGastos,
 @IdComprobanteImputado,
 @IdCuentaOtros,
 @PRESTOFechaProceso,
 @DestinoPago,
 @NumeroRendicionFF,
 @Cuit,
 @FechaAsignacionPresupuesto,
 @Dolarizada,
 @NumeroOrdenPagoFondoReparo,
 @IdListaPrecios,
 @IdComprobanteProveedorOriginal,
 @PorcentajeIVAParaMonotributistas,
 @IdDiferenciaCambio,
 @TomarEnCuboDeGastos,
 @ConfirmadoPorWeb,
 @CircuitoFirmasCompleto,
 @IdLiquidacionFlete,
 @NumeroCAE,
 @IdImpuestoDirecto,
 @IdPoliza,
 @NumeroCuotaPoliza,
 @IdOrdenPagoRetencionIva,
 @ImporteRetencionIvaEnOrdenPago,
 @DebitoAutomatico,
 @FechaPrestacionServicio,
 @IdTipoOperacion,
 @ArchivoAdjunto1,
 @ArchivoAdjunto2
)

SELECT @IdComprobanteProveedor=@@identity

IF @@ERROR <> 0 GOTO AbortTransaction

COMMIT TRAN
GOTO EndTransaction

AbortTransaction:
ROLLBACK TRAN

EndTransaction:
RETURN(@IdComprobanteProveedor)