CREATE Procedure [dbo].[CondicionesCompra_A]

@IdCondicionCompra int  output,
@Descripcion varchar(50),
@CantidadDias int,
@CodigoCondicion varchar(2),
@CantidadDias1 int,
@CantidadDias2 int,
@CantidadDias3 int,
@CantidadDias4 int,
@CantidadDias5 int,
@CantidadDias6 int,
@Porcentaje1 numeric(6,2),
@Porcentaje2 numeric(6,2),
@Porcentaje3 numeric(6,2),
@Porcentaje4 numeric(6,2),
@Porcentaje5 numeric(6,2),
@Porcentaje6 numeric(6,2),
@CantidadDias7 int,
@CantidadDias8 int,
@CantidadDias9 int,
@CantidadDias10 int,
@CantidadDias11 int,
@CantidadDias12 int,
@Porcentaje7 numeric(6,2),
@Porcentaje8 numeric(6,2),
@Porcentaje9 numeric(6,2),
@Porcentaje10 numeric(6,2),
@Porcentaje11 numeric(6,2),
@Porcentaje12 numeric(6,2),
@Observaciones ntext,
@Codigo varchar(10),
@PorcentajeBonificacion numeric(6,2),
@ContraEntregaDeValores varchar(2)

AS 

INSERT INTO [Condiciones Compra]
(
 Descripcion,
 CantidadDias,
 CodigoCondicion,
 CantidadDias1,
 CantidadDias2,
 CantidadDias3,
 CantidadDias4,
 CantidadDias5,
 CantidadDias6,
 Porcentaje1,
 Porcentaje2,
 Porcentaje3,
 Porcentaje4,
 Porcentaje5,
 Porcentaje6,
 CantidadDias7,
 CantidadDias8,
 CantidadDias9,
 CantidadDias10,
 CantidadDias11,
 CantidadDias12,
 Porcentaje7,
 Porcentaje8,
 Porcentaje9,
 Porcentaje10,
 Porcentaje11,
 Porcentaje12,
 Observaciones,
 Codigo,
 PorcentajeBonificacion,
 ContraEntregaDeValores
)
VALUES
(
 @Descripcion,
 @CantidadDias,
 @CodigoCondicion,
 @CantidadDias1,
 @CantidadDias2,
 @CantidadDias3,
 @CantidadDias4,
 @CantidadDias5,
 @CantidadDias6,
 @Porcentaje1,
 @Porcentaje2,
 @Porcentaje3,
 @Porcentaje4,
 @Porcentaje5,
 @Porcentaje6,
 @CantidadDias7,
 @CantidadDias8,
 @CantidadDias9,
 @CantidadDias10,
 @CantidadDias11,
 @CantidadDias12,
 @Porcentaje7,
 @Porcentaje8,
 @Porcentaje9,
 @Porcentaje10,
 @Porcentaje11,
 @Porcentaje12,
 @Observaciones,
 @Codigo,
 @PorcentajeBonificacion,
 @ContraEntregaDeValores
)

SELECT @IdCondicionCompra=@@identity

RETURN(@IdCondicionCompra)