CREATE Procedure [dbo].[Devoluciones_A]

@IdDevolucion int  output,
@NumeroDevolucion int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdFactura int,
@IdCliente int,
@FechaDevolucion datetime,
@IdVendedor int,
@TipoPedidoConsignacion varchar(1),
@Anulada varchar(2),
@FechaAnulacion datetime,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@ImporteBonificacion numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@ConvenioMultilateral varchar(2),
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@IdTipoVentaC smallint,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@IVANoDiscriminado numeric(18,2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@PorcentajeBonificacion numeric(6,2),
@Observaciones ntext,
@FechaRegistracion datetime,
@IdProvinciaDestino int,
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdIBCondicion int,
@IdPuntoVenta int,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@IdObra int,
@IdCodigoIva int,
@IdListaPrecios int,
@IdIBCondicion2 int,
@IdIBCondicion3 int,
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@IdDeposito int,
@IdUsuarioAnulacion int

AS

INSERT INTO [Devoluciones]
(
 NumeroDevolucion,
 TipoABC,
 PuntoVenta,
 IdFactura,
 IdCliente,
 FechaDevolucion,
 IdVendedor,
 TipoPedidoConsignacion,
 Anulada,
 FechaAnulacion,
 ImporteTotal,
 ImporteIva1,
 ImporteIva2,
 ImporteBonificacion,
 RetencionIBrutos1,
 PorcentajeIBrutos1,
 RetencionIBrutos2,
 PorcentajeIBrutos2,
 ConvenioMultilateral,
 RetencionIBrutos3,
 PorcentajeIBrutos3,
 IdTipoVentaC,
 ImporteIvaIncluido,
 CotizacionDolar,
 PorcentajeIva1,
 PorcentajeIva2,
 IVANoDiscriminado,
 IdMoneda,
 CotizacionMoneda,
 PorcentajeBonificacion,
 Observaciones,
 FechaRegistracion,
 IdProvinciaDestino,
 OtrasPercepciones1,
 OtrasPercepciones1Desc,
 OtrasPercepciones2,
 OtrasPercepciones2Desc,
 IdIBCondicion,
 IdPuntoVenta,
 NumeroCAI,
 FechaVencimientoCAI,
 IdObra,
 IdCodigoIva,
 IdListaPrecios,
 IdIBCondicion2,
 IdIBCondicion3,
 PercepcionIVA,
 PorcentajePercepcionIVA,
 IdDeposito,
 IdUsuarioAnulacion
)
VALUES
(
 @NumeroDevolucion,
 @TipoABC,
 @PuntoVenta,
 @IdFactura,
 @IdCliente,
 @FechaDevolucion,
 @IdVendedor,
 @TipoPedidoConsignacion,
 @Anulada,
 @FechaAnulacion,
 @ImporteTotal,
 @ImporteIva1,
 @ImporteIva2,
 @ImporteBonificacion,
 @RetencionIBrutos1,
 @PorcentajeIBrutos1,
 @RetencionIBrutos2,
 @PorcentajeIBrutos2,
 @ConvenioMultilateral,
 @RetencionIBrutos3,
 @PorcentajeIBrutos3,
 @IdTipoVentaC,
 @ImporteIvaIncluido,
 @CotizacionDolar,
 @PorcentajeIva1,
 @PorcentajeIva2,
 @IVANoDiscriminado,
 @IdMoneda,
 @CotizacionMoneda,
 @PorcentajeBonificacion,
 @Observaciones,
 GetDate(),
 @IdProvinciaDestino,
 @OtrasPercepciones1,
 @OtrasPercepciones1Desc,
 @OtrasPercepciones2,
 @OtrasPercepciones2Desc,
 @IdIBCondicion,
 @IdPuntoVenta,
 @NumeroCAI,
 @FechaVencimientoCAI,
 @IdObra,
 @IdCodigoIva,
 @IdListaPrecios,
 @IdIBCondicion2,
 @IdIBCondicion3,
 @PercepcionIVA,
 @PorcentajePercepcionIVA,
 @IdDeposito,
 @IdUsuarioAnulacion
)

SELECT @IdDevolucion=@@identity

RETURN(@IdDevolucion)