CREATE Procedure [dbo].[Devoluciones_M]

@IdDevolucion int,
@NumeroDevolucion int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdFactura int,
@IdCliente int,
@FechaDevolucion datetime,
@IdVendedor int,
@TipoPedidoConsignacion varchar(1),
@Anulada varchar(2),
@FechaAnulacion datetime,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@ImporteBonificacion numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@ConvenioMultilateral varchar(2),
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@IdTipoVentaC smallint,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@IVANoDiscriminado numeric(18,2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@PorcentajeBonificacion numeric(6,2),
@Observaciones ntext,
@FechaRegistracion datetime,
@IdProvinciaDestino int,
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdIBCondicion int,
@IdPuntoVenta int,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@IdObra int,
@IdCodigoIva int,
@IdListaPrecios int,
@IdIBCondicion2 int,
@IdIBCondicion3 int,
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@IdDeposito int,
@IdUsuarioAnulacion int

AS

UPDATE Devoluciones
SET 
 NumeroDevolucion=@NumeroDevolucion,
 TipoABC=@TipoABC,
 PuntoVenta=@PuntoVenta,
 IdFactura=@IdFactura,
 IdCliente=@IdCliente,
 FechaDevolucion=@FechaDevolucion,
 IdVendedor=@IdVendedor,
 TipoPedidoConsignacion=@TipoPedidoConsignacion,
 Anulada=@Anulada,
 FechaAnulacion=@FechaAnulacion,
 ImporteTotal=@ImporteTotal,
 ImporteIva1=@ImporteIva1,
 ImporteIva2=@ImporteIva2,
 ImporteBonificacion=@ImporteBonificacion,
 RetencionIBrutos1=@RetencionIBrutos1,
 PorcentajeIBrutos1=@PorcentajeIBrutos1,
 RetencionIBrutos2=@RetencionIBrutos2,
 PorcentajeIBrutos2=@PorcentajeIBrutos2,
 ConvenioMultilateral=@ConvenioMultilateral,
 RetencionIBrutos3=@RetencionIBrutos3,
 PorcentajeIBrutos3=@PorcentajeIBrutos3,
 IdTipoVentaC=@IdTipoVentaC,
 ImporteIvaIncluido=@ImporteIvaIncluido,
 CotizacionDolar=@CotizacionDolar,
 PorcentajeIva1=@PorcentajeIva1,
 PorcentajeIva2=@PorcentajeIva2,
 IVANoDiscriminado=@IVANoDiscriminado,
 IdMoneda=@IdMoneda,
 CotizacionMoneda=@CotizacionMoneda,
 PorcentajeBonificacion=@PorcentajeBonificacion,
 Observaciones=@Observaciones,
 FechaRegistracion=@FechaRegistracion,
 IdProvinciaDestino=@IdProvinciaDestino,
 OtrasPercepciones1=@OtrasPercepciones1,
 OtrasPercepciones1Desc=@OtrasPercepciones1Desc,
 OtrasPercepciones2=@OtrasPercepciones2,
 OtrasPercepciones2Desc=@OtrasPercepciones2Desc,
 IdIBCondicion=@IdIBCondicion,
 IdPuntoVenta=@IdPuntoVenta,
 NumeroCAI=@NumeroCAI,
 FechaVencimientoCAI=@FechaVencimientoCAI,
 IdObra=@IdObra,
 IdCodigoIva=@IdCodigoIva,
 IdListaPrecios=@IdListaPrecios,
 IdIBCondicion2=@IdIBCondicion2,
 IdIBCondicion3=@IdIBCondicion3,
 PercepcionIVA=@PercepcionIVA,
 PorcentajePercepcionIVA=@PorcentajePercepcionIVA,
 IdDeposito=@IdDeposito,
 IdUsuarioAnulacion=@IdUsuarioAnulacion
WHERE (IdDevolucion=@IdDevolucion)

RETURN(@IdDevolucion)