CREATE Procedure [dbo].[Empleados_A]

@IdEmpleado int  output,
@Legajo int,
@Nombre varchar(50),
@UsuarioNT varchar(50),
@IdSector int,
@IdCargo int,
@Email varchar(50),
@Interno varchar(20),
@Administrador varchar(2),
@Iniciales varchar(6),
@Password varchar(50),
@SisMan varchar(2),
@HorasJornada numeric(12,2),
@IdSector1 int,
@IdCargo1 int,
@IdSector2 int,
@IdCargo2 int,
@IdSector3 int,
@IdCargo3 int,
@IdSector4 int,
@IdCargo4 int,
@Dominio varchar(50),
@SisMat varchar(2),
@FechaNacimiento datetime,
@TipoUsuario int,
@GrupoDeCarga int,
@CuentaBancaria varchar(20),
@InformacionAuxiliar varchar(50),
@IdCuentaFondoFijo int,
@IdObraAsignada int,
@Activo varchar(2),
@Idioma varchar(3),
@PuntoVentaAsociado int,
@IdLugarEntregaAsignado int,
@EsConductor varchar(2),
@FechaVencimientoRegistro datetime,
@LimitarUbicacionesAsignadas varchar(2),
@PermitirAccesoATodasLasObras varchar(2)

AS 

INSERT INTO [Empleados]
(
 Legajo,
 Nombre,
 UsuarioNT,
 IdSector,
 IdCargo,
 Email,
 Interno,
 Administrador,
 Iniciales,
 Password,
 SisMan,
 HorasJornada,
 IdSector1,
 IdCargo1,
 IdSector2,
 IdCargo2,
 IdSector3,
 IdCargo3,
 IdSector4,
 IdCargo4,
 Dominio,
 SisMat,
 FechaNacimiento,
 TipoUsuario,
 GrupoDeCarga,
 CuentaBancaria,
 InformacionAuxiliar,
 IdCuentaFondoFijo,
 IdObraAsignada,
 Activo,
 Idioma,
 PuntoVentaAsociado,
 IdLugarEntregaAsignado,
 EsConductor,
 FechaVencimientoRegistro,
 LimitarUbicacionesAsignadas,
 PermitirAccesoATodasLasObras
)
VALUES 
(
 @Legajo,
 @Nombre,
 @UsuarioNT,
 @IdSector,
 @IdCargo,
 @Email,
 @Interno,
 @Administrador,
 @Iniciales,
 @Password,
 @SisMan,
 @HorasJornada,
 @IdSector1,
 @IdCargo1,
 @IdSector2,
 @IdCargo2,
 @IdSector3,
 @IdCargo3,
 @IdSector4,
 @IdCargo4,
 @Dominio,
 @SisMat,
 @FechaNacimiento,
 @TipoUsuario,
 @GrupoDeCarga,
 @CuentaBancaria,
 @InformacionAuxiliar,
 @IdCuentaFondoFijo,
 @IdObraAsignada,
 @Activo,
 @Idioma,
 @PuntoVentaAsociado,
 @IdLugarEntregaAsignado,
 @EsConductor,
 @FechaVencimientoRegistro,
 @LimitarUbicacionesAsignadas,
 @PermitirAccesoATodasLasObras
)

SELECT @IdEmpleado=@@identity

RETURN(@IdEmpleado)