CREATE Procedure [dbo].[Facturas_M]

@IdFactura int,
@NumeroFactura int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdCliente int,
@FechaFactura datetime,
@IdCondicionVenta smallint,
@IdVendedor int,
@IdTransportista1 int,
@IdTransportista2 int,
@ItemDireccion tinyint,
@OrdenCompra varchar(20),
@TipoPedidoConsignacion varchar(1),
@Anulada varchar(2),
@FechaAnulacion datetime,
@Observaciones ntext,
@IdRemito int,
@NumeroRemito int,
@IdPedido int,
@NumeroPedido int,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@ImporteBonificacion numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@ConvenioMultilateral varchar(2),
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@IdTipoVentaC smallint,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@EsMuestra varchar(2),
@CotizacionADolarFijo numeric(18,3),
@ImporteParteEnDolares numeric(18,2),
@ImporteParteEnPesos numeric(18,2),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@FechaVencimiento datetime,
@IVANoDiscriminado numeric(18,2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@PorcentajeBonificacion numeric(6,2),
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdProvinciaDestino int,
@IdIBCondicion int,
@IdAutorizaAnulacion int,
@IdPuntoVenta int,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@NumeroCertificadoPercepcionIIBB int,
@NumeroTicketInicial int,
@NumeroTicketFinal int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdObra int,
@IdIBCondicion2 int,
@IdIBCondicion3 int,
@IdCodigoIva int,
@Exportacion_FOB numeric(18,2),
@Exportacion_PosicionAduana varchar(20),
@Exportacion_Despacho varchar(30),
@Exportacion_Guia varchar(20),
@Exportacion_IdPaisDestino int,
@Exportacion_FechaEmbarque datetime,
@Exportacion_FechaOficializacion datetime,
@OtrasPercepciones3 numeric(18,2),
@OtrasPercepciones3Desc varchar(15),
@NoIncluirEnCubos varchar(2),
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@ActivarRecuperoGastos varchar(2),
@IdAutorizoRecuperoGastos int,
@ContabilizarAFechaVencimiento varchar(2),
@FacturaContado varchar(2),
@IdReciboContado int,
@EnviarEmail int,
@IdOrigenTransmision int,
@IdFacturaOriginal int,
@FechaImportacionTransmision datetime,
@CuitClienteTransmision varchar(13),
@IdReciboContadoOriginal int,
@DevolucionAnticipo varchar(2),
@PorcentajeDevolucionAnticipo numeric(18,10),
@CAE varchar(14),
@RechazoCAE varchar(11),
@FechaVencimientoORechazoCAE datetime,
@IdListaPrecios int,
@IdIdentificacionCAE int,
@AjusteIva numeric(18,2),
@TipoExportacion int,
@PermisoEmbarque varchar(2),
@NumeroFacturaInicial int,
@NumeroFacturaFinal int,
@CodigoIdAuxiliar int,
@NumeroCertificadoObra int,
@ImporteCertificacionObra numeric(18,2),
@FondoReparoCertificacionObra numeric(18,2),
@PorcentajeRetencionesEstimadasCertificacionObra numeric(6,2),
@NumeroExpedienteCertificacionObra varchar(20),
@NumeroProyecto int,
@IdCertificacionObras int,
@IdCertificacionObraDatos int,
@FechaRecepcionCliente datetime,
@CuentaVentaLetra varchar(1),
@CuentaVentaPuntoVenta int,
@CuentaVentaNumero int,
@IdDeposito int,
@Cliente varchar(50),
@OrigenRegistro varchar(12),
@TotalBultos int,
@IdDetalleClienteLugarEntrega int,
@CuitClienteExterno varchar(13),
@ComisionDiferenciada numeric(6,2),
@IdTipoNegocioVentas int,
@NumeroOrdenCompraExterna bigint,
@IdTipoOperacion int,
@FueEnviadoCorreoConFacturaElectronica varchar(2)

AS

SET NOCOUNT ON

IF @Anulada='SI' and LEFT(CAST(@Observaciones AS nvarchar(100)),23) <>' -- NO LIBERAR CDPS -- '
  BEGIN
	UPDATE CartasDePorte
	SET IdFacturaImputada=Null, IdDetalleFactura=Null
	WHERE IdFacturaImputada=@IdFactura

	UPDATE CartasPorteMovimientos
	SET IdFacturaImputada=Null, IdDetalleFactura=Null
	WHERE IdFacturaImputada=@IdFactura
  END

SET NOCOUNT OFF

UPDATE Facturas
SET 
 NumeroFactura=@NumeroFactura,
 TipoABC=@TipoABC,
 PuntoVenta=@PuntoVenta,
 IdCliente=@IdCliente,
 FechaFactura=@FechaFactura,
 IdCondicionVenta=@IdCondicionVenta,
 IdVendedor=@IdVendedor,
 IdTransportista1=@IdTransportista1,
 IdTransportista2=@IdTransportista2,
 ItemDireccion=@ItemDireccion,
 OrdenCompra=@OrdenCompra,
 TipoPedidoConsignacion=@TipoPedidoConsignacion,
 Anulada=@Anulada,
 FechaAnulacion=@FechaAnulacion,
 Observaciones=@Observaciones,
 IdRemito=@IdRemito,
 NumeroRemito=@NumeroRemito,
 IdPedido=@IdPedido,
 NumeroPedido=@NumeroPedido,
 ImporteTotal=@ImporteTotal,
 ImporteIva1=@ImporteIva1,
 ImporteIva2=@ImporteIva2,
 ImporteBonificacion=@ImporteBonificacion,
 RetencionIBrutos1=@RetencionIBrutos1,
 PorcentajeIBrutos1=@PorcentajeIBrutos1,
 RetencionIBrutos2=@RetencionIBrutos2,
 PorcentajeIBrutos2=@PorcentajeIBrutos2,
 ConvenioMultilateral=@ConvenioMultilateral,
 RetencionIBrutos3=@RetencionIBrutos3,
 PorcentajeIBrutos3=@PorcentajeIBrutos3,
 IdTipoVentaC=@IdTipoVentaC,
 ImporteIvaIncluido=@ImporteIvaIncluido,
 CotizacionDolar=@CotizacionDolar,
 EsMuestra=@EsMuestra,
 CotizacionADolarFijo=@CotizacionADolarFijo,
 ImporteParteEnDolares=@ImporteParteEnDolares,
 ImporteParteEnPesos=@ImporteParteEnPesos,
 PorcentajeIva1=@PorcentajeIva1,
 PorcentajeIva2=@PorcentajeIva2,
 FechaVencimiento=@FechaVencimiento,
 IVANoDiscriminado=@IVANoDiscriminado,
 IdMoneda=@IdMoneda, CotizacionMoneda=@CotizacionMoneda,
 PorcentajeBonificacion=@PorcentajeBonificacion,
 OtrasPercepciones1=@OtrasPercepciones1,
 OtrasPercepciones1Desc=@OtrasPercepciones1Desc, OtrasPercepciones2=@OtrasPercepciones2,
 OtrasPercepciones2Desc=@OtrasPercepciones2Desc,
 IdProvinciaDestino=@IdProvinciaDestino,
 IdIBCondicion=@IdIBCondicion,
 IdAutorizaAnulacion=@IdAutorizaAnulacion,
 IdPuntoVenta=@IdPuntoVenta,
 NumeroCAI=@NumeroCAI,
 FechaVencimientoCAI=@FechaVencimientoCAI,
 NumeroCertificadoPercepcionIIBB=@NumeroCertificadoPercepcionIIBB,
 NumeroTicketInicial=@NumeroTicketInicial,
 NumeroTicketFinal=@NumeroTicketFinal,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdObra=@IdObra,
 IdIBCondicion2=@IdIBCondicion2,
 IdIBCondicion3=@IdIBCondicion3,
 IdCodigoIva=@IdCodigoIva,
 Exportacion_FOB=@Exportacion_FOB,
 Exportacion_PosicionAduana=@Exportacion_PosicionAduana,
 Exportacion_Despacho=@Exportacion_Despacho,
 Exportacion_Guia=@Exportacion_Guia,
 Exportacion_IdPaisDestino=@Exportacion_IdPaisDestino,
 Exportacion_FechaEmbarque=@Exportacion_FechaEmbarque,
 Exportacion_FechaOficializacion=@Exportacion_FechaOficializacion,
 OtrasPercepciones3=@OtrasPercepciones3,
 OtrasPercepciones3Desc=@OtrasPercepciones3Desc,
 NoIncluirEnCubos=@NoIncluirEnCubos,
 PercepcionIVA=@PercepcionIVA,
 PorcentajePercepcionIVA=@PorcentajePercepcionIVA,
 ActivarRecuperoGastos=@ActivarRecuperoGastos,
 IdAutorizoRecuperoGastos=@IdAutorizoRecuperoGastos,
 ContabilizarAFechaVencimiento=@ContabilizarAFechaVencimiento,
 FacturaContado=@FacturaContado,
 IdReciboContado=@IdReciboContado,
 EnviarEmail=@EnviarEmail,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdFacturaOriginal=@IdFacturaOriginal,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 CuitClienteTransmision=@CuitClienteTransmision,
 IdReciboContadoOriginal=@IdReciboContadoOriginal,
 DevolucionAnticipo=@DevolucionAnticipo,
 PorcentajeDevolucionAnticipo=@PorcentajeDevolucionAnticipo,
 CAE=@CAE,
 RechazoCAE=@RechazoCAE,
 FechaVencimientoORechazoCAE=@FechaVencimientoORechazoCAE,
 IdListaPrecios=@IdListaPrecios,
 IdIdentificacionCAE=@IdIdentificacionCAE,
 AjusteIva=@AjusteIva,
 TipoExportacion=@TipoExportacion,
 PermisoEmbarque=@PermisoEmbarque,
 NumeroFacturaInicial=@NumeroFacturaInicial,
 NumeroFacturaFinal=@NumeroFacturaFinal,
 CodigoIdAuxiliar=@CodigoIdAuxiliar,
 NumeroCertificadoObra=@NumeroCertificadoObra,
 ImporteCertificacionObra=@ImporteCertificacionObra,
 FondoReparoCertificacionObra=@FondoReparoCertificacionObra,
 PorcentajeRetencionesEstimadasCertificacionObra=@PorcentajeRetencionesEstimadasCertificacionObra,
 NumeroExpedienteCertificacionObra=@NumeroExpedienteCertificacionObra,
 NumeroProyecto=@NumeroProyecto,
 IdCertificacionObras=@IdCertificacionObras,
 IdCertificacionObraDatos=@IdCertificacionObraDatos,
 FechaRecepcionCliente=@FechaRecepcionCliente,
 CuentaVentaLetra=@CuentaVentaLetra,
 CuentaVentaPuntoVenta=@CuentaVentaPuntoVenta,
 CuentaVentaNumero=@CuentaVentaNumero,
 IdDeposito=@IdDeposito,
 Cliente=@Cliente,
 OrigenRegistro=@OrigenRegistro,
 TotalBultos=@TotalBultos, 
 IdDetalleClienteLugarEntrega=@IdDetalleClienteLugarEntrega,
 CuitClienteExterno=@CuitClienteExterno,
 ComisionDiferenciada=@ComisionDiferenciada,
 IdTipoNegocioVentas=@IdTipoNegocioVentas,
 NumeroOrdenCompraExterna=@NumeroOrdenCompraExterna,
 IdTipoOperacion=@IdTipoOperacion,
 FueEnviadoCorreoConFacturaElectronica=@FueEnviadoCorreoConFacturaElectronica
WHERE (IdFactura=@IdFactura)

RETURN(@IdFactura)