CREATE Procedure [dbo].[Facturas_A]

@IdFactura int  output,
@NumeroFactura int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdCliente int,
@FechaFactura datetime,
@IdCondicionVenta smallint,
@IdVendedor int,
@IdTransportista1 int,
@IdTransportista2 int,
@ItemDireccion tinyint,
@OrdenCompra varchar(20),
@TipoPedidoConsignacion varchar(1),
@Anulada varchar(2),
@FechaAnulacion datetime,
@Observaciones ntext,
@IdRemito int,
@NumeroRemito int,
@IdPedido int,
@NumeroPedido int,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@ImporteBonificacion numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@ConvenioMultilateral varchar(2),
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@IdTipoVentaC smallint,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@EsMuestra varchar(2),
@CotizacionADolarFijo numeric(18,3),
@ImporteParteEnDolares numeric(18,2),
@ImporteParteEnPesos numeric(18,2),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@FechaVencimiento datetime,
@IVANoDiscriminado numeric(18,2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@PorcentajeBonificacion numeric(6,2),
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdProvinciaDestino int,
@IdIBCondicion int,
@IdAutorizaAnulacion int,
@IdPuntoVenta int,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@NumeroCertificadoPercepcionIIBB int,
@NumeroTicketInicial int,
@NumeroTicketFinal int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdObra int,
@IdIBCondicion2 int,
@IdIBCondicion3 int,
@IdCodigoIva int,
@Exportacion_FOB numeric(18,2),
@Exportacion_PosicionAduana varchar(20),
@Exportacion_Despacho varchar(30),
@Exportacion_Guia varchar(20),
@Exportacion_IdPaisDestino int,
@Exportacion_FechaEmbarque datetime,
@Exportacion_FechaOficializacion datetime,
@OtrasPercepciones3 numeric(18,2),
@OtrasPercepciones3Desc varchar(15),
@NoIncluirEnCubos varchar(2),
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@ActivarRecuperoGastos varchar(2),
@IdAutorizoRecuperoGastos int,
@ContabilizarAFechaVencimiento varchar(2),
@FacturaContado varchar(2),
@IdReciboContado int,
@EnviarEmail int,
@IdOrigenTransmision int,
@IdFacturaOriginal int,
@FechaImportacionTransmision datetime,
@CuitClienteTransmision varchar(13),
@IdReciboContadoOriginal int,
@DevolucionAnticipo varchar(2),
@PorcentajeDevolucionAnticipo numeric(18,10),
@CAE varchar(14),
@RechazoCAE varchar(11),
@FechaVencimientoORechazoCAE datetime,
@IdListaPrecios int,
@IdIdentificacionCAE int,
@AjusteIva numeric(18,2),
@TipoExportacion int,
@PermisoEmbarque varchar(2),
@NumeroFacturaInicial int,
@NumeroFacturaFinal int,
@CodigoIdAuxiliar int,
@NumeroCertificadoObra int,
@ImporteCertificacionObra numeric(18,2),
@FondoReparoCertificacionObra numeric(18,2),
@PorcentajeRetencionesEstimadasCertificacionObra numeric(6,2),
@NumeroExpedienteCertificacionObra varchar(20),
@NumeroProyecto int,
@IdCertificacionObras int,
@IdCertificacionObraDatos int,
@FechaRecepcionCliente datetime,
@CuentaVentaLetra varchar(1),
@CuentaVentaPuntoVenta int,
@CuentaVentaNumero int,
@IdDeposito int,
@Cliente varchar(50),
@OrigenRegistro varchar(12),
@TotalBultos int,
@IdDetalleClienteLugarEntrega int,
@CuitClienteExterno varchar(13),
@ComisionDiferenciada numeric(6,2),
@IdTipoNegocioVentas int,
@NumeroOrdenCompraExterna bigint,
@IdTipoOperacion int,
@FueEnviadoCorreoConFacturaElectronica varchar(2)

AS 

INSERT INTO [Facturas]
(
 NumeroFactura,
 TipoABC,
 PuntoVenta,
 IdCliente,
 FechaFactura,
 IdCondicionVenta,
 IdVendedor,
 IdTransportista1,
 IdTransportista2,
 ItemDireccion,
 OrdenCompra,
 TipoPedidoConsignacion,
 Anulada,
 FechaAnulacion,
 Observaciones,
 IdRemito,
 NumeroRemito,
 IdPedido,
 NumeroPedido,
 ImporteTotal,
 ImporteIva1,
 ImporteIva2,
 ImporteBonificacion,
 RetencionIBrutos1,
 PorcentajeIBrutos1,
 RetencionIBrutos2,
 PorcentajeIBrutos2, ConvenioMultilateral,
 RetencionIBrutos3,
 PorcentajeIBrutos3,
 IdTipoVentaC,
 ImporteIvaIncluido,
 CotizacionDolar,
 EsMuestra,
 CotizacionADolarFijo,
 ImporteParteEnDolares,
 ImporteParteEnPesos,
 PorcentajeIva1,
 PorcentajeIva2,
 FechaVencimiento,
 IVANoDiscriminado,
 IdMoneda,
 CotizacionMoneda,
 PorcentajeBonificacion,
 OtrasPercepciones1,
 OtrasPercepciones1Desc,
 OtrasPercepciones2,
 OtrasPercepciones2Desc,
 IdProvinciaDestino,
 IdIBCondicion,
 IdAutorizaAnulacion,
 IdPuntoVenta,
 NumeroCAI,
 FechaVencimientoCAI,
 NumeroCertificadoPercepcionIIBB,
 NumeroTicketInicial,
 NumeroTicketFinal,
 IdUsuarioIngreso,
 FechaIngreso,
 IdObra,
 IdIBCondicion2,
 IdIBCondicion3,
 IdCodigoIva,
 Exportacion_FOB,
 Exportacion_PosicionAduana,
 Exportacion_Despacho,
 Exportacion_Guia,
 Exportacion_IdPaisDestino,
 Exportacion_FechaEmbarque,
 Exportacion_FechaOficializacion,
 OtrasPercepciones3,
 OtrasPercepciones3Desc, NoIncluirEnCubos,
 PercepcionIVA,
 PorcentajePercepcionIVA,
 ActivarRecuperoGastos,
 IdAutorizoRecuperoGastos,
 ContabilizarAFechaVencimiento,
 FacturaContado,
 IdReciboContado,
 EnviarEmail,
 IdOrigenTransmision,
 IdFacturaOriginal,
 FechaImportacionTransmision,
 CuitClienteTransmision,
 IdReciboContadoOriginal,
 DevolucionAnticipo,
 PorcentajeDevolucionAnticipo,
 CAE,
 RechazoCAE,
 FechaVencimientoORechazoCAE,
 IdListaPrecios,
 IdIdentificacionCAE,
 AjusteIva,
 TipoExportacion,
 PermisoEmbarque,
 NumeroFacturaInicial,
 NumeroFacturaFinal,
 CodigoIdAuxiliar,
 NumeroCertificadoObra,
 ImporteCertificacionObra,
 FondoReparoCertificacionObra,
 PorcentajeRetencionesEstimadasCertificacionObra,
 NumeroExpedienteCertificacionObra,
 NumeroProyecto,
 IdCertificacionObras,
 IdCertificacionObraDatos,
 FechaRecepcionCliente,
 CuentaVentaLetra,
 CuentaVentaPuntoVenta,
 CuentaVentaNumero,
 IdDeposito,
 Cliente,
 OrigenRegistro,
 TotalBultos,
 IdDetalleClienteLugarEntrega,
 CuitClienteExterno,
 ComisionDiferenciada,
 IdTipoNegocioVentas,
 NumeroOrdenCompraExterna,
 IdTipoOperacion,
 FueEnviadoCorreoConFacturaElectronica
)
VALUES
( @NumeroFactura,
 @TipoABC,
 @PuntoVenta,
 @IdCliente,
 @FechaFactura,
 @IdCondicionVenta,
 @IdVendedor,
 @IdTransportista1,
 @IdTransportista2,
 @ItemDireccion,
 @OrdenCompra,
 @TipoPedidoConsignacion,
 @Anulada,
 @FechaAnulacion,
 @Observaciones,
 @IdRemito,
 @NumeroRemito,
 @IdPedido,
 @NumeroPedido,
 @ImporteTotal,
 @ImporteIva1,
 @ImporteIva2,
 @ImporteBonificacion,
 @RetencionIBrutos1,
 @PorcentajeIBrutos1,
 @RetencionIBrutos2,
 @PorcentajeIBrutos2,
 @ConvenioMultilateral,
 @RetencionIBrutos3,
 @PorcentajeIBrutos3,
 @IdTipoVentaC,
 @ImporteIvaIncluido,
 @CotizacionDolar,
 @EsMuestra,
 @CotizacionADolarFijo,
 @ImporteParteEnDolares,
 @ImporteParteEnPesos,
 @PorcentajeIva1,
 @PorcentajeIva2,
 @FechaVencimiento,
 @IVANoDiscriminado,
 @IdMoneda,
 @CotizacionMoneda,
 @PorcentajeBonificacion,
 @OtrasPercepciones1,
 @OtrasPercepciones1Desc,
 @OtrasPercepciones2,
 @OtrasPercepciones2Desc,
 @IdProvinciaDestino,
 @IdIBCondicion,
 @IdAutorizaAnulacion,
 @IdPuntoVenta,
 @NumeroCAI, @FechaVencimientoCAI, @NumeroCertificadoPercepcionIIBB,
 @NumeroTicketInicial,
 @NumeroTicketFinal, @IdUsuarioIngreso,
 @FechaIngreso,
 @IdObra,
 @IdIBCondicion2,
 @IdIBCondicion3,
 @IdCodigoIva,
 @Exportacion_FOB,
 @Exportacion_PosicionAduana,
 @Exportacion_Despacho,
 @Exportacion_Guia,
 @Exportacion_IdPaisDestino,
 @Exportacion_FechaEmbarque,
 @Exportacion_FechaOficializacion,
 @OtrasPercepciones3,
 @OtrasPercepciones3Desc,
 @NoIncluirEnCubos,
 @PercepcionIVA,
 @PorcentajePercepcionIVA,
 @ActivarRecuperoGastos,
 @IdAutorizoRecuperoGastos,
 @ContabilizarAFechaVencimiento,
 @FacturaContado,
 @IdReciboContado,
 @EnviarEmail,
 @IdOrigenTransmision,
 @IdFacturaOriginal,
 @FechaImportacionTransmision,
 @CuitClienteTransmision,
 @IdReciboContadoOriginal,
 @DevolucionAnticipo, @PorcentajeDevolucionAnticipo,
 @CAE,
 @RechazoCAE,
 @FechaVencimientoORechazoCAE,
 @IdListaPrecios,
 @IdIdentificacionCAE,
 @AjusteIva,
 @TipoExportacion,
 @PermisoEmbarque,
 @NumeroFacturaInicial,
 @NumeroFacturaFinal,
 @CodigoIdAuxiliar,
 @NumeroCertificadoObra,
 @ImporteCertificacionObra,
 @FondoReparoCertificacionObra,
 @PorcentajeRetencionesEstimadasCertificacionObra,
 @NumeroExpedienteCertificacionObra,
 @NumeroProyecto,
 @IdCertificacionObras,
 @IdCertificacionObraDatos,
 @FechaRecepcionCliente,
 @CuentaVentaLetra,
 @CuentaVentaPuntoVenta,
 @CuentaVentaNumero,
 @IdDeposito,
 @Cliente,
 @OrigenRegistro,
 @TotalBultos,
 @IdDetalleClienteLugarEntrega,
 @CuitClienteExterno,
 @ComisionDiferenciada,
 @IdTipoNegocioVentas,
 @NumeroOrdenCompraExterna,
 @IdTipoOperacion,
 @FueEnviadoCorreoConFacturaElectronica
)

SELECT @IdFactura=@@identity

RETURN(@IdFactura)