CREATE Procedure [dbo].[NotasDebito_A]

@IdNotaDebito int  output,
@NumeroNotaDebito int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdCliente int,
@FechaNotaDebito datetime,
@IdVendedor int,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@IdCodigoIva int,
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@Observaciones ntext,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@CtaCte varchar(2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@IVANoDiscriminado numeric(18,2),
@ConvenioMultilateral varchar(2),
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdProvinciaDestino int,
@IdIBCondicion int,
@IdPuntoVenta int,
@Anulada varchar(2),
@IdUsuarioAnulacion int,
@FechaAnulacion datetime,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@IdObra int,
@NumeroCertificadoPercepcionIIBB int,
@IdVentaEnCuotas int,
@NumeroCuota int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@AplicarEnCtaCte varchar(2),
@IdIBCondicion2 int,
@OtrasPercepciones3 numeric(18,2),
@OtrasPercepciones3Desc varchar(15),
@NoIncluirEnCubos varchar(2),
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@IdNotaCreditoVenta_RecuperoGastos int,
@IdListaPrecios int,
@IdIBCondicion3 int,
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@CAE varchar(14),
@RechazoCAE varchar(11),
@FechaVencimientoORechazoCAE datetime,
@IdIdentificacionCAE int

AS 

INSERT INTO [NotasDebito]
(
 NumeroNotaDebito,
 TipoABC,
 PuntoVenta,
 IdCliente,
 FechaNotaDebito,
 IdVendedor,
 ImporteTotal,
 ImporteIva1,
 ImporteIva2,
 RetencionIBrutos1,
 PorcentajeIBrutos1,
 RetencionIBrutos2,
 PorcentajeIBrutos2,
 IdCodigoIva,
 PorcentajeIva1,
 PorcentajeIva2,
 Observaciones,
 ImporteIvaIncluido,
 CotizacionDolar,
 CtaCte,
 IdMoneda,
 CotizacionMoneda,
 IVANoDiscriminado,
 ConvenioMultilateral,
 OtrasPercepciones1,
 OtrasPercepciones1Desc,
 OtrasPercepciones2,
 OtrasPercepciones2Desc,
 IdProvinciaDestino,
 IdIBCondicion,
 IdPuntoVenta,
 Anulada,
 IdUsuarioAnulacion,
 FechaAnulacion,
 NumeroCAI,
 FechaVencimientoCAI,
 IdObra,
 NumeroCertificadoPercepcionIIBB,
 IdVentaEnCuotas,
 NumeroCuota,
 IdUsuarioIngreso,
 FechaIngreso,
 AplicarEnCtaCte,
 IdIBCondicion2,
 OtrasPercepciones3,
 OtrasPercepciones3Desc,
 NoIncluirEnCubos,
 PercepcionIVA,
 PorcentajePercepcionIVA,
 IdNotaCreditoVenta_RecuperoGastos,
 IdListaPrecios,
 IdIBCondicion3,
 RetencionIBrutos3,
 PorcentajeIBrutos3,
 CAE,
 RechazoCAE,
 FechaVencimientoORechazoCAE,
 IdIdentificacionCAE
)
VALUES
(
 @NumeroNotaDebito,
 @TipoABC,
 @PuntoVenta,
 @IdCliente,
 @FechaNotaDebito,
 @IdVendedor,
 @ImporteTotal,
 @ImporteIva1,
 @ImporteIva2,
 @RetencionIBrutos1,
 @PorcentajeIBrutos1,
 @RetencionIBrutos2,
 @PorcentajeIBrutos2,
 @IdCodigoIva,
 @PorcentajeIva1,
 @PorcentajeIva2,
 @Observaciones,
 @ImporteIvaIncluido,
 @CotizacionDolar,
 @CtaCte,
 @IdMoneda,
 @CotizacionMoneda,
 @IVANoDiscriminado,
 @ConvenioMultilateral,
 @OtrasPercepciones1,
 @OtrasPercepciones1Desc,
 @OtrasPercepciones2,
 @OtrasPercepciones2Desc,
 @IdProvinciaDestino,
 @IdIBCondicion,
 @IdPuntoVenta,
 @Anulada,
 @IdUsuarioAnulacion,
 @FechaAnulacion,
 @NumeroCAI,
 @FechaVencimientoCAI,
 @IdObra,
 @NumeroCertificadoPercepcionIIBB,
 @IdVentaEnCuotas,
 @NumeroCuota,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @AplicarEnCtaCte,
 @IdIBCondicion2,
 @OtrasPercepciones3,
 @OtrasPercepciones3Desc,
 @NoIncluirEnCubos,
 @PercepcionIVA,
 @PorcentajePercepcionIVA,
 @IdNotaCreditoVenta_RecuperoGastos,
 @IdListaPrecios,
 @IdIBCondicion3,
 @RetencionIBrutos3,
 @PorcentajeIBrutos3,
 @CAE,
 @RechazoCAE,
 @FechaVencimientoORechazoCAE,
 @IdIdentificacionCAE
 )

SELECT @IdNotaDebito=@@identity
RETURN(@IdNotaDebito)