CREATE Procedure [dbo].[NotasDebito_M]

@IdNotaDebito int,
@NumeroNotaDebito int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdCliente int,
@FechaNotaDebito datetime,
@IdVendedor int,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@IdCodigoIva int,
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@Observaciones ntext,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@CtaCte varchar(2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@IVANoDiscriminado numeric(18,2),
@ConvenioMultilateral varchar(2),
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdProvinciaDestino int,
@IdIBCondicion int,
@IdPuntoVenta int,
@Anulada varchar(2),
@IdUsuarioAnulacion int,
@FechaAnulacion datetime,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@IdObra int,
@NumeroCertificadoPercepcionIIBB int,
@IdVentaEnCuotas int,
@NumeroCuota int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@AplicarEnCtaCte varchar(2),
@IdIBCondicion2 int,
@OtrasPercepciones3 numeric(18,2),
@OtrasPercepciones3Desc varchar(15),
@NoIncluirEnCubos varchar(2),
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@IdNotaCreditoVenta_RecuperoGastos int,
@IdListaPrecios int,
@IdIBCondicion3 int,
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@CAE varchar(14),
@RechazoCAE varchar(11),
@FechaVencimientoORechazoCAE datetime,
@IdIdentificacionCAE int

AS 

UPDATE NotasDebito
SET 
 NumeroNotaDebito=@NumeroNotaDebito,
 TipoABC=@TipoABC,
 PuntoVenta=@PuntoVenta,
 IdCliente=@IdCliente,
 FechaNotaDebito=@FechaNotaDebito,
 IdVendedor=@IdVendedor,
 ImporteTotal=@ImporteTotal,
 ImporteIva1=@ImporteIva1,
 ImporteIva2=@ImporteIva2,
 RetencionIBrutos1=@RetencionIBrutos1,
 PorcentajeIBrutos1=@PorcentajeIBrutos1,
 RetencionIBrutos2=@RetencionIBrutos2,
 PorcentajeIBrutos2=@PorcentajeIBrutos2,
 IdCodigoIva=@IdCodigoIva,
 PorcentajeIva1=@PorcentajeIva1,
 PorcentajeIva2=@PorcentajeIva2,
 Observaciones=@Observaciones,
 ImporteIvaIncluido=@ImporteIvaIncluido,
 CotizacionDolar=@CotizacionDolar,
 CtaCte=@CtaCte,
 IdMoneda=@IdMoneda,
 CotizacionMoneda=@CotizacionMoneda,
 IVANoDiscriminado=@IVANoDiscriminado,
 ConvenioMultilateral=@ConvenioMultilateral,
 OtrasPercepciones1=@OtrasPercepciones1,
 OtrasPercepciones1Desc=@OtrasPercepciones1Desc,
 OtrasPercepciones2=@OtrasPercepciones2,
 OtrasPercepciones2Desc=@OtrasPercepciones2Desc,
 IdProvinciaDestino=@IdProvinciaDestino,
 IdIBCondicion=@IdIBCondicion,
 IdPuntoVenta=@IdPuntoVenta,
 Anulada=@Anulada,
 IdUsuarioAnulacion=@IdUsuarioAnulacion,
 FechaAnulacion=@FechaAnulacion,
 NumeroCAI=@NumeroCAI,
 FechaVencimientoCAI=@FechaVencimientoCAI,
 IdObra=@IdObra,
 NumeroCertificadoPercepcionIIBB=@NumeroCertificadoPercepcionIIBB,
 IdVentaEnCuotas=@IdVentaEnCuotas,
 NumeroCuota=@NumeroCuota,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 AplicarEnCtaCte=@AplicarEnCtaCte,
 IdIBCondicion2=@IdIBCondicion2,
 OtrasPercepciones3=@OtrasPercepciones3,
 OtrasPercepciones3Desc=@OtrasPercepciones3Desc,
 NoIncluirEnCubos=@NoIncluirEnCubos,
 PercepcionIVA=@PercepcionIVA,
 PorcentajePercepcionIVA=@PorcentajePercepcionIVA,
 IdNotaCreditoVenta_RecuperoGastos=@IdNotaCreditoVenta_RecuperoGastos,
 IdListaPrecios=@IdListaPrecios,
 IdIBCondicion3=@IdIBCondicion3,
 RetencionIBrutos3=@RetencionIBrutos3,
 PorcentajeIBrutos3=@PorcentajeIBrutos3,
 CAE=@CAE,
 RechazoCAE=@RechazoCAE,
 FechaVencimientoORechazoCAE=@FechaVencimientoORechazoCAE,
 IdIdentificacionCAE=@IdIdentificacionCAE
WHERE (IdNotaDebito=@IdNotaDebito)

RETURN(@IdNotaDebito)