CREATE Procedure [dbo].[NotasCredito_A]

@IdNotaCredito int  output,
@NumeroNotaCredito int,
@TipoABC varchar(1),
@PuntoVenta smallint,
@IdCliente int,
@FechaNotaCredito datetime,
@IdVendedor int,
@ImporteTotal numeric(18,2),
@ImporteIva1 numeric(18,2),
@ImporteIva2 numeric(18,2),
@RetencionIBrutos1 numeric(18,2),
@PorcentajeIBrutos1 numeric(6,2),
@RetencionIBrutos2 numeric(18,2),
@PorcentajeIBrutos2 numeric(6,2),
@IdCodigoIva int,
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@Observaciones ntext,
@ImporteIvaIncluido numeric(18,2),
@CotizacionDolar numeric(18,3),
@CtaCte varchar(2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@IVANoDiscriminado numeric(18,2),
@ConvenioMultilateral varchar(2),
@OtrasPercepciones1 numeric(18,2),
@OtrasPercepciones1Desc varchar(15),
@OtrasPercepciones2 numeric(18,2),
@OtrasPercepciones2Desc varchar(15),
@IdProvinciaDestino int,
@IdIBCondicion int,
@IdPuntoVenta int,
@Anulada varchar(2),
@IdUsuarioAnulacion int,
@FechaAnulacion datetime,
@NumeroCAI numeric(19,0),
@FechaVencimientoCAI datetime,
@IdObra int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@AplicarEnCtaCte varchar(2),
@IdIBCondicion2 int,
@OtrasPercepciones3 numeric(18,2),
@OtrasPercepciones3Desc varchar(15),
@NoIncluirEnCubos varchar(2),
@PercepcionIVA numeric(18,2),
@PorcentajePercepcionIVA numeric(6,2),
@ActivarRecuperoGastos varchar(2),
@IdAutorizoRecuperoGastos int,
@IdFacturaVenta_RecuperoGastos int,
@IdListaPrecios int,
@IdIBCondicion3 int,
@RetencionIBrutos3 numeric(18,2),
@PorcentajeIBrutos3 numeric(6,2),
@CAE varchar(14),
@RechazoCAE varchar(11),
@FechaVencimientoORechazoCAE datetime,
@IdIdentificacionCAE int,
@CodigoIdAuxiliar int,
@NumeroFacturaOriginal int,
@FechaRecepcionCliente datetime,
@LiberarCartasDePorte varchar(2),
@CuentaVentaLetra varchar(1),
@CuentaVentaPuntoVenta int,
@CuentaVentaNumero int,
@IdTipoOperacion int

AS

INSERT INTO [NotasCredito]
(
 NumeroNotaCredito,
 TipoABC,
 PuntoVenta,
 IdCliente,
 FechaNotaCredito,
 IdVendedor,
 ImporteTotal,
 ImporteIva1,
 ImporteIva2,
 RetencionIBrutos1,
 PorcentajeIBrutos1,
 RetencionIBrutos2,
 PorcentajeIBrutos2,
 IdCodigoIva,
 PorcentajeIva1,
 PorcentajeIva2,
 Observaciones,
 ImporteIvaIncluido,
 CotizacionDolar,
 CtaCte,
 IdMoneda,
 CotizacionMoneda,
 IVANoDiscriminado,
 ConvenioMultilateral,
 OtrasPercepciones1,
 OtrasPercepciones1Desc,
 OtrasPercepciones2,
 OtrasPercepciones2Desc,
 IdProvinciaDestino,
 IdIBCondicion,
 IdPuntoVenta,
 Anulada,
 IdUsuarioAnulacion,
 FechaAnulacion,
 NumeroCAI,
 FechaVencimientoCAI,
 IdObra,
 IdUsuarioIngreso,
 FechaIngreso,
 AplicarEnCtaCte,
 IdIBCondicion2,
 OtrasPercepciones3,
 OtrasPercepciones3Desc,
 NoIncluirEnCubos,
 PercepcionIVA,
 PorcentajePercepcionIVA,
 ActivarRecuperoGastos,
 IdAutorizoRecuperoGastos,
 IdFacturaVenta_RecuperoGastos,
 IdListaPrecios,
 IdIBCondicion3,
 RetencionIBrutos3,
 PorcentajeIBrutos3,
 CAE,
 RechazoCAE,
 FechaVencimientoORechazoCAE,
 IdIdentificacionCAE,
 CodigoIdAuxiliar,
 NumeroFacturaOriginal,
 FechaRecepcionCliente,
 LiberarCartasDePorte,
 CuentaVentaLetra,
 CuentaVentaPuntoVenta,
 CuentaVentaNumero,
 IdTipoOperacion
)
VALUES
(
 @NumeroNotaCredito,
 @TipoABC,
 @PuntoVenta,
 @IdCliente,
 @FechaNotaCredito,
 @IdVendedor,
 @ImporteTotal,
 @ImporteIva1,
 @ImporteIva2,
 @RetencionIBrutos1,
 @PorcentajeIBrutos1,
 @RetencionIBrutos2,
 @PorcentajeIBrutos2,
 @IdCodigoIva,
 @PorcentajeIva1,
 @PorcentajeIva2,
 @Observaciones,
 @ImporteIvaIncluido,
 @CotizacionDolar,
 @CtaCte,
 @IdMoneda,
 @CotizacionMoneda,
 @IVANoDiscriminado,
 @ConvenioMultilateral,
 @OtrasPercepciones1,
 @OtrasPercepciones1Desc,
 @OtrasPercepciones2,
 @OtrasPercepciones2Desc,
 @IdProvinciaDestino,
 @IdIBCondicion,
 @IdPuntoVenta,
 @Anulada,
 @IdUsuarioAnulacion,
 @FechaAnulacion,
 @NumeroCAI,
 @FechaVencimientoCAI,
 @IdObra,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @AplicarEnCtaCte,
 @IdIBCondicion2,
 @OtrasPercepciones3,
 @OtrasPercepciones3Desc,
 @NoIncluirEnCubos,
 @PercepcionIVA,
 @PorcentajePercepcionIVA,
 @ActivarRecuperoGastos,
 @IdAutorizoRecuperoGastos,
 @IdFacturaVenta_RecuperoGastos,
 @IdListaPrecios,
 @IdIBCondicion3,
 @RetencionIBrutos3,
 @PorcentajeIBrutos3,
 @CAE,
 @RechazoCAE,
 @FechaVencimientoORechazoCAE,
 @IdIdentificacionCAE,
 @CodigoIdAuxiliar,
 @NumeroFacturaOriginal,
 @FechaRecepcionCliente,
 @LiberarCartasDePorte,
 @CuentaVentaLetra,
 @CuentaVentaPuntoVenta,
 @CuentaVentaNumero,
 @IdTipoOperacion
)

SELECT @IdNotaCredito=@@identity

RETURN(@IdNotaCredito)