CREATE Procedure [dbo].[OrdenesPago_M]

@IdOrdenPago int,
@NumeroOrdenPago int,
@FechaOrdenPago datetime,
@IdProveedor int,
@Efectivo numeric(12,2),
@Descuentos numeric(12,2),
@Valores numeric(12,2),
@Documentos numeric(12,2),
@Otros1 numeric(12,2),
@IdCuenta1 int,
@Otros2 numeric(12,2),
@IdCuenta2 int,
@Otros3 numeric(12,2),
@IdCuenta3 int,
@Acreedores numeric(12,2),
@RetencionIVA numeric(12,2),
@RetencionGanancias numeric(12,2),
@RetencionIBrutos numeric(12,2),
@GastosGenerales numeric(12,2),
@Estado varchar(2),
@IdCuenta int,
@Tipo varchar(2),
@Anulada varchar(2),
@CotizacionDolar numeric(18,4),
@Dolarizada varchar(2),
@Exterior varchar(2),
@NumeroCertificadoRetencionGanancias int,
@BaseGanancias numeric(18,2),
@IdMoneda int,
@CotizacionMoneda numeric(18,4),
@AsientoManual varchar(2),
@Observaciones ntext,
@IdObra int,
@IdCuentaGasto int,
@DiferenciaBalanceo numeric(18,2),
@IdOPComplementariaFF int,
@IdEmpleadoFF int,
@NumeroCertificadoRetencionIVA int,
@NumeroCertificadoRetencionIIBB int,
@RetencionSUSS numeric(18,2),
@NumeroCertificadoRetencionSUSS int,
@TipoOperacionOtros int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@Confirmado varchar(2),
@IdObraOrigen int,
@CotizacionEuro numeric(18,4),
@TipoGrabacion varchar(1),
@IdProvinciaDestino int,
@CalculaSUSS varchar(2),
@RetencionIVAComprobantesM numeric(18,2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@NumeroRendicionFF int,
@ConfirmacionAcreditacionFF varchar(2),
@OPInicialFF varchar(2),
@IdConcepto int,
@IdConcepto2 int,
@FormaAnulacionCheques varchar(1),
@Detalle varchar(20),
@RecalculoRetencionesUltimaModificacion varchar(2),
@IdImpuestoDirecto int,
@NumeroReciboProveedor int,
@FechaReciboProveedor datetime,
@TextoAuxiliar1 varchar(100),
@TextoAuxiliar2 varchar(100),
@TextoAuxiliar3 varchar(100),
@IdsComprobanteProveedorRetenidosIva varchar(100),
@TotalesImportesRetenidosIva varchar(100),
@ReversionContablePorAnulacion varchar(2)

AS

UPDATE OrdenesPago
SET 
 NumeroOrdenPago=@NumeroOrdenPago,
 FechaOrdenPago=@FechaOrdenPago,
 IdProveedor=@IdProveedor,
 Efectivo=@Efectivo,
 Descuentos=@Descuentos,
 Valores=@Valores,
 Documentos=@Documentos,
 Otros1=@Otros1,
 IdCuenta1=@IdCuenta1,
 Otros2=@Otros2,
 IdCuenta2=@IdCuenta2,
 Otros3=@Otros3,
 IdCuenta3=@IdCuenta3,
 Acreedores=@Acreedores,
 RetencionIVA=@RetencionIVA,
 RetencionGanancias=@RetencionGanancias,
 RetencionIBrutos=@RetencionIBrutos,
 GastosGenerales=@GastosGenerales,
 Estado=@Estado,
 IdCuenta=@IdCuenta,
 Tipo=@Tipo,
 Anulada=@Anulada,
 CotizacionDolar=@CotizacionDolar,
 Dolarizada=@Dolarizada,
 Exterior=@Exterior,
 NumeroCertificadoRetencionGanancias=@NumeroCertificadoRetencionGanancias,
 BaseGanancias=@BaseGanancias,
 IdMoneda=@IdMoneda,
 CotizacionMoneda=@CotizacionMoneda,
 AsientoManual=@AsientoManual,
 Observaciones=@Observaciones,
 IdObra=@IdObra,
 IdCuentaGasto=@IdCuentaGasto,
 DiferenciaBalanceo=@DiferenciaBalanceo,
 IdOPComplementariaFF=@IdOPComplementariaFF,
 IdEmpleadoFF=@IdEmpleadoFF,
 NumeroCertificadoRetencionIVA=@NumeroCertificadoRetencionIVA,
 NumeroCertificadoRetencionIIBB=@NumeroCertificadoRetencionIIBB,
 RetencionSUSS=@RetencionSUSS,
 NumeroCertificadoRetencionSUSS=@NumeroCertificadoRetencionSUSS,
 TipoOperacionOtros=@TipoOperacionOtros,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaModifico=@FechaModifico,
 Confirmado=@Confirmado,
 IdObraOrigen=@IdObraOrigen,
 CotizacionEuro=@CotizacionEuro,
 TipoGrabacion=@TipoGrabacion,
 IdProvinciaDestino=@IdProvinciaDestino,
 CalculaSUSS=@CalculaSUSS,
 RetencionIVAComprobantesM=@RetencionIVAComprobantesM,
 IdUsuarioAnulo=@IdUsuarioAnulo,
 FechaAnulacion=@FechaAnulacion,
 MotivoAnulacion=@MotivoAnulacion,
 NumeroRendicionFF=@NumeroRendicionFF,
 ConfirmacionAcreditacionFF=@ConfirmacionAcreditacionFF,
 OPInicialFF=@OPInicialFF,
 IdConcepto=@IdConcepto,
 IdConcepto2=@IdConcepto2,
 FormaAnulacionCheques=@FormaAnulacionCheques,
 Detalle=@Detalle,
 RecalculoRetencionesUltimaModificacion=@RecalculoRetencionesUltimaModificacion,
 IdImpuestoDirecto=@IdImpuestoDirecto,
 NumeroReciboProveedor=@NumeroReciboProveedor,
 FechaReciboProveedor=@FechaReciboProveedor,
 TextoAuxiliar1=@TextoAuxiliar1,
 TextoAuxiliar2=@TextoAuxiliar2,
 TextoAuxiliar3=@TextoAuxiliar3,
 IdsComprobanteProveedorRetenidosIva=@IdsComprobanteProveedorRetenidosIva,
 TotalesImportesRetenidosIva=@TotalesImportesRetenidosIva,
 ReversionContablePorAnulacion=@ReversionContablePorAnulacion
WHERE (IdOrdenPago=@IdOrdenPago)

RETURN(@IdOrdenPago)