CREATE Procedure [dbo].[OrdenesCompra_A]

@IdOrdenCompra int  output,
@NumeroOrdenCompra int,
@IdCliente int,
@FechaOrdenCompra datetime,
@IdCondicionVenta int,
@Anulada varchar(2),
@FechaAnulacion datetime,
@Observaciones ntext,
@ImporteTotal numeric(18,2),
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@NumeroOrdenCompraCliente varchar(20),
@IdObra int,
@IdMoneda int,
@IdUsuarioAnulacion int,
@AgrupacionFacturacion int,
@Agrupacion2Facturacion int,
@SeleccionadaParaFacturacion varchar(2),
@PorcentajeBonificacion numeric(6,2),
@IdListaPrecios int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@Aprobo int,
@FechaAprobacion datetime,
@CircuitoFirmasCompleto varchar(2),
@IdDetalleClienteLugarEntrega int,
@Estado varchar(2),
@IdUsuarioCambioEstado int,
@FechaCambioEstado datetime

AS 

INSERT INTO OrdenesCompra
(
 NumeroOrdenCompra,
 IdCliente,
 FechaOrdenCompra,
 IdCondicionVenta,
 Anulada,
 FechaAnulacion,
 Observaciones,
 ImporteTotal,
 ArchivoAdjunto1,
 ArchivoAdjunto2,
 ArchivoAdjunto3,
 ArchivoAdjunto4,
 ArchivoAdjunto5,
 ArchivoAdjunto6,
 ArchivoAdjunto7,
 ArchivoAdjunto8,
 ArchivoAdjunto9,
 ArchivoAdjunto10,
 NumeroOrdenCompraCliente,
 IdObra,
 IdMoneda,
 IdUsuarioAnulacion,
 AgrupacionFacturacion,
 Agrupacion2Facturacion,
 SeleccionadaParaFacturacion,
 PorcentajeBonificacion,
 IdListaPrecios,
 IdUsuarioIngreso,
 FechaIngreso,
 IdUsuarioModifico,
 FechaModifico,
 Aprobo,
 FechaAprobacion,
 CircuitoFirmasCompleto,
 IdDetalleClienteLugarEntrega,
 Estado,
 IdUsuarioCambioEstado,
 FechaCambioEstado
)
VALUES
(
 @NumeroOrdenCompra,
 @IdCliente,
 @FechaOrdenCompra,
 @IdCondicionVenta,
 @Anulada,
 @FechaAnulacion,
 @Observaciones,
 @ImporteTotal,
 @ArchivoAdjunto1,
 @ArchivoAdjunto2,
 @ArchivoAdjunto3,
 @ArchivoAdjunto4,
 @ArchivoAdjunto5,
 @ArchivoAdjunto6,
 @ArchivoAdjunto7,
 @ArchivoAdjunto8,
 @ArchivoAdjunto9,
 @ArchivoAdjunto10,
 @NumeroOrdenCompraCliente,
 @IdObra,
 @IdMoneda,
 @IdUsuarioAnulacion,
 @AgrupacionFacturacion,
 @Agrupacion2Facturacion,
 @SeleccionadaParaFacturacion,
 @PorcentajeBonificacion,
 @IdListaPrecios,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @IdUsuarioModifico,
 @FechaModifico,
 @Aprobo,
 @FechaAprobacion,
 @CircuitoFirmasCompleto,
 @IdDetalleClienteLugarEntrega,
 @Estado,
 @IdUsuarioCambioEstado,
 @FechaCambioEstado
)

SELECT @IdOrdenCompra=@@identity

RETURN(@IdOrdenCompra)