//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoMVC.Data.Models.Mantenimiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartesDiarios
    {
        public int IdParteDiario { get; set; }
        public Nullable<int> NumeroParteDiario { get; set; }
        public Nullable<System.DateTime> FechaParteDiario { get; set; }
        public Nullable<int> IdObra { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdParteDiarioOriginal { get; set; }
        public Nullable<int> IdOrigenTransmision { get; set; }
        public Nullable<System.DateTime> FechaImportacion { get; set; }
    }
}
