// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ProntoMVC.Controllers
{
    public partial class CuentaController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CuentaController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CuentaController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCuentasAutocomplete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCuentasGastoAutocomplete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasGastoAutocomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCodigosCuentasAutocomplete2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosCuentasAutocomplete2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCodigosCuentasGastoAutocomplete2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosCuentasGastoAutocomplete2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCuentasFFAutocomplete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasFFAutocomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCuentasAutocomplete2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCuentasAutocomplete3()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete3);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Cuentas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cuentas);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult AddToEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CuentaController Actions { get { return MVC.Cuenta; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Cuenta";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Cuenta";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetCuentasAutocomplete = "GetCuentasAutocomplete";
            public readonly string GetCuentasGastoAutocomplete = "GetCuentasGastoAutocomplete";
            public readonly string GetCodigosCuentasAutocomplete2 = "GetCodigosCuentasAutocomplete2";
            public readonly string GetCodigosCuentasGastoAutocomplete2 = "GetCodigosCuentasGastoAutocomplete2";
            public readonly string GetCuentasFFAutocomplete = "GetCuentasFFAutocomplete";
            public readonly string GetCuentasAutocomplete2 = "GetCuentasAutocomplete2";
            public readonly string GetCuentasAutocomplete3 = "GetCuentasAutocomplete3";
            public readonly string Cuentas = "Cuentas";
            public readonly string Index = "Index";
            public readonly string IndexFF = "IndexFF";
            public readonly string AddToEmpresa = "AddToEmpresa";
            public readonly string RemoveFromEmpresa = "RemoveFromEmpresa";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetCuentasAutocomplete = "GetCuentasAutocomplete";
            public const string GetCuentasGastoAutocomplete = "GetCuentasGastoAutocomplete";
            public const string GetCodigosCuentasAutocomplete2 = "GetCodigosCuentasAutocomplete2";
            public const string GetCodigosCuentasGastoAutocomplete2 = "GetCodigosCuentasGastoAutocomplete2";
            public const string GetCuentasFFAutocomplete = "GetCuentasFFAutocomplete";
            public const string GetCuentasAutocomplete2 = "GetCuentasAutocomplete2";
            public const string GetCuentasAutocomplete3 = "GetCuentasAutocomplete3";
            public const string Cuentas = "Cuentas";
            public const string Index = "Index";
            public const string IndexFF = "IndexFF";
            public const string AddToEmpresa = "AddToEmpresa";
            public const string RemoveFromEmpresa = "RemoveFromEmpresa";
        }


        static readonly ActionParamsClass_GetCuentasAutocomplete s_params_GetCuentasAutocomplete = new ActionParamsClass_GetCuentasAutocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCuentasAutocomplete GetCuentasAutocompleteParams { get { return s_params_GetCuentasAutocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCuentasAutocomplete
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCuentasGastoAutocomplete s_params_GetCuentasGastoAutocomplete = new ActionParamsClass_GetCuentasGastoAutocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCuentasGastoAutocomplete GetCuentasGastoAutocompleteParams { get { return s_params_GetCuentasGastoAutocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCuentasGastoAutocomplete
        {
            public readonly string term = "term";
            public readonly string obra = "obra";
        }
        static readonly ActionParamsClass_GetCodigosCuentasAutocomplete2 s_params_GetCodigosCuentasAutocomplete2 = new ActionParamsClass_GetCodigosCuentasAutocomplete2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCodigosCuentasAutocomplete2 GetCodigosCuentasAutocomplete2Params { get { return s_params_GetCodigosCuentasAutocomplete2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCodigosCuentasAutocomplete2
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCodigosCuentasGastoAutocomplete2 s_params_GetCodigosCuentasGastoAutocomplete2 = new ActionParamsClass_GetCodigosCuentasGastoAutocomplete2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCodigosCuentasGastoAutocomplete2 GetCodigosCuentasGastoAutocomplete2Params { get { return s_params_GetCodigosCuentasGastoAutocomplete2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCodigosCuentasGastoAutocomplete2
        {
            public readonly string term = "term";
            public readonly string obra = "obra";
        }
        static readonly ActionParamsClass_GetCuentasFFAutocomplete s_params_GetCuentasFFAutocomplete = new ActionParamsClass_GetCuentasFFAutocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCuentasFFAutocomplete GetCuentasFFAutocompleteParams { get { return s_params_GetCuentasFFAutocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCuentasFFAutocomplete
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCuentasAutocomplete2 s_params_GetCuentasAutocomplete2 = new ActionParamsClass_GetCuentasAutocomplete2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCuentasAutocomplete2 GetCuentasAutocomplete2Params { get { return s_params_GetCuentasAutocomplete2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCuentasAutocomplete2
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCuentasAutocomplete3 s_params_GetCuentasAutocomplete3 = new ActionParamsClass_GetCuentasAutocomplete3();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCuentasAutocomplete3 GetCuentasAutocomplete3Params { get { return s_params_GetCuentasAutocomplete3; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCuentasAutocomplete3
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_Cuentas s_params_Cuentas = new ActionParamsClass_Cuentas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Cuentas CuentasParams { get { return s_params_Cuentas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Cuentas
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
            public readonly string FechaInicial = "FechaInicial";
            public readonly string FechaFinal = "FechaFinal";
            public readonly string IdObra = "IdObra";
        }
        static readonly ActionParamsClass_AddToEmpresa s_params_AddToEmpresa = new ActionParamsClass_AddToEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToEmpresa AddToEmpresaParams { get { return s_params_AddToEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ActionParamsClass_RemoveFromEmpresa s_params_RemoveFromEmpresa = new ActionParamsClass_RemoveFromEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveFromEmpresa RemoveFromEmpresaParams { get { return s_params_RemoveFromEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveFromEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Edit = "Edit";
                public readonly string EditExterno = "EditExterno";
                public readonly string Index = "Index";
                public readonly string IndexExterno = "IndexExterno";
                public readonly string IndexFF = "IndexFF";
            }
            public readonly string Edit = "~/Views/Cuenta/Edit.cshtml";
            public readonly string EditExterno = "~/Views/Cuenta/EditExterno.cshtml";
            public readonly string Index = "~/Views/Cuenta/Index.cshtml";
            public readonly string IndexExterno = "~/Views/Cuenta/IndexExterno.cshtml";
            public readonly string IndexFF = "~/Views/Cuenta/IndexFF.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CuentaController : ProntoMVC.Controllers.CuentaController
    {
        public T4MVC_CuentaController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetCuentasAutocompleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCuentasAutocomplete(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCuentasAutocompleteOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCuentasGastoAutocompleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string term, int obra);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCuentasGastoAutocomplete(string term, int obra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasGastoAutocomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "obra", obra);
            GetCuentasGastoAutocompleteOverride(callInfo, term, obra);
            return callInfo;
        }

        [NonAction]
        partial void GetCodigosCuentasAutocomplete2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCodigosCuentasAutocomplete2(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosCuentasAutocomplete2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCodigosCuentasAutocomplete2Override(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCodigosCuentasGastoAutocomplete2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string term, int obra);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCodigosCuentasGastoAutocomplete2(string term, int obra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosCuentasGastoAutocomplete2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "obra", obra);
            GetCodigosCuentasGastoAutocomplete2Override(callInfo, term, obra);
            return callInfo;
        }

        [NonAction]
        partial void GetCuentasFFAutocompleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCuentasFFAutocomplete(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasFFAutocomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCuentasFFAutocompleteOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCuentasAutocomplete2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCuentasAutocomplete2(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCuentasAutocomplete2Override(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCuentasAutocomplete3Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCuentasAutocomplete3(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCuentasAutocomplete3);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCuentasAutocomplete3Override(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void CuentasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cuentas(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cuentas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaInicial", FechaInicial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaFinal", FechaFinal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IdObra", IdObra);
            CuentasOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString, FechaInicial, FechaFinal, IdObra);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexFFOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexFF()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexFF);
            IndexFFOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddToEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult AddToEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            AddToEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

        [NonAction]
        partial void RemoveFromEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            RemoveFromEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
