// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace jqGridWeb.Controllers
{
    public partial class jqGridPaginacionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public jqGridPaginacionController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected jqGridPaginacionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DynamicGridData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DynamicGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult grilladinamica_CuentasFF()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.grilladinamica_CuentasFF);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult AddToEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public jqGridPaginacionController Actions { get { return MVC.jqGridPaginacion; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "jqGridPaginacion";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "jqGridPaginacion";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DynamicGridData = "DynamicGridData";
            public readonly string grilladinamica_CuentasFF = "grilladinamica_CuentasFF";
            public readonly string About = "About";
            public readonly string AddToEmpresa = "AddToEmpresa";
            public readonly string RemoveFromEmpresa = "RemoveFromEmpresa";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DynamicGridData = "DynamicGridData";
            public const string grilladinamica_CuentasFF = "grilladinamica_CuentasFF";
            public const string About = "About";
            public const string AddToEmpresa = "AddToEmpresa";
            public const string RemoveFromEmpresa = "RemoveFromEmpresa";
        }


        static readonly ActionParamsClass_DynamicGridData s_params_DynamicGridData = new ActionParamsClass_DynamicGridData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DynamicGridData DynamicGridDataParams { get { return s_params_DynamicGridData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DynamicGridData
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_grilladinamica_CuentasFF s_params_grilladinamica_CuentasFF = new ActionParamsClass_grilladinamica_CuentasFF();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_grilladinamica_CuentasFF grilladinamica_CuentasFFParams { get { return s_params_grilladinamica_CuentasFF; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_grilladinamica_CuentasFF
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_AddToEmpresa s_params_AddToEmpresa = new ActionParamsClass_AddToEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToEmpresa AddToEmpresaParams { get { return s_params_AddToEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ActionParamsClass_RemoveFromEmpresa s_params_RemoveFromEmpresa = new ActionParamsClass_RemoveFromEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveFromEmpresa RemoveFromEmpresaParams { get { return s_params_RemoveFromEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveFromEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_jqGridPaginacionController : jqGridWeb.Controllers.jqGridPaginacionController
    {
        public T4MVC_jqGridPaginacionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DynamicGridDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string sidx, string sord, int page, int rows, bool _search, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult DynamicGridData(string sidx, string sord, int page, int rows, bool _search, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DynamicGridData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            DynamicGridDataOverride(callInfo, sidx, sord, page, rows, _search, filters);
            return callInfo;
        }

        [NonAction]
        partial void grilladinamica_CuentasFFOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string sidx, string sord, int page, int rows, bool _search, string searchField, string searchOper, string searchString, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult grilladinamica_CuentasFF(string sidx, string sord, int page, int rows, bool _search, string searchField, string searchOper, string searchString, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.grilladinamica_CuentasFF);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            grilladinamica_CuentasFFOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString, filters);
            return callInfo;
        }

        [NonAction]
        partial void AboutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult About()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.About);
            AboutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddToEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult AddToEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            AddToEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

        [NonAction]
        partial void RemoveFromEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            RemoveFromEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
