// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ProntoMVC.Controllers
{
    public partial class ObraController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ObraController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ObraController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Details()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult BatchUpdate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.BatchUpdate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IBCondicionPorId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IBCondicionPorId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Obras()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Obras);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArticulosGridDataResumido()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridDataResumido);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult Imprimir()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.Imprimir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RefrescarMascara()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefrescarMascara);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteConfirmed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetDocumentos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetDocumentos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetUnidades()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetUnidades);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Uploadfile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Uploadfile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UpdateAwesomeGridData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateAwesomeGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemitosPendienteArticulocion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemitosPendienteArticulocion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OrdenesCompraPendientesArticulor()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrdenesCompraPendientesArticulor);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArticulosGridDataSP()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridDataSP);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArticulosGridData2()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridData2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult AddToEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ObraController Actions { get { return MVC.Obra; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Obra";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Obra";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Details = "Details";
            public readonly string IndexResumido = "IndexResumido";
            public readonly string BatchUpdate = "BatchUpdate";
            public readonly string IBCondicionPorId = "IBCondicionPorId";
            public readonly string Obras = "Obras";
            public readonly string ArticulosGridDataResumido = "ArticulosGridDataResumido";
            public readonly string Imprimir = "Imprimir";
            public readonly string Edit = "Edit";
            public readonly string RefrescarMascara = "RefrescarMascara";
            public readonly string Delete = "Delete";
            public readonly string DeleteConfirmed = "Delete";
            public readonly string DetDocumentos = "DetDocumentos";
            public readonly string DetUnidades = "DetUnidades";
            public readonly string Uploadfile = "Uploadfile";
            public readonly string UpdateAwesomeGridData = "UpdateAwesomeGridData";
            public readonly string RemitosPendienteArticulocion = "RemitosPendienteArticulocion";
            public readonly string OrdenesCompraPendientesArticulor = "OrdenesCompraPendientesArticulor";
            public readonly string Articulos = "Articulos";
            public readonly string GetUnidades = "GetUnidades";
            public readonly string Unidades = "Unidades";
            public readonly string ArticulosGridDataSP = "ArticulosGridDataSP";
            public readonly string ArticulosGridData2 = "ArticulosGridData2";
            public readonly string AddToEmpresa = "AddToEmpresa";
            public readonly string RemoveFromEmpresa = "RemoveFromEmpresa";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Details = "Details";
            public const string IndexResumido = "IndexResumido";
            public const string BatchUpdate = "BatchUpdate";
            public const string IBCondicionPorId = "IBCondicionPorId";
            public const string Obras = "Obras";
            public const string ArticulosGridDataResumido = "ArticulosGridDataResumido";
            public const string Imprimir = "Imprimir";
            public const string Edit = "Edit";
            public const string RefrescarMascara = "RefrescarMascara";
            public const string Delete = "Delete";
            public const string DeleteConfirmed = "Delete";
            public const string DetDocumentos = "DetDocumentos";
            public const string DetUnidades = "DetUnidades";
            public const string Uploadfile = "Uploadfile";
            public const string UpdateAwesomeGridData = "UpdateAwesomeGridData";
            public const string RemitosPendienteArticulocion = "RemitosPendienteArticulocion";
            public const string OrdenesCompraPendientesArticulor = "OrdenesCompraPendientesArticulor";
            public const string Articulos = "Articulos";
            public const string GetUnidades = "GetUnidades";
            public const string Unidades = "Unidades";
            public const string ArticulosGridDataSP = "ArticulosGridDataSP";
            public const string ArticulosGridData2 = "ArticulosGridData2";
            public const string AddToEmpresa = "AddToEmpresa";
            public const string RemoveFromEmpresa = "RemoveFromEmpresa";
        }


        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_BatchUpdate s_params_BatchUpdate = new ActionParamsClass_BatchUpdate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BatchUpdate BatchUpdateParams { get { return s_params_BatchUpdate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BatchUpdate
        {
            public readonly string Articulo = "Articulo";
        }
        static readonly ActionParamsClass_IBCondicionPorId s_params_IBCondicionPorId = new ActionParamsClass_IBCondicionPorId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IBCondicionPorId IBCondicionPorIdParams { get { return s_params_IBCondicionPorId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IBCondicionPorId
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Obras s_params_Obras = new ActionParamsClass_Obras();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Obras ObrasParams { get { return s_params_Obras; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Obras
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_ArticulosGridDataResumido s_params_ArticulosGridDataResumido = new ActionParamsClass_ArticulosGridDataResumido();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArticulosGridDataResumido ArticulosGridDataResumidoParams { get { return s_params_ArticulosGridDataResumido; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArticulosGridDataResumido
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_Imprimir s_params_Imprimir = new ActionParamsClass_Imprimir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Imprimir ImprimirParams { get { return s_params_Imprimir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Imprimir
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string Articulo = "Articulo";
        }
        static readonly ActionParamsClass_RefrescarMascara s_params_RefrescarMascara = new ActionParamsClass_RefrescarMascara();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefrescarMascara RefrescarMascaraParams { get { return s_params_RefrescarMascara; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefrescarMascara
        {
            public readonly string o = "o";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteConfirmed s_params_DeleteConfirmed = new ActionParamsClass_DeleteConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteConfirmed DeleteConfirmedParams { get { return s_params_DeleteConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteConfirmed
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DetDocumentos s_params_DetDocumentos = new ActionParamsClass_DetDocumentos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetDocumentos DetDocumentosParams { get { return s_params_DetDocumentos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetDocumentos
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_DetUnidades s_params_DetUnidades = new ActionParamsClass_DetUnidades();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetUnidades DetUnidadesParams { get { return s_params_DetUnidades; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetUnidades
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_Uploadfile s_params_Uploadfile = new ActionParamsClass_Uploadfile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Uploadfile UploadfileParams { get { return s_params_Uploadfile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Uploadfile
        {
            public readonly string containers = "containers";
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_UpdateAwesomeGridData s_params_UpdateAwesomeGridData = new ActionParamsClass_UpdateAwesomeGridData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateAwesomeGridData UpdateAwesomeGridDataParams { get { return s_params_UpdateAwesomeGridData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateAwesomeGridData
        {
            public readonly string formulario = "formulario";
            public readonly string grilla = "grilla";
        }
        static readonly ActionParamsClass_RemitosPendienteArticulocion s_params_RemitosPendienteArticulocion = new ActionParamsClass_RemitosPendienteArticulocion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemitosPendienteArticulocion RemitosPendienteArticulocionParams { get { return s_params_RemitosPendienteArticulocion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemitosPendienteArticulocion
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
            public readonly string FechaInicial = "FechaInicial";
            public readonly string FechaFinal = "FechaFinal";
            public readonly string IdObra = "IdObra";
        }
        static readonly ActionParamsClass_OrdenesCompraPendientesArticulor s_params_OrdenesCompraPendientesArticulor = new ActionParamsClass_OrdenesCompraPendientesArticulor();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrdenesCompraPendientesArticulor OrdenesCompraPendientesArticulorParams { get { return s_params_OrdenesCompraPendientesArticulor; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrdenesCompraPendientesArticulor
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
            public readonly string FechaInicial = "FechaInicial";
            public readonly string FechaFinal = "FechaFinal";
            public readonly string IdObra = "IdObra";
        }
        static readonly ActionParamsClass_ArticulosGridDataSP s_params_ArticulosGridDataSP = new ActionParamsClass_ArticulosGridDataSP();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArticulosGridDataSP ArticulosGridDataSPParams { get { return s_params_ArticulosGridDataSP; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArticulosGridDataSP
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
        }
        static readonly ActionParamsClass_ArticulosGridData2 s_params_ArticulosGridData2 = new ActionParamsClass_ArticulosGridData2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArticulosGridData2 ArticulosGridData2Params { get { return s_params_ArticulosGridData2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArticulosGridData2
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
        }
        static readonly ActionParamsClass_AddToEmpresa s_params_AddToEmpresa = new ActionParamsClass_AddToEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToEmpresa AddToEmpresaParams { get { return s_params_AddToEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ActionParamsClass_RemoveFromEmpresa s_params_RemoveFromEmpresa = new ActionParamsClass_RemoveFromEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveFromEmpresa RemoveFromEmpresaParams { get { return s_params_RemoveFromEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveFromEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/Obra/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ObraController : ProntoMVC.Controllers.ObraController
    {
        public T4MVC_ObraController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ViewResult Details(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void IndexResumidoOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexResumido()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexResumido);
            IndexResumidoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BatchUpdateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, ProntoMVC.Data.Models.Articulo Articulo);

        [NonAction]
        public override System.Web.Mvc.JsonResult BatchUpdate(ProntoMVC.Data.Models.Articulo Articulo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.BatchUpdate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Articulo", Articulo);
            BatchUpdateOverride(callInfo, Articulo);
            return callInfo;
        }

        [NonAction]
        partial void IBCondicionPorIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult IBCondicionPorId(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IBCondicionPorId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IBCondicionPorIdOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ObrasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult Obras(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Obras);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ObrasOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString);
            return callInfo;
        }

        [NonAction]
        partial void ArticulosGridDataResumidoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult ArticulosGridDataResumido(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridDataResumido);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ArticulosGridDataResumidoOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString);
            return callInfo;
        }

        [NonAction]
        partial void ImprimirOverride(T4MVC_System_Web_Mvc_FileResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.FileResult Imprimir(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.Imprimir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ImprimirOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RefrescarMascaraOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ProntoMVC.Data.Models.Articulo o);

        [NonAction]
        public override System.Web.Mvc.ActionResult RefrescarMascara(ProntoMVC.Data.Models.Articulo o)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefrescarMascara);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "o", o);
            RefrescarMascaraOverride(callInfo, o);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ProntoMVC.Data.Models.Articulo Articulo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(ProntoMVC.Data.Models.Articulo Articulo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Articulo", Articulo);
            EditOverride(callInfo, Articulo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteConfirmed(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteConfirmedOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DetDocumentosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetDocumentos(string sidx, string sord, int? page, int? rows, int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetDocumentos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DetDocumentosOverride(callInfo, sidx, sord, page, rows, Id);
            return callInfo;
        }

        [NonAction]
        partial void DetUnidadesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetUnidades(string sidx, string sord, int? page, int? rows, int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetUnidades);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DetUnidadesOverride(callInfo, sidx, sord, page, rows, Id);
            return callInfo;
        }

        [NonAction]
        partial void UploadfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.ComponentModel.Container containers, System.Web.HttpPostedFileBase file);

        [NonAction]
        public override System.Web.Mvc.ActionResult Uploadfile(System.ComponentModel.Container containers, System.Web.HttpPostedFileBase file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Uploadfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "containers", containers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            UploadfileOverride(callInfo, containers, file);
            return callInfo;
        }

        [NonAction]
        partial void UpdateAwesomeGridDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string formulario, string grilla);

        [NonAction]
        public override System.Web.Mvc.JsonResult UpdateAwesomeGridData(string formulario, string grilla)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateAwesomeGridData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formulario", formulario);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "grilla", grilla);
            UpdateAwesomeGridDataOverride(callInfo, formulario, grilla);
            return callInfo;
        }

        [NonAction]
        partial void RemitosPendienteArticulocionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemitosPendienteArticulocion(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemitosPendienteArticulocion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaInicial", FechaInicial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaFinal", FechaFinal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IdObra", IdObra);
            RemitosPendienteArticulocionOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString, FechaInicial, FechaFinal, IdObra);
            return callInfo;
        }

        [NonAction]
        partial void OrdenesCompraPendientesArticulorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra);

        [NonAction]
        public override System.Web.Mvc.ActionResult OrdenesCompraPendientesArticulor(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrdenesCompraPendientesArticulor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaInicial", FechaInicial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaFinal", FechaFinal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IdObra", IdObra);
            OrdenesCompraPendientesArticulorOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString, FechaInicial, FechaFinal, IdObra);
            return callInfo;
        }

        [NonAction]
        partial void ArticulosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Articulos()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Articulos);
            ArticulosOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetUnidadesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetUnidades()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetUnidades);
            GetUnidadesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UnidadesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Unidades()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Unidades);
            UnidadesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ArticulosGridDataSPOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows);

        [NonAction]
        public override System.Web.Mvc.ActionResult ArticulosGridDataSP(string sidx, string sord, int? page, int? rows)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridDataSP);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ArticulosGridDataSPOverride(callInfo, sidx, sord, page, rows);
            return callInfo;
        }

        [NonAction]
        partial void ArticulosGridData2Override(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString);

        [NonAction]
        public override System.Web.Mvc.ActionResult ArticulosGridData2(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticulosGridData2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ArticulosGridData2Override(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString);
            return callInfo;
        }

        [NonAction]
        partial void AddToEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult AddToEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            AddToEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

        [NonAction]
        partial void RemoveFromEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            RemoveFromEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
