// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ProntoMVC.Controllers
{
    public partial class ProveedorController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProveedorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProveedorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetProveedoresAutocomplete2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetProveedoresAutocomplete2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCodigosProveedorAutocomplete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCodigosProveedorAutocompleteEventuales2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocompleteEventuales2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCodigosProveedorAutocompleteEventuales()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocompleteEventuales);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult BatchUpdate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.BatchUpdate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Listado_jqGrid()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Listado_jqGrid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult AddToEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProveedorController Actions { get { return MVC.Proveedor; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Proveedor";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Proveedor";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetProveedoresAutocomplete2 = "GetProveedoresAutocomplete2";
            public readonly string GetCodigosProveedorAutocomplete = "GetCodigosProveedorAutocomplete";
            public readonly string GetCodigosProveedorAutocompleteEventuales2 = "GetCodigosProveedorAutocompleteEventuales2";
            public readonly string GetCodigosProveedorAutocompleteEventuales = "GetCodigosProveedorAutocompleteEventuales";
            public readonly string Edit = "Edit";
            public readonly string BatchUpdate = "BatchUpdate";
            public readonly string Listado_jqGrid = "Listado_jqGrid";
            public readonly string AddToEmpresa = "AddToEmpresa";
            public readonly string RemoveFromEmpresa = "RemoveFromEmpresa";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetProveedoresAutocomplete2 = "GetProveedoresAutocomplete2";
            public const string GetCodigosProveedorAutocomplete = "GetCodigosProveedorAutocomplete";
            public const string GetCodigosProveedorAutocompleteEventuales2 = "GetCodigosProveedorAutocompleteEventuales2";
            public const string GetCodigosProveedorAutocompleteEventuales = "GetCodigosProveedorAutocompleteEventuales";
            public const string Edit = "Edit";
            public const string BatchUpdate = "BatchUpdate";
            public const string Listado_jqGrid = "Listado_jqGrid";
            public const string AddToEmpresa = "AddToEmpresa";
            public const string RemoveFromEmpresa = "RemoveFromEmpresa";
        }


        static readonly ActionParamsClass_GetProveedoresAutocomplete2 s_params_GetProveedoresAutocomplete2 = new ActionParamsClass_GetProveedoresAutocomplete2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProveedoresAutocomplete2 GetProveedoresAutocomplete2Params { get { return s_params_GetProveedoresAutocomplete2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProveedoresAutocomplete2
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCodigosProveedorAutocomplete s_params_GetCodigosProveedorAutocomplete = new ActionParamsClass_GetCodigosProveedorAutocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCodigosProveedorAutocomplete GetCodigosProveedorAutocompleteParams { get { return s_params_GetCodigosProveedorAutocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCodigosProveedorAutocomplete
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_GetCodigosProveedorAutocompleteEventuales2 s_params_GetCodigosProveedorAutocompleteEventuales2 = new ActionParamsClass_GetCodigosProveedorAutocompleteEventuales2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCodigosProveedorAutocompleteEventuales2 GetCodigosProveedorAutocompleteEventuales2Params { get { return s_params_GetCodigosProveedorAutocompleteEventuales2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCodigosProveedorAutocompleteEventuales2
        {
            public readonly string idproveedor = "idproveedor";
        }
        static readonly ActionParamsClass_GetCodigosProveedorAutocompleteEventuales s_params_GetCodigosProveedorAutocompleteEventuales = new ActionParamsClass_GetCodigosProveedorAutocompleteEventuales();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCodigosProveedorAutocompleteEventuales GetCodigosProveedorAutocompleteEventualesParams { get { return s_params_GetCodigosProveedorAutocompleteEventuales; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCodigosProveedorAutocompleteEventuales
        {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_BatchUpdate s_params_BatchUpdate = new ActionParamsClass_BatchUpdate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BatchUpdate BatchUpdateParams { get { return s_params_BatchUpdate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BatchUpdate
        {
            public readonly string Proveedor = "Proveedor";
        }
        static readonly ActionParamsClass_Listado_jqGrid s_params_Listado_jqGrid = new ActionParamsClass_Listado_jqGrid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Listado_jqGrid Listado_jqGridParams { get { return s_params_Listado_jqGrid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Listado_jqGrid
        {
            public readonly string sidx = "sidx";
            public readonly string sord = "sord";
            public readonly string page = "page";
            public readonly string rows = "rows";
            public readonly string _search = "_search";
            public readonly string searchField = "searchField";
            public readonly string searchOper = "searchOper";
            public readonly string searchString = "searchString";
            public readonly string FechaInicial = "FechaInicial";
            public readonly string FechaFinal = "FechaFinal";
            public readonly string IdObra = "IdObra";
        }
        static readonly ActionParamsClass_AddToEmpresa s_params_AddToEmpresa = new ActionParamsClass_AddToEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToEmpresa AddToEmpresaParams { get { return s_params_AddToEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ActionParamsClass_RemoveFromEmpresa s_params_RemoveFromEmpresa = new ActionParamsClass_RemoveFromEmpresa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveFromEmpresa RemoveFromEmpresaParams { get { return s_params_RemoveFromEmpresa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveFromEmpresa
        {
            public readonly string id = "id";
            public readonly string empresa = "empresa";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _GrillaContactos = "_GrillaContactos";
                public readonly string _GrillaLugaresEntrega = "_GrillaLugaresEntrega";
                public readonly string Edit = "Edit";
                public readonly string FormEditing = "FormEditing";
                public readonly string Index = "Index";
                public readonly string IndexResumido = "IndexResumido";
            }
            public readonly string _GrillaContactos = "~/Views/Proveedor/_GrillaContactos.cshtml";
            public readonly string _GrillaLugaresEntrega = "~/Views/Proveedor/_GrillaLugaresEntrega.cshtml";
            public readonly string Edit = "~/Views/Proveedor/Edit.cshtml";
            public readonly string FormEditing = "~/Views/Proveedor/FormEditing.cshtml";
            public readonly string Index = "~/Views/Proveedor/Index.cshtml";
            public readonly string IndexResumido = "~/Views/Proveedor/IndexResumido.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProveedorController : ProntoMVC.Controllers.ProveedorController
    {
        public T4MVC_ProveedorController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetProveedoresAutocomplete2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetProveedoresAutocomplete2(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetProveedoresAutocomplete2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetProveedoresAutocomplete2Override(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCodigosProveedorAutocompleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCodigosProveedorAutocomplete(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCodigosProveedorAutocompleteOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void GetCodigosProveedorAutocompleteEventuales2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, int idproveedor);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCodigosProveedorAutocompleteEventuales2(int idproveedor)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocompleteEventuales2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idproveedor", idproveedor);
            GetCodigosProveedorAutocompleteEventuales2Override(callInfo, idproveedor);
            return callInfo;
        }

        [NonAction]
        partial void GetCodigosProveedorAutocompleteEventualesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCodigosProveedorAutocompleteEventuales(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCodigosProveedorAutocompleteEventuales);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetCodigosProveedorAutocompleteEventualesOverride(callInfo, term);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void BatchUpdateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, ProntoMVC.Data.Models.Proveedor Proveedor);

        [NonAction]
        public override System.Web.Mvc.JsonResult BatchUpdate(ProntoMVC.Data.Models.Proveedor Proveedor)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.BatchUpdate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Proveedor", Proveedor);
            BatchUpdateOverride(callInfo, Proveedor);
            return callInfo;
        }

        [NonAction]
        partial void Listado_jqGridOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra);

        [NonAction]
        public override System.Web.Mvc.ActionResult Listado_jqGrid(string sidx, string sord, int? page, int? rows, bool _search, string searchField, string searchOper, string searchString, string FechaInicial, string FechaFinal, string IdObra)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Listado_jqGrid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sidx", sidx);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sord", sord);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rows", rows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_search", _search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchField", searchField);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOper", searchOper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaInicial", FechaInicial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "FechaFinal", FechaFinal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IdObra", IdObra);
            Listado_jqGridOverride(callInfo, sidx, sord, page, rows, _search, searchField, searchOper, searchString, FechaInicial, FechaFinal, IdObra);
            return callInfo;
        }

        [NonAction]
        partial void AddToEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult AddToEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.AddToEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            AddToEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

        [NonAction]
        partial void RemoveFromEmpresaOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, System.Guid id, string empresa);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult RemoveFromEmpresa(System.Guid id, string empresa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.RemoveFromEmpresa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "empresa", empresa);
            RemoveFromEmpresaOverride(callInfo, id, empresa);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
