CREATE Procedure [dbo].[Pedidos_M]

@IdPedido int,
@NumeroPedido int,
@IdProveedor int,
@FechaPedido datetime,
@LugarEntrega ntext,
@FormaPago ntext,
@Observaciones ntext,
@Bonificacion numeric(18,2),
@TotalIva1 numeric(18,2),
@TotalIva2 numeric(18,2),
@TotalPedido numeric(18,2),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@IdComprador int,
@PorcentajeBonificacion numeric(6,2),
@NumeroComparativa int,
@Contacto varchar(50),
@PlazoEntrega ntext,
@Garantia ntext,
@Documentacion ntext,
@Aprobo int,
@IdMoneda int,
@FechaAprobacion datetime,
@Importante ntext,
@TipoCompra int,
@Consorcial varchar(2),
@Cumplido varchar(2),
@DetalleCondicionCompra varchar(200),
@IdAutorizoCumplido int,
@IdDioPorCumplido int,
@FechaDadoPorCumplido datetime,
@ObservacionesCumplido ntext,
@SubNumero int,
@UsuarioAnulacion varchar(6),
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@ImprimeImportante varchar(2),
@ImprimePlazoEntrega varchar(2),
@ImprimeLugarEntrega varchar(2),
@ImprimeFormaPago varchar(2),
@ImprimeImputaciones varchar(2),
@ImprimeInspecciones varchar(2),
@ImprimeGarantia varchar(2),
@ImprimeDocumentacion varchar(2),
@CotizacionDolar numeric(18,3),
@CotizacionMoneda numeric(18,3),
@PedidoExterior varchar(2),
@PRESTOPedido varchar(13),
@PRESTOFechaProceso datetime,
@IdCondicionCompra int,
@EnviarEmail tinyint,
@IdPedidoOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@Subcontrato varchar(2),
@IdPedidoAbierto int,
@NumeroLicitacion varchar(20),
@Transmitir_a_SAT varchar(2),
@NumeracionAutomatica varchar(2),
@Impresa varchar(2),
@EmbarcadoA varchar(50),
@FacturarA varchar(50),
@ProveedorExt varchar(50),
@ImpuestosInternos numeric(18,2),
@FechaSalida datetime,
@CodigoControl numeric(10,0),
@CircuitoFirmasCompleto varchar(2),
@OtrosConceptos1 numeric(18,2),
@OtrosConceptos2 numeric(18,2),
@OtrosConceptos3 numeric(18,2),
@OtrosConceptos4 numeric(18,2),
@OtrosConceptos5 numeric(18,2),
@IdClausula int,
@IncluirObservacionesRM varchar(2),
@NumeroSubcontrato int,
@IdPuntoVenta int,
@PuntoVenta int,
@IdMonedaOriginal int,
@IdLugarEntrega int,
@ConfirmadoPorWeb varchar(2),
@IdTipoCompraRM int,
@FechaEnvioProveedor datetime,
@IdUsuarioEnvioProveedor int,
@IdPlazoEntrega int

AS

/*
IF IsNull(@Aprobo,0)>0 and IsNull(@CircuitoFirmasCompleto,'NO')='NO' 
	IF Not Exists(Select Top 1 da.IdDetalleAutorizacion From DetalleAutorizaciones da
			Left Outer Join Autorizaciones a On a.IdAutorizacion=da.IdAutorizacion
			Where a.IdFormulario=4)
		SET @CircuitoFirmasCompleto='SI'
*/

UPDATE Pedidos
SET 
 NumeroPedido=@NumeroPedido,
 IdProveedor=@IdProveedor,
 FechaPedido=@FechaPedido,
 LugarEntrega=@LugarEntrega,
 FormaPago=@FormaPago,
 Observaciones=@Observaciones,
 Bonificacion=@Bonificacion,
 TotalIva1=@TotalIva1,
 TotalIva2=@TotalIva2,
 TotalPedido=@TotalPedido,
 PorcentajeIva1=@PorcentajeIva1,
 PorcentajeIva2=@PorcentajeIva2,
 IdComprador=@IdComprador,
 PorcentajeBonificacion=@PorcentajeBonificacion,
 NumeroComparativa=@NumeroComparativa,
 Contacto=@Contacto,
 PlazoEntrega=@PlazoEntrega,
 Garantia=@Garantia,
 Documentacion=@Documentacion,
 Aprobo=@Aprobo,
 IdMoneda=@IdMoneda,
 FechaAprobacion=@FechaAprobacion,
 Importante=@Importante,
 TipoCompra=@TipoCompra,
 Consorcial=@Consorcial,
 Cumplido=@Cumplido,
 DetalleCondicionCompra=@DetalleCondicionCompra,
 IdAutorizoCumplido=@IdAutorizoCumplido,
 IdDioPorCumplido=@IdDioPorCumplido,
 FechaDadoPorCumplido=@FechaDadoPorCumplido,
 ObservacionesCumplido=@ObservacionesCumplido,
 SubNumero=@SubNumero,
 UsuarioAnulacion=@UsuarioAnulacion,
 FechaAnulacion=@FechaAnulacion,
 MotivoAnulacion=@MotivoAnulacion,
 ArchivoAdjunto1=@ArchivoAdjunto1,
 ArchivoAdjunto2=@ArchivoAdjunto2,
 ArchivoAdjunto3=@ArchivoAdjunto3,
 ArchivoAdjunto4=@ArchivoAdjunto4,
 ArchivoAdjunto5=@ArchivoAdjunto5,
 ArchivoAdjunto6=@ArchivoAdjunto6,
 ArchivoAdjunto7=@ArchivoAdjunto7,
 ArchivoAdjunto8=@ArchivoAdjunto8,
 ArchivoAdjunto9=@ArchivoAdjunto9,
 ArchivoAdjunto10=@ArchivoAdjunto10,
 ImprimeImportante=@ImprimeImportante,
 ImprimePlazoEntrega=@ImprimePlazoEntrega,
 ImprimeLugarEntrega=@ImprimeLugarEntrega,
 ImprimeFormaPago=@ImprimeFormaPago,
 ImprimeImputaciones=@ImprimeImputaciones,
 ImprimeInspecciones=@ImprimeInspecciones,
 ImprimeGarantia=@ImprimeGarantia,
 ImprimeDocumentacion=@ImprimeDocumentacion,
 CotizacionDolar=@CotizacionDolar,
 CotizacionMoneda=@CotizacionMoneda,
 PedidoExterior=@PedidoExterior,
 PRESTOPedido=@PRESTOPedido,
 PRESTOFechaProceso=@PRESTOFechaProceso,
 IdCondicionCompra=@IdCondicionCompra,
 EnviarEmail=@EnviarEmail,
 IdPedidoOriginal=@IdPedidoOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 Subcontrato=@Subcontrato,
 IdPedidoAbierto=@IdPedidoAbierto,
 NumeroLicitacion=@NumeroLicitacion,
 Transmitir_a_SAT=@Transmitir_a_SAT,
 NumeracionAutomatica=@NumeracionAutomatica,
 Impresa=@Impresa,
 EmbarcadoA=@EmbarcadoA,
 FacturarA=@FacturarA,
 ProveedorExt=@ProveedorExt,
 ImpuestosInternos=@ImpuestosInternos,
 FechaSalida=@FechaSalida,
 CodigoControl=@CodigoControl,
 CircuitoFirmasCompleto=@CircuitoFirmasCompleto,
 OtrosConceptos1=@OtrosConceptos1,
 OtrosConceptos2=@OtrosConceptos2,
 OtrosConceptos3=@OtrosConceptos3,
 OtrosConceptos4=@OtrosConceptos4,
 OtrosConceptos5=@OtrosConceptos5,
 IdClausula=@IdClausula,
 IncluirObservacionesRM=@IncluirObservacionesRM,
 NumeroSubcontrato=@NumeroSubcontrato,
 IdPuntoVenta=@IdPuntoVenta,
 PuntoVenta=@PuntoVenta,
 IdMonedaOriginal=@IdMonedaOriginal,
 IdLugarEntrega=@IdLugarEntrega,
 ConfirmadoPorWeb=@ConfirmadoPorWeb,
 IdTipoCompraRM=@IdTipoCompraRM,
 FechaEnvioProveedor=@FechaEnvioProveedor,
 IdUsuarioEnvioProveedor=@IdUsuarioEnvioProveedor,
 IdPlazoEntrega=@IdPlazoEntrega
WHERE (IdPedido=@IdPedido)

IF IsNull(@Aprobo,0)>0 and IsNull(@CircuitoFirmasCompleto,'NO')='NO' 
    BEGIN
	DECLARE @RespetarPrecedencia varchar(2)

	SET @RespetarPrecedencia=Isnull((Select Top 1 ProntoIni.Valor From ProntoIni 
						Left Outer Join ProntoIniClaves pic On pic.IdProntoIniClave=ProntoIni.IdProntoIniClave
						Where pic.Clave='Respetar precedencia en circuito de firmas'),'NO')

	EXEC AutorizacionesPorComprobante_Generar @RespetarPrecedencia

	IF Not Exists(Select Top 1 IdComprobante From _TempAutorizaciones Where IdFormulario=4 and IdComprobante=@IdPedido)
		UPDATE Pedidos
		SET CircuitoFirmasCompleto='SI'
		WHERE IdPedido=@IdPedido
    END

RETURN(@IdPedido)