
CREATE  Procedure [dbo].[PedidosSAT_A]
@IdPedido int  output,
@NumeroPedido int,
@IdProveedor int,
@FechaPedido datetime,
@LugarEntrega ntext,
@FormaPago ntext,
@Observaciones ntext,
@Bonificacion numeric(12,2),
@TotalIva1 numeric(12,2),
@TotalIva2 numeric(12,2),
@TotalPedido numeric(12,2),
@PorcentajeIva1 numeric(6,2),
@PorcentajeIva2 numeric(6,2),
@IdComprador int,
@PorcentajeBonificacion numeric(6,2),
@NumeroComparativa int,
@Contacto varchar(50),
@PlazoEntrega ntext,
@Garantia ntext,
@Documentacion ntext,
@Aprobo int,
@IdMoneda int,
@FechaAprobacion datetime,
@Importante ntext,
@TipoCompra int,
@Consorcial varchar(2),
@Cumplido varchar(2),
@DetalleCondicionCompra varchar(200),
@IdAutorizoCumplido int,
@IdDioPorCumplido int,
@FechaDadoPorCumplido datetime,
@ObservacionesCumplido ntext,
@SubNumero int,
@UsuarioAnulacion varchar(6),
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@ImprimeImportante varchar(2),
@ImprimePlazoEntrega varchar(2),
@ImprimeLugarEntrega varchar(2),
@ImprimeFormaPago varchar(2),
@ImprimeImputaciones varchar(2),
@ImprimeInspecciones varchar(2),
@ImprimeGarantia varchar(2),
@ImprimeDocumentacion varchar(2),
@CotizacionDolar numeric(18,3),
@CotizacionMoneda numeric(18,3),
@PedidoExterior varchar(2),
@PRESTOPedido varchar(13),
@PRESTOFechaProceso datetime,
@IdCondicionCompra int,
@EnviarEmail tinyint,
@IdPedidoOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime

AS

INSERT INTO [PedidosSAT]
(
 NumeroPedido,
 IdProveedor,
 FechaPedido,
 LugarEntrega,
 FormaPago,
 Observaciones,
 Bonificacion,
 TotalIva1,
 TotalIva2,
 TotalPedido,
 PorcentajeIva1,
 PorcentajeIva2,
 IdComprador,
 PorcentajeBonificacion,
 NumeroComparativa,
 Contacto,
 PlazoEntrega,
 Garantia,
 Documentacion,
 Aprobo,
 IdMoneda,
 FechaAprobacion,
 Importante,
 TipoCompra,
 Consorcial,
 Cumplido,
 DetalleCondicionCompra,
 IdAutorizoCumplido,
 IdDioPorCumplido,
 FechaDadoPorCumplido,
 ObservacionesCumplido,
 SubNumero,
 UsuarioAnulacion,
 FechaAnulacion,
 MotivoAnulacion,
 ArchivoAdjunto1,
 ArchivoAdjunto2,
 ArchivoAdjunto3,
 ArchivoAdjunto4,
 ArchivoAdjunto5,
 ArchivoAdjunto6,
 ArchivoAdjunto7,
 ArchivoAdjunto8,
 ArchivoAdjunto9,
 ArchivoAdjunto10,
 ImprimeImportante,
 ImprimePlazoEntrega,
 ImprimeLugarEntrega, 
 ImprimeFormaPago,
 ImprimeImputaciones,
 ImprimeInspecciones,
 ImprimeGarantia,
 ImprimeDocumentacion,
 CotizacionDolar,
 CotizacionMoneda,
 PedidoExterior,
 PRESTOPedido,
 PRESTOFechaProceso,
 IdCondicionCompra,
 EnviarEmail,
 IdPedidoOriginal,
 IdOrigenTransmision,
 FechaImportacionTransmision
)
VALUES
(
 @NumeroPedido,
 @IdProveedor,
 @FechaPedido,
 @LugarEntrega,
 @FormaPago,
 @Observaciones,
 @Bonificacion,
 @TotalIva1,
 @TotalIva2,
 @TotalPedido,
 @PorcentajeIva1,
 @PorcentajeIva2,
 @IdComprador,
 @PorcentajeBonificacion,
 @NumeroComparativa,
 @Contacto,
 @PlazoEntrega,
 @Garantia,
 @Documentacion,
 @Aprobo,
 @IdMoneda,
 @FechaAprobacion,
 @Importante,
 @TipoCompra,
 @Consorcial,
 @Cumplido,
 @DetalleCondicionCompra,
 @IdAutorizoCumplido,
 @IdDioPorCumplido,
 @FechaDadoPorCumplido,
 @ObservacionesCumplido,
 @SubNumero,
 @UsuarioAnulacion,
 @FechaAnulacion,
 @MotivoAnulacion,
 @ArchivoAdjunto1,
 @ArchivoAdjunto2,
 @ArchivoAdjunto3,
 @ArchivoAdjunto4,
 @ArchivoAdjunto5,
 @ArchivoAdjunto6,
 @ArchivoAdjunto7,
 @ArchivoAdjunto8,
 @ArchivoAdjunto9,
 @ArchivoAdjunto10,
 @ImprimeImportante,
 @ImprimePlazoEntrega,
 @ImprimeLugarEntrega, 
 @ImprimeFormaPago,
 @ImprimeImputaciones,
 @ImprimeInspecciones,
 @ImprimeGarantia,
 @ImprimeDocumentacion,
 @CotizacionDolar,
 @CotizacionMoneda,
 @PedidoExterior,
 @PRESTOPedido,
 @PRESTOFechaProceso,
 @IdCondicionCompra,
 @EnviarEmail,
 @IdPedidoOriginal,
 @IdOrigenTransmision,
 @FechaImportacionTransmision
)
SELECT @IdPedido=@@identity
RETURN(@IdPedido)
