
CREATE Procedure [dbo].[Pesadas_M]

@IdPesada  int,
@NumeroPesada int,
@IdUsuarioIngreso int ,
@FechaIngreso datetime ,
@Anulada varchar(2) ,
@IdUsuarioAnulo int ,
@FechaAnulacion datetime ,
@Observaciones varchar(200) ,
@IdArticulo int  ,
@IdStock int ,
@Partida varchar(20),
@IdUnidad int,
@IdUbicacion int ,
@Cantidad numeric(12,2) ,
@PesoBruto numeric(18,2) ,
@PesoNeto numeric(18,2) ,
@Tara numeric(18,2) ,
@Chofer int , --id?
@TxtChofer varchar(30) , --mientras no haya id
@IdCamion int , -- id?
@TxtCamion varchar(30) ,	
@IdTransportista int , --id? SÃ­, el pronto tiene tabla de transportistas
@IdProveedor int ,
@IdCliente int ,
@IdObra int ,
@RemitoMaterial int ,
@RemitoTransportista int ,
@CantidadEnOrigen numeric(12,2), 	
@PesoBrutoIngresadoManualmente varchar(2),
@TaraIngresadaManualmente varchar(2),
@Tipo varchar(15),
@IdSalidaMateriales int,
@IdOtroIngresoAlmacen int,
@IdRecepcion int,
@IdRemito int,
@NetoEquivalente int,
@IdChofer int,
@IdFlete int,
@RemitoTransportista2 int,
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@RemitoMaterial2 int,
@NumeroOrdenCarga int,
@Patente varchar(10),
@IdDetallePedido int,
@IdTarifaFlete int,
@TarifaFlete numeric(18,2),
@PesadaTara1 numeric(18,2),
@PesadaTara2 numeric(18,2),
@PesadaPesoBruto1 numeric(18,2),
@PesadaPesoBruto2 numeric(18,2),
@TipoMovimiento varchar(1),
@IdOrdenCarga int,
@CoeficienteAKilos numeric(18,6),
@FechaUltimaPesada datetime,
@IdDetalleRequerimiento int,
@CoeficienteControlPesada numeric(18,2),
@CantidadSegunRemitoMasCoefEnKg numeric(18,2),
@TomarPesadaORemito varchar(1),
@Progresiva1 numeric(18,2),
@Progresiva2 numeric(18,2),
@IdPesadaOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime

AS 

UPDATE [Pesadas]
SET
 NumeroPesada=@NumeroPesada ,
 IdUsuarioIngreso=@IdUsuarioIngreso  ,
 FechaIngreso=@FechaIngreso  ,
 Anulada=@Anulada  ,
 IdUsuarioAnulo=@IdUsuarioAnulo  ,
 FechaAnulacion=@FechaAnulacion  ,
 Observaciones=@Observaciones  ,
 IdArticulo=@IdArticulo   ,
 IdStock=@IdStock  ,
 Partida=@Partida ,
 IdUnidad=@IdUnidad ,
 IdUbicacion=@IdUbicacion  ,
 Cantidad=@Cantidad  ,
 PesoBruto=@PesoBruto  ,
 PesoNeto=@PesoNeto  ,
 Tara=@Tara  ,
 Chofer=@Chofer  , 
 TxtChofer=@TxtChofer  ,
 IdCamion=@IdCamion ,
 TxtCamion=@TxtCamion  ,	
 IdTransportista=@IdTransportista  , 
 IdProveedor=@IdProveedor  ,
 IdCliente=@IdCliente  ,
 IdObra=@IdObra  ,
 RemitoMaterial=@RemitoMaterial  ,
 RemitoTransportista=@RemitoTransportista ,
 CantidadEnOrigen=@CantidadEnOrigen, 	
 PesoBrutoIngresadoManualmente=@PesoBrutoIngresadoManualmente,
 TaraIngresadaManualmente=@TaraIngresadaManualmente,
 Tipo=@Tipo ,
 IdSalidaMateriales=@IdSalidaMateriales ,
 IdOtroIngresoAlmacen=@IdOtroIngresoAlmacen ,
 IdRecepcion=@IdRecepcion ,
 IdRemito=@IdRemito,
 NetoEquivalente=@NetoEquivalente,
 IdChofer=@IdChofer,
 IdFlete=@IdFlete,
 RemitoTransportista2=@RemitoTransportista2,
 DistanciaRecorrida=@DistanciaRecorrida,
 CodigoTarifador=@CodigoTarifador,
 RemitoMaterial2=@RemitoMaterial2,
 NumeroOrdenCarga=@NumeroOrdenCarga,
 Patente=@Patente,
 IdDetallePedido=@IdDetallePedido,
 IdTarifaFlete=@IdTarifaFlete,
 TarifaFlete=@TarifaFlete,
 PesadaTara1=@PesadaTara1,
 PesadaTara2=@PesadaTara2,
 PesadaPesoBruto1=@PesadaPesoBruto1,
 PesadaPesoBruto2=@PesadaPesoBruto2,
 TipoMovimiento=@TipoMovimiento,
 IdOrdenCarga=@IdOrdenCarga,
 CoeficienteAKilos=@CoeficienteAKilos,
 FechaUltimaPesada=@FechaUltimaPesada,
 IdDetalleRequerimiento=@IdDetalleRequerimiento,
 CoeficienteControlPesada=@CoeficienteControlPesada,
 CantidadSegunRemitoMasCoefEnKg=@CantidadSegunRemitoMasCoefEnKg,
 TomarPesadaORemito=@TomarPesadaORemito,
 Progresiva1=@Progresiva1,
 Progresiva2=@Progresiva2,
 IdPesadaOriginal=@IdPesadaOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision
WHERE (IdPesada=@IdPesada)

RETURN(@IdPesada)
