CREATE Procedure [dbo].[PlazosFijos_A]

@IdPlazoFijo int output,
@IdBanco int,
@NumeroCertificado1 int,
@NumeroCertificado2 varchar(20),
@DireccionEmisionYPago varchar(50),
@Titulares varchar(50),
@CodigoDeposito int,
@CodigoClase int,
@PlazoEnDias int,
@TasaNominalAnual numeric(18,3),
@Importe numeric(18,2),
@TasaEfectivaMensual numeric(18,3),
@FechaVencimiento datetime,
@ImporteIntereses numeric(18,2),
@Orden varchar(50),
@Detalle varchar(50),
@IdPlazoFijoOrigen int,
@FechaInicioPlazoFijo datetime,
@IdMoneda int,
@CotizacionMonedaAlInicio numeric(18,4),
@CotizacionMonedaAlFinal numeric(18,4),
@Finalizado varchar(2),
@IdCajaOrigen int,
@IdCuentaBancariaOrigen int,
@IdCajaDestino int,
@IdCuentaBancariaDestino int,
@RetencionGanancia numeric(18,2),
@Anulado varchar(2),
@AcreditarInteresesAlFinalizar varchar(2),
@NoExigirRubroContable varchar(2)

AS

INSERT INTO [PlazosFijos]
(
 IdBanco,
 NumeroCertificado1,
 NumeroCertificado2,
 DireccionEmisionYPago,
 Titulares,
 CodigoDeposito,
 CodigoClase,
 PlazoEnDias,
 TasaNominalAnual,
 Importe,
 TasaEfectivaMensual,
 FechaVencimiento,
 ImporteIntereses,
 Orden,
 Detalle,
 IdPlazoFijoOrigen,
 FechaInicioPlazoFijo,
 IdMoneda,
 CotizacionMonedaAlInicio,
 CotizacionMonedaAlFinal,
 Finalizado,
 IdCajaOrigen,
 IdCuentaBancariaOrigen,
 IdCajaDestino,
 IdCuentaBancariaDestino,
 RetencionGanancia,
 Anulado,
 AcreditarInteresesAlFinalizar,
 NoExigirRubroContable
)
VALUES
(
 @IdBanco,
 @NumeroCertificado1,
 @NumeroCertificado2,
 @DireccionEmisionYPago,
 @Titulares,
 @CodigoDeposito,
 @CodigoClase,
 @PlazoEnDias,
 @TasaNominalAnual,
 @Importe,
 @TasaEfectivaMensual,
 @FechaVencimiento,
 @ImporteIntereses,
 @Orden,
 @Detalle,
 @IdPlazoFijoOrigen,
 @FechaInicioPlazoFijo,
 @IdMoneda,
 @CotizacionMonedaAlInicio,
 @CotizacionMonedaAlFinal,
 @Finalizado,
 @IdCajaOrigen,
 @IdCuentaBancariaOrigen,
 @IdCajaDestino,
 @IdCuentaBancariaDestino,
 @RetencionGanancia,
 @Anulado,
 @AcreditarInteresesAlFinalizar,
 @NoExigirRubroContable
)

SELECT @IdPlazoFijo=@@identity

RETURN(@IdPlazoFijo)