
CREATE Procedure [dbo].[RecepcionesSAT_M]

@IdRecepcion int,
@NumeroRecepcion1 int,
@NumeroRecepcion2 int,
@IdProveedor int,
@FechaRecepcion datetime,
@Observaciones ntext,
@IdPedido int,
@IdRequerimiento int,
@NumeroRecepcionAlmacen int,
@IdTransportista int,
@Acargo varchar(1),
@Realizo int,
@Anulada varchar(2),
@IdAcopio int,
@SubNumero varchar(1),
@FechaRegistracion datetime,
@EnviarEmail tinyint,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@ProcesadoPorCPManualmente varchar(2),
@ActualizarCostoImportacionDesdePedido varchar(2),
@ImpuestosInternos numeric(18,2),
@PercepcionIIBB numeric(18,2),
@PercepcionIVA numeric(18,2),
@ImporteIVA numeric(18,2),
@Chofer varchar(50),
@Patente varchar(10),
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@NumeroOrdenCarga int,
@IdPesada int

AS

UPDATE RecepcionesSAT
SET 
 NumeroRecepcion1=@NumeroRecepcion1,
 NumeroRecepcion2=@NumeroRecepcion2,
 IdProveedor=@IdProveedor,
 FechaRecepcion=@FechaRecepcion,
 Observaciones=@Observaciones,
 IdPedido=@IdPedido,
 IdRequerimiento=@IdRequerimiento,
 NumeroRecepcionAlmacen=@NumeroRecepcionAlmacen,
 IdTransportista=@IdTransportista,
 Acargo=@Acargo,
 Realizo=@Realizo,
 Anulada=@Anulada,
 IdAcopio=@IdAcopio,
 SubNumero=@SubNumero,
 FechaRegistracion=@FechaRegistracion,
 EnviarEmail=@EnviarEmail,
 IdRecepcionOriginal=@IdRecepcionOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 ProcesadoPorCPManualmente=@ProcesadoPorCPManualmente,
 ActualizarCostoImportacionDesdePedido=@ActualizarCostoImportacionDesdePedido,
 ImpuestosInternos=@ImpuestosInternos,
 PercepcionIIBB=@PercepcionIIBB,
 PercepcionIVA=@PercepcionIVA,
 ImporteIVA=@ImporteIVA,
 Chofer=@Chofer,
 Patente=@Patente,
 NumeroRemitoTransporte1=@NumeroRemitoTransporte1,
 NumeroRemitoTransporte2=@NumeroRemitoTransporte2,
 IdChofer=@IdChofer,
 IdFlete=@IdFlete,
 PesoBruto=@PesoBruto,
 PesoNeto=@PesoNeto,
 Tara=@Tara,
 CantidadEnOrigen=@CantidadEnOrigen,
 DistanciaRecorrida=@DistanciaRecorrida,
 CodigoTarifador=@CodigoTarifador,
 NumeroOrdenCarga=@NumeroOrdenCarga,
 IdPesada=@IdPesada
WHERE (IdRecepcion=@IdRecepcion)

RETURN(@IdRecepcion)
