
CREATE Procedure [dbo].[RecepcionesSAT_A]

@IdRecepcion int  output,
@NumeroRecepcion1 int,
@NumeroRecepcion2 int,
@IdProveedor int,
@FechaRecepcion datetime,
@Observaciones ntext,
@IdPedido int,
@IdRequerimiento int,
@NumeroRecepcionAlmacen int,
@IdTransportista int,
@Acargo varchar(1),
@Realizo int,
@Anulada varchar(2),
@IdAcopio int,
@SubNumero varchar(1),
@FechaRegistracion datetime,
@EnviarEmail tinyint,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@ProcesadoPorCPManualmente varchar(2),
@ActualizarCostoImportacionDesdePedido varchar(2),
@ImpuestosInternos numeric(18,2),
@PercepcionIIBB numeric(18,2),
@PercepcionIVA numeric(18,2),
@ImporteIVA numeric(18,2),
@Chofer varchar(50),
@Patente varchar(10),
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@NumeroOrdenCarga int,
@IdPesada int

AS

INSERT INTO RecepcionesSAT
(
 NumeroRecepcion1,
 NumeroRecepcion2,
 IdProveedor,
 FechaRecepcion,
 Observaciones,
 IdPedido,
 IdRequerimiento,
 NumeroRecepcionAlmacen,
 IdTransportista,
 Acargo,
 Realizo,
 Anulada,
 IdAcopio,
 SubNumero,
 FechaRegistracion,
 EnviarEmail,
 IdRecepcionOriginal,
 IdOrigenTransmision,
 FechaImportacionTransmision,
 ProcesadoPorCPManualmente,
 ActualizarCostoImportacionDesdePedido,
 ImpuestosInternos,
 PercepcionIIBB,
 PercepcionIVA,
 ImporteIVA,
 Chofer,
 Patente,
 NumeroRemitoTransporte1,
 NumeroRemitoTransporte2,
 IdChofer,
 IdFlete,
 PesoBruto,
 PesoNeto,
 Tara,
 CantidadEnOrigen,
 DistanciaRecorrida,
 CodigoTarifador,
 NumeroOrdenCarga,
 IdPesada
)
VALUES
(
 @NumeroRecepcion1,
 @NumeroRecepcion2,
 @IdProveedor,
 @FechaRecepcion,
 @Observaciones,
 @IdPedido,
 @IdRequerimiento,
 @NumeroRecepcionAlmacen,
 @IdTransportista,
 @Acargo,
 @Realizo,
 @Anulada,
 @IdAcopio,
 @SubNumero,
 GetDate(),
 @EnviarEmail,
 @IdRecepcionOriginal,
 @IdOrigenTransmision,
 @FechaImportacionTransmision,
 @ProcesadoPorCPManualmente,
 @ActualizarCostoImportacionDesdePedido,
 @ImpuestosInternos,
 @PercepcionIIBB,
 @PercepcionIVA,
 @ImporteIVA,
 @Chofer,
 @Patente,
 @NumeroRemitoTransporte1,
 @NumeroRemitoTransporte2,
 @IdChofer,
 @IdFlete,
 @PesoBruto,
 @PesoNeto,
 @Tara,
 @CantidadEnOrigen,
 @DistanciaRecorrida,
 @CodigoTarifador,
 @NumeroOrdenCarga,
 @IdPesada
)

SELECT @IdRecepcion=@@identity
RETURN(@IdRecepcion)
