CREATE Procedure [dbo].[Recepciones_A]

@IdRecepcion int  OUTPUT,
@NumeroRecepcion1 int,
@NumeroRecepcion2 int,
@IdProveedor int,
@FechaRecepcion datetime,
@Observaciones ntext,
@IdPedido int,
@IdRequerimiento int,
@NumeroRecepcionAlmacen int,
@IdTransportista int,
@Acargo varchar(1),
@Realizo int,
@Anulada varchar(2),
@IdAcopio int,
@SubNumero varchar(1),
@FechaRegistracion datetime,
@EnviarEmail tinyint,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@ProcesadoPorCPManualmente varchar(2),
@ActualizarCostoImportacionDesdePedido varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@IdUsuarioModifico int,
@FechaUltimaModificacion datetime,
@ImpuestosInternos numeric(18,2),
@PercepcionIIBB numeric(18,2),
@PercepcionIVA numeric(18,2),
@PRESTOFechaProceso datetime,
@ImporteIVA numeric(18,2),
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@Libero int,
@FechaLiberacion datetime,
@CircuitoFirmasCompleto varchar(2),
@IdComprador int,
@NumeroRecepcionOrigen1 int,
@NumeroRecepcionOrigen2 int,
@Chofer varchar(50),
@NumeroDocumentoChofer varchar(30),
@IdEquipo int,
@Patente varchar(10),
@IdDepositoOrigen int,
@IdRecepcionSAT int,
@TipoRecepcion int,
@IdObra int,
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@NumeroOrdenCarga int,
@IdPesada int,
@IdTarifaFlete int,
@TarifaFlete numeric(18,2),
@ArchivoAdjunto1 varchar(200),
@NumeroPesada int,
@Progresiva1 numeric(18,2),
@Progresiva2 numeric(18,2),
@FechaPesada datetime,
@ObservacionesPesada varchar(200)

AS

BEGIN TRAN

BEGIN
	SET @NumeroRecepcionAlmacen=IsNull((Select Top 1 ProximoNumeroInternoRecepcion From Parametros Where IdParametro=1),1)
	UPDATE Parametros
	SET ProximoNumeroInternoRecepcion=@NumeroRecepcionAlmacen+1
END

INSERT INTO Recepciones
(
 NumeroRecepcion1,
 NumeroRecepcion2,
 IdProveedor,
 FechaRecepcion,
 Observaciones,
 IdPedido,
 IdRequerimiento,
 NumeroRecepcionAlmacen,
 IdTransportista,
 Acargo,
 Realizo,
 Anulada,
 IdAcopio,
 SubNumero,
 FechaRegistracion,
 EnviarEmail,
 IdRecepcionOriginal,
 IdOrigenTransmision,
 FechaImportacionTransmision,
 ProcesadoPorCPManualmente,
 ActualizarCostoImportacionDesdePedido,
 IdUsuarioAnulo,
 FechaAnulacion,
 MotivoAnulacion,
 IdUsuarioModifico,
 FechaUltimaModificacion,
 ImpuestosInternos,
 PercepcionIIBB,
 PercepcionIVA,
 PRESTOFechaProceso,
 ImporteIVA,
 IdUsuarioIngreso,
 FechaIngreso,
 Libero,
 FechaLiberacion,
 CircuitoFirmasCompleto,
 IdComprador,
 NumeroRecepcionOrigen1,
 NumeroRecepcionOrigen2,
 Chofer,
 NumeroDocumentoChofer,
 IdEquipo,
 Patente,
 IdDepositoOrigen,
 IdRecepcionSAT,
 TipoRecepcion,
 IdObra,
 NumeroRemitoTransporte1,
 NumeroRemitoTransporte2,
 IdChofer,
 IdFlete,
 PesoBruto,
 PesoNeto,
 Tara,
 CantidadEnOrigen,
 DistanciaRecorrida,
 CodigoTarifador,
 NumeroOrdenCarga,
 IdPesada,
 IdTarifaFlete,
 TarifaFlete,
 ArchivoAdjunto1,
 NumeroPesada,
 Progresiva1,
 Progresiva2,
 FechaPesada,
 ObservacionesPesada
)
VALUES
(
 @NumeroRecepcion1,
 @NumeroRecepcion2,
 @IdProveedor,
 @FechaRecepcion,
 @Observaciones,
 @IdPedido,
 @IdRequerimiento,
 @NumeroRecepcionAlmacen,
 @IdTransportista,
 @Acargo,
 @Realizo,
 @Anulada,
 @IdAcopio,
 @SubNumero,
 GetDate(),
 @EnviarEmail,
 @IdRecepcionOriginal,
 @IdOrigenTransmision,
 @FechaImportacionTransmision,
 @ProcesadoPorCPManualmente,
 @ActualizarCostoImportacionDesdePedido,
 @IdUsuarioAnulo,
 @FechaAnulacion,
 @MotivoAnulacion,
 @IdUsuarioModifico,
 @FechaUltimaModificacion,
 @ImpuestosInternos,
 @PercepcionIIBB,
 @PercepcionIVA,
 @PRESTOFechaProceso,
 @ImporteIVA,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @Libero,
 @FechaLiberacion,
 @CircuitoFirmasCompleto,
 @IdComprador,
 @NumeroRecepcionOrigen1,
 @NumeroRecepcionOrigen2,
 @Chofer,
 @NumeroDocumentoChofer,
 @IdEquipo,
 @Patente,
 @IdDepositoOrigen,
 @IdRecepcionSAT,
 @TipoRecepcion,
 @IdObra,
 @NumeroRemitoTransporte1,
 @NumeroRemitoTransporte2,
 @IdChofer,
 @IdFlete,
 @PesoBruto,
 @PesoNeto,
 @Tara,
 @CantidadEnOrigen,
 @DistanciaRecorrida,
 @CodigoTarifador,
 @NumeroOrdenCarga,
 @IdPesada,
 @IdTarifaFlete,
 @TarifaFlete,
 @ArchivoAdjunto1,
 @NumeroPesada,
 @Progresiva1,
 @Progresiva2,
 @FechaPesada,
 @ObservacionesPesada
)
SELECT @IdRecepcion=@@identity

IF @@ERROR <> 0 GOTO AbortTransaction

COMMIT TRAN
GOTO EndTransaction

AbortTransaction:
ROLLBACK TRAN

EndTransaction:
RETURN(@IdRecepcion)