CREATE Procedure [dbo].[Recepciones_M]

@IdRecepcion int,
@NumeroRecepcion1 int,
@NumeroRecepcion2 int,
@IdProveedor int,
@FechaRecepcion datetime,
@Observaciones ntext,
@IdPedido int,
@IdRequerimiento int,
@NumeroRecepcionAlmacen int,
@IdTransportista int,
@Acargo varchar(1),
@Realizo int,
@Anulada varchar(2),
@IdAcopio int,
@SubNumero varchar(1),
@FechaRegistracion datetime,
@EnviarEmail tinyint,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@ProcesadoPorCPManualmente varchar(2),
@ActualizarCostoImportacionDesdePedido varchar(2),
@IdUsuarioAnulo int,
@FechaAnulacion datetime,
@MotivoAnulacion ntext,
@IdUsuarioModifico int,
@FechaUltimaModificacion datetime,
@ImpuestosInternos numeric(18,2),
@PercepcionIIBB numeric(18,2),
@PercepcionIVA numeric(18,2),
@PRESTOFechaProceso datetime,
@ImporteIVA numeric(18,2),
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@Libero int,
@FechaLiberacion datetime,
@CircuitoFirmasCompleto varchar(2),
@IdComprador int,
@NumeroRecepcionOrigen1 int,
@NumeroRecepcionOrigen2 int,
@Chofer varchar(50),
@NumeroDocumentoChofer varchar(30),
@IdEquipo int,
@Patente varchar(10),
@IdDepositoOrigen int,
@IdRecepcionSAT int,
@TipoRecepcion int,
@IdObra int,
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@NumeroOrdenCarga int,
@IdPesada int,
@IdTarifaFlete int,
@TarifaFlete numeric(18,2),
@ArchivoAdjunto1 varchar(200),
@NumeroPesada int,
@Progresiva1 numeric(18,2),
@Progresiva2 numeric(18,2),
@FechaPesada datetime,
@ObservacionesPesada varchar(200)

AS

UPDATE Recepciones
SET 
 NumeroRecepcion1=@NumeroRecepcion1,
 NumeroRecepcion2=@NumeroRecepcion2,
 IdProveedor=@IdProveedor,
 FechaRecepcion=@FechaRecepcion,
 Observaciones=@Observaciones,
 IdPedido=@IdPedido,
 IdRequerimiento=@IdRequerimiento,
 NumeroRecepcionAlmacen=@NumeroRecepcionAlmacen,
 IdTransportista=@IdTransportista,
 Acargo=@Acargo,
 Realizo=@Realizo,
 Anulada=@Anulada,
 IdAcopio=@IdAcopio,
-- SubNumero=@SubNumero,
 FechaRegistracion=@FechaRegistracion,
 EnviarEmail=@EnviarEmail,
 IdRecepcionOriginal=@IdRecepcionOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 ProcesadoPorCPManualmente=@ProcesadoPorCPManualmente,
 ActualizarCostoImportacionDesdePedido=@ActualizarCostoImportacionDesdePedido,
 IdUsuarioAnulo=@IdUsuarioAnulo,
 FechaAnulacion=@FechaAnulacion,
 MotivoAnulacion=@MotivoAnulacion,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaUltimaModificacion=@FechaUltimaModificacion,
 ImpuestosInternos=@ImpuestosInternos,
 PercepcionIIBB=@PercepcionIIBB,
 PercepcionIVA=@PercepcionIVA,
 PRESTOFechaProceso=@PRESTOFechaProceso,
 ImporteIVA=@ImporteIVA,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 Libero=@Libero,
 FechaLiberacion=@FechaLiberacion,
 CircuitoFirmasCompleto=@CircuitoFirmasCompleto,
 IdComprador=@IdComprador,
 NumeroRecepcionOrigen1=@NumeroRecepcionOrigen1,
 NumeroRecepcionOrigen2=@NumeroRecepcionOrigen2,
 Chofer=@Chofer,
 NumeroDocumentoChofer=@NumeroDocumentoChofer,
 IdEquipo=@IdEquipo,
 Patente=@Patente,
 IdDepositoOrigen=@IdDepositoOrigen,
 IdRecepcionSAT=@IdRecepcionSAT,
 TipoRecepcion=@TipoRecepcion,
 IdObra=@IdObra,
 NumeroRemitoTransporte1=@NumeroRemitoTransporte1,
 NumeroRemitoTransporte2=@NumeroRemitoTransporte2,
 IdChofer=@IdChofer,
 IdFlete=@IdFlete,
 PesoBruto=@PesoBruto,
 PesoNeto=@PesoNeto,
 Tara=@Tara,
 CantidadEnOrigen=@CantidadEnOrigen,
 DistanciaRecorrida=@DistanciaRecorrida,
 CodigoTarifador=@CodigoTarifador,
 NumeroOrdenCarga=@NumeroOrdenCarga,
 IdPesada=@IdPesada,
 IdTarifaFlete=@IdTarifaFlete,
 TarifaFlete=@TarifaFlete,
 ArchivoAdjunto1=@ArchivoAdjunto1,
 NumeroPesada=@NumeroPesada,
 Progresiva1=@Progresiva1,
 Progresiva2=@Progresiva2,
 FechaPesada=@FechaPesada,
 ObservacionesPesada=@ObservacionesPesada
WHERE (IdRecepcion=@IdRecepcion)

RETURN(@IdRecepcion)