CREATE Procedure [dbo].[Recibos_M]

@IdRecibo int,
@NumeroRecibo int,
@FechaRecibo datetime,
@IdCliente int,
@Efectivo numeric(18,2),
@Descuentos numeric(18,2),
@Valores numeric(18,2),
@Documentos numeric(18,2),
@Otros1 numeric(18,2),
@IdCuenta1 int,
@Otros2 numeric(18,2),
@IdCuenta2 int,
@Otros3 numeric(18,2),
@IdCuenta3 int,
@Deudores numeric(18,2),
@RetencionIVA numeric(18,2),
@RetencionGanancias numeric(18,2),
@RetencionIBrutos numeric(18,2),
@GastosGenerales numeric(18,2),
@Cotizacion numeric(18,4),
@Observaciones ntext,
@IdMoneda int,
@Dolarizada varchar(2),
@IdObra1 int,
@IdCuentaGasto1 int,
@IdObra2 int,
@IdCuentaGasto2 int,
@IdObra3 int,
@IdCuentaGasto3 int,
@IdObra4 int,
@IdCuentaGasto4 int,
@IdCuenta4 int,
@Otros4 numeric(18,2),
@IdObra5 int,
@IdCuentaGasto5 int,
@IdCuenta5 int,
@Otros5 numeric(18,2),
@Tipo varchar(2),
@IdCuenta int,
@AsientoManual varchar(2),
@IdObra int,
@IdCuentaGasto int,
@NumeroCertificadoRetencionGanancias numeric(18,0),
@NumeroCertificadoRetencionIVA numeric(18,0),
@NumeroCertificadoSUSS numeric(18,0),
@IdTipoRetencionGanancia int,
@CotizacionMoneda numeric(18,4),
@NumeroCertificadoRetencionIngresosBrutos int,
@Anulado varchar(2),
@PuntoVenta int,
@IdPuntoVenta int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@IdCobrador int,
@IdVendedor int,
@Lote int,
@Sublote int,
@IdCodigoIvaOpcional int,
@TipoOperacionOtros int,
@FechaLote datetime,
@CuitOpcional varchar(13),
@IdComprobanteProveedorReintegro int,
@IdObra6 int,
@IdCuentaGasto6 int,
@IdCuenta6 int,
@Otros6 numeric(18,2),
@IdObra7 int,
@IdCuentaGasto7 int,
@IdCuenta7 int,
@Otros7 numeric(18,2),
@IdObra8 int,
@IdCuentaGasto8 int,
@IdCuenta8 int,
@Otros8 numeric(18,2),
@IdObra9 int,
@IdCuentaGasto9 int,
@IdCuenta9 int,
@Otros9 numeric(18,2),
@IdObra10 int,
@IdCuentaGasto10 int,
@IdCuenta10 int,
@Otros10 numeric(18,2),
@NumeroComprobante1 numeric(18,0),
@NumeroComprobante2 numeric(18,0),
@NumeroComprobante3 numeric(18,0),
@NumeroComprobante4 numeric(18,0),
@NumeroComprobante5 numeric(18,0),
@NumeroComprobante6 numeric(18,0),
@NumeroComprobante7 numeric(18,0),
@NumeroComprobante8 numeric(18,0),
@NumeroComprobante9 numeric(18,0),
@NumeroComprobante10 numeric(18,0),
@EnviarEmail tinyint,
@IdOrigenTransmision int,
@IdReciboOriginal int,
@FechaImportacionTransmision datetime,
@CuitClienteTransmision varchar(13),
@IdProvinciaDestino int,
@ServicioCobro varchar(10),
@LoteServicioCobro varchar(15),
@IdFacturaDirecta int

AS 

UPDATE Recibos
SET 
 NumeroRecibo=@NumeroRecibo,
 FechaRecibo=@FechaRecibo,
 IdCliente=@IdCliente,
 Efectivo=@Efectivo,
 Descuentos=@Descuentos,
 Valores=@Valores,
 Documentos=@Documentos,
 Otros1=@Otros1,
 IdCuenta1=@IdCuenta1,
 Otros2=@Otros2,
 IdCuenta2=@IdCuenta2,
 Otros3=@Otros3,
 IdCuenta3=@IdCuenta3,
 Deudores=@Deudores,
 RetencionIVA=@RetencionIVA,
 RetencionGanancias=@RetencionGanancias,
 RetencionIBrutos=@RetencionIBrutos,
 GastosGenerales=@GastosGenerales,
 Cotizacion=@Cotizacion,
 Observaciones=@Observaciones,
 IdMoneda=@IdMoneda,
 Dolarizada=@Dolarizada,
 IdObra1=@IdObra1,
 IdCuentaGasto1=@IdCuentaGasto1,
 IdObra2=@IdObra2,
 IdCuentaGasto2=@IdCuentaGasto2,
 IdObra3=@IdObra3,
 IdCuentaGasto3=@IdCuentaGasto3,
 IdObra4=@IdObra4,
 IdCuentaGasto4=@IdCuentaGasto4,
 IdCuenta4=@IdCuenta4,
 Otros4=@Otros4,
 IdObra5=@IdObra5,
 IdCuentaGasto5=@IdCuentaGasto5,
 IdCuenta5=@IdCuenta5,
 Otros5=@Otros5,
 Tipo=@Tipo,
 IdCuenta=@IdCuenta,
 AsientoManual=@AsientoManual,
 IdObra=@IdObra,
 IdCuentaGasto=@IdCuentaGasto,
 NumeroCertificadoRetencionGanancias=@NumeroCertificadoRetencionGanancias,
 NumeroCertificadoRetencionIVA=@NumeroCertificadoRetencionIVA,
 NumeroCertificadoSUSS=@NumeroCertificadoSUSS,
 IdTipoRetencionGanancia=@IdTipoRetencionGanancia,
 CotizacionMoneda=@CotizacionMoneda,
 NumeroCertificadoRetencionIngresosBrutos=@NumeroCertificadoRetencionIngresosBrutos,
 Anulado=@Anulado,
 PuntoVenta=@PuntoVenta,
 IdPuntoVenta=@IdPuntoVenta,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaModifico=@FechaModifico,
 IdCobrador=@IdCobrador,
 IdVendedor=@IdVendedor,
 Lote=@Lote,
 Sublote=@Sublote,
 IdCodigoIvaOpcional=@IdCodigoIvaOpcional,
 TipoOperacionOtros=@TipoOperacionOtros,
 FechaLote=@FechaLote,
 CuitOpcional=@CuitOpcional,
 IdComprobanteProveedorReintegro=@IdComprobanteProveedorReintegro,
 IdObra6=@IdObra6,
 IdCuentaGasto6=@IdCuentaGasto6,
 IdCuenta6=@IdCuenta6,
 Otros6=@Otros6,
 IdObra7=@IdObra7,
 IdCuentaGasto7=@IdCuentaGasto7,
 IdCuenta7=@IdCuenta7,
 Otros7=@Otros7,
 IdObra8=@IdObra8,
 IdCuentaGasto8=@IdCuentaGasto8,
 IdCuenta8=@IdCuenta8,
 Otros8=@Otros8,
 IdObra9=@IdObra9,
 IdCuentaGasto9=@IdCuentaGasto9,
 IdCuenta9=@IdCuenta9,
 Otros9=@Otros9,
 IdObra10=@IdObra10,
 IdCuentaGasto10=@IdCuentaGasto10,
 IdCuenta10=@IdCuenta10,
 Otros10=@Otros10,
 NumeroComprobante1=@NumeroComprobante1,
 NumeroComprobante2=@NumeroComprobante2,
 NumeroComprobante3=@NumeroComprobante3,
 NumeroComprobante4=@NumeroComprobante4,
 NumeroComprobante5=@NumeroComprobante5,
 NumeroComprobante6=@NumeroComprobante6,
 NumeroComprobante7=@NumeroComprobante7,
 NumeroComprobante8=@NumeroComprobante8,
 NumeroComprobante9=@NumeroComprobante9,
 NumeroComprobante10=@NumeroComprobante10,
 EnviarEmail=@EnviarEmail,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdReciboOriginal=@IdReciboOriginal,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 CuitClienteTransmision=@CuitClienteTransmision,
 IdProvinciaDestino=@IdProvinciaDestino,
 ServicioCobro=@ServicioCobro,
 LoteServicioCobro=@LoteServicioCobro,
 IdFacturaDirecta=@IdFacturaDirecta
WHERE (IdRecibo=@IdRecibo)

IF @Anulado='SI'
	UPDATE Valores
	SET IdReciboAsignado=Null
	WHERE IsNull(IdReciboAsignado,0)=@IdRecibo

RETURN(@IdRecibo)