CREATE Procedure [dbo].[Recibos_A]

@IdRecibo int  output,
@NumeroRecibo int,
@FechaRecibo datetime,
@IdCliente int,
@Efectivo numeric(18,2),
@Descuentos numeric(18,2),
@Valores numeric(18,2),
@Documentos numeric(18,2),
@Otros1 numeric(18,2),
@IdCuenta1 int,
@Otros2 numeric(18,2),
@IdCuenta2 int,
@Otros3 numeric(18,2),
@IdCuenta3 int,
@Deudores numeric(18,2),
@RetencionIVA numeric(18,2),
@RetencionGanancias numeric(18,2),
@RetencionIBrutos numeric(18,2),
@GastosGenerales numeric(18,2),
@Cotizacion numeric(18,4),
@Observaciones ntext,
@IdMoneda int,
@Dolarizada varchar(2),
@IdObra1 int,
@IdCuentaGasto1 int,
@IdObra2 int,
@IdCuentaGasto2 int,
@IdObra3 int,
@IdCuentaGasto3 int,
@IdObra4 int,
@IdCuentaGasto4 int,
@IdCuenta4 int,
@Otros4 numeric(18,2),
@IdObra5 int,
@IdCuentaGasto5 int,
@IdCuenta5 int,
@Otros5 numeric(18,2),
@Tipo varchar(2),
@IdCuenta int,
@AsientoManual varchar(2),
@IdObra int,
@IdCuentaGasto int,
@NumeroCertificadoRetencionGanancias numeric(18,0),
@NumeroCertificadoRetencionIVA numeric(18,0),
@NumeroCertificadoSUSS numeric(18,0),
@IdTipoRetencionGanancia int,
@CotizacionMoneda numeric(18,4),
@NumeroCertificadoRetencionIngresosBrutos int,
@Anulado varchar(2),
@PuntoVenta int,
@IdPuntoVenta int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@IdCobrador int,
@IdVendedor int,
@Lote int,
@Sublote int,
@IdCodigoIvaOpcional int,
@TipoOperacionOtros int,
@FechaLote datetime,
@CuitOpcional varchar(13),
@IdComprobanteProveedorReintegro int,
@IdObra6 int,
@IdCuentaGasto6 int,
@IdCuenta6 int,
@Otros6 numeric(18,2),
@IdObra7 int,
@IdCuentaGasto7 int,
@IdCuenta7 int,
@Otros7 numeric(18,2),
@IdObra8 int,
@IdCuentaGasto8 int,
@IdCuenta8 int,
@Otros8 numeric(18,2),
@IdObra9 int,
@IdCuentaGasto9 int,
@IdCuenta9 int,
@Otros9 numeric(18,2),
@IdObra10 int,
@IdCuentaGasto10 int,
@IdCuenta10 int,
@Otros10 numeric(18,2),
@NumeroComprobante1 numeric(18,0),
@NumeroComprobante2 numeric(18,0),
@NumeroComprobante3 numeric(18,0),
@NumeroComprobante4 numeric(18,0),
@NumeroComprobante5 numeric(18,0),
@NumeroComprobante6 numeric(18,0),
@NumeroComprobante7 numeric(18,0),
@NumeroComprobante8 numeric(18,0),
@NumeroComprobante9 numeric(18,0),
@NumeroComprobante10 numeric(18,0),
@EnviarEmail tinyint,
@IdOrigenTransmision int,
@IdReciboOriginal int,
@FechaImportacionTransmision datetime,
@CuitClienteTransmision varchar(13),
@IdProvinciaDestino int,
@ServicioCobro varchar(10),
@LoteServicioCobro varchar(15),
@IdFacturaDirecta int

AS 

BEGIN TRAN
  BEGIN
	DECLARE @NumeracionAutomaticaDeRecibos varchar(2), @Numero int, @PermitirModificarNumeroRecibo varchar(2), @PermitirRepetirNumeroRecibo varchar(2)

	SET @PermitirModificarNumeroRecibo=Isnull((Select Top 1 ProntoIni.Valor From ProntoIni 
												Left Outer Join ProntoIniClaves pic On pic.IdProntoIniClave=ProntoIni.IdProntoIniClave
												Where pic.Clave='Permitir modificar el numero de recibo' and IsNull(ProntoIni.Valor,'')='SI'),'')
	SET @PermitirRepetirNumeroRecibo=Isnull((Select Top 1 ProntoIni.Valor From ProntoIni 
												Left Outer Join ProntoIniClaves pic On pic.IdProntoIniClave=ProntoIni.IdProntoIniClave
												Where pic.Clave='Permitir repetir numeros de recibo' and IsNull(ProntoIni.Valor,'')='SI'),'')

	SET @NumeracionAutomaticaDeRecibos=IsNull((Select Top 1 NumeroReciboPagoAutomatico From Parametros Where IdParametro=1),'')

	IF @NumeracionAutomaticaDeRecibos='SI'
	  BEGIN
		SET @Numero=IsNull((Select Top 1 ProximoNumero From PuntosVenta Where IdPuntoVenta=@IdPuntoVenta),0)

		IF @PermitirRepetirNumeroRecibo<>'SI'
			WHILE Exists(Select Top 1 IdRecibo From Recibos Where NumeroRecibo=@Numero and IdPuntoVenta=@IdPuntoVenta)
				SET @Numero=@Numero+1

		IF @Numero>0 and (@PermitirModificarNumeroRecibo<>'SI' or @NumeroRecibo<=@Numero)
		  BEGIN
			SET @NumeroRecibo=@Numero
			UPDATE PuntosVenta SET ProximoNumero=@NumeroRecibo+1 WHERE IdPuntoVenta=@IdPuntoVenta
		  END
	  END
  END

INSERT INTO [Recibos]
(
 NumeroRecibo,
 FechaRecibo,
 IdCliente,
 Efectivo,
 Descuentos,
 Valores,
 Documentos,
 Otros1,
 IdCuenta1,
 Otros2,
 IdCuenta2,
 Otros3,
 IdCuenta3,
 Deudores,
 RetencionIVA,
 RetencionGanancias,
 RetencionIBrutos,
 GastosGenerales,
 Cotizacion,
 Observaciones,
 IdMoneda,
 Dolarizada,
 IdObra1,
 IdCuentaGasto1,
 IdObra2,
 IdCuentaGasto2,
 IdObra3,
 IdCuentaGasto3,
 IdObra4,
 IdCuentaGasto4,
 IdCuenta4,
 Otros4,
 IdObra5,
 IdCuentaGasto5,
 IdCuenta5,
 Otros5,
 Tipo,
 IdCuenta,
 AsientoManual,
 IdObra,
 IdCuentaGasto,
 NumeroCertificadoRetencionGanancias,
 NumeroCertificadoRetencionIVA,
 NumeroCertificadoSUSS,
 IdTipoRetencionGanancia,
 CotizacionMoneda,
 NumeroCertificadoRetencionIngresosBrutos,
 Anulado,
 PuntoVenta,
 IdPuntoVenta,
 IdUsuarioIngreso,
 FechaIngreso,
 IdUsuarioModifico,
 FechaModifico,
 IdCobrador,
 IdVendedor,
 Lote,
 Sublote,
 IdCodigoIvaOpcional,
 TipoOperacionOtros,
 FechaLote,
 CuitOpcional,
 IdComprobanteProveedorReintegro,
 IdObra6,
 IdCuentaGasto6,
 IdCuenta6,
 Otros6,
 IdObra7,
 IdCuentaGasto7,
 IdCuenta7,
 Otros7,
 IdObra8,
 IdCuentaGasto8,
 IdCuenta8,
 Otros8,
 IdObra9,
 IdCuentaGasto9,
 IdCuenta9,
 Otros9,
 IdObra10,
 IdCuentaGasto10,
 IdCuenta10,
 Otros10,
 NumeroComprobante1,
 NumeroComprobante2,
 NumeroComprobante3,
 NumeroComprobante4,
 NumeroComprobante5,
 NumeroComprobante6,
 NumeroComprobante7,
 NumeroComprobante8,
 NumeroComprobante9,
 NumeroComprobante10,
 EnviarEmail, IdOrigenTransmision,
 IdReciboOriginal,
 FechaImportacionTransmision,
 CuitClienteTransmision,
 IdProvinciaDestino,
 ServicioCobro,
 LoteServicioCobro,
 IdFacturaDirecta
)
VALUES 
(
 @NumeroRecibo,
 @FechaRecibo,
 @IdCliente,
 @Efectivo,
 @Descuentos,
 @Valores,
 @Documentos,
 @Otros1,
 @IdCuenta1,
 @Otros2,
 @IdCuenta2,
 @Otros3,
 @IdCuenta3,
 @Deudores,
 @RetencionIVA,
 @RetencionGanancias,
 @RetencionIBrutos,
 @GastosGenerales,
 @Cotizacion,
 @Observaciones,
 @IdMoneda,
 @Dolarizada,
 @IdObra1,
 @IdCuentaGasto1,
 @IdObra2,
 @IdCuentaGasto2,
 @IdObra3,
 @IdCuentaGasto3,
 @IdObra4,
 @IdCuentaGasto4,
 @IdCuenta4,
 @Otros4,
 @IdObra5,
 @IdCuentaGasto5,
 @IdCuenta5,
 @Otros5,
 @Tipo,
 @IdCuenta,
 @AsientoManual,
 @IdObra,
 @IdCuentaGasto,
 @NumeroCertificadoRetencionGanancias,
 @NumeroCertificadoRetencionIVA,
 @NumeroCertificadoSUSS,
 @IdTipoRetencionGanancia,
 @CotizacionMoneda,
 @NumeroCertificadoRetencionIngresosBrutos,
 @Anulado,
 @PuntoVenta,
 @IdPuntoVenta,
 @IdUsuarioIngreso,
 @FechaIngreso,
 @IdUsuarioModifico,
 @FechaModifico,
 @IdCobrador,
 @IdVendedor,
 @Lote,
 @Sublote,
 @IdCodigoIvaOpcional, 
 @TipoOperacionOtros,
 @FechaLote,
 @CuitOpcional,
 @IdComprobanteProveedorReintegro,
 @IdObra6,
 @IdCuentaGasto6,
 @IdCuenta6,
 @Otros6,
 @IdObra7,
 @IdCuentaGasto7,
 @IdCuenta7,
 @Otros7,
 @IdObra8,
 @IdCuentaGasto8,
 @IdCuenta8,
 @Otros8,
 @IdObra9,
 @IdCuentaGasto9,
 @IdCuenta9,
 @Otros9,
 @IdObra10,
 @IdCuentaGasto10,
 @IdCuenta10,
 @Otros10,
 @NumeroComprobante1,
 @NumeroComprobante2,
 @NumeroComprobante3,
 @NumeroComprobante4,
 @NumeroComprobante5,
 @NumeroComprobante6,
 @NumeroComprobante7,
 @NumeroComprobante8,
 @NumeroComprobante9,
 @NumeroComprobante10,
 @EnviarEmail,
 @IdOrigenTransmision,
 @IdReciboOriginal,
 @FechaImportacionTransmision,
 @CuitClienteTransmision,
 @IdProvinciaDestino,
 @ServicioCobro,
 @LoteServicioCobro,
 @IdFacturaDirecta
)

SELECT @IdRecibo=@@identity
IF @@ERROR <> 0 GOTO AbortTransaction

COMMIT TRAN
GOTO EndTransaction

AbortTransaction:
ROLLBACK TRAN

EndTransaction:
RETURN(@IdRecibo)