
CREATE Procedure [dbo].[Remitos_M]

@IdRemito int,
@NumeroRemito int,
@IdCliente int,
@FechaRemito datetime,
@IdCondicionVenta int,
@Anulado varchar(2),
@FechaAnulacion datetime,
@Observaciones ntext,
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@Destino int,
@IdProveedor int,
@IdTransportista int,
@TotalBultos int,
@ValorDeclarado numeric(18,2),
@FechaRegistracion datetime,
@IdAutorizaAnulacion int,
@IdPuntoVenta int,
@PuntoVenta int,
@Patente varchar(25),
@Chofer varchar(50),
@NumeroDocumento varchar(30),
@OrdenCarga varchar(10),
@OrdenCompra varchar(10),
@COT varchar(20),
@IdEquipo int,
@IdObra int,
@IdListaPrecios int,
@IdDetalleClienteLugarEntrega int,
@HoraSalida varchar(10),
@PesoBruto numeric(18,2),
@Tara numeric(18,2)

AS

UPDATE Remitos
SET 
 NumeroRemito=@NumeroRemito,
 IdCliente=@IdCliente,
 FechaRemito=@FechaRemito,
 IdCondicionVenta=@IdCondicionVenta,
 Anulado=@Anulado,
 FechaAnulacion=@FechaAnulacion,
 Observaciones=@Observaciones,
 ArchivoAdjunto1=@ArchivoAdjunto1,
 ArchivoAdjunto2=@ArchivoAdjunto2,
 ArchivoAdjunto3=@ArchivoAdjunto3,
 ArchivoAdjunto4=@ArchivoAdjunto4,
 ArchivoAdjunto5=@ArchivoAdjunto5,
 ArchivoAdjunto6=@ArchivoAdjunto6,
 ArchivoAdjunto7=@ArchivoAdjunto7,
 ArchivoAdjunto8=@ArchivoAdjunto8,
 ArchivoAdjunto9=@ArchivoAdjunto9,
 ArchivoAdjunto10=@ArchivoAdjunto10,
 Destino=@Destino,
 IdProveedor=@IdProveedor,
 IdTransportista=@IdTransportista,
 TotalBultos=@TotalBultos,
 ValorDeclarado=@ValorDeclarado,
 FechaRegistracion=@FechaRegistracion,
 IdAutorizaAnulacion=@IdAutorizaAnulacion,
 IdPuntoVenta=@IdPuntoVenta,
 PuntoVenta=@PuntoVenta,
 Patente=@Patente,
 Chofer=@Chofer,
 NumeroDocumento=@NumeroDocumento,
 OrdenCarga=@OrdenCarga,
 OrdenCompra=@OrdenCompra,
 COT=@COT,
 IdEquipo=@IdEquipo,
 IdObra=@IdObra,
 IdListaPrecios=@IdListaPrecios,
 IdDetalleClienteLugarEntrega=@IdDetalleClienteLugarEntrega,
 HoraSalida=@HoraSalida,
 PesoBruto=@PesoBruto,
 Tara=@Tara
WHERE (IdRemito=@IdRemito)

RETURN(@IdRemito)
