
CREATE Procedure [dbo].[SalidasMaterialesSAT_M]

@IdSalidaMateriales int,
@NumeroSalidaMateriales int,
@FechaSalidaMateriales datetime,
@IdObra int,
@Observaciones ntext,
@Aprobo int,
@TipoSalida int,
@IdTransportista1 int,
@IdTransportista2 int,
@Cliente varchar(50),
@Direccion varchar(50),
@Localidad varchar(50),
@CodigoPostal varchar(30),
@CondicionIva varchar(30),
@Cuit varchar(13),
@NumeroSalidaMateriales2 int,
@ACargo varchar(1),
@Emitio int,
@ValePreimpreso int,
@Referencia varchar(50),
@NumeroDocumento varchar(30),
@Patente1 varchar(25),
@Patente2 varchar(25),
@Patente3 varchar(25),
@Patente4 varchar(25),
@IdProveedor int,
@Chofer varchar(50),
@IdCentroCosto int,
@FechaRegistracion datetime,
@Anulada varchar(2),
@FechaAnulacion datetime,
@IdUsuarioAnulo int,
@EnviarEmail tinyint,
@IdSalidaMaterialesOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@MotivoAnulacion ntext,
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@IdPesada int

AS

UPDATE SalidasMaterialesSAT
SET
 NumeroSalidaMateriales=@NumeroSalidaMateriales,
 FechaSalidaMateriales=@FechaSalidaMateriales,
 IdObra=@IdObra,
 Observaciones=@Observaciones,
 Aprobo=@Aprobo,
 TipoSalida=@TipoSalida,
 IdTransportista1=@IdTransportista1,
 IdTransportista2=@IdTransportista2,
 Cliente=@Cliente,
 Direccion=@Direccion,
 Localidad=@Localidad,
 CodigoPostal=@CodigoPostal,
 CondicionIva=@CondicionIva,
 Cuit=@Cuit,
 NumeroSalidaMateriales2=@NumeroSalidaMateriales2,
 ACargo=@ACargo,
 Emitio=@Emitio,
 ValePreimpreso=@ValePreimpreso,
 Referencia=@Referencia,
 NumeroDocumento=@NumeroDocumento,
 Patente1=@Patente1,
 Patente2=@Patente2,
 Patente3=@Patente3,
 Patente4=@Patente4,
 IdProveedor=@IdProveedor,
 Chofer=@Chofer,
 IdCentroCosto=@IdCentroCosto,
 FechaRegistracion=@FechaRegistracion,
 Anulada=@Anulada,
 FechaAnulacion=@FechaAnulacion,
 IdUsuarioAnulo=@IdUsuarioAnulo,
 EnviarEmail=@EnviarEmail,
 IdSalidaMaterialesOriginal=@IdSalidaMaterialesOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 MotivoAnulacion=@MotivoAnulacion,
 NumeroRemitoTransporte1=@NumeroRemitoTransporte1,
 NumeroRemitoTransporte2=@NumeroRemitoTransporte2,
 IdChofer=@IdChofer,
 IdFlete=@IdFlete,
 PesoBruto=@PesoBruto,
 PesoNeto=@PesoNeto,
 Tara=@Tara,
 CantidadEnOrigen=@CantidadEnOrigen,
 DistanciaRecorrida=@DistanciaRecorrida,
 CodigoTarifador=@CodigoTarifador,
 IdPesada=@IdPesada
WHERE (IdSalidaMateriales=@IdSalidaMateriales)

RETURN(@IdSalidaMateriales)
