CREATE Procedure [dbo].[SalidasMateriales_M]

@IdSalidaMateriales int,
@NumeroSalidaMateriales int,
@FechaSalidaMateriales datetime,
@IdObra int,
@Observaciones ntext,
@Aprobo int,
@TipoSalida int,
@IdTransportista1 int,
@IdTransportista2 int,
@Cliente varchar(100),
@Direccion varchar(50),
@Localidad varchar(50),
@CodigoPostal varchar(30),
@CondicionIva varchar(30),
@Cuit varchar(13),
@NumeroSalidaMateriales2 int,
@ACargo varchar(1),
@Emitio int,
@ValePreimpreso int,
@Referencia varchar(50),
@NumeroDocumento varchar(30),
@Patente1 varchar(25),
@Patente2 varchar(25),
@Patente3 varchar(25),
@Patente4 varchar(25),
@IdProveedor int,
@Chofer varchar(50),
@IdCentroCosto int,
@FechaRegistracion datetime,
@Anulada varchar(2),
@FechaAnulacion datetime,
@IdUsuarioAnulo int,
@EnviarEmail tinyint,
@IdSalidaMaterialesOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@MotivoAnulacion ntext,
@NumeroOrdenProduccion int,
@IdDepositoOrigen int,
@IdUsuarioIngreso int,
@FechaIngreso datetime,
@IdUsuarioModifico int,
@FechaModifico datetime,
@IdRecepcionSAT int,
@ClaveTipoSalida varchar(30),
@SalidaADepositoEnTransito varchar(2),
@ValorDeclarado numeric(18,2),
@Bultos int,
@IdColor int,
@Embalo varchar(50),
@CircuitoFirmasCompleto varchar(2),
@IdPuntoVenta int,
@NumeroRemitoTransporte varchar(15),
@IdEquipo int,
@IdSalidaMaterialesSAT int,
@IdObraOrigen int,
@NumeroRemitoPreimpreso1 int,
@NumeroRemitoPreimpreso2 int,
@IdFlete int,
@IdChofer int,
@DestinoDeObra varchar(50),
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@IdPesada int,
@IdTarifaFlete int,
@TarifaFlete numeric(18,2),
@Detalle varchar(30),
@IdProduccionOrden int,
@IdDepositoIntermedio int,
@NumeroPesada int,
@Progresiva1 numeric(18,2),
@Progresiva2 numeric(18,2),
@FechaPesada datetime,
@ObservacionesPesada varchar(200),
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@RecibidosEnDestino varchar(2),
@RecibidosEnDestinoFecha datetime,
@RecibidosEnDestinoIdUsuario int,
@IdCalle1 int,
@IdCalle2 int,
@IdCalle3 int

AS

UPDATE SalidasMateriales
SET
 NumeroSalidaMateriales=@NumeroSalidaMateriales,
 FechaSalidaMateriales=@FechaSalidaMateriales,
 IdObra=@IdObra,
 Observaciones=@Observaciones,
 Aprobo=@Aprobo,
 TipoSalida=@TipoSalida,
 IdTransportista1=@IdTransportista1,
 IdTransportista2=@IdTransportista2,
 Cliente=@Cliente,
 Direccion=@Direccion,
 Localidad=@Localidad,
 CodigoPostal=@CodigoPostal,
 CondicionIva=@CondicionIva,
 Cuit=@Cuit,
 NumeroSalidaMateriales2=@NumeroSalidaMateriales2,
 ACargo=@ACargo,
 Emitio=@Emitio,
 ValePreimpreso=@ValePreimpreso,
 Referencia=@Referencia,
 NumeroDocumento=@NumeroDocumento,
 Patente1=@Patente1,
 Patente2=@Patente2,
 Patente3=@Patente3,
 Patente4=@Patente4,
 IdProveedor=@IdProveedor,
 Chofer=@Chofer,
 IdCentroCosto=@IdCentroCosto,
 FechaRegistracion=@FechaRegistracion,
 Anulada=@Anulada,
 FechaAnulacion=@FechaAnulacion,
 IdUsuarioAnulo=@IdUsuarioAnulo,
 EnviarEmail=@EnviarEmail,
 IdSalidaMaterialesOriginal=@IdSalidaMaterialesOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 MotivoAnulacion=@MotivoAnulacion,
 NumeroOrdenProduccion=@NumeroOrdenProduccion,
 IdDepositoOrigen=@IdDepositoOrigen,
 IdUsuarioIngreso=@IdUsuarioIngreso,
 FechaIngreso=@FechaIngreso,
 IdUsuarioModifico=@IdUsuarioModifico,
 FechaModifico=@FechaModifico,
 IdRecepcionSAT=@IdRecepcionSAT,
 ClaveTipoSalida=@ClaveTipoSalida,
 SalidaADepositoEnTransito=@SalidaADepositoEnTransito,
 ValorDeclarado=@ValorDeclarado,
 Bultos=@Bultos,
 IdColor=@IdColor,
 Embalo=@Embalo,
 CircuitoFirmasCompleto=@CircuitoFirmasCompleto,
 IdPuntoVenta=@IdPuntoVenta,
 NumeroRemitoTransporte=@NumeroRemitoTransporte,
 IdEquipo=@IdEquipo,
 IdSalidaMaterialesSAT=@IdSalidaMaterialesSAT,
 IdObraOrigen=@IdObraOrigen,
 NumeroRemitoPreimpreso1=@NumeroRemitoPreimpreso1,
 NumeroRemitoPreimpreso2=@NumeroRemitoPreimpreso2,
 IdFlete=@IdFlete,
 IdChofer=@IdChofer,
 DestinoDeObra=@DestinoDeObra,
 PesoBruto=@PesoBruto,
 PesoNeto=@PesoNeto,
 Tara=@Tara,
 CantidadEnOrigen=@CantidadEnOrigen,
 DistanciaRecorrida=@DistanciaRecorrida,
 CodigoTarifador=@CodigoTarifador,
 IdPesada=@IdPesada,
 IdTarifaFlete=@IdTarifaFlete,
 TarifaFlete=@TarifaFlete,
 Detalle=@Detalle,
 IdProduccionOrden=@IdProduccionOrden,
 IdDepositoIntermedio=@IdDepositoIntermedio,
 NumeroPesada=@NumeroPesada,
 Progresiva1=@Progresiva1,
 Progresiva2=@Progresiva2,
 FechaPesada=@FechaPesada,
 ObservacionesPesada=@ObservacionesPesada,
 NumeroRemitoTransporte1=@NumeroRemitoTransporte1,
 NumeroRemitoTransporte2=@NumeroRemitoTransporte2,
 RecibidosEnDestino=@RecibidosEnDestino,
 RecibidosEnDestinoFecha=@RecibidosEnDestinoFecha,
 RecibidosEnDestinoIdUsuario=@RecibidosEnDestinoIdUsuario,
 IdCalle1=@IdCalle1,
 IdCalle2=@IdCalle2,
 IdCalle3=@IdCalle3
WHERE (IdSalidaMateriales=@IdSalidaMateriales)

IF IsNull(@SalidaADepositoEnTransito,'NO')='SI' and 
	Exists(Select Top 1 IdObra From ArchivosATransmitirDestinos Where IsNull(Activo,'SI')='SI' and IsNull(Sistema,'')='SAT' and IdObra=@IdObra) and 
	Not Exists(Select Top 1 IdSalidaMateriales From OtrosIngresosAlmacen Where IdSalidaMateriales=@IdSalidaMateriales)
   BEGIN
	DECLARE @NumeroOtroIngresoAlmacen int, @Salida varchar(20)

	SET @NumeroOtroIngresoAlmacen=IsNull((Select Top 1 ProximoNumeroOtroIngresoAlmacen From Parametros Where IdParametro=1),1)

	UPDATE Parametros
	SET ProximoNumeroOtroIngresoAlmacen=@NumeroOtroIngresoAlmacen+1

	SET @Salida=Substring('0000',1,4-Len(Convert(varchar,IsNull(@NumeroSalidaMateriales2,0))))+Convert(varchar,IsNull(@NumeroSalidaMateriales2,0))+'-'+
			Substring('00000000',1,8-Len(Convert(varchar,@NumeroSalidaMateriales)))+Convert(varchar,@NumeroSalidaMateriales)

	INSERT INTO OtrosIngresosAlmacen
	(NumeroOtroIngresoAlmacen, FechaOtroIngresoAlmacen, IdObra, Observaciones, Aprobo, TipoIngreso, Emitio, FechaRegistracion, IdSalidaMateriales)
	VALUES 
	(@NumeroOtroIngresoAlmacen, @FechaSalidaMateriales, @IdObra, 'SALIDA '+@Salida, @Aprobo, 4, @Aprobo, GetDate(), @IdSalidaMateriales)
   END

RETURN(@IdSalidaMateriales)