
CREATE Procedure [dbo].[SalidasMaterialesSAT_A]

@IdSalidaMateriales int  output,
@NumeroSalidaMateriales int,
@FechaSalidaMateriales datetime,
@IdObra int,
@Observaciones ntext,
@Aprobo int,
@TipoSalida int,
@IdTransportista1 int,
@IdTransportista2 int,
@Cliente varchar(50),
@Direccion varchar(50),
@Localidad varchar(50),
@CodigoPostal varchar(30),
@CondicionIva varchar(30),
@Cuit varchar(13),
@NumeroSalidaMateriales2 int,
@ACargo varchar(1),
@Emitio int,
@ValePreimpreso int,
@Referencia varchar(50),
@NumeroDocumento varchar(30),
@Patente1 varchar(25),
@Patente2 varchar(25),
@Patente3 varchar(25),
@Patente4 varchar(25),
@IdProveedor int,
@Chofer varchar(50),
@IdCentroCosto int,
@FechaRegistracion datetime,
@Anulada varchar(2),
@FechaAnulacion datetime,
@IdUsuarioAnulo int,
@EnviarEmail tinyint,
@IdSalidaMaterialesOriginal int,
@IdOrigenTransmision int,
@FechaImportacionTransmision datetime,
@MotivoAnulacion ntext,
@NumeroRemitoTransporte1 int,
@NumeroRemitoTransporte2 int,
@IdChofer int,
@IdFlete int,
@PesoBruto numeric(18,2),
@PesoNeto numeric(18,2),
@Tara numeric(18,2),
@CantidadEnOrigen numeric(18,2),
@DistanciaRecorrida numeric(18,2),
@CodigoTarifador varchar(10),
@IdPesada int

AS 

INSERT INTO SalidasMaterialesSAT
(
 NumeroSalidaMateriales,
 FechaSalidaMateriales,
 IdObra,
 Observaciones,
 Aprobo,
 TipoSalida,
 IdTransportista1,
 IdTransportista2,
 Cliente,
 Direccion,
 Localidad,
 CodigoPostal,
 CondicionIva,
 Cuit,
 NumeroSalidaMateriales2,
 ACargo,
 Emitio,
 ValePreimpreso,
 Referencia,
 NumeroDocumento,
 Patente1,
 Patente2,
 Patente3,
 Patente4,
 IdProveedor,
 Chofer,
 IdCentroCosto,
 FechaRegistracion,
 Anulada,
 FechaAnulacion,
 IdUsuarioAnulo,
 EnviarEmail,
 IdSalidaMaterialesOriginal,
 IdOrigenTransmision,
 FechaImportacionTransmision,
 MotivoAnulacion,
 NumeroRemitoTransporte1,
 NumeroRemitoTransporte2,
 IdChofer,
 IdFlete,
 PesoBruto,
 PesoNeto,
 Tara,
 CantidadEnOrigen,
 DistanciaRecorrida,
 CodigoTarifador,
 IdPesada
)
Values
(
 @NumeroSalidaMateriales,
 @FechaSalidaMateriales,
 @IdObra,
 @Observaciones,
 @Aprobo,
 @TipoSalida,
 @IdTransportista1,
 @IdTransportista2,
 @Cliente,
 @Direccion,
 @Localidad,
 @CodigoPostal,
 @CondicionIva,
 @Cuit,
 @NumeroSalidaMateriales2,
 @ACargo,
 @Emitio,
 @ValePreimpreso,
 @Referencia,
 @NumeroDocumento,
 @Patente1,
 @Patente2,
 @Patente3,
 @Patente4,
 @IdProveedor,
 @Chofer,
 @IdCentroCosto,
 GetDate(),
 @Anulada,
 @FechaAnulacion,
 @IdUsuarioAnulo,
 @EnviarEmail,
 @IdSalidaMaterialesOriginal,
 @IdOrigenTransmision,
 @FechaImportacionTransmision,
 @MotivoAnulacion,
 @NumeroRemitoTransporte1,
 @NumeroRemitoTransporte2,
 @IdChofer,
 @IdFlete,
 @PesoBruto,
 @PesoNeto,
 @Tara,
 @CantidadEnOrigen,
 @DistanciaRecorrida,
 @CodigoTarifador,
 @IdPesada
)

SELECT @IdSalidaMateriales=@@identity
RETURN(@IdSalidaMateriales)
