//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Applications))]
    [KnownType(typeof(aspnet_PersonalizationAllUsers))]
    [KnownType(typeof(aspnet_PersonalizationPerUser))]
    public partial class aspnet_Paths: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ApplicationId
        {
            get { return _applicationId; }
            set
            {
                if (_applicationId != value)
                {
                    ChangeTracker.RecordOriginalValue("ApplicationId", _applicationId);
                    if (!IsDeserializing)
                    {
                        if (aspnet_Applications != null && aspnet_Applications.ApplicationId != value)
                        {
                            aspnet_Applications = null;
                        }
                    }
                    _applicationId = value;
                    OnPropertyChanged("ApplicationId");
                }
            }
        }
        private System.Guid _applicationId;
    
        [DataMember]
        public System.Guid PathId
        {
            get { return _pathId; }
            set
            {
                if (_pathId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PathId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pathId = value;
                    OnPropertyChanged("PathId");
                }
            }
        }
        private System.Guid _pathId;
    
        [DataMember]
        public string Path
        {
            get { return _path; }
            set
            {
                if (_path != value)
                {
                    _path = value;
                    OnPropertyChanged("Path");
                }
            }
        }
        private string _path;
    
        [DataMember]
        public string LoweredPath
        {
            get { return _loweredPath; }
            set
            {
                if (_loweredPath != value)
                {
                    _loweredPath = value;
                    OnPropertyChanged("LoweredPath");
                }
            }
        }
        private string _loweredPath;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public aspnet_Applications aspnet_Applications
        {
            get { return _aspnet_Applications; }
            set
            {
                if (!ReferenceEquals(_aspnet_Applications, value))
                {
                    var previousValue = _aspnet_Applications;
                    _aspnet_Applications = value;
                    Fixupaspnet_Applications(previousValue);
                    OnNavigationPropertyChanged("aspnet_Applications");
                }
            }
        }
        private aspnet_Applications _aspnet_Applications;
    
        [DataMember]
        public aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers
        {
            get { return _aspnet_PersonalizationAllUsers; }
            set
            {
                if (!ReferenceEquals(_aspnet_PersonalizationAllUsers, value))
                {
                    var previousValue = _aspnet_PersonalizationAllUsers;
                    _aspnet_PersonalizationAllUsers = value;
                    Fixupaspnet_PersonalizationAllUsers(previousValue);
                    OnNavigationPropertyChanged("aspnet_PersonalizationAllUsers");
                }
            }
        }
        private aspnet_PersonalizationAllUsers _aspnet_PersonalizationAllUsers;
    
        [DataMember]
        public TrackableCollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser
        {
            get
            {
                if (_aspnet_PersonalizationPerUser == null)
                {
                    _aspnet_PersonalizationPerUser = new TrackableCollection<aspnet_PersonalizationPerUser>();
                    _aspnet_PersonalizationPerUser.CollectionChanged += Fixupaspnet_PersonalizationPerUser;
                }
                return _aspnet_PersonalizationPerUser;
            }
            set
            {
                if (!ReferenceEquals(_aspnet_PersonalizationPerUser, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_aspnet_PersonalizationPerUser != null)
                    {
                        _aspnet_PersonalizationPerUser.CollectionChanged -= Fixupaspnet_PersonalizationPerUser;
                    }
                    _aspnet_PersonalizationPerUser = value;
                    if (_aspnet_PersonalizationPerUser != null)
                    {
                        _aspnet_PersonalizationPerUser.CollectionChanged += Fixupaspnet_PersonalizationPerUser;
                    }
                    OnNavigationPropertyChanged("aspnet_PersonalizationPerUser");
                }
            }
        }
        private TrackableCollection<aspnet_PersonalizationPerUser> _aspnet_PersonalizationPerUser;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            aspnet_Applications = null;
            aspnet_PersonalizationAllUsers = null;
            aspnet_PersonalizationPerUser.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void Fixupaspnet_Applications(aspnet_Applications previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.aspnet_Paths.Contains(this))
            {
                previousValue.aspnet_Paths.Remove(this);
            }
    
            if (aspnet_Applications != null)
            {
                if (!aspnet_Applications.aspnet_Paths.Contains(this))
                {
                    aspnet_Applications.aspnet_Paths.Add(this);
                }
    
                ApplicationId = aspnet_Applications.ApplicationId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("aspnet_Applications")
                    && (ChangeTracker.OriginalValues["aspnet_Applications"] == aspnet_Applications))
                {
                    ChangeTracker.OriginalValues.Remove("aspnet_Applications");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("aspnet_Applications", previousValue);
                }
                if (aspnet_Applications != null && !aspnet_Applications.ChangeTracker.ChangeTrackingEnabled)
                {
                    aspnet_Applications.StartTracking();
                }
            }
        }
    
        private void Fixupaspnet_PersonalizationAllUsers(aspnet_PersonalizationAllUsers previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (aspnet_PersonalizationAllUsers != null)
            {
                ChangeTracker.ObjectStateChanging += aspnet_PersonalizationAllUsers.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.aspnet_Paths, this))
            {
                previousValue.aspnet_Paths = null;
            }
    
            if (aspnet_PersonalizationAllUsers != null)
            {
                aspnet_PersonalizationAllUsers.aspnet_Paths = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("aspnet_PersonalizationAllUsers")
                    && (ChangeTracker.OriginalValues["aspnet_PersonalizationAllUsers"] == aspnet_PersonalizationAllUsers))
                {
                    ChangeTracker.OriginalValues.Remove("aspnet_PersonalizationAllUsers");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("aspnet_PersonalizationAllUsers", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (aspnet_PersonalizationAllUsers != null && !aspnet_PersonalizationAllUsers.ChangeTracker.ChangeTrackingEnabled)
                {
                    aspnet_PersonalizationAllUsers.StartTracking();
                }
            }
        }
    
        private void Fixupaspnet_PersonalizationPerUser(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (aspnet_PersonalizationPerUser item in e.NewItems)
                {
                    item.aspnet_Paths = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("aspnet_PersonalizationPerUser", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (aspnet_PersonalizationPerUser item in e.OldItems)
                {
                    if (ReferenceEquals(item.aspnet_Paths, this))
                    {
                        item.aspnet_Paths = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("aspnet_PersonalizationPerUser", item);
                    }
                }
            }
        }

        #endregion
    }
}
