//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(BancoChequera))]
    [KnownType(typeof(Cuenta))]
    public partial class Banco
    {
        public Banco()
        {
            this.BancoChequeras = new HashSet<BancoChequera>();
        }
    
        [DataMember]
        public int IdBanco { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public Nullable<int> IdCuenta { get; set; }
        [DataMember]
        public string CodigoCuenta { get; set; }
        [DataMember]
        public string NombreDatanet { get; set; }
        [DataMember]
        public string Cuit { get; set; }
        [DataMember]
        public Nullable<int> Codigo { get; set; }
        [DataMember]
        public Nullable<int> IdCodigoIva { get; set; }
        [DataMember]
        public Nullable<int> CodigoUniversal { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaParaChequesDiferidos { get; set; }
        [DataMember]
        public Nullable<int> CodigoResumen { get; set; }
        [DataMember]
        public Nullable<int> Entidad { get; set; }
        [DataMember]
        public Nullable<int> Subentidad { get; set; }
    
        [DataMember]
        public virtual ICollection<BancoChequera> BancoChequeras { get; set; }
        [DataMember]
        public virtual Cuenta Cuenta { get; set; }
        [DataMember]
        public virtual Cuenta Cuenta1 { get; set; }
    }
    
}
