//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Empleado))]
    [KnownType(typeof(Cuenta))]
    [KnownType(typeof(IBCondicion))]
    [KnownType(typeof(Vendedor))]
    [KnownType(typeof(Condiciones_Compra))]
    [KnownType(typeof(DescripcionIva))]
    [KnownType(typeof(IGCondicion))]
    [KnownType(typeof(ListasPrecio))]
    [KnownType(typeof(Localidad))]
    [KnownType(typeof(Moneda))]
    [KnownType(typeof(Pais))]
    [KnownType(typeof(Provincia))]
    [KnownType(typeof(Factura))]
    [KnownType(typeof(DetalleCliente))]
    [KnownType(typeof(DetalleClientesLugaresEntrega))]
    [KnownType(typeof(Estados_Proveedore))]
    [KnownType(typeof(CuentasCorrientesDeudor))]
    [KnownType(typeof(OrdenesCompra))]
    [KnownType(typeof(Remito))]
    [KnownType(typeof(Recibo))]
    [KnownType(typeof(NotasCredito))]
    [KnownType(typeof(NotasDebito))]
    public partial class Cliente
    {
        public Cliente()
        {
            this.Facturas = new HashSet<Factura>();
            this.DetalleClientes = new HashSet<DetalleCliente>();
            this.DetalleClientesLugaresEntregas = new HashSet<DetalleClientesLugaresEntrega>();
            this.CuentasCorrientesDeudores = new HashSet<CuentasCorrientesDeudor>();
            this.OrdenesCompras = new HashSet<OrdenesCompra>();
            this.Remitos = new HashSet<Remito>();
            this.Recibos = new HashSet<Recibo>();
            this.NotasCreditoes = new HashSet<NotasCredito>();
            this.NotasDebitoes = new HashSet<NotasDebito>();
        }
    
        [DataMember]
        public int IdCliente { get; set; }
        [DataMember]
        public string RazonSocial { get; set; }
        [DataMember]
        public string Direccion { get; set; }
        [DataMember]
        public Nullable<int> IdLocalidad { get; set; }
        [DataMember]
        public string CodigoPostal { get; set; }
        [DataMember]
        public Nullable<int> IdProvincia { get; set; }
        [DataMember]
        public Nullable<int> IdPais { get; set; }
        [DataMember]
        public string Telefono { get; set; }
        [DataMember]
        public string Fax { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Cuit { get; set; }
        [DataMember]
        public Nullable<byte> IdCodigoIva { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaAlta { get; set; }
        [DataMember]
        public string Contacto { get; set; }
        [DataMember]
        public Nullable<byte> EnviarEmail { get; set; }
        [DataMember]
        public string DireccionEntrega { get; set; }
        [DataMember]
        public Nullable<int> IdLocalidadEntrega { get; set; }
        [DataMember]
        public Nullable<int> IdProvinciaEntrega { get; set; }
        [DataMember]
        public Nullable<int> CodigoCliente { get; set; }
        [DataMember]
        public Nullable<int> IdCuenta { get; set; }
        [DataMember]
        public Nullable<decimal> Saldo { get; set; }
        [DataMember]
        public Nullable<decimal> SaldoDocumentos { get; set; }
        [DataMember]
        public Nullable<int> Vendedor1 { get; set; }
        [DataMember]
        public Nullable<decimal> CreditoMaximo { get; set; }
        [DataMember]
        public Nullable<int> IGCondicion { get; set; }
        [DataMember]
        public Nullable<int> IdCondicionVenta { get; set; }
        [DataMember]
        public Nullable<int> IdMoneda { get; set; }
        [DataMember]
        public string IBNumeroInscripcion { get; set; }
        [DataMember]
        public Nullable<int> IBCondicion { get; set; }
        [DataMember]
        public Nullable<int> TipoCliente { get; set; }
        [DataMember]
        public string Codigo { get; set; }
        [DataMember]
        public Nullable<int> IdListaPrecios { get; set; }
        [DataMember]
        public Nullable<int> IdIBCondicionPorDefecto { get; set; }
        [DataMember]
        public string Confirmado { get; set; }
        [DataMember]
        public string CodigoPresto { get; set; }
        [DataMember]
        public string Observaciones { get; set; }
        [DataMember]
        public string Importaciones_NumeroInscripcion { get; set; }
        [DataMember]
        public string Importaciones_DenominacionInscripcion { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaMonedaExt { get; set; }
        [DataMember]
        public Nullable<int> Cobrador { get; set; }
        [DataMember]
        public string Auxiliar { get; set; }
        [DataMember]
        public Nullable<int> IdIBCondicionPorDefecto2 { get; set; }
        [DataMember]
        public Nullable<int> IdIBCondicionPorDefecto3 { get; set; }
        [DataMember]
        public Nullable<int> IdEstado { get; set; }
        [DataMember]
        public string NombreFantasia { get; set; }
        [DataMember]
        public string EsAgenteRetencionIVA { get; set; }
        [DataMember]
        public Nullable<decimal> BaseMinimaParaPercepcionIVA { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajePercepcionIVA { get; set; }
        [DataMember]
        public Nullable<int> IdUsuarioIngreso { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        [DataMember]
        public Nullable<int> IdUsuarioModifico { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaModifico { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeIBDirecto { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaInicioVigenciaIBDirecto { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaFinVigenciaIBDirecto { get; set; }
        [DataMember]
        public Nullable<int> GrupoIIBB { get; set; }
        [DataMember]
        public Nullable<int> IdBancoDebito { get; set; }
        [DataMember]
        public string CBU { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeIBDirectoCapital { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaInicioVigenciaIBDirectoCapital { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaFinVigenciaIBDirectoCapital { get; set; }
        [DataMember]
        public Nullable<int> GrupoIIBBCapital { get; set; }
        [DataMember]
        public Nullable<int> IdBancoGestionador { get; set; }
        [DataMember]
        public string ExpresionRegularNoAgruparFacturasConEstosVendedores_1 { get; set; }
        [DataMember]
        public string ExigeDatosCompletosEnCartaDePorteQueLoUse_1 { get; set; }
        [DataMember]
        public string DireccionDeCorreos_1 { get; set; }
        [DataMember]
        public Nullable<int> IdLocalidadDeCorreos_1 { get; set; }
        [DataMember]
        public Nullable<int> IdProvinciaDeCorreos_1 { get; set; }
        [DataMember]
        public string CodigoPostalDeCorreos_1 { get; set; }
        [DataMember]
        public string ObservacionesDeCorreos_1 { get; set; }
        [DataMember]
        public string IncluyeTarifaEnFactura_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoTitular_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoIntermediario_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoRemcomercial_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoCorredor_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoDestinatario_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoDestinatarioExportador_1 { get; set; }
        [DataMember]
        public string SeLeDerivaSuFacturaAlCorredorDeLaCarta_1 { get; set; }
        [DataMember]
        public string HabilitadoParaCartaPorte_1 { get; set; }
        [DataMember]
        public string SeLeFacturaCartaPorteComoClienteAuxiliar_1 { get; set; }
        [DataMember]
        public string EsAcondicionadoraDeCartaPorte_1 { get; set; }
        [DataMember]
        public string Contactos_1 { get; set; }
        [DataMember]
        public string TelefonosFijosOficina_1 { get; set; }
        [DataMember]
        public string TelefonosCelulares_1 { get; set; }
        [DataMember]
        public string CorreosElectronicos_1 { get; set; }
        [DataMember]
        public Nullable<int> IdTarjetaCredito { get; set; }
        [DataMember]
        public string Tarjeta_NumeroTarjeta { get; set; }
        [DataMember]
        public string EsEntregador { get; set; }
        [DataMember]
        public Nullable<int> IdTransportista { get; set; }
        [DataMember]
        public Nullable<int> IdRegion { get; set; }
        [DataMember]
        public Nullable<int> IdCategoriaCredito { get; set; }
        [DataMember]
        public string RegistrarMovimientosEnCuentaCorriente { get; set; }
        [DataMember]
        public Nullable<decimal> ComisionDiferenciada { get; set; }
    
        [DataMember]
        public virtual Empleado Empleados { get; set; }
        [DataMember]
        public virtual Empleado Empleados1 { get; set; }
        [DataMember]
        public virtual Cuenta Cuenta { get; set; }
        [DataMember]
        public virtual IBCondicion IBCondicione { get; set; }
        [DataMember]
        public virtual Vendedor VendedorCobrador { get; set; }
        [DataMember]
        public virtual Condiciones_Compra Condiciones_Compra { get; set; }
        [DataMember]
        public virtual IBCondicion IBCondicionCat1 { get; set; }
        [DataMember]
        public virtual Cuenta CuentaMonedaExt { get; set; }
        [DataMember]
        public virtual DescripcionIva DescripcionIva { get; set; }
        [DataMember]
        public virtual IGCondicion IGCondicione { get; set; }
        [DataMember]
        public virtual ListasPrecio ListasPrecio { get; set; }
        [DataMember]
        public virtual Vendedor Vendedor { get; set; }
        [DataMember]
        public virtual Localidad LocalidadEntrega { get; set; }
        [DataMember]
        public virtual Localidad Localidad { get; set; }
        [DataMember]
        public virtual Moneda Moneda { get; set; }
        [DataMember]
        public virtual Pais Pais { get; set; }
        [DataMember]
        public virtual Pais Pais1 { get; set; }
        [DataMember]
        public virtual Provincia ProvinciaEntrega { get; set; }
        [DataMember]
        public virtual Provincia Provincia { get; set; }
        [DataMember]
        public virtual ICollection<Factura> Facturas { get; set; }
        [DataMember]
        public virtual IBCondicion IBCondicionCat2 { get; set; }
        [DataMember]
        public virtual IBCondicion IBCondicionCat3 { get; set; }
        [DataMember]
        public virtual ICollection<DetalleCliente> DetalleClientes { get; set; }
        [DataMember]
        public virtual ICollection<DetalleClientesLugaresEntrega> DetalleClientesLugaresEntregas { get; set; }
        [DataMember]
        public virtual Estados_Proveedore Estados_Proveedores { get; set; }
        [DataMember]
        public virtual ICollection<CuentasCorrientesDeudor> CuentasCorrientesDeudores { get; set; }
        [DataMember]
        public virtual ICollection<OrdenesCompra> OrdenesCompras { get; set; }
        [DataMember]
        public virtual ICollection<Remito> Remitos { get; set; }
        [DataMember]
        public virtual ICollection<Recibo> Recibos { get; set; }
        [DataMember]
        public virtual ICollection<NotasCredito> NotasCreditoes { get; set; }
        [DataMember]
        public virtual ICollection<NotasDebito> NotasDebitoes { get; set; }
    }
    
}
