//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Cuenta))]
    [KnownType(typeof(DetalleNotasCredito))]
    [KnownType(typeof(DetalleNotasDebito))]
    public partial class Concepto
    {
        public Concepto()
        {
            this.DetalleNotasCreditoes = new HashSet<DetalleNotasCredito>();
            this.DetalleNotasDebitoes = new HashSet<DetalleNotasDebito>();
        }
    
        [DataMember]
        public int IdConcepto { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public Nullable<int> IdCuenta { get; set; }
        [DataMember]
        public string ValorRechazado { get; set; }
        [DataMember]
        public Nullable<int> CodigoConcepto { get; set; }
        [DataMember]
        public string GravadoDefault { get; set; }
        [DataMember]
        public Nullable<int> Grupo { get; set; }
        [DataMember]
        public string CodigoAFIP { get; set; }
        [DataMember]
        public Nullable<decimal> CoeficienteAuxiliar_1 { get; set; }
        [DataMember]
        public string GeneraComision { get; set; }
    
        [DataMember]
        public virtual Cuenta Cuenta { get; set; }
        [DataMember]
        public virtual ICollection<DetalleNotasCredito> DetalleNotasCreditoes { get; set; }
        [DataMember]
        public virtual ICollection<DetalleNotasDebito> DetalleNotasDebitoes { get; set; }
    }
    
}
