//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Presupuesto))]
    [KnownType(typeof(Cliente))]
    public partial class Condiciones_Compra
    {
        public Condiciones_Compra()
        {
            this.Presupuestos = new HashSet<Presupuesto>();
            this.Clientes = new HashSet<Cliente>();
        }
    
        [DataMember]
        public int IdCondicionCompra { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias { get; set; }
        [DataMember]
        public string CodigoCondicion { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias1 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias2 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias3 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias4 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias5 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias6 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje1 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje2 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje3 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje4 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje5 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje6 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias7 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias8 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias9 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias10 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias11 { get; set; }
        [DataMember]
        public Nullable<int> CantidadDias12 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje7 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje8 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje9 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje10 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje11 { get; set; }
        [DataMember]
        public Nullable<decimal> Porcentaje12 { get; set; }
        [DataMember]
        public string Observaciones { get; set; }
        [DataMember]
        public string Codigo { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeBonificacion { get; set; }
        [DataMember]
        public string ContraEntregaDeValores { get; set; }
    
        [DataMember]
        public virtual ICollection<Presupuesto> Presupuestos { get; set; }
        [DataMember]
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
    
}
