//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Moneda))]
    public partial class Cotizacione
    {
        [DataMember]
        public int IdCotizacion { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Fecha { get; set; }
        [DataMember]
        public Nullable<int> IdMoneda { get; set; }
        [DataMember]
        public Nullable<decimal> Cotizacion { get; set; }
        [DataMember]
        public Nullable<decimal> CotizacionLibre { get; set; }
        [DataMember]
        public string REP_COTIZACION_INS { get; set; }
        [DataMember]
        public string REP_COTIZACION_UPD { get; set; }
    
        [DataMember]
        public virtual Moneda Moneda { get; set; }
    }
    
}
