//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Articulo))]
    [KnownType(typeof(Cliente))]
    [KnownType(typeof(Concepto))]
    [KnownType(typeof(Obra))]
    [KnownType(typeof(IBCondicion))]
    [KnownType(typeof(Rubro))]
    [KnownType(typeof(Banco))]
    [KnownType(typeof(DetalleCuenta))]
    [KnownType(typeof(Subdiario))]
    [KnownType(typeof(DetalleComprobantesProveedore))]
    [KnownType(typeof(Caja))]
    [KnownType(typeof(ComprobanteProveedor))]
    [KnownType(typeof(TiposCuentaGrupos))]
    [KnownType(typeof(CuentasGasto))]
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Articulos = new HashSet<Articulo>();
            this.Articulos1 = new HashSet<Articulo>();
            this.Articulos2 = new HashSet<Articulo>();
            this.Clientes = new HashSet<Cliente>();
            this.Conceptos = new HashSet<Concepto>();
            this.Clientes1 = new HashSet<Cliente>();
            this.IBCondiciones = new HashSet<IBCondicion>();
            this.IBCondiciones1 = new HashSet<IBCondicion>();
            this.IBCondiciones2 = new HashSet<IBCondicion>();
            this.Rubros = new HashSet<Rubro>();
            this.Bancos = new HashSet<Banco>();
            this.Bancos1 = new HashSet<Banco>();
            this.DetalleCuentas = new HashSet<DetalleCuenta>();
            this.Subdiarios = new HashSet<Subdiario>();
            this.DetalleComprobantesProveedores = new HashSet<DetalleComprobantesProveedore>();
            this.Cajas = new HashSet<Caja>();
            this.ComprobantesProveedores = new HashSet<ComprobanteProveedor>();
        }
    
        [DataMember]
        public int IdCuenta { get; set; }
        [DataMember]
        public Nullable<int> Codigo { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public Nullable<int> IdTipoCuenta { get; set; }
        [DataMember]
        public Nullable<int> NivelTotal { get; set; }
        [DataMember]
        public Nullable<int> IdRubroContable { get; set; }
        [DataMember]
        public string Jerarquia { get; set; }
        [DataMember]
        public Nullable<int> IdObra { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaGasto { get; set; }
        [DataMember]
        public string DebeHaber { get; set; }
        [DataMember]
        public Nullable<int> IdTipoCuentaGrupo { get; set; }
        [DataMember]
        public string VaAlCiti { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes01 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes02 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes03 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes04 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes05 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes06 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes07 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes08 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes09 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes10 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes11 { get; set; }
        [DataMember]
        public Nullable<decimal> PresupuestoTeoricoMes12 { get; set; }
        [DataMember]
        public Nullable<byte> EnviarEmail { get; set; }
        [DataMember]
        public Nullable<int> CodigoAgrupacionAuxiliar { get; set; }
        [DataMember]
        public Nullable<int> IdObraAgrupacionAuxiliar { get; set; }
        [DataMember]
        public Nullable<int> IdProvincia { get; set; }
        [DataMember]
        public string AjustaPorInflacion { get; set; }
        [DataMember]
        public string CodigoSecundario { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaConsolidacion { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaConsolidacion2 { get; set; }
        [DataMember]
        public Nullable<int> IdCuentaConsolidacion3 { get; set; }
        [DataMember]
        public Nullable<int> NumeroAuxiliar { get; set; }
        [DataMember]
        public Nullable<int> IdRubroFinanciero { get; set; }
        [DataMember]
        public Nullable<int> IdPresupuestoObraRubro { get; set; }
        [DataMember]
        public Nullable<int> OrdenamientoAuxiliar { get; set; }
        [DataMember]
        public string TextoAuxiliar1 { get; set; }
        [DataMember]
        public string TextoAuxiliar2 { get; set; }
        [DataMember]
        public string TextoAuxiliar3 { get; set; }
        [DataMember]
        public string ImputarAPresupuestoDeObra { get; set; }
    
        [DataMember]
        public virtual ICollection<Articulo> Articulos { get; set; }
        [DataMember]
        public virtual ICollection<Articulo> Articulos1 { get; set; }
        [DataMember]
        public virtual ICollection<Articulo> Articulos2 { get; set; }
        [DataMember]
        public virtual ICollection<Cliente> Clientes { get; set; }
        [DataMember]
        public virtual ICollection<Concepto> Conceptos { get; set; }
        [DataMember]
        public virtual Obra Obra { get; set; }
        [DataMember]
        public virtual ICollection<Cliente> Clientes1 { get; set; }
        [DataMember]
        public virtual ICollection<IBCondicion> IBCondiciones { get; set; }
        [DataMember]
        public virtual ICollection<IBCondicion> IBCondiciones1 { get; set; }
        [DataMember]
        public virtual ICollection<IBCondicion> IBCondiciones2 { get; set; }
        [DataMember]
        public virtual ICollection<Rubro> Rubros { get; set; }
        [DataMember]
        public virtual ICollection<Banco> Bancos { get; set; }
        [DataMember]
        public virtual ICollection<Banco> Bancos1 { get; set; }
        [DataMember]
        public virtual ICollection<DetalleCuenta> DetalleCuentas { get; set; }
        [DataMember]
        public virtual ICollection<Subdiario> Subdiarios { get; set; }
        [DataMember]
        public virtual ICollection<DetalleComprobantesProveedore> DetalleComprobantesProveedores { get; set; }
        [DataMember]
        public virtual ICollection<Caja> Cajas { get; set; }
        [DataMember]
        public virtual ICollection<ComprobanteProveedor> ComprobantesProveedores { get; set; }
        [DataMember]
        public virtual TiposCuentaGrupos TiposCuentaGrupos { get; set; }
        [DataMember]
        public virtual CuentasGasto CuentasGasto { get; set; }
    }
    
}
