//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Articulo))]
    [KnownType(typeof(OrdenesCompra))]
    [KnownType(typeof(Unidad))]
    public partial class DetalleOrdenesCompra
    {
        [DataMember]
        public int IdDetalleOrdenCompra { get; set; }
        [DataMember]
        public Nullable<int> IdOrdenCompra { get; set; }
        [DataMember]
        public Nullable<int> NumeroItem { get; set; }
        [DataMember]
        public Nullable<decimal> Cantidad { get; set; }
        [DataMember]
        public Nullable<int> IdUnidad { get; set; }
        [DataMember]
        public Nullable<int> IdArticulo { get; set; }
        [DataMember]
        public Nullable<decimal> Precio { get; set; }
        [DataMember]
        public string Observaciones { get; set; }
        [DataMember]
        public Nullable<int> OrigenDescripcion { get; set; }
        [DataMember]
        public Nullable<int> TipoCancelacion { get; set; }
        [DataMember]
        public string Cumplido { get; set; }
        [DataMember]
        public string FacturacionAutomatica { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaComienzoFacturacion { get; set; }
        [DataMember]
        public Nullable<int> CantidadMesesAFacturar { get; set; }
        [DataMember]
        public string FacturacionCompletaMensual { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeBonificacion { get; set; }
        [DataMember]
        public Nullable<int> IdDetalleObraDestino { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaNecesidad { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        [DataMember]
        public Nullable<int> IdColor { get; set; }
        [DataMember]
        public Nullable<int> IdDioPorCumplido { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaDadoPorCumplido { get; set; }
        [DataMember]
        public string ObservacionesCumplido { get; set; }
        [DataMember]
        public string Estado { get; set; }
        [DataMember]
        public Nullable<int> IdUsuarioCambioEstado { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaCambioEstado { get; set; }
    
        [DataMember]
        public virtual Articulo Articulo { get; set; }
        [DataMember]
        public virtual OrdenesCompra OrdenesCompra { get; set; }
        [DataMember]
        public virtual Unidad Unidade { get; set; }
    }
    
}
