//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    public partial class DetalleEmpleadosSectore
    {
        [DataMember]
        public int IdDetalleEmpleadoSector { get; set; }
        [DataMember]
        public Nullable<int> IdEmpleado { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaCambio { get; set; }
        [DataMember]
        public Nullable<int> IdSectorNuevo { get; set; }
    }
    
}
