//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    public partial class DetalleOrdenesPagoImpuesto
    {
        [DataMember]
        public int IdDetalleOrdenPagoImpuestos { get; set; }
        [DataMember]
        public Nullable<int> IdOrdenPago { get; set; }
        [DataMember]
        public string TipoImpuesto { get; set; }
        [DataMember]
        public Nullable<int> IdTipoRetencionGanancia { get; set; }
        [DataMember]
        public Nullable<decimal> ImportePagado { get; set; }
        [DataMember]
        public Nullable<decimal> ImpuestoRetenido { get; set; }
        [DataMember]
        public Nullable<int> IdIBCondicion { get; set; }
        [DataMember]
        public Nullable<int> NumeroCertificadoRetencionGanancias { get; set; }
        [DataMember]
        public Nullable<int> NumeroCertificadoRetencionIIBB { get; set; }
        [DataMember]
        public Nullable<decimal> AlicuotaAplicada { get; set; }
        [DataMember]
        public Nullable<decimal> AlicuotaConvenioAplicada { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeATomarSobreBase { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeAdicional { get; set; }
        [DataMember]
        public Nullable<decimal> ImpuestoAdicional { get; set; }
        [DataMember]
        public string LeyendaPorcentajeAdicional { get; set; }
        [DataMember]
        public Nullable<decimal> ImporteTotalFacturasMPagadasSujetasARetencion { get; set; }
        [DataMember]
        public Nullable<int> IdDetalleImpuesto { get; set; }
        [DataMember]
        public Nullable<int> IdRubroContable { get; set; }
    }
    
}
