//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Articulo))]
    [KnownType(typeof(Obra))]
    [KnownType(typeof(Unidad))]
    [KnownType(typeof(Remito))]
    [KnownType(typeof(Ubicacion))]
    public partial class DetalleRemito
    {
        [DataMember]
        public int IdDetalleRemito { get; set; }
        [DataMember]
        public Nullable<int> IdRemito { get; set; }
        [DataMember]
        public Nullable<int> NumeroItem { get; set; }
        [DataMember]
        public Nullable<decimal> Cantidad { get; set; }
        [DataMember]
        public Nullable<int> IdUnidad { get; set; }
        [DataMember]
        public Nullable<int> IdArticulo { get; set; }
        [DataMember]
        public Nullable<decimal> Precio { get; set; }
        [DataMember]
        public string Observaciones { get; set; }
        [DataMember]
        public Nullable<decimal> PorcentajeCertificacion { get; set; }
        [DataMember]
        public Nullable<int> OrigenDescripcion { get; set; }
        [DataMember]
        public Nullable<int> IdDetalleOrdenCompra { get; set; }
        [DataMember]
        public Nullable<int> TipoCancelacion { get; set; }
        [DataMember]
        public Nullable<int> IdUbicacion { get; set; }
        [DataMember]
        public Nullable<int> IdObra { get; set; }
        [DataMember]
        public string Partida { get; set; }
        [DataMember]
        public string DescargaPorKit { get; set; }
        [DataMember]
        public Nullable<int> NumeroCaja { get; set; }
        [DataMember]
        public string Talle { get; set; }
        [DataMember]
        public Nullable<int> IdColor { get; set; }
    
        [DataMember]
        public virtual Articulo Articulo { get; set; }
        [DataMember]
        public virtual Obra Obra { get; set; }
        [DataMember]
        public virtual Unidad Unidade { get; set; }
        [DataMember]
        public virtual Remito Remito { get; set; }
        [DataMember]
        public virtual Ubicacion Ubicacione { get; set; }
    }
    
}
