//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Recibo))]
    public partial class DetalleRecibo
    {
        [DataMember]
        public int IdDetalleRecibo { get; set; }
        [DataMember]
        public Nullable<int> IdRecibo { get; set; }
        [DataMember]
        public Nullable<int> IdImputacion { get; set; }
        [DataMember]
        public Nullable<decimal> Importe { get; set; }
        [DataMember]
        public Nullable<decimal> SaldoParteEnDolaresAnterior { get; set; }
        [DataMember]
        public Nullable<decimal> PagadoParteEnDolares { get; set; }
        [DataMember]
        public Nullable<decimal> NuevoSaldoParteEnDolares { get; set; }
        [DataMember]
        public Nullable<decimal> SaldoParteEnPesosAnterior { get; set; }
        [DataMember]
        public Nullable<decimal> PagadoParteEnPesos { get; set; }
        [DataMember]
        public Nullable<decimal> NuevoSaldoParteEnPesos { get; set; }
        [DataMember]
        public Nullable<byte> EnviarEmail { get; set; }
        [DataMember]
        public Nullable<int> IdOrigenTransmision { get; set; }
        [DataMember]
        public Nullable<int> IdReciboOriginal { get; set; }
        [DataMember]
        public Nullable<int> IdDetalleReciboOriginal { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaImportacionTransmision { get; set; }
    
        [DataMember]
        public virtual Recibo Recibo { get; set; }
    }
    
}
