//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Cliente))]
    [KnownType(typeof(Provincia))]
    [KnownType(typeof(Proveedor))]
    public partial class Pais
    {
        public Pais()
        {
            this.Clientes = new HashSet<Cliente>();
            this.Clientes1 = new HashSet<Cliente>();
            this.Provincias = new HashSet<Provincia>();
            this.Proveedores = new HashSet<Proveedor>();
        }
    
        [DataMember]
        public int IdPais { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public string Codigo { get; set; }
        [DataMember]
        public Nullable<byte> EnviarEmail { get; set; }
        [DataMember]
        public string Codigo2 { get; set; }
        [DataMember]
        public string Cuit { get; set; }
        [DataMember]
        public string CodigoESRI { get; set; }
    
        [DataMember]
        public virtual ICollection<Cliente> Clientes { get; set; }
        [DataMember]
        public virtual ICollection<Cliente> Clientes1 { get; set; }
        [DataMember]
        public virtual ICollection<Provincia> Provincias { get; set; }
        [DataMember]
        public virtual ICollection<Proveedor> Proveedores { get; set; }
    }
    
}
