//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Cuenta))]
    public partial class TiposCuentaGrupos
    {
        public TiposCuentaGrupos()
        {
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        [DataMember]
        public int IdTipoCuentaGrupo { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public string EsCajaBanco { get; set; }
        [DataMember]
        public string AjustarDiferenciasEnSubdiarios { get; set; }
    
        [DataMember]
        public virtual ICollection<Cuenta> Cuentas { get; set; }
    }
    
}
