//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace ProntoMVC.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Articulo))]
    [KnownType(typeof(DetalleRequerimiento))]
    [KnownType(typeof(DetallePedido))]
    [KnownType(typeof(DetallePresupuesto))]
    [KnownType(typeof(DetalleRemito))]
    [KnownType(typeof(DetalleOrdenesCompra))]
    [KnownType(typeof(DetalleFactura))]
    [KnownType(typeof(DetalleArticulosUnidade))]
    [KnownType(typeof(DetalleComparativa))]
    public partial class Unidad
    {
        public Unidad()
        {
            this.Articulos = new HashSet<Articulo>();
            this.DetalleRequerimientos = new HashSet<DetalleRequerimiento>();
            this.DetallePedidos = new HashSet<DetallePedido>();
            this.DetallePresupuestos = new HashSet<DetallePresupuesto>();
            this.DetalleRemitos = new HashSet<DetalleRemito>();
            this.DetalleOrdenesCompras = new HashSet<DetalleOrdenesCompra>();
            this.DetalleFacturas = new HashSet<DetalleFactura>();
            this.DetalleArticulosUnidades = new HashSet<DetalleArticulosUnidade>();
            this.DetalleComparativas = new HashSet<DetalleComparativa>();
        }
    
        [DataMember]
        public int IdUnidad { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public string Abreviatura { get; set; }
        [DataMember]
        public string CodigoAFIP { get; set; }
        [DataMember]
        public Nullable<int> UnidadesPorPack { get; set; }
        [DataMember]
        public Nullable<decimal> TaraEnKg { get; set; }
    
        [DataMember]
        public virtual ICollection<Articulo> Articulos { get; set; }
        [DataMember]
        public virtual ICollection<DetalleRequerimiento> DetalleRequerimientos { get; set; }
        [DataMember]
        public virtual ICollection<DetallePedido> DetallePedidos { get; set; }
        [DataMember]
        public virtual ICollection<DetallePresupuesto> DetallePresupuestos { get; set; }
        [DataMember]
        public virtual ICollection<DetalleRemito> DetalleRemitos { get; set; }
        [DataMember]
        public virtual ICollection<DetalleOrdenesCompra> DetalleOrdenesCompras { get; set; }
        [DataMember]
        public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }
        [DataMember]
        public virtual ICollection<DetalleArticulosUnidade> DetalleArticulosUnidades { get; set; }
        [DataMember]
        public virtual ICollection<DetalleComparativa> DetalleComparativas { get; set; }
    }
    
}
