--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
--correccion del Clientes_M y Clientes_A


 alter Procedure [dbo].[Clientes_A]  
  
@IdCliente int output,  
@RazonSocial varchar(100),  
@Direccion varchar(100),  
@IdLocalidad int,  
@CodigoPostal varchar(30),  
@IdProvincia int,  
@IdPais int,  
@Telefono varchar(50),  
@Fax varchar(50),  
@Email varchar(200),  
@Cuit varchar(13),  
@IdCodigoIva tinyint,  
@FechaAlta datetime,  
@Contacto varchar(50),  
@EnviarEmail tinyint,  
@DireccionEntrega varchar(50),  
@IdLocalidadEntrega int,  
@IdProvinciaEntrega int,  
@CodigoCliente int,  
@IdCuenta int,  
@Saldo numeric(18,2),  
@SaldoDocumentos numeric(18,2),  
@Vendedor1 int,  
@CreditoMaximo numeric(18,2),  
@IGCondicion int,  
@IdCondicionVenta int,  
@IdMoneda int,  
@IBNumeroInscripcion varchar(20),  
@IBCondicion int,  
@TipoCliente int,  
@Codigo varchar(10),  
@IdListaPrecios int,  
@IdIBCondicionPorDefecto int,  
@Confirmado varchar(2),  
@CodigoPresto varchar(13),  
@Observaciones ntext,  
@Importaciones_NumeroInscripcion varchar(20),  
@Importaciones_DenominacionInscripcion varchar(10),  
@IdCuentaMonedaExt int,  
@Cobrador int,  
@Auxiliar varchar(50),  
@IdIBCondicionPorDefecto2 int,  
@IdIBCondicionPorDefecto3 int,  
@IdEstado int,  
@NombreFantasia varchar(50),  
@EsAgenteRetencionIVA varchar(2),  
@BaseMinimaParaPercepcionIVA numeric(18,2),  
@PorcentajePercepcionIVA numeric(6,2),  
@IdUsuarioIngreso int,  
@FechaIngreso datetime,  
@IdUsuarioModifico int,  
@FechaModifico datetime,  
@PorcentajeIBDirecto numeric(6,2),  
@FechaInicioVigenciaIBDirecto datetime,  
@FechaFinVigenciaIBDirecto datetime,  
@GrupoIIBB int,  
@IdBancoDebito int,  
@CBU varchar(22),  
@PorcentajeIBDirectoCapital numeric(6,2),  
@FechaInicioVigenciaIBDirectoCapital datetime,  
@FechaFinVigenciaIBDirectoCapital datetime,  
@GrupoIIBBCapital int,  
@IdBancoGestionador int,  
@ExpresionRegularNoAgruparFacturasConEstosVendedores varchar(200),  
@ExigeDatosCompletosEnCartaDePorteQueLoUse varchar(2),  
@DireccionDeCorreos varchar(50),  
@IdLocalidadDeCorreos int,  
@IdProvinciaDeCorreos int,  
@CodigoPostalDeCorreos varchar(30),  
@ObservacionesDeCorreos varchar(150),  
@IdTarjetaCredito int,  
@Tarjeta_NumeroTarjeta varchar(16)    ,

@IncluyeTarifaEnFactura	varchar	(2),
@SeLeFacturaCartaPorteComoTitular	varchar	(2),
@SeLeFacturaCartaPorteComoIntermediario	varchar	(2),
@SeLeFacturaCartaPorteComoRemcomercial	varchar	(2),
@SeLeFacturaCartaPorteComoCorredor	varchar	(2),
@SeLeFacturaCartaPorteComoDestinatario	varchar	(2),
@SeLeFacturaCartaPorteComoDestinatarioExportador	varchar	(2),
@SeLeDerivaSuFacturaAlCorredorDeLaCarta	varchar	(2),
@HabilitadoParaCartaPorte	varchar	(2),
@SeLeFacturaCartaPorteComoClienteAuxiliar	varchar	(2),
@EsAcondicionadoraDeCartaPorte	varchar	(2),
@Contactos	varchar	(150),
@TelefonosFijosOficina	varchar	(150),
@TelefonosCelulares	varchar	(150),
@CorreosElectronicos	varchar	(150)  
AS   
  
INSERT INTO Clientes  
(  
 RazonSocial,  
 Direccion,  
 IdLocalidad,  
 CodigoPostal,  
 IdProvincia,  
 IdPais,  
 Telefono,  
 Fax,  
 Email,  
 Cuit,  
 IdCodigoIva,  
 FechaAlta,  
 Contacto,  
 EnviarEmail,  
 DireccionEntrega,  
 IdLocalidadEntrega,  
 IdProvinciaEntrega,  
 CodigoCliente,  
 IdCuenta,  
 Saldo,  
 SaldoDocumentos,  
 Vendedor1,  
 CreditoMaximo,  
 IGCondicion,  
 IdCondicionVenta,  
 IdMoneda,  
 IBNumeroInscripcion,  
 IBCondicion,  
 TipoCliente,  
 Codigo,  
 IdListaPrecios,  
 IdIBCondicionPorDefecto,  
 Confirmado,  
 CodigoPresto,  
 Observaciones,  
 Importaciones_NumeroInscripcion,  
 Importaciones_DenominacionInscripcion,  
 IdCuentaMonedaExt,  
 Cobrador,  
 Auxiliar,  
 IdIBCondicionPorDefecto2,  
 IdIBCondicionPorDefecto3,  
 IdEstado,  
 NombreFantasia,  
 EsAgenteRetencionIVA,  
 BaseMinimaParaPercepcionIVA,  
 PorcentajePercepcionIVA,  
 IdUsuarioIngreso,  
 FechaIngreso,   
 IdUsuarioModifico,  
 FechaModifico,  
 PorcentajeIBDirecto,  
 FechaInicioVigenciaIBDirecto,  
 FechaFinVigenciaIBDirecto,  
 GrupoIIBB,  
 IdBancoDebito,  
 CBU,  
 PorcentajeIBDirectoCapital,  
 FechaInicioVigenciaIBDirectoCapital,  
 FechaFinVigenciaIBDirectoCapital,  
 GrupoIIBBCapital,  
 IdBancoGestionador,  
 ExpresionRegularNoAgruparFacturasConEstosVendedores,  
 ExigeDatosCompletosEnCartaDePorteQueLoUse,  
 DireccionDeCorreos,  
 IdLocalidadDeCorreos,  
 IdProvinciaDeCorreos,  
 CodigoPostalDeCorreos,  
 ObservacionesDeCorreos,  
 IdTarjetaCredito,  
 Tarjeta_NumeroTarjeta  ,

  IncluyeTarifaEnFactura,
SeLeFacturaCartaPorteComoTitular,
SeLeFacturaCartaPorteComoIntermediario	,
SeLeFacturaCartaPorteComoRemcomercial	,
SeLeFacturaCartaPorteComoCorredor	,
SeLeFacturaCartaPorteComoDestinatario	,
SeLeFacturaCartaPorteComoDestinatarioExportador	,
SeLeDerivaSuFacturaAlCorredorDeLaCarta	,
HabilitadoParaCartaPorte	,
SeLeFacturaCartaPorteComoClienteAuxiliar	,
EsAcondicionadoraDeCartaPorte,
Contactos	,
TelefonosFijosOficina	,
TelefonosCelulares	,
CorreosElectronicos
)  
 VALUES   
(  
 @RazonSocial,  
 @Direccion,  
 @IdLocalidad,  
 @CodigoPostal,  
 @IdProvincia,  
 @IdPais,  
 @Telefono,  
 @Fax,  
 @Email,  
 @Cuit,  
 @IdCodigoIva,  
 @FechaAlta,  
 @Contacto,  
 @EnviarEmail,  
 @DireccionEntrega,  
 @IdLocalidadEntrega,  
 @IdProvinciaEntrega,  
 @CodigoCliente,  
 @IdCuenta,  
 @Saldo,  
 @SaldoDocumentos,  
 @Vendedor1,  
 @CreditoMaximo,  
 @IGCondicion,  
 @IdCondicionVenta,  
 @IdMoneda,  
 @IBNumeroInscripcion,  
 @IBCondicion,  
 @TipoCliente,  
 @Codigo,  
 @IdListaPrecios,  
 @IdIBCondicionPorDefecto,  
 @Confirmado,  
 @CodigoPresto,  
 @Observaciones,  
 @Importaciones_NumeroInscripcion,  
 @Importaciones_DenominacionInscripcion,  
 @IdCuentaMonedaExt,  
 @Cobrador,  
 @Auxiliar,  
 @IdIBCondicionPorDefecto2,  
 @IdIBCondicionPorDefecto3,  
 @IdEstado,  
 @NombreFantasia,  
 @EsAgenteRetencionIVA,  
 @BaseMinimaParaPercepcionIVA,  
 @PorcentajePercepcionIVA,  
 @IdUsuarioIngreso,  
 @FechaIngreso,  
 @IdUsuarioModifico,  
 @FechaModifico,  
 @PorcentajeIBDirecto,  
 @FechaInicioVigenciaIBDirecto,  
 @FechaFinVigenciaIBDirecto,  
 @GrupoIIBB,  
 @IdBancoDebito,  
 @CBU,  
 @PorcentajeIBDirectoCapital,  
 @FechaInicioVigenciaIBDirectoCapital,  
 @FechaFinVigenciaIBDirectoCapital,  
 @GrupoIIBBCapital,  
 @IdBancoGestionador,  
 @ExpresionRegularNoAgruparFacturasConEstosVendedores,  
 @ExigeDatosCompletosEnCartaDePorteQueLoUse,  
 @DireccionDeCorreos,  
 @IdLocalidadDeCorreos,  
 @IdProvinciaDeCorreos,  
 @CodigoPostalDeCorreos,  
 @ObservacionesDeCorreos,  
 @IdTarjetaCredito,  
 @Tarjeta_NumeroTarjeta  ,

 @IncluyeTarifaEnFactura,
@SeLeFacturaCartaPorteComoTitular,
@SeLeFacturaCartaPorteComoIntermediario	,
@SeLeFacturaCartaPorteComoRemcomercial	,
@SeLeFacturaCartaPorteComoCorredor	,
@SeLeFacturaCartaPorteComoDestinatario	,
@SeLeFacturaCartaPorteComoDestinatarioExportador	,
@SeLeDerivaSuFacturaAlCorredorDeLaCarta	,
@HabilitadoParaCartaPorte	,
@SeLeFacturaCartaPorteComoClienteAuxiliar	,
@EsAcondicionadoraDeCartaPorte,
@Contactos	,
@TelefonosFijosOficina	,
@TelefonosCelulares	,
@CorreosElectronicos	

)  
  
SELECT @IdCliente=@@identity  
  
RETURN(@IdCliente)  
go

------------------------------------------------------

drop procedure [Clientes_M]
go

 CREATE  Procedure [dbo].[Clientes_M]  
  
@IdCliente int,  
@RazonSocial varchar(100),  
@Direccion varchar(100),  
@IdLocalidad int,  
@CodigoPostal varchar(30),  
@IdProvincia int,  
@IdPais int,  
@Telefono varchar(50),  
@Fax varchar(50),  
@Email varchar(200),  
@Cuit varchar(13),  
@IdCodigoIva tinyint,  
@FechaAlta datetime,  
@Contacto varchar(50),  
@EnviarEmail tinyint,  
@DireccionEntrega varchar(50),  
@IdLocalidadEntrega int,  
@IdProvinciaEntrega int,  
@CodigoCliente int,  
@IdCuenta int,  
@Saldo numeric(18,2),  
@SaldoDocumentos numeric(18,2),  
@Vendedor1 int,  
@CreditoMaximo numeric(18,2),  
@IGCondicion int,  
@IdCondicionVenta int,  
@IdMoneda int,  
@IBNumeroInscripcion varchar(20),  
@IBCondicion int,  
@TipoCliente int,  
@Codigo varchar(10),  
@IdListaPrecios int,  
@IdIBCondicionPorDefecto int,  
@Confirmado varchar(2),  
@CodigoPresto varchar(13),  
@Observaciones ntext,  
@Importaciones_NumeroInscripcion varchar(20),  
@Importaciones_DenominacionInscripcion varchar(10),  
@IdCuentaMonedaExt int,  
@Cobrador int,  
@Auxiliar varchar(50),  
@IdIBCondicionPorDefecto2 int,  
@IdIBCondicionPorDefecto3 int,  
@IdEstado int,  
@NombreFantasia varchar(50),  
@EsAgenteRetencionIVA varchar(2),  
@BaseMinimaParaPercepcionIVA numeric(18,2),  
@PorcentajePercepcionIVA numeric(6,2),  
@IdUsuarioIngreso int,  
@FechaIngreso datetime,  
@IdUsuarioModifico int,  
@FechaModifico datetime,  
@PorcentajeIBDirecto numeric(6,2),  
@FechaInicioVigenciaIBDirecto datetime,  
@FechaFinVigenciaIBDirecto datetime,  
@GrupoIIBB int,  
@IdBancoDebito int,  
@CBU varchar(22),  
@PorcentajeIBDirectoCapital numeric(6,2),  
@FechaInicioVigenciaIBDirectoCapital datetime,  
@FechaFinVigenciaIBDirectoCapital datetime,  
@GrupoIIBBCapital int,  
@IdBancoGestionador int,  
@ExpresionRegularNoAgruparFacturasConEstosVendedores varchar(200),  
@ExigeDatosCompletosEnCartaDePorteQueLoUse varchar(2),  
@DireccionDeCorreos varchar(50),  
@IdLocalidadDeCorreos int,  
@IdProvinciaDeCorreos int,  
@CodigoPostalDeCorreos varchar(30),  
@ObservacionesDeCorreos varchar(150),  
@IdTarjetaCredito int,  
@Tarjeta_NumeroTarjeta varchar(16), 


@IncluyeTarifaEnFactura	varchar	(2),
@SeLeFacturaCartaPorteComoTitular	varchar	(2),
@SeLeFacturaCartaPorteComoIntermediario	varchar	(2),
@SeLeFacturaCartaPorteComoRemcomercial	varchar	(2),
@SeLeFacturaCartaPorteComoCorredor	varchar	(2),
@SeLeFacturaCartaPorteComoDestinatario	varchar	(2),
@SeLeFacturaCartaPorteComoDestinatarioExportador	varchar	(2),
@SeLeDerivaSuFacturaAlCorredorDeLaCarta	varchar	(2),
@HabilitadoParaCartaPorte	varchar	(2),
@SeLeFacturaCartaPorteComoClienteAuxiliar	varchar	(2),
@EsAcondicionadoraDeCartaPorte	varchar	(2),
@Contactos	varchar	(150),
@TelefonosFijosOficina	varchar	(150),
@TelefonosCelulares	varchar	(150),
@CorreosElectronicos	varchar	(150)
  
AS   
  
UPDATE Clientes  
SET  
 RazonSocial = @RazonSocial,  
 Direccion = @Direccion,  
 IdLocalidad = @IdLocalidad,  
 CodigoPostal = @CodigoPostal,  
 IdProvincia = @IdProvincia,  
 IdPais = @IdPais,  
 Telefono = @Telefono,  
 Fax = @Fax,  
 Email = @Email,  
 Cuit = @Cuit,  
 IdCodigoIva = @IdCodigoIva,  
 FechaAlta = @FechaAlta,  
 Contacto = @Contacto,  
 EnviarEmail = @EnviarEmail,  
 DireccionEntrega = @DireccionEntrega,  
 IdLocalidadEntrega = @IdLocalidadEntrega,  
 IdProvinciaEntrega = @IdProvinciaEntrega,  
 CodigoCliente = @CodigoCliente,  
 IdCuenta = @IdCuenta,  
 Saldo = @Saldo,  
 SaldoDocumentos = @SaldoDocumentos,  
 Vendedor1 = @Vendedor1,  
 CreditoMaximo = @CreditoMaximo,  
 IGCondicion = @IGCondicion,  
 IdCondicionVenta = @IdCondicionVenta,  
 IdMoneda = @IdMoneda,  
 IBNumeroInscripcion = @IBNumeroInscripcion,  
 IBCondicion = @IBCondicion,  
 TipoCliente = @TipoCliente,  
 Codigo  = @Codigo,  
 IdListaPrecios = @IdListaPrecios,  
 IdIBCondicionPorDefecto = @IdIBCondicionPorDefecto,  
 Confirmado = @Confirmado,  
 CodigoPresto = @CodigoPresto,  
 Observaciones = @Observaciones,  
 Importaciones_NumeroInscripcion=@Importaciones_NumeroInscripcion,  
 Importaciones_DenominacionInscripcion=@Importaciones_DenominacionInscripcion,  
 IdCuentaMonedaExt = @IdCuentaMonedaExt,  
 Cobrador = @Cobrador,  
 Auxiliar = @Auxiliar,  
 IdIBCondicionPorDefecto2 = @IdIBCondicionPorDefecto2,  
 IdIBCondicionPorDefecto3 = @IdIBCondicionPorDefecto3,  
 IdEstado = @IdEstado,  
 NombreFantasia = @NombreFantasia,  
 EsAgenteRetencionIVA = @EsAgenteRetencionIVA,  
 BaseMinimaParaPercepcionIVA = @BaseMinimaParaPercepcionIVA,  
 PorcentajePercepcionIVA = @PorcentajePercepcionIVA,  
 IdUsuarioIngreso = @IdUsuarioIngreso,  
 FechaIngreso = @FechaIngreso,  
 IdUsuarioModifico = @IdUsuarioModifico,  
 FechaModifico = @FechaModifico,  
 PorcentajeIBDirecto = @PorcentajeIBDirecto,  
 FechaInicioVigenciaIBDirecto = @FechaInicioVigenciaIBDirecto,  
 FechaFinVigenciaIBDirecto=@FechaFinVigenciaIBDirecto,  
 GrupoIIBB = @GrupoIIBB,  
 IdBancoDebito=@IdBancoDebito,  
 CBU=@CBU,  
 PorcentajeIBDirectoCapital=@PorcentajeIBDirectoCapital,  
 FechaInicioVigenciaIBDirectoCapital=@FechaInicioVigenciaIBDirectoCapital,  
 FechaFinVigenciaIBDirectoCapital=@FechaFinVigenciaIBDirectoCapital,  
 GrupoIIBBCapital=@GrupoIIBBCapital,  
 IdBancoGestionador=@IdBancoGestionador,  
 ExpresionRegularNoAgruparFacturasConEstosVendedores=@ExpresionRegularNoAgruparFacturasConEstosVendedores,  
 ExigeDatosCompletosEnCartaDePorteQueLoUse=@ExigeDatosCompletosEnCartaDePorteQueLoUse,  
 DireccionDeCorreos=@DireccionDeCorreos,  
 IdLocalidadDeCorreos=@IdLocalidadDeCorreos,  
 IdProvinciaDeCorreos=@IdProvinciaDeCorreos,  
 CodigoPostalDeCorreos=@CodigoPostalDeCorreos,  
 ObservacionesDeCorreos=@ObservacionesDeCorreos,  


 IdTarjetaCredito=@IdTarjetaCredito,  
 Tarjeta_NumeroTarjeta=@Tarjeta_NumeroTarjeta  ,


IncluyeTarifaEnFactura = @IncluyeTarifaEnFactura,
SeLeFacturaCartaPorteComoTitular=@SeLeFacturaCartaPorteComoTitular,
SeLeFacturaCartaPorteComoIntermediario=@SeLeFacturaCartaPorteComoIntermediario	,
SeLeFacturaCartaPorteComoRemcomercial=@SeLeFacturaCartaPorteComoRemcomercial	,
SeLeFacturaCartaPorteComoCorredor=@SeLeFacturaCartaPorteComoCorredor	,
SeLeFacturaCartaPorteComoDestinatario=@SeLeFacturaCartaPorteComoDestinatario	,
SeLeFacturaCartaPorteComoDestinatarioExportador=@SeLeFacturaCartaPorteComoDestinatarioExportador	,
SeLeDerivaSuFacturaAlCorredorDeLaCarta=@SeLeDerivaSuFacturaAlCorredorDeLaCarta	,
HabilitadoParaCartaPorte=@HabilitadoParaCartaPorte	,
SeLeFacturaCartaPorteComoClienteAuxiliar=@SeLeFacturaCartaPorteComoClienteAuxiliar	,
EsAcondicionadoraDeCartaPorte=@EsAcondicionadoraDeCartaPorte,
Contactos=@Contactos	,
TelefonosFijosOficina=@TelefonosFijosOficina	,
TelefonosCelulares=@TelefonosCelulares	,
CorreosElectronicos=@CorreosElectronicos

WHERE [IdCliente]=@IdCliente  
  
RETURN(@IdCliente)  







go



sp_help 'clientes'
