CREATE  Procedure [dbo].[Cuentas_M]

@IdCuenta int ,
@Codigo int,
@Descripcion varchar(50),
@IdTipoCuenta int,
@NivelTotal int,
@IdRubroContable int,
@Jerarquia varchar(20),
@IdObra int,
@IdCuentaGasto int,
@DebeHaber varchar(1),
@IdTipoCuentaGrupo int,
@VaAlCiti varchar(2),
@PresupuestoTeoricoMes01 numeric(18,2),
@PresupuestoTeoricoMes02 numeric(18,2),
@PresupuestoTeoricoMes03 numeric(18,2),
@PresupuestoTeoricoMes04 numeric(18,2),
@PresupuestoTeoricoMes05 numeric(18,2),
@PresupuestoTeoricoMes06 numeric(18,2),
@PresupuestoTeoricoMes07 numeric(18,2),
@PresupuestoTeoricoMes08 numeric(18,2),
@PresupuestoTeoricoMes09 numeric(18,2),
@PresupuestoTeoricoMes10 numeric(18,2),
@PresupuestoTeoricoMes11 numeric(18,2),
@PresupuestoTeoricoMes12 numeric(18,2),
@EnviarEmail tinyint,
@CodigoAgrupacionAuxiliar int,
@IdObraAgrupacionAuxiliar int,
@IdProvincia int,
@AjustaPorInflacion varchar(2),
@CodigoSecundario varchar(30),
@IdCuentaConsolidacion int,
@IdCuentaConsolidacion2 int,
@IdCuentaConsolidacion3 int,
@NumeroAuxiliar int,
@IdRubroFinanciero int,
@IdPresupuestoObraRubro int,
@OrdenamientoAuxiliar int,
@TextoAuxiliar1 varchar(100),
@TextoAuxiliar2 varchar(100),
@TextoAuxiliar3 varchar(100),
@ImputarAPresupuestoDeObra varchar(2)

AS 

UPDATE Cuentas
SET 
 Codigo=@Codigo,
 Descripcion=@Descripcion,
 IdTipoCuenta=@IdTipoCuenta,
 NivelTotal=@NivelTotal,
 IdRubroContable=@IdRubroContable,
 Jerarquia=@Jerarquia,
 IdObra=@IdObra,
 IdCuentaGasto=@IdCuentaGasto,
 DebeHaber=@DebeHaber,
 IdTipoCuentaGrupo=@IdTipoCuentaGrupo,
 VaAlCiti=@VaAlCiti,
 PresupuestoTeoricoMes01=@PresupuestoTeoricoMes01,
 PresupuestoTeoricoMes02=@PresupuestoTeoricoMes02,
 PresupuestoTeoricoMes03=@PresupuestoTeoricoMes03,
 PresupuestoTeoricoMes04=@PresupuestoTeoricoMes04,
 PresupuestoTeoricoMes05=@PresupuestoTeoricoMes05,
 PresupuestoTeoricoMes06=@PresupuestoTeoricoMes06,
 PresupuestoTeoricoMes07=@PresupuestoTeoricoMes07,
 PresupuestoTeoricoMes08=@PresupuestoTeoricoMes08,
 PresupuestoTeoricoMes09=@PresupuestoTeoricoMes09,
 PresupuestoTeoricoMes10=@PresupuestoTeoricoMes10,
 PresupuestoTeoricoMes11=@PresupuestoTeoricoMes11,
 PresupuestoTeoricoMes12=@PresupuestoTeoricoMes12,
 EnviarEmail=@EnviarEmail,
 CodigoAgrupacionAuxiliar=@CodigoAgrupacionAuxiliar,
 IdObraAgrupacionAuxiliar=@IdObraAgrupacionAuxiliar,
 IdProvincia=@IdProvincia,
 AjustaPorInflacion=@AjustaPorInflacion,
 CodigoSecundario=@CodigoSecundario,
 IdCuentaConsolidacion=@IdCuentaConsolidacion,
 IdCuentaConsolidacion2=@IdCuentaConsolidacion2,
 IdCuentaConsolidacion3=@IdCuentaConsolidacion3,
 NumeroAuxiliar=@NumeroAuxiliar,
 IdRubroFinanciero=@IdRubroFinanciero,
 IdPresupuestoObraRubro=@IdPresupuestoObraRubro,
 OrdenamientoAuxiliar=@OrdenamientoAuxiliar,
 TextoAuxiliar1=@TextoAuxiliar1,
 TextoAuxiliar2=@TextoAuxiliar2,
 TextoAuxiliar3=@TextoAuxiliar3,
 ImputarAPresupuestoDeObra=@ImputarAPresupuestoDeObra
WHERE (IdCuenta=@IdCuenta)

RETURN(@IdCuenta)