CREATE Procedure [dbo].[DetFacturas_A]

@IdDetalleFactura int  output,
@IdFactura int,
@NumeroFactura int,
@TipoABC varchar(1),
@PuntoVenta int,
@IdArticulo int,
@CodigoArticulo varchar(20),
@Cantidad numeric(18,3),
@Costo numeric(19,8),
@PrecioUnitario numeric(19,8),
@Bonificacion numeric(12,2),
@IdDetalleRemito int,
@ParteDolar numeric(9,2),
@PartePesos numeric(9,2),
@PorcentajeCertificacion numeric(18,10),
@OrigenDescripcion int,
@TipoCancelacion int,
@IdUnidad int,
@PrecioUnitarioTotal numeric(18,2),
@Observaciones ntext,
@NotaAclaracion varchar(50),
@EnviarEmail int,
@IdOrigenTransmision int,
@IdFacturaOriginal int,
@IdDetalleFacturaOriginal int,
@FechaImportacionTransmision datetime,
@Talle varchar(2),
@IdColor int,
@IdDetallePresupuestoVenta int,
@OrigenRegistro varchar(12)

AS

INSERT INTO [DetalleFacturas]
(
 IdFactura,
 NumeroFactura,
 TipoABC,
 PuntoVenta,
 IdArticulo,
 CodigoArticulo,
 Cantidad,
 Costo,
 PrecioUnitario,
 Bonificacion,
 IdDetalleRemito,
 ParteDolar,
 PartePesos,
 PorcentajeCertificacion,
 OrigenDescripcion,
 TipoCancelacion,
 IdUnidad,
 PrecioUnitarioTotal,
 Observaciones,
 NotaAclaracion,
 EnviarEmail,
 IdOrigenTransmision,
 IdFacturaOriginal,
 IdDetalleFacturaOriginal,
 FechaImportacionTransmision,
 Talle,
 IdColor,
 IdDetallePresupuestoVenta,
 OrigenRegistro
)
VALUES
(
 @IdFactura,
 @NumeroFactura,
 @TipoABC,
 @PuntoVenta,
 @IdArticulo,
 @CodigoArticulo,
 @Cantidad,
 @Costo,
 @PrecioUnitario,
 @Bonificacion,
 @IdDetalleRemito,
 @ParteDolar,
 @PartePesos,
 @PorcentajeCertificacion,
 @OrigenDescripcion,
 @TipoCancelacion,
 @IdUnidad,
 @PrecioUnitarioTotal,
 @Observaciones,
 @NotaAclaracion,
 @EnviarEmail,
 @IdOrigenTransmision,
 @IdFacturaOriginal,
 @IdDetalleFacturaOriginal,
 @FechaImportacionTransmision,
 @Talle,
 @IdColor,
 @IdDetallePresupuestoVenta,
 @OrigenRegistro
)
SELECT @IdDetalleFactura=@@identity

RETURN(@IdDetalleFactura)