CREATE Procedure [dbo].[DetFacturas_M]

@IdDetalleFactura int,
@IdFactura int,
@NumeroFactura int,
@TipoABC varchar(1),
@PuntoVenta int,
@IdArticulo int,
@CodigoArticulo varchar(20),
@Cantidad numeric(18,3),
@Costo numeric(19,8),
@PrecioUnitario numeric(19,8),
@Bonificacion numeric(12,2),
@IdDetalleRemito int,
@ParteDolar numeric(9,2),
@PartePesos numeric(9,2),
@PorcentajeCertificacion numeric(18,10),
@OrigenDescripcion int,
@TipoCancelacion int,
@IdUnidad int,
@PrecioUnitarioTotal numeric(18,2),
@Observaciones ntext,
@NotaAclaracion varchar(50),
@EnviarEmail int,
@IdOrigenTransmision int,
@IdFacturaOriginal int,
@IdDetalleFacturaOriginal int,
@FechaImportacionTransmision datetime,
@Talle varchar(2),
@IdColor int,
@IdDetallePresupuestoVenta int,
@OrigenRegistro varchar(12)

AS

UPDATE DetalleFacturas
SET
 IdFactura=@IdFactura,
 NumeroFactura=@NumeroFactura,
 TipoABC=@TipoABC,
 PuntoVenta=@PuntoVenta,
 IdArticulo=@IdArticulo,
 CodigoArticulo=@CodigoArticulo,
 Cantidad=@Cantidad,
 Costo=@Costo,
 PrecioUnitario=@PrecioUnitario,
 Bonificacion=@Bonificacion,
 IdDetalleRemito=@IdDetalleRemito,
 ParteDolar=@ParteDolar,
 PartePesos=@PartePesos,
 PorcentajeCertificacion=@PorcentajeCertificacion,
 OrigenDescripcion=@OrigenDescripcion,
 TipoCancelacion=@TipoCancelacion,
 IdUnidad=@IdUnidad,
 PrecioUnitarioTotal=@PrecioUnitarioTotal,
 Observaciones=@Observaciones,
 NotaAclaracion=@NotaAclaracion,
 EnviarEmail=@EnviarEmail,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdFacturaOriginal=@IdFacturaOriginal,
 IdDetalleFacturaOriginal=@IdDetalleFacturaOriginal,
 FechaImportacionTransmision=@FechaImportacionTransmision,
 Talle=@Talle,
 IdColor=@IdColor,
 IdDetallePresupuestoVenta=@IdDetallePresupuestoVenta,
 OrigenRegistro=@OrigenRegistro
WHERE (IdDetalleFactura=@IdDetalleFactura)

RETURN(@IdDetalleFactura)