
CREATE Procedure [dbo].[DetLMateriales_M]

@IdDetalleLMateriales int,
@IdLMateriales int,
@NumeroItem int,
@NumeroOrden int,
@Revision varchar(10),
@Cantidad numeric(12,2),
@IdUnidad int,
@IdArticulo int,
@Peso numeric(12,2),
@IdUnidadPeso int,
@IdControlCalidad int,
@Cantidad1 numeric(12,2),
@Cantidad2 numeric(12,2),
@Detalle varchar(50),
@IdPlano int,
@IdDetalleAcopios int,
@Adjunto varchar(2),
@ArchivoAdjunto varchar(50),
@Observaciones ntext,
@Despacha varchar(2),
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@DescripcionManual varchar(250),
@EnviarEmail tinyint,
@IdLMaterialesOriginal int,
@IdDetalleLMaterialesOriginal int,
@IdOrigenTransmision int,
@IdDetalleObraDestino int

AS

UPDATE [DetalleLMateriales]
SET 
 IdLMateriales=@IdLMateriales,
 NumeroItem=@NumeroItem,
 NumeroOrden=@NumeroOrden,
 Revision=@Revision,
 Cantidad=@Cantidad,
 IdUnidad=@IdUnidad,
 IdArticulo=@IdArticulo,
 Peso=@Peso,
 IdUnidadPeso=@IdUnidadPeso,
 IdControlCalidad=@IdControlCalidad,
 Cantidad1=@Cantidad1,
 Cantidad2=@Cantidad2,
 Detalle=@Detalle,
 IdPlano=@IdPlano,
 IdDetalleAcopios=@IdDetalleAcopios,
 Adjunto=@Adjunto,
 ArchivoAdjunto=@ArchivoAdjunto,
 Observaciones=@Observaciones,
 Despacha=@Despacha,
 ArchivoAdjunto1=@ArchivoAdjunto1,
 ArchivoAdjunto2=@ArchivoAdjunto2,
 ArchivoAdjunto3=@ArchivoAdjunto3,
 ArchivoAdjunto4=@ArchivoAdjunto4,
 ArchivoAdjunto5=@ArchivoAdjunto5,
 ArchivoAdjunto6=@ArchivoAdjunto6,
 ArchivoAdjunto7=@ArchivoAdjunto7,
 ArchivoAdjunto8=@ArchivoAdjunto8,
 ArchivoAdjunto9=@ArchivoAdjunto9,
 ArchivoAdjunto10=@ArchivoAdjunto10,
 DescripcionManual=@DescripcionManual,
 EnviarEmail=@EnviarEmail,
 IdLMaterialesOriginal=@IdLMaterialesOriginal,
 IdDetalleLMaterialesOriginal=@IdDetalleLMaterialesOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdDetalleObraDestino=@IdDetalleObraDestino
WHERE (IdDetalleLMateriales=@IdDetalleLMateriales)

RETURN(@IdDetalleLMateriales)
