
CREATE Procedure [dbo].[DetLMateriales_A]

@IdDetalleLMateriales int  output,
@IdLMateriales int,
@NumeroItem int,
@NumeroOrden int,
@Revision varchar(10),
@Cantidad numeric(12,2),
@IdUnidad int,
@IdArticulo int,
@Peso numeric(12,2),
@IdUnidadPeso int,
@IdControlCalidad int,
@Cantidad1 numeric(12,2),
@Cantidad2 numeric(12,2),
@Detalle varchar(50),
@IdPlano int,
@IdDetalleAcopios int,
@Adjunto varchar(2),
@ArchivoAdjunto varchar(50),
@Observaciones ntext,
@Despacha varchar(2),
@ArchivoAdjunto1 varchar(50),
@ArchivoAdjunto2 varchar(50),
@ArchivoAdjunto3 varchar(50),
@ArchivoAdjunto4 varchar(50),
@ArchivoAdjunto5 varchar(50),
@ArchivoAdjunto6 varchar(50),
@ArchivoAdjunto7 varchar(50),
@ArchivoAdjunto8 varchar(50),
@ArchivoAdjunto9 varchar(50),
@ArchivoAdjunto10 varchar(50),
@DescripcionManual varchar(250),
@EnviarEmail tinyint,
@IdLMaterialesOriginal int,
@IdDetalleLMaterialesOriginal int,
@IdOrigenTransmision int,
@IdDetalleObraDestino int

AS 

INSERT INTO [DetalleLMateriales]
(
 IdLMateriales,
 NumeroItem,
 NumeroOrden,
 Revision,
 Cantidad,
 IdUnidad,
 IdArticulo,
 Peso,
 IdUnidadPeso,
 IdControlCalidad,
 Cantidad1,
 Cantidad2,
 Detalle,
 IdPlano,
 IdDetalleAcopios,
 Adjunto,
 ArchivoAdjunto,
 Observaciones,
 Despacha,
 ArchivoAdjunto1,
 ArchivoAdjunto2,
 ArchivoAdjunto3,
 ArchivoAdjunto4,
 ArchivoAdjunto5,
 ArchivoAdjunto6,
 ArchivoAdjunto7,
 ArchivoAdjunto8,
 ArchivoAdjunto9,
 ArchivoAdjunto10,
 DescripcionManual,
 EnviarEmail,
 IdLMaterialesOriginal,
 IdDetalleLMaterialesOriginal,
 IdOrigenTransmision,
 IdDetalleObraDestino
)
VALUES
(
 @IdLMateriales,
 @NumeroItem,
 @NumeroOrden,
 @Revision,
 @Cantidad,
 @IdUnidad,
 @IdArticulo,
 @Peso,
 @IdUnidadPeso,
 @IdControlCalidad,
 @Cantidad1,
 @Cantidad2,
 @Detalle,
 @IdPlano,
 @IdDetalleAcopios,
 @Adjunto,
 @ArchivoAdjunto,
 @Observaciones,
 @Despacha,
 @ArchivoAdjunto1,
 @ArchivoAdjunto2,
 @ArchivoAdjunto3,
 @ArchivoAdjunto4,
 @ArchivoAdjunto5,
 @ArchivoAdjunto6,
 @ArchivoAdjunto7,
 @ArchivoAdjunto8,
 @ArchivoAdjunto9,
 @ArchivoAdjunto10,
 @DescripcionManual,
 @EnviarEmail,
 @IdLMaterialesOriginal,
 @IdDetalleLMaterialesOriginal,
 @IdOrigenTransmision,
 @IdDetalleObraDestino
)

SELECT @IdDetalleLMateriales=@@identity
RETURN(@IdDetalleLMateriales)
