
CREATE Procedure [dbo].[DetPedidos_A]

@IdDetallePedido int  output,
@IdPedido int,
@NumeroItem int,
@Cantidad numeric(12,2),
@IdUnidad int,
@IdArticulo int,
@FechaEntrega datetime,
@IdControlCalidad int,
@Precio numeric(12,4),
@Observaciones ntext,
@Cantidad1 numeric(12,2),
@Cantidad2 numeric(12,2),
@IdDetalleAcopios int,
@IdDetalleRequerimiento int,
@Cumplido varchar(2),
@CantidadAdicional numeric(16,2),
@CantidadRecibida numeric(12,2),
@CantidadAdicionalRecibida numeric(16,2),
@Adjunto varchar(2),
@ArchivoAdjunto varchar(50),
@FechaNecesidad datetime,
@IdDetalleLMateriales int,
@IdCuenta int,
@OrigenDescripcion int,
@ArchivoAdjunto1 varchar(100),
@ArchivoAdjunto2 varchar(100),
@ArchivoAdjunto3 varchar(100),
@ArchivoAdjunto4 varchar(100),
@ArchivoAdjunto5 varchar(100),
@ArchivoAdjunto6 varchar(100),
@ArchivoAdjunto7 varchar(100),
@ArchivoAdjunto8 varchar(100),
@ArchivoAdjunto9 varchar(100),
@ArchivoAdjunto10 varchar(100),
@IdAutorizoCumplido int,
@IdDioPorCumplido int,
@FechaDadoPorCumplido datetime,
@ObservacionesCumplido ntext,
@IdCentroCosto int,
@PorcentajeBonificacion numeric(6,2),
@ImporteBonificacion numeric(18,4),
@PorcentajeIVA numeric(6,2),
@ImporteIVA numeric(18,4),
@ImporteTotalItem numeric(18,4),
@Costo numeric(18,2),
@PRESTOPedido varchar(13),
@PRESTOFechaProceso datetime,
@IdAsignacionCosto int,
@CostoAsignado numeric(18,4),
@IdUsuarioAsignoCosto int,
@FechaAsignacionCosto datetime,
@EnviarEmail tinyint,
@IdDetallePedidoOriginal int,
@IdPedidoOriginal int,
@IdOrigenTransmision int,
@PlazoEntrega varchar(50),
@CostoAsignadoDolar numeric(18,4),
@IdDetalleComparativa int,
@IdDetalleRequerimientoOriginal int,
@ImpuestosInternos numeric(18,2),
@CostoOriginal numeric(18,4),
@IdUsuarioModificoCosto int, 
@FechaModificacionCosto datetime, 
@ObservacionModificacionCosto ntext

AS 

INSERT INTO [DetallePedidos]
(
 IdPedido,
 NumeroItem,
 Cantidad,
 IdUnidad,
 IdArticulo,
 FechaEntrega,
 IdControlCalidad,
 Precio,
 Observaciones,
 Cantidad1,
 Cantidad2,
 IdDetalleAcopios,
 IdDetalleRequerimiento,
 Cumplido,
 CantidadAdicional,
 CantidadRecibida,
 CantidadAdicionalRecibida,
 Adjunto,
 ArchivoAdjunto,
 FechaNecesidad,
 IdDetalleLMateriales,
 IdCuenta,
 OrigenDescripcion,
 ArchivoAdjunto1,
 ArchivoAdjunto2,
 ArchivoAdjunto3,
 ArchivoAdjunto4,
 ArchivoAdjunto5,
 ArchivoAdjunto6,
 ArchivoAdjunto7,
 ArchivoAdjunto8,
 ArchivoAdjunto9,
 ArchivoAdjunto10,
 IdAutorizoCumplido,
 IdDioPorCumplido,
 FechaDadoPorCumplido,
 ObservacionesCumplido,
 IdCentroCosto,
 PorcentajeBonificacion,
 ImporteBonificacion,
 PorcentajeIVA,
 ImporteIVA,
 ImporteTotalItem,
 Costo,
 PRESTOPedido,
 PRESTOFechaProceso,
 IdAsignacionCosto,
 CostoAsignado,
 IdUsuarioAsignoCosto,
 FechaAsignacionCosto,
 EnviarEmail,
 IdDetallePedidoOriginal,
 IdPedidoOriginal,
 IdOrigenTransmision,
 PlazoEntrega,
 CostoAsignadoDolar,
 IdDetalleComparativa,
 IdDetalleRequerimientoOriginal,
 ImpuestosInternos,
 CostoOriginal,
 IdUsuarioModificoCosto,
 FechaModificacionCosto,
 ObservacionModificacionCosto
)
VALUES
(
 @IdPedido,
 @NumeroItem,
 @Cantidad,
 @IdUnidad,
 @IdArticulo,
 @FechaEntrega,
 @IdControlCalidad,
 @Precio,
 @Observaciones,
 @Cantidad1,
 @Cantidad2,
 @IdDetalleAcopios,
 @IdDetalleRequerimiento,
 @Cumplido,
 @CantidadAdicional,
 @CantidadRecibida,
 @CantidadAdicionalRecibida,
 @Adjunto,
 @ArchivoAdjunto,
 @FechaNecesidad,
 @IdDetalleLMateriales,
 @IdCuenta,
 @OrigenDescripcion,
 @ArchivoAdjunto1,
 @ArchivoAdjunto2,
 @ArchivoAdjunto3,
 @ArchivoAdjunto4,
 @ArchivoAdjunto5,
 @ArchivoAdjunto6,
 @ArchivoAdjunto7,
 @ArchivoAdjunto8,
 @ArchivoAdjunto9,
 @ArchivoAdjunto10,
 @IdAutorizoCumplido,
 @IdDioPorCumplido,
 @FechaDadoPorCumplido,
 @ObservacionesCumplido,
 @IdCentroCosto,
 @PorcentajeBonificacion,
 @ImporteBonificacion,
 @PorcentajeIVA,
 @ImporteIVA,
 @ImporteTotalItem,
 @Costo,
 @PRESTOPedido,
 @PRESTOFechaProceso,
 @IdAsignacionCosto,
 @CostoAsignado,
 @IdUsuarioAsignoCosto,
 @FechaAsignacionCosto,
 @EnviarEmail,
 @IdDetallePedidoOriginal,
 @IdPedidoOriginal,
 @IdOrigenTransmision,
 @PlazoEntrega,
 @CostoAsignadoDolar,
 @IdDetalleComparativa,
 @IdDetalleRequerimientoOriginal,
 @ImpuestosInternos,
 @CostoOriginal,
 @IdUsuarioModificoCosto,
 @FechaModificacionCosto,
 @ObservacionModificacionCosto
)

SELECT @IdDetallePedido=@@identity
RETURN(@IdDetallePedido)
