
CREATE Procedure [dbo].[DetRecepcionesSAT_M]
@IdDetalleRecepcion int,
@IdRecepcion int,
@Cantidad numeric(18,2),
@IdUnidad int,
@IdArticulo int,
@IdControlCalidad int,
@Observaciones ntext,
@Cantidad1 numeric(18,2),
@Cantidad2 numeric(18,2),
@IdDetallePedido int,
@Controlado varchar(2),
@CantidadAdicional numeric(18,2),
@Partida varchar(20),
@CantidadCC numeric(18,2),
@Cantidad1CC numeric(18,2),
@Cantidad2CC numeric(18,2),
@CantidadAdicionalCC numeric(18,2),
@ObservacionesCC ntext,
@CantidadRechazadaCC numeric(18,2),
@IdMotivoRechazo int,
@IdRealizo int,
@IdDetalleRequerimiento int,
@Trasabilidad varchar(10),
@IdDetalleAcopios int,
@IdUbicacion int,
@IdObra int,
@CostoUnitario numeric(18,3),
@IdMoneda int,
@CotizacionDolar numeric(18,3),
@CotizacionMoneda numeric(18,3),
@EnviarEmail tinyint,
@IdDetalleRecepcionOriginal int,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@IdDetalleSalidaMaterialesPRONTO int
As
Update [DetalleRecepcionesSAT]
Set  
 IdRecepcion=@IdRecepcion,
 Cantidad=@Cantidad,
 IdUnidad=@IdUnidad,
 IdArticulo=@IdArticulo,
 IdControlCalidad=@IdControlCalidad,
 Observaciones=@Observaciones,
 Cantidad1=@Cantidad1,
 Cantidad2=@Cantidad2,
 IdDetallePedido=@IdDetallePedido,
 Controlado=@Controlado,
 CantidadAdicional=@CantidadAdicional,
 Partida=Null,
 CantidadCC=@CantidadCC,
 Cantidad1CC=@Cantidad1CC,
 Cantidad2CC=@Cantidad2CC,
 CantidadAdicionalCC=@CantidadAdicionalCC,
 ObservacionesCC=@ObservacionesCC,
 CantidadRechazadaCC=@CantidadRechazadaCC,
 IdMotivoRechazo=@IdMotivoRechazo,
 IdRealizo=@IdRealizo,
 IdDetalleRequerimiento=@IdDetalleRequerimiento,
 Trasabilidad=@Trasabilidad,
 IdDetalleAcopios=@IdDetalleAcopios,
 IdUbicacion=@IdUbicacion,
 IdObra=@IdObra,
 CostoUnitario=@CostoUnitario,
 IdMoneda=@IdMoneda,
 CotizacionDolar=@CotizacionDolar,
 CotizacionMoneda=@CotizacionMoneda,
 EnviarEmail=@EnviarEmail,
 IdDetalleRecepcionOriginal=@IdDetalleRecepcionOriginal,
 IdRecepcionOriginal=@IdRecepcionOriginal,
 IdOrigenTransmision=@IdOrigenTransmision,
 IdDetalleSalidaMaterialesPRONTO=@IdDetalleSalidaMaterialesPRONTO
Where (IdDetalleRecepcion=@IdDetalleRecepcion)
Return(@IdDetalleRecepcion)
