
CREATE Procedure [dbo].[DetRecepcionesSAT_A]
@IdDetalleRecepcion int  output,
@IdRecepcion int,
@Cantidad numeric(18,2),
@IdUnidad int,
@IdArticulo int,
@IdControlCalidad int,
@Observaciones ntext,
@Cantidad1 numeric(18,2),
@Cantidad2 numeric(18,2),
@IdDetallePedido int,
@Controlado varchar(2),
@CantidadAdicional numeric(18,2),
@Partida varchar(20),
@CantidadCC numeric(18,2),
@Cantidad1CC numeric(18,2),
@Cantidad2CC numeric(18,2),
@CantidadAdicionalCC numeric(18,2),
@ObservacionesCC ntext,
@CantidadRechazadaCC numeric(18,2),
@IdMotivoRechazo int,
@IdRealizo int,
@IdDetalleRequerimiento int,
@Trasabilidad varchar(10),
@IdDetalleAcopios int,
@IdUbicacion int,
@IdObra int,
@CostoUnitario numeric(18,3),
@IdMoneda int,
@CotizacionDolar numeric(18,3),
@CotizacionMoneda numeric(18,3),
@EnviarEmail tinyint,
@IdDetalleRecepcionOriginal int,
@IdRecepcionOriginal int,
@IdOrigenTransmision int,
@IdDetalleSalidaMaterialesPRONTO int
As 
Insert into [DetalleRecepcionesSAT]
(
 IdRecepcion,
 Cantidad,
 IdUnidad,
 IdArticulo,
 IdControlCalidad,
 Observaciones,
 Cantidad1,
 Cantidad2,
 IdDetallePedido,
 Controlado,
 CantidadAdicional,
 Partida,
 CantidadCC,
 Cantidad1CC,
 Cantidad2CC,
 CantidadAdicionalCC,
 ObservacionesCC,
 CantidadRechazadaCC,
 IdMotivoRechazo,
 IdRealizo,
 IdDetalleRequerimiento,
 Trasabilidad,
 IdDetalleAcopios,
 IdUbicacion,
 IdObra,
 CostoUnitario,
 IdMoneda,
 CotizacionDolar,
 CotizacionMoneda,
 EnviarEmail,
 IdDetalleRecepcionOriginal,
 IdRecepcionOriginal,
 IdOrigenTransmision,
 IdDetalleSalidaMaterialesPRONTO
)
Values
(
 @IdRecepcion,
 @Cantidad,
 @IdUnidad,
 @IdArticulo,
 @IdControlCalidad,
 @Observaciones,
 @Cantidad1,
 @Cantidad2,
 @IdDetallePedido,
 @Controlado,
 @CantidadAdicional,
 Null,
 @CantidadCC,
 @Cantidad1CC,
 @Cantidad2CC,
 @CantidadAdicionalCC,
 @ObservacionesCC,
 @CantidadRechazadaCC,
 @IdMotivoRechazo,
 @IdRealizo,
 @IdDetalleRequerimiento,
 @Trasabilidad,
 @IdDetalleAcopios,
 @IdUbicacion,
 @IdObra,
 @CostoUnitario,
 @IdMoneda,
 @CotizacionDolar,
 @CotizacionMoneda,
 @EnviarEmail,
 @IdDetalleRecepcionOriginal,
 @IdRecepcionOriginal,
 @IdOrigenTransmision,
 @IdDetalleSalidaMaterialesPRONTO
)
Select @IdDetalleRecepcion=@@identity
Return(@IdDetalleRecepcion)
